### ISSUE TITLE
Please add cmake options to build tests, demos, examples,etc.

### ISSUE THREAD

**Issue by yurivict** [simdjson/simdjson#1013]
With ```SIMDJSON_JUST_LIBRARY``` is still builds a demo ```amalgamate_demo```.

All non-essential parts should be conditional on their individual cmake options.

**Comment by lemire** [comment]
Pull request invited.

**Comment by yurivict** [comment]
I'm just a FreeBSD port update contributor, not even a maintainer of the port, and don't have resources to submit pull requests, sorry.

**Comment by lemire** [comment]
I will issue a PR.

**Comment by jkeiser** [comment]
We wouldn't make a point release, right? Doesn't hurt to get it done as polish but it doesn't actually prevent anything from working, building or getting packages?

**Comment by jkeiser** [comment]
(Don't mind if we do issue one, but I'd hate to see this add to the day you've already had without it actually fixing something urgent :)

**Comment by yurivict** [comment]
This can break some toolchains, because SONAME is incorrect.

**Comment by lemire** [comment]
@yurivict 

Please see my PR at https://github.com/simdjson/simdjson/pull/1016

I appreciate your help.

I'm a little bit annoyed regarding the soversion thing, but it is not your fault in the least. It is one of these things where it is hard to figure out the right move and the documentation is poor...

**Comment by lemire** [comment]
Closing.
