### ISSUE TITLE
[regression between 0.3.1 and 0.4.4] SONAME has disappeared

### ISSUE THREAD

**Issue by yurivict** [simdjson/simdjson#1014]
Shared library should normally have a SONAME, otherwise it's difficult to track library changes and all dependencies have to always be updated.

```
-lib/libsimdjson.so.1
 lib/libsimdjson.so
-lib/libsimdjson.so.0.3.1
```

**Comment by lemire** [comment]
This was removed in commit https://github.com/simdjson/simdjson/commit/54b7291c341b6fd3369a2243d80de35b1df28773#diff-95e351a3805a1dafa85bf20b81d086e6

I missed it in my review at the time.

**Comment by lemire** [comment]
Fixed in version 0.4.5.

I have added tests so it should never happen again.

**Comment by yurivict** [comment]
The new SONAME is incorrect:
```
lib/libsimdjson.so.0.4.5
lib/libsimdjson.so.2
```

```libsimdjson.so.2``` should match ```libsimdjson.so.0.4.5```.

**Comment by lemire** [comment]
> The new SONAME is incorrect:

Pull request invited. Please review the history of the soversions for this project...  https://github.com/simdjson/simdjson/issues/661 https://github.com/simdjson/simdjson/pull/98 and explain, in your pull request, what policy we should follow.

Currently, here is the policy:

- We bump the soversion with each time the shared library ABI changes in a way that may break binaries linked against older versions of the shared library.
- We otherwise follow http://semver.org/ which specifically allows breaking checking in a 0.X.Y library.

If this is incorrect, please provide references, in a distinct issue/PR (not here, please).

If you want us to use a soversion of 0, then you will have to live with ABI changes with the same soversion.

**Comment by yurivict** [comment]
The digit(s) of the short version of SONAME should always match the first digit(s) of the full SONAME, ex.:
```
lrwxr-xr-x    1 root  wheel        19 May 13 18:26 libxkbfile.so -> libxkbfile.so.1.0.2
lrwxr-xr-x    1 root  wheel        19 May 13 18:26 libxkbfile.so.1 -> libxkbfile.so.1.0.2
-rwxr-xr-x    1 root  wheel    163648 May 13 18:26 libxkbfile.so.1.0.2
lrwxr-xr-x    1 root  wheel        21 May 22 18:46 libxklavier.so -> libxklavier.so.16.3.0
lrwxr-xr-x    1 root  wheel        21 May 22 18:46 libxklavier.so.16 -> libxklavier.so.16.3.0
-rwxr-xr-x    1 root  wheel    119000 May 22 18:46 libxklavier.so.16.3.0
lrwxr-xr-x    1 root  wheel        21 Jun  5 18:44 libxml++-2.6.so -> libxml++-2.6.so.2.0.7
lrwxr-xr-x    1 root  wheel        21 Jun  5 18:44 libxml++-2.6.so.2 -> libxml++-2.6.so.2.0.7
-rwxr-xr-x    1 root  wheel    237120 Jun  5 18:44 libxml++-2.6.so.2.0.7
lrwxr-xr-x    1 root  wheel        17 May 13 18:10 libxml2.so -> libxml2.so.2.9.10
lrwxr-xr-x    1 root  wheel        17 May 13 18:10 libxml2.so.2 -> libxml2.so.2.9.10
-rwxr-xr-x    1 root  wheel   1669480 May 13 18:10 libxml2.so.2.9.10
lrwxr-xr-x    1 root  wheel        27 Jun 19 18:31 libxmlsec1-gcrypt.so -> libxmlsec1-gcrypt.so.1.2.29
lrwxr-xr-x    1 root  wheel        27 Jun 19 18:31 libxmlsec1-gcrypt.so.1 -> libxmlsec1-gcrypt.so.1.2.29
-rwxr-xr-x    1 root  wheel    139400 Jun 19 18:31 libxmlsec1-gcrypt.so.1.2.29
```

**Comment by lemire** [comment]
@yurivict I have this other comment by @cdluminate who write...


"""
@lemire The missing cmake code is
```
set_target_properties(<simdjson_shared_library> PROPERTIES
  VERSION $(SIMDJSON_VERSION)
  SOVERSION $(SIMDJSON_SOVERSION)
)
```
"""

**Comment by cdluminate** [comment]
We can imitate the versioning scheme like `libxkbfile.so.1 -> libxkbfile.so.1.0.2` when we can make sure the ABI version will stay consistent in all the minor updates and patch updates. SOVERSION is used to track the ABI change, and it does not have to be consistent with the VERSION, especially ABI consistency is not guaranteed for minor updates.

Setting VERSION to 0.4.5 and SOVERSION to 2 is not wrong.
