### ISSUE TITLE
Re-examine stage 2 switch/case

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1034]
In a comment, @aqrit reports that part of our stage 2 under GCC gets compiled as a binary search. He suggests removing a key ('-'), and points out that c>>3 forms a perfect hash.

**Comment by lemire** [comment]
This should be revisited before the next release.

cc @jkeiser

**Comment by lemire** [comment]
Closing since this has been done.

**Comment by jkeiser** [comment]
The - is gone, but I don't think we've investigated using c >> 3 yet.

**Comment by jkeiser** [comment]
Oh, I see your comment. I guess this is a place having the computed go-to hindered optimization.

**Comment by lemire** [comment]
I don’t think we could safely hash the characters because we need to validate them... so what you coded is nearly optimal.

**Comment by aqrit** [comment]
Indirect jump/call then validate.
The `if (char == expected)` validations check, placed at the callee/target locations, should always be predicted correctly.

The compiler generates such a mess for switch statements :-(
This would eliminate the switch statement.

Computed gotos would eliminate the loop (and extra error checking).

---

'n' is validated by `is_valid_null_atom()`
't' is validated by `is_valid_true_atom()`
digits/minus are validated by `parse_number()`

so new checks would be needed in the handlers for:
0x22 // '"'
0x5B // '['
0x66 // 'f'
0x7B // '{'

---
I was actually arguing in favor of keeping the '-' special case because it was (or should have been) "free".

**Comment by aqrit** [comment]
The questions would seems to be:
* how predictable is an indirect branch?
* how predictable was the binary search (splitting first on 0x5B)?
* how much would a hash function ruin the Feng Shui of the code?
* Is it worth special casing '0' too?

**Comment by jkeiser** [comment]
@aqrit #1078 appears to restore the compiler's willingness to generate a jump table, which is what @lemire is referring to here.

There is no reason I can think of why that change should have that effect, except that perhaps the compiler is past the limits of its patience (or optimization budget) in stage 2, which could well explain the bizarre performance swings we see when making seemingly innocuous changes there.

**Comment by jkeiser** [comment]
Though to be clear, I am not certain the compiler even has a budget--it just seems like the kind of thing one would need to do when building a compiler.

**Comment by lemire** [comment]
@aqrit I may have misunderstood your hints earlier, sorry about that.

This being said, by removing '-', @jkeiser managed to turn our messy switch/case statements into something the compiler (all compilers?) turn into a jump table (not a binary search), at least in my toy examples (I have not verified our own assembly per se). John thinks that it happens due to a budget constraint. He might be right. But I think that the compiler looks at different things like the range of values, the number of jumps and so forth. I am not sure how the heuristic work.

**Comment by lemire** [comment]
I have manually verified that the new switch/case, in actual code, do get compiled as jump tables.

**Comment by lemire** [comment]
Note that it is possible to force the table lookup with an array...

```
table = {7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 1, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 7, 7, 7, 7, 7, 7, 7, 5, 7, 7, 7, 7, 7, 3, 7, 7, 7, 7, 7, 7, 0, 7, 7, 7, 7}

idx = table[c]

switch(idx):
  case 0
  case 1


```

This generates nicer looking assembly, and shaves a few instructions, but it is not faster and it is arguably harder to read and to maintain.

**Comment by lemire** [comment]
I have spent more time on @jkeiser's new code and I am pretty confident that there is no low-hanging fruit there. You can shave some instructions, but I could not find a good consistent way to go faster by modifying the switch/case.

Again... we would need to roll out our own assembly, I think, to go faster.

**Comment by aqrit** [comment]
No worries, it is all fun and games to me.

It looks like it takes 4 comparisons and 5 condition jumps to get to the double_quote handler or digit handler.

```
// built from simdjson-jkeiser-no-error.zip
// g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
// "main_array_switch" ... both streaming<false> & <true> look similar.

	movzx   eax, byte ptr [rdi]
	cmp     al, 7Bh ; '{'
	ja      loc_11AB4
	cmp     al, 5Ah ; 'Z'        // split in half
	jbe     loc_1244F            // unpredictable ?

// send 0x5B..0x7B thru a jump table //
	sub     eax, 5Bh ; '['
	cmp     al, 20h ; ' '
	ja      loc_11AB4
	lea     rcx, unk_1AB10
	movzx   eax, al
	movsxd  rax, dword ptr [rcx+rax*4]
	add     rax, rcx
	db      3Eh
	jmp     rax

...
loc_1244F:
	cmp     al, 2Dh ; '-'
	jz      loc_133E9
	jbe     loc_12698
	lea     edx, [rax-30h]
	cmp     dl, 9            // range check digits
	ja      loc_11AB4

...
loc_12698:
	cmp     al, 22h ; '"'
	jnz     loc_11AB4
```

**Comment by lemire** [comment]
@aqrit I am not sure what you are saying but GCC definitively gives me a jump table...

```asm
	movl	4(%rbp), %edx
	leaq	0(%r13,%rdx), %rdi
	movzbl	(%rdi), %eax
	cmpb	$123, %al
	ja	.L1273
	cmpb	$90, %al
	jbe	.L1298
	subl	$91, %eax
	cmpb	$32, %al
	ja	.L1273
	leaq	.L1015(%rip), %rdx
	movzbl	%al, %eax
	movslq	(%rdx,%rax,4), %rax
	addq	%rdx, %rax
	notrack jmp	*%rax
	.section	.rodata
	.align 4
	.align 4
.L1015:
	.long	.L1019-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1018-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1017-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1016-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1273-.L1015
	.long	.L1014-.L1015
	.text
```

This is with jkeiser/no-computed-goto.

**Comment by aqrit** [comment]
I get the hybrid switch statement with `no-computed-goto` as well (AFAICT).
I'm not concerned, I just thought I'd point it out.

**Comment by lemire** [comment]
Verified as well with the jkeiser/no_error branch:

```asm
	movl	4(%rbp), %edx
	leaq	(%r14,%rdx), %rdi
	movzbl	(%rdi), %eax
	cmpb	$123, %al
	ja	.L1323
	cmpb	$90, %al
	jbe	.L1778
	subl	$91, %eax
	cmpb	$32, %al
	ja	.L1323
	leaq	.L1518(%rip), %rdx
	movzbl	%al, %eax
	movslq	(%rdx,%rax,4), %rax
	addq	%rdx, %rax
	notrack jmp	*%rax
	.section	.rodata
	.align 4
	.align 4
.L1518:
	.long	.L1522-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1521-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1520-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1519-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1323-.L1518
	.long	.L1517-.L1518
	.text
```

```
$ g++ --version
g++ (Ubuntu 9.3.0-13ubuntu1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

To check, I run `amalgamate.sh` and then I build `simdjson.cpp` as a single unit. Then I scan the assembly like a madman.

**Comment by lemire** [comment]
> I'm not concerned, I just thought I'd point it out.

Yes, but how do you check? See my methodology above.

**Comment by aqrit** [comment]
:-D

You're posting the same snippet as me...
That jump table is only for 0x5B thru 0x7B

Anyways this is how I built it:
```
mkdir build
cd build
cmake ..
cmake --build . --config Release
```

**Comment by lemire** [comment]
@aqrit Ok. So we are good.

As I described above, you can "force" C++ to use a full table lookup. Just lookup the character into a 256-entry table with the numbers from 0 to 7 corresponding to our case. It does lower the instruction count very slightly, as you would expect, but it does not consistently improve the speed.

I mean, this stuff is branchy. There is no getting around it.
