### ISSUE TITLE
All simdjson macros should be prefixed with SIMDJSON to avoid clashes

### ISSUE THREAD

**Issue by sehoffmann** [simdjson/simdjson#1035]
**Describe the bug**
simdjson defines the macro `likely` for manual branch prediction. The same name is used by Boost.DateTime as method name in `datetime/special_value_parser.hpp:105`. 

**To Reproduce**
`#include <simdjson/simdjson.h>`
`#include <boost/date_time/posix_time/posix_time.hpp>`

**How to fix**
Rename `likely` to `simdjson_likely` per default

**Configuration (please complete the following information if relevant):**
 - OS: Ubuntu 20.02 LTS
 - Compiler gcc 9.3
 - Version v0.3.1
 - Boost: 1.72

**Indicate whether you are willing or able to provide a bug fix as a pull request**
No

**Comment by sehoffmann** [comment]
In general all macros should be prefixed with some sort of "namespace" to prevent similiar issues in the future.

**Comment by sehoffmann** [comment]
This will also become an even bigger issue with C++20: https://en.cppreference.com/w/cpp/language/attributes/likely
Notice that `likely` is not a reserved keyword though

**Comment by jkeiser** [comment]
This seems important! Boost is a big deal, and people are definitely going to be using date times when they parse json, so it's not like you can even reasonably split up your code to not hit this.

We should:
* Avoid non-namespaced macros
* `#undef` all non-namespaced macros.

**Comment by lemire** [comment]
Yes. We should prefix all macros.

**Comment by lemire** [comment]
I have increased the range of the issue. It is now marked for 0.5. Let us fix that.

What we need is a test that tells you which macros we added so we can detect illegal macros in the future.
