### ISSUE TITLE
Use fast float parsing on larger significands

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1036]
Right now we use strtod to reparse floats with more than 19 digits (which overflow our int parsing). Could we theoretically stop reading digits after the 19th (significant) digit, use the fast float assembly algorithm, and still achieve precise results? Could cut down on branches, if nothing else.

For example, 3333333333333333333000000000000e1 and 3333333333333333333999999999999e1 seem like they should yield the same answer, floating-point-wise (and they do appear to, in python).

Given that floating-point numbers only have 15-17 decimal digits of precision and we are parsing the integer part with 19-20, it feels like we could do this safely ...

**Comment by lemire** [comment]
You would think, right? 

But no. 

You definitively can stop reading after a time, but it is nothing like 19 digits.

You can take you 150-digit number, round it just right to a 17-digit number and you are good... But if I give you a 150-digit number and you truncate it after 19-digit, then you will introduce an error in the rounding.

*However*, we don't have to care about the performance if someone feeds in a lot of digits. This person wasn't very serious in the first place and they probably don't care about performance.

**Comment by jkeiser** [comment]
> You can take your 150-digit number, round it just right to a 17-digit number and you are good... But if I give you a 150-digit number and you truncate it after 19-digit, then you will introduce an error in the rounding.

If I take a 150-digit number, truncate it to 19 digits, and then round *that* to 17 digits, do I still introduce an error in the rounding? That *seems* more analogous to what we're doing here.

Since decimal and binary can't represent the same numbers, the true question is, "if I take a 150-digit decimal number, truncate it to 19 digits, and then round that to the nearest double (53-bit binary precision), does that introduce an error in the rounding?" Or perhaps "is the value of the 20th decimal digit ever significant in deciding which double value to choose?" Your comment that you can't stop reading after 19 digits indicates the answer is probably "yes."

**Comment by plokhotnyuk** [comment]
ICYMI: https://www.exploringbinary.com/maximum-number-of-decimal-digits-in-binary-floating-point-numbers/

**Comment by jkeiser** [comment]
Oh. OH. I understand now. Thank you so much for the link! It also [linked to this](https://www.exploringbinary.com/17-digits-gets-you-there-once-youve-found-your-way/), which basically specifically explains the root of my misconception here.

**Comment by plokhotnyuk** [comment]
@jkeiser Sorry, I had pasted a wrong link, but you have managed to follow to the right page.

Yep, the "Example 3: Just Below Halfway" section has a counterexample for the rounding to 17 digits.

**Comment by lemire** [comment]
This being said, it would be totally fair to introduce a mode where you do truncate after 19 digits. But unless it buys you performance...

**Comment by jkeiser** [comment]
Closing this, since the idea is wrong :) Will keep the "truncate for people who don't care" idea in the back of the head.

**Comment by lemire** [comment]
> Closing this, since the idea is wrong

The reason I knew immediately that it was wrong is that I had the same idea originally. It is what I call a bad "good idea".
