### ISSUE TITLE
This commit breaks compilation with GCC

### ISSUE THREAD

**Issue by jrch2k20** [simdjson/simdjson#1083]
Hi, just reporting that commit 796588900cde2df3e7d974d4250f057ff204a80f breaks GCC compilation in ArchLinux.

**Error:**
static assertion failed3194 | static_assert(std::ranges::sized_range<simdjson::dom::array>);

**Compiler version:**
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.1.0 (GCC)

**Comment by jrch2k20** [comment]
Just reverting it in my local repo seems to work fine, btw

Thank you for your hard work :1st_place_medal:

**Comment by lemire** [comment]
@jrch2k20 Something is flaky with this C++20 code. We are aware. Narrowing down the problem has been difficult.

cc @jkeiser

**Comment by jkeiser** [comment]
Fixed in the linked PR.
