### ISSUE TITLE
Give access to the JSON source string in `load_many`

### ISSUE THREAD

**Issue by casperisfine** [simdjson/simdjson#1088]
My use case is rather simple. I have large (several GiB) files containing a stream of JSON objects that parses just fine with `load_many`, and that I want to filter based on some conditions to produce a smaller file that is a subset of the source one.

Here's a simplified snippet of what I'm currently doing:

```cpp
    std::ifstream input(source_path);
    std::ofstream output(destination_path, std::ofstream::out);
    for (std::string line; getline( input, line );) {
        dom::element object = parser.parse(line);
        if (<some conditions>) {
            output << line << std::endl;
        }
    }
```

In such case it would be very useful if the `dom::element` objects yielded by `load_many` had a reference to their source, e.g.:

```cpp
dom::parser parser;
std::ofstream output(destination_path, std::ofstream::out);
auto [objects, error] = parser.load_many(path);
if (error == SUCCESS) {
    for (dom::object object : objects) {
      if (<some conditions>) {
          output << object.source() << std::endl;
      }
    }
}
```

**Comment by lemire** [comment]
Sounds doable. Marking for 0.5.

**Comment by jkeiser** [comment]
I don't think it is doable, actually, not in a short timeframe: we strip the source indexing data when we serialize the DOM.

**Comment by jkeiser** [comment]
It *is* doable, to be clear, at some point :)

**Comment by jkeiser** [comment]
It is also doable to get the document source from load_many actually (though not through the object interface). That's likely a 0.5-able thing.

**Comment by lemire** [comment]
We already expose the index, so grabbing a string_view ought to be easy.

**Comment by jkeiser** [comment]
Yeah, you're right, at the document level we should be able to swing it.

**Comment by lemire** [comment]
Will be in 0.5 on an experimental basis. We want, in time, to have a nicer API.
