### ISSUE TITLE
Conan Package Support

### ISSUE THREAD

**Issue by uilianries** [simdjson/simdjson#109]
Hello,

Do you know about [Conan](https://conan.io)?

Conan is modern dependency and package manager for C/C++. And would be great if your library would be available via package manager for other developers.

All official Conan packages are available on [Conan Center](https://bintray.com/conan/conan-center), where is possible search, install and upload any Conan package.

Since your project have a header-only option, it can be distributed as pre-built library or even as single header.

We could support you writing a recipe and help you to publish your packages on [Bintray](https://bintray.com).

If you have any questions, just ask :-)

Regards!

**Comment by lemire** [comment]
Marked as "help wanted".

**Comment by lemire** [comment]
Version 0.2.1 is on conan already and I have submitted version 0.4.6.

https://github.com/conan-io/conan-center-index/pull/2104

I am going to close this.

**Comment by lemire** [comment]
Thanks for your work.
