### ISSUE TITLE
Support UTF-16 parsing

### ISSUE THREAD

**Issue by wangjiachun** [simdjson/simdjson#112]
It seems that it only parse a char characters stream. And I found get_corpus function that only produce a char-unit character. But for wchar_t-unit characters which have two bytes for each, I can use "std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>" to convert them to char-unit and parse them then. The conversion process is costing much time while the parsing process is so fast. Are you gonging to support parsing wchar_t characters stream so that the huge conversion time can be reduced?

**Comment by lemire** [comment]
We only support UTF-8 inputs. UTF-8 is the standard encoding for JSON, XML.

Support for UTF-16 and UTF-32 inputs is not unthinkable but would be best done as separate code paths.

There is currently nobody working on this. Contributions invited.

**Comment by lemire** [comment]
Here is @timbray introducing the latest JSON specification...

> “JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8 [RFC3629].” Given that, by 2017, an attempt to exchange JSON encoded in anything but UTF-8 would be irrational, this hardly needs saying; but its absence felt like an omission.


Furthermore, this issue has been open for more than a year and nobody has offered to help implement UTF-16.

I am going to close this issue.

As separate projects, we might support fast UTF16-UTF8 transcoding, but at this point, if you have to consume UTF-16 JSON documents, you are probably working in a legacy internal system.

**Comment by michaeleisel** [comment]
I can say I have a use case for this. I'm looking at using simdjson for JSON parsing in Java (via JNI), and it can be significantly faster to get a UTF-16 copy of the bytes of a Java string to work with in C++-land rather than a UTF-8 string.
