### ISSUE TITLE
Move inline/*.h to dom/*-inl.h

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1125]
Our current method (which is my fault :) of having inline definition headers in inline/<file>.h causes conflicts when paired with namespaces. When trying to add ondemand interfaces, I'm running into predictable naming conflicts when I try to add the corresponding files to include/simdjson/inline. For example, ondemand/document.h (the ondemand::document class) needs inline functions, but include/simdjson/inline/document.h already exists.

I searched around and found Google's guidlines, which suggest appending -inl to the header name instead of having a separate directory. While Google has abandoned the practice of extensive inlining in headers, this seems like it would work for us.

So we'd solve the problem by having a dom/document-inl.h and an ondemand/document-inl.h. I like the fact that they are next to each other directory-wise, too.

I would have just made a PR, but there are several large outstanding PRs against these files and I'm going to wait for merge; this is just to telegraph intent and get feedback.

**Comment by lemire** [comment]
I think we need to discuss whether this is pre-0.5 or post-0.5.

I am trying to wrap up 0.5.

**Comment by jkeiser** [comment]
It can wait, if 0.5 is going out in short order. Say, if we intend to release it prior to landing the SAX factoring.

**Comment by jkeiser** [comment]
It's also relatively low-risk and mechanical, so 0.5 could probably be released with it, too.

**Comment by lemire** [comment]
Tentatively marking as 0.5.
