### ISSUE TITLE
parse_many seems to be broken in 0.5.0.

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#1133]
I'm possibly missing something obvious here, but `parse_many` does not appear to work in many cases where I would expect it to.

```cpp
#include "simdjson.h"

int main(void) {
    simdjson::dom::parser parser;
    simdjson::active_implementation = simdjson::available_implementations["fallback"];
    simdjson::dom::document_stream docs = parser.parse_many(
        "{\"hello\": \"world\"}"_padded
    );

    for (simdjson::dom::element doc : docs) {
        std::cout << doc << std::endl;
    }
}
```

The above will raise `what():  The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.`

**Comment by lemire** [comment]
The following works for me...

```
  bool single_document() {
    std::cout << "Running " << __func__ << std::endl;
    simdjson::dom::parser parser;
    auto json = R"({"hello": "world"})"_padded;
    simdjson::dom::document_stream stream;
    ASSERT_SUCCESS(parser.parse_many(json).get(stream));
    size_t count = 0;
    for (simdjson::dom::element doc : stream) {
        std::cout << doc << std::endl;
        count += 1;
    }
    return count == 1;
  }
```

I am going to check with the fallback kernel.

**Comment by lemire** [comment]
@TkTech 

Sorry for the delay.

Let us look at your code...

```C++
    simdjson::dom::parser parser;
    simdjson::dom::document_stream docs = parser.parse_many(
        "{\"hello\": \"world\"}"_padded
    );

 ```

At this point, the padded string has been deleted (its constructor called) so there is no more input.

```C++
   for (simdjson::dom::element doc : docs) {
        std::cout << doc << std::endl;
    }
```

As the loop begins, it tries to parse but the input is gone.


Let me explain. What `parse_many` does is not to parse all of the JSON documents. It parses on demand. At the start of the loop, it parses the first JSON, then at the second iteration, the second JSON and so forth.

This differs from `parse` which does immediately the parsing and allows you to discard the input.

I will improve the documentation.

**Comment by lemire** [comment]
@TkTech So just do this...

```
auto json =  "{\"hello\": \"world\"}"_padded;
simdjson::dom::parser parser;
simdjson::dom::document_stream docs = parser.parse_many(json);
```

So that the `json` variable lives as long as the parser. And you will be fine.

If you think about it... it is logical...

1. We make no copy.
2. We need to access the data to parse the JSON.
3. The parse_many function is lazy.

But it wasn't documented very well. I am fixing this.

**Comment by lemire** [comment]
Thanks for the report. It is now fixed (using new documentation).

The short story is that your code is unsafe because the input is deleted by the time we parse it.

**Comment by TkTech** [comment]
You're right, and it makes sense. I've gotten too used to smarter compilers where this would have been an error.

**Comment by lemire** [comment]
@TkTech 

The compiler is not dumb but our API is a bit dumb.

We can make it an error, I think.

**Comment by lemire** [comment]
@TkTech I made it a compile-time error...

https://github.com/simdjson/simdjson/pull/1137

If you don't understand what is going on, you can still get in trouble, but the new code will make it harder to do the wrong thing.
