### ISSUE TITLE
vcpkg supported in future?

### ISSUE THREAD

**Issue by Edassap** [simdjson/simdjson#1146]
Hi, do you have a plan to support vcpkg? It will be better to pull the lib from vcpkg!

**Comment by TkTech** [comment]
simdjson is already on vcpkg and has been for awhile.

**Comment by lemire** [comment]
Please see instructions at ...

https://github.com/simdjson/simdjson/wiki/vcpkg

**Comment by lemire** [comment]
Closing. If there is an issue with support, please let us know.
