### ISSUE TITLE
Extract child node as string

### ISSUE THREAD

**Issue by benstadin** [simdjson/simdjson#1147]
I have one feature which currently holds me back form switching form Rapidjson to SimdJson. I have a json scheme where there are a number of items for which a type is defined, but there is also one item where the type is dynamic. An example:

```
{
    "a": 123,
    "b": 456,
    "custom_properties": {
        "some_value": "abc"
    }
}
```

Here custom_properties can be any type, dynamically assignable by for example a customer. Internally I keep the representation of that object by parsing the custom_properties to an std::string in my model. Eventually I could copy the node, and keep that as part of my model, but I dislike this approach. 

Or is that already possible with the current API?

**Comment by lemire** [comment]
I do not understand. I expect you will have to elaborate.

With simdjson, you will get the value as an "element". In this case, the type of the element will be "object". Once you have an element in simdjson, you can serialize it back as a minified string.

If you'd like some other functionality, we can certainly discuss it... but it would be helpful if you could be more precise.

**Comment by jkeiser** [comment]
We have an api to do ostream << element, so you could use a string stream to get the json out.

**Comment by lemire** [comment]
@jkeiser 

Can't you just do `simdjson::minify(e)` and get back a string? Or something?

**Comment by jkeiser** [comment]
Well, it seems I did in fact write that function, so yes :) `std::string s = simdjson::minify(e)` should work just fine :)

**Comment by lemire** [comment]
I think it is a documentation issue.

https://github.com/simdjson/simdjson/pull/1153

**Comment by lemire** [comment]
This issue has been closed via improved documentation.

**Comment by benstadin** [comment]
Thanks, that's what I was looking for.
