### ISSUE TITLE
Add runtime dispatching to the on-demand API

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1161]
I am adding this to milestone 0.7. So not for 0.6.

**Comment by jkeiser** [comment]
Obviously contingent on #947 being merged.

**Comment by lemire** [comment]
I consider this issue resolved by https://github.com/simdjson/simdjson/pull/1376 even though it is only stage 1 that gets the runtime dispatching. It is not the case that we can't improve the results further but I think if we want to make it an issue, we should make it clear what we imagine should happen and what the gains should be.
