### ISSUE TITLE
validate_utf8() gives different results depending on implementation

### ISSUE THREAD

**Issue by pauldreik** [simdjson/simdjson#1169]
The fuzzer at https://github.com/pauldreik/simdjson/blob/pauldreik/fuzz_utf8/fuzz/fuzz_utf8.cpp found a difference in utf8 validation between the implementations.
The fuzzer just sends the same input to all implementations and see if they agree.

The following triggers the difference:
```bash
echo -en '                                                               \xff' >tjoff
fuzz/fuzz_utf8 tjoff
# ....snip....
Mismatch between implementations of validate_utf8() found:
haswell returns true
westmere returns true
fallback returns false
```
The data input is 63 spaces followed by an ff byte. I do not think the spaces are particularly important. I believe the fallback implementation is the correct one here (bytes 0xF5-0xFF should never appear in valid utf-8).

**Comment by lemire** [comment]
@jkeiser's code looks like it should handle that...

```
  if (buf[idx] >= 0b11110101) { error = UTF8_ERROR; }
```

**Comment by jkeiser** [comment]
Hmm. It's uint8_t, too, so we shouldn't be having a signed error ... but maybe we are anyway?

**Comment by pauldreik** [comment]
I think the fallback is the correct one, it returns false which is correct according to the documentation.
https://github.com/simdjson/simdjson/blob/6ecbcc7c198b5b61810dee2aeeba879e0e4b8042/singleheader/simdjson.h#L2744-L2746

**Comment by lemire** [comment]
@pauldreik Ah. So the error is with lookup.

Interesting.

**Comment by lemire** [comment]
Hmmm... I can immediately reproduce the issue.

**Comment by lemire** [comment]
Got it now.

**Comment by lemire** [comment]
Verified. The fix is at https://github.com/simdjson/simdjson/pull/1173

As these things tend to be, it was trivial. We have a "check the end of the stream" function... but we were not calling it, for some reason.

**Comment by lemire** [comment]
So you could include bad UTF-8 at the very end of the stream... 

This was us using poorly about own API.

(Well. It was me, to be clear.)

**Comment by pauldreik** [comment]
I think the same thing happens on arm. The following base64 coded input
gave a difference between fallback and arm64:

```
ICAg7pijIO6Yo+6Yo+6Yo+6Yo+6YoyAgICDumKPuk5juo6Mg7pqj7pij7pij7pij7pij7pijICAg
7pij7pij/w==
```

The error report is:
Mismatch between implementations of validate_utf8() found:
arm64 returns true
fallback returns false

The last byte is 0xFF, so the fallback seems to be correct.

Perhaps I should file a separate issue?

**Comment by jkeiser** [comment]
One of the nice things about the generic implementations: you will rarely find a difference between arm64, haswell and westmere.

**Comment by lemire** [comment]
@pauldreik At a high level, this is the same issue. I am somewhat disappointed that our tests did not catch it.

Basically, our SIMD UTF-8 validation scheme processes the data in chunks, then at the end, there is a separate check for the last few bytes. And finally you can determine whether you encountered an error. Yet we simply did not call the "separate check for the last few bytes". So it wasn't a deep bug at all.

Of course, we don't want to have bugs, whether they are deep or shallow, but the great thing with shallow bugs is that the fix takes a couple of minutes.

**Comment by pauldreik** [comment]
Yep, the DRY principle, again!

Well, it will be caught by the fuzzer in https://github.com/simdjson/simdjson/pull/1172. It would be nice to run a CI fuzzing job on arm64 as well, just like the existing github action. Which of the CI services for simdjoson would be suitable to run that?

**Comment by lemire** [comment]
We run ARM tests on drone: https://github.com/simdjson/simdjson/blob/master/.drone.yml

There may be other systems too... but drone supports ARM.
