### ISSUE TITLE
Move include/simdjson/inline/* to *-inl.h

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1174]
To prevent namespace collisions, we should follow the Google standard for inline headers and name them the same as the declaration header, with -inl.h instead of .h. On Demand has made this leap, but we should do the same for everything in inline/. Easier to find the files.

**Comment by jkeiser** [comment]
Note: I'm planning to wait until #947 is merged to mess with this.

**Comment by lemire** [comment]
@jkeiser I expect that this issue can be closed.

**Comment by jkeiser** [comment]
Indeed :)
