### ISSUE TITLE
[ondemand] Fuzz testing

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1185]
#947 has a lot of possible permutations. basictests might not cover it all.

I'm not sure precisely how to fuzz test it, but besides generating the JSON itself, full vs. partial iteration (breaking out of one or more for loops) needs to be tested thoroughly, so different programs need to be generated as well.

**Comment by pauldreik** [comment]
Ddid you want fuzzing to make sure it is clean before merging? Hit me up when it builds clean and you think it is stable enough.

Regarding how to write the fuzzer, I usually start with a code example or unit test, then look at coverage from oss-fuzz to see what is missing and then try to hit those paths locally, running the fuzzer in the debugger.

**Comment by pauldreik** [comment]
This is inplace, perhaps not fully covered yet, but sufficient to close this ticket unless you think otherwise.

**Comment by lemire** [comment]
I will let John speak up.

**Comment by jkeiser** [comment]
I'm ok with that--we can improve as time goes by. Thank you :)
