### ISSUE TITLE
validate_utf8() for fallback allows unnecessary leading zeros in four byte sequence

### ISSUE THREAD

**Issue by pauldreik** [simdjson/simdjson#1187]
When getting #1172 ready for merging, I found a case where the simd implementations says a byte sequence is NOT valid utf-8, while the fallback implementations says it is valid.

This is the test case:
```sh
echo -en '\xf0\x8f\xbf\xbf' >crash.json
```
which is (if I get this correct...) the four byte sequence:

 - 0b1111 0000 (payload: 000)
 - 0b1000 1111 (payload 001111)
 - 0b1011 1111 payload (111111)
 - 0b1011 1111 payload (111111)

It seems like this could have been coded as a three byte sequence instead, because the first six bits of the payload are zeros. I do not know if utf-8 forbids using a unnecessary long sequence.

`fuzzer_utf8` aborts with
```
ossfuzz-out/fuzz_utf8 crash.json
#snip....
Mismatch between implementations of validate_utf8() found:
haswell returns false
westmere returns false
fallback returns true
```

Python (script below), says it is invalid
```python
#!/usr/bin/python3
import codecs
try:
    f = codecs.open('crash.json', encoding='utf-8', errors='strict')
    for line in f:
        pass
    print("Valid utf-8")
except UnicodeDecodeError:
    print("invalid utf-8")
```

I believe the fallback implementation should match what the others say.

**Comment by lemire** [comment]
At a glance, it should catch it...

```
if (buf[idx] == 0b11110000 && buf[idx+1] <= 0b10001111) { error = UTF8_ERROR; }
```
https://github.com/simdjson/simdjson/blob/master/src/fallback/dom_parser_implementation.cpp#L83-L92

**Comment by lemire** [comment]
This code is never called because the fallback validator only operates on strings. Not in what falls outside of the strings.

**Comment by lemire** [comment]
What @jkeiser 's code does is that it detects these "outside of string" characters and flag them as "structural characters". He does this because he knows he will catch the error later (I think). So this might be something that we need to fix with documentation because some kernels will detect "out of strings" UTF-8 as UTF8 errors and not others. That is fine if it is documented.

This says nothing about the issue you have encountered.

**Comment by lemire** [comment]
Verified.

https://github.com/simdjson/simdjson/pull/1192

**Comment by lemire** [comment]
The issue was introduced by me when I borrowed fast code from the Fushia project. Their function had bugs, and I thought I had caught them all, but apparently not.

**Comment by lemire** [comment]
Note that this does not affect JSON parsing.

**Comment by lemire** [comment]
Fixed. Thanks for the report. It is very useful to have such reports.

**Comment by pauldreik** [comment]
Thanks for fixing it! Will try to get the utf8 fuzzer merged now.
