### ISSUE TITLE
Using deprecated functionality in github actions

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1207]
We're getting a warning when running github actions:

```
Check warning on line 1 in .github

@github-actions
github-actions / ubuntu-build

.github#L1
The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

We should do the suggested :)

**Comment by pauldreik** [comment]
This could be closed, right? _grep -rin add-path .github_/ gives nothing.

**Comment by lemire** [comment]
I am not sure we ever had a add-path command. I think it upstream in one of the actions we use. It may be resolved. I am not sure.

**Comment by lemire** [comment]
Presumably fixed. Closing.
