### ISSUE TITLE
"Fuzz and run valgrind / build (pull_request)" failing in CI

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1209]
The "Fuzz and run valgrind / build (pull_request)" test is failing consistently in CI, even on documentation-only changes. See [here](https://github.com/simdjson/simdjson/pull/1205/checks?check_run_id=1215001003) for an example.

The failure is in the "Install packages necessary for building" step, and seems to be related to an offline package source for azure-cli:

```

Get:26 https://apt.llvm.org/bionic llvm-toolchain-bionic-10/main amd64 Packages [8762 B]
Hit:28 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease
Ign:29 https://packages.microsoft.com/repos/azure-cli bionic InRelease
Err:30 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
  Could not connect to packages.microsoft.com:443 (13.90.56.68), connection timed out [IP: 13.90.56.68 443]
Err:31 https://packages.microsoft.com/repos/azure-cli bionic Release
  Unable to connect to packages.microsoft.com:https: [IP: 13.90.56.68 443]
Reading package lists...
E: The repository 'https://packages.microsoft.com/repos/azure-cli bionic Release' no longer has a Release file.
Error: Process completed with exit code 100.
```

**Comment by jkeiser** [comment]
Ping @pauldreik, who might have sufficient context for what the package is used for :)

**Comment by pauldreik** [comment]
Quick look: This is a 404, seems like a problem with the github actions system rather than anything related to simdjson and/or fuzzing. Have had such problems in the past, just wait a while and see if "it fixes itself". Will check more carefully later!

**Comment by pauldreik** [comment]
Ok, had a closer look, it is a leftover merge conflict checked in:

https://github.com/simdjson/simdjson/blob/a9480a768bd80174928fee25ecc33947faad4603/fuzz/build_fuzzer_variants.sh#L48-L53

@jkeiser could you fix it? Otherwise you have to wait a few days for me to get around to it.
