### ISSUE TITLE
Version 0.6 outline

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1225]
Version 0.6 is mostly done. Let us publish it! Here is a sketch of the outline.

(for discussion)

-----

Release 0.6 features faster serialization, updated number parsing and a new parsing API (On Demand).

*Novel parsing approach*: Prior to release 0.6, the simdjson only supported the DOM model. In the DOM model, you parse the entire document eagerly and then query the resulting parsed document. With release 0.6, we have introduced an innovative  new query model called "On Demand" (credit: @jkeiser). As the name suggests, the programmer can now access only the components of the JSON documents that are needed. It is useful when the dialect of the JSON document is known at compile-time. It can multiply the performance: on a benchmark where we retrieve unique identifiers from a file, we go from 2.3 GB/s to 4.6 GB/s. Compared to the generic DOM approach, the On Demand strategy may improve parsing speed and reduce memory usage. The On Demand API is both easy to use and highly efficient. We encourage our users to try out the new On Demand API and to provide constructive feedback. Though it is well tested, we consider On Demand to be a novel and experimental feature that will receive  further updates in the upcoming releases including runtime dispatching. Users should be mindful that the On Demand API is subject to change in future releases, we encourage testing more than deployment.  Please check our documentation:
https://github.com/simdjson/simdjson/blob/master/doc/ondemand.md

*Performance*:
  - Serializing a parsed JSON element is about 10x faster compared to previous releases.

*New features*:
 - We make it easier to check whether a given implementation/kernel is available at runtime with a new function `my_implementation->supported_by_runtime_system()`. 

*Correctness*:
  -  Serialization is now guaranteed to be locale-independent.
  -  We have redone the number parsing routines and extended our testing. We no longer fall back on the system's C library thus avoiding potential sources of unexact parsing.
  - Fuzz testing has been extended. E.g., our standalone UTF-8 validation is now fuzz tested. (Credit @pauldreik)

-----

**Comment by lemire** [comment]
> Perhaps say something about the impressive recent 1:st position obtained on the Kostya Benchmark?

It would be interesting to add a reference to benchmark numbers.

**Comment by lemire** [comment]
@jkeiser Ok. I am doing the release today.

**Comment by pauldreik** [comment]
Nice writeup, and thanks for the mention! Do you have any thoughts on when and what should be included in a 0.7 release?

**Comment by lemire** [comment]
We do have milestones on github, so you can review what was tagged. But we have not discussed it yet!

**Comment by jkeiser** [comment]
For my part, the main priority is to polish the On Demand Api and move it out of preview. If there were time I'd want to build streaming stage 1... but there won't be (for me anyway :). I imagine as soon as we polish it we'll release, rather than wait for more stuff.

Polish items include order insensitive objects, bugfixes including depth tracking, possibly recursion optimization, and (I expect) more benchmarking and snazzier benchmark results.

**Comment by lemire** [comment]
I will open a distinct issue to discuss this.
