### ISSUE TITLE
Make it easy for the user to go from raw_json_string to something more usable 

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1231]
The On Demand API relies on the `raw_json_string` type, but you can't print it, convert it to a string or do anything much with it.

**Comment by jkeiser** [comment]
Yeah, all you can do right now is `==` or use `unescape(buffer)` to have it unescape into a preallocated buffer and return a string_view to it.

I can see having a method to allocate a `std::string`.

**Comment by lemire** [comment]
> I can see having a method to allocate a std::string.


I have an implementation in a PR.
