### ISSUE TITLE
Autocomplete on simdjson_result with exceptions off can lead to antipattern usage

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1243]
Many people will learn an API via autocomplete. In [this Twitter thread](https://twitter.com/jkeiser2/status/1318653954108977152), a user was trying to find out how to get the value out of a simdjson_result<array> variable. This user was running with exceptions disabled. When they typed ".", a nice list of member variables and methods showed up. However, they ended up selecting the least idiomatic option:

- **array() cast** was unavailable because exceptions were disabled. I doubt it would show up anyway.
- **.value()** was unavailable because exceptions were disabled. The user definitely would have selected this--they even suggested we add it to the API.
- **.get()** was in the list, but has a non-specific name, is templated and involves an out-variable, so they (likely) skipped it as a "method of last resort." We have been trained to treat non-specific names as "unimportant system details," as a non-specific name doesn't seem designed with human readers in mind.
- **.first** was in the list, and while its name was also non-specific, it was a member variable and had the right type, so the user rightly decided it contained the value they needed.

Thus, they selected .first, which we prefer people not do.

The user understood error codes, and wrote code like this:

```c++
auto elem = doc["foo"]; // Not sure what the expression was, this is just an example.
if (!elem.error() && elem.is_array()) {
  for (auto child : elem.get_array().first) { // Not sure if this is what they were doing with it, but it's a good guess)
  }
}
```

Several things could have made this better:

1. Don't expose `.first` from simdjson_result, so that the user is forced to look for other alternatives and ultimately find `.get()`. This would be an API change, but as use of these is discouraged, it might be an acceptable one.
2. Enable .value() when exceptions are off, even though it's "unsafe." We'd be asking no-exception users to understand that they have to check the error, but that's not unreasonable given that even having ".value()" implies there must be something else on the result besides a value (plus, autocomplete would include ".error()").
3. Create `.value(arr)` as an alias for `.get()`. The user would likely have chosen this if they saw it, even if `.first` was there.

**Comment by jeremyong** [comment]
Thanks for writing this issue @jkeiser .

If I could suggest a fourth option (additive to the other options): `.value_unsafe()` which would be available regardless of if exceptions are disabled or not. In some cases (e.g. parsing a json file with a known schema exported by the user), it is acceptable to extract values directly without any safety measures.

**Comment by lemire** [comment]
@jeremyong 

> it is acceptable to extract values directly without any safety measures

It is certainly a lot better to expose `value_unsafe()` than to expose `value()` while trying to communicate that it is potentially unsafe. For better or worse, people trust the name of the function more than they trust the documentation.
