### ISSUE TITLE
Can't disable Westmere and fallback implementations on MSVC targeting AVX2

### ISSUE THREAD

**Issue by 2-5** [simdjson/simdjson#1247]
**Describe the bug**
Can't disable the Westmere and fallback implementations on MSVC when compiling for AVX2.

**To Reproduce**
I'm trying to disable the westmere and fallback implementations, to force the builtin implementation used by on-demand to haswell:

    -DSIMDJSON_IMPLEMENTATION_WESTMERE=0
    -DSIMDJSON_IMPLEMENTATION_FALLBACK=0
    /arch:AVX2

Compilation fails with this error message:

    All possible implementations (including fallback) have been disabled! simdjson will not run.

This seems to be caused by this line:
```C
#define SIMDJSON_CAN_ALWAYS_RUN_HASWELL ((SIMDJSON_IMPLEMENTATION_HASWELL) && (SIMDJSON_IS_X86_64) && (__AVX2__) && (__BMI__) && (__PCLMUL__) && (__LZCNT__))
```

On MSVC with `/arch:AVX2`, `__AVX2__` is defined, but those other macros (`__BMI__`, `__PCLMUL__`, `__LZCNT__`) are not.

The code works successfully if I don't try disabling the westmere and fallback implementations, with `active_implementation` showing `haswell` and `builtin_implementation` showing `fallback`.

As a workaround, I use `-DSIMDJSON_BUILTIN_IMPLEMENTATION=haswell`, but this is not documented and not sure if supported.

**Configuration (please complete the following information if relevant):**
 - OS: Windows 10 64 bit
 - Compiler Visual Studio 2019
 - Version 14.27.29110

**Indicate whether you are willing or able to provide a bug fix as a pull request**
No

**Comment by jkeiser** [comment]
I can't check right now but I've always set them =OFF rather than =0. Can you check if that works? 

Also, if you intend to disable all but the native implementation, the simpler way is to compile for the current host processor (not sure about msvc but on Linux it's - march=native. If you compile for an instruction set, simdjson will disable any implementations below it because they can never be selected.

**Comment by jkeiser** [comment]
Oh. I see, that's not cmake options. That's weird behavior and probably a bug. Maybe try compiling without - D and then see what implementations actually got enabled?

**Comment by jkeiser** [comment]
(Because as noted, it should be automatically disalblng anything other than Haswell. It might be a buggy interaction between - D and autodetection.)

**Comment by 2-5** [comment]
When compiling under MSVC targeting AVX2 (`/arch:AVX2`), without any `-D`, all three backends are compiled, `active_implementation` is `haswell` and `builtin_implementation` is `fallback`.

**Comment by jkeiser** [comment]
OK, that's unexpected behavior to me, if you are using simdjson master or 0.6. If you are using an earlier version, would you mind trying one of those? We changed implementation selection in 0.6 to the above behavior.

**Comment by 2-5** [comment]
I'm using 0.6, upgraded to it today.

**Comment by 2-5** [comment]
This line is causing the problem:

    #define SIMDJSON_CAN_ALWAYS_RUN_HASWELL ((SIMDJSON_IMPLEMENTATION_HASWELL) && (SIMDJSON_IS_X86_64) && (__AVX2__) && (__BMI__) && (__PCLMUL__) && (__LZCNT__))

`__BMI__`, `__PCLMUL__` and `__LZCNT__` are not defined under MSVC when targeting AVX2, only `__AVX2__` is defined.

**Comment by lemire** [comment]
> __BMI__, __PCLMUL__ and __LZCNT__ are not defined under MSVC when targeting AVX2, only __AVX2__ is defined.


That's correct and we don't actually need to check them because, to my knowledge, there is no CPU with AVX2 but without BMI, PCLMUL and LZCNT.

**Comment by jkeiser** [comment]
That's a real bug then ; even with that, though, Haswell should get compiled by default!

A workaround for you might be to add a - D for Haswell and set it to 1...

**Comment by 2-5** [comment]
Haswell does get compiled by default, but `builtin_implementation` is set to `fallback`, which according to the on-demand docs is slow.

As a workaround, I use `-DSIMDJSON_BUILTIN_IMPLEMENTATION=haswell`, but this is not documented and not sure if supported.

**Comment by jkeiser** [comment]
I think I probably made it work, but it's not a long term supported thing. I'm glad it lets you work around it while we sort this out, though!
