### ISSUE TITLE
[DOM] Expose the total number of elements contained within an array.

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#1251]
`dom::array` should expose the total number of elements contained within it, not just the number of elements at the current scope.

Since the `[` element on the tape encodes the location of its closing `]`, when a user provides typing information for an array we can make a best-guess at how much space we need to store it. It should be clear this API is for advanced usage in the documentation.

https://github.com/TkTech/pysimdjson/pull/59 provides a mechanism for efficiently copying homogeneous arrays around Python without uplifting to complex types. To do this, we have the user explicitly provide the type they want. For example, loading GeoJSON into numpy:

```python
numpy.frombuffer(
    doc.at_pointer('/features/0/geometry/coordinates')
    .as_buffer(of_type='d')
)
```
For 1-dimensional arrays, we just call `m_vec->reserve(src.size())` and all is well. However, for n-dimensional arrays, we have no way of guessing what size of container we really need and need to re-allocate each time we descend into a new scope if `m_vec->capacity() - m_vec->size() < arr.size()`.

By exposing the total number of elements between the start and end, I can do a single allocation which will slightly over-allocate depending on the number of nested `[` and `]` elements, which is fine (and can be fixed after with a single `shrink_to_fit`.

**Comment by lemire** [comment]
That sounds sensible at a glance. We certainly want to support what you describe.
