### ISSUE TITLE
Milestone 0.7 outline

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1257]
With 0.6 behind us, we should discuss what is planned for 0.7.

* Polish the On Demand Api and move it out of preview, see project https://github.com/simdjson/simdjson/projects/5
* Try to make some progress regarding runtime dispatching for On Demand Api (https://github.com/simdjson/simdjson/issues/1161) 
* It looks like we might get accelerated support for POWER processors (https://github.com/simdjson/simdjson/pull/1254) thanks to @danlark1 ; at least as a preview feature
* It would be interesting to upgrade our fallback architecture (https://github.com/simdjson/simdjson/issues/1245) and it is tentatively part of 0.7, but unless someone jumps that it, it will probably get delayed.

I think that @jkeiser is mostly preoccupied with the API design: removing rough edges from the point of view of users.

We want to be flexible on the content of 0.7 because we don't want to delay the released of an improved On Demand API... as we eager to get it out there in production.

I (@lemire) am preoccupied with runtime dispatching for the On Demand API. I am not necessarily aiming to crack the problem for release 0.7, but I am hoping that we will have a better grasp on the problem since it is an essential feature for 1.0.

cc @pauldreik @jkeiser

**Comment by pauldreik** [comment]
Here is my input to the discussion (it adds to the above, not replaces)

I want get the fuzzer coverage up, I track this in #368 .

Getting #1220 is part of this (fuzzing ondemand).

There are also some simdjson api functions that are deprecated, could we put some cmake flag which disables the deprecated part (off by default) so the fuzzers can build without it? That way, the fuzz coverage will be more relevant and it is easier to see what to work on.

And here are some nice to have things:
Perhaps the cmake cleanup could be included as well?

I also wonder what your thoughts are on the CI situation - some of the jobs take really long (appveyor). Could that functionality be duplicated and/or replaced?

Tracking binary size and other metrics over time. There was some effort a while ago (early 2020?) about storing benchmark results somewhere, what happened with that? And could it be appended to include other metrics such as binary size and compilation time?

**Comment by lemire** [comment]
> There are also some simdjson api functions that are deprecated, could we put some cmake flag which disables the deprecated part (off by default) so the fuzzers can build without it? That way, the fuzz coverage will be more relevant and it is easier to see what to work on.

I am not sure what it entails, but it sounds reasonable.

I think that many of the deprecated functions will be removed when we reach 1.0. Anything that is as old as the original API from releases 0.1 and 0.2... should be removed, I think... I normally do not want to remove deprecated features, but we will need to do some cleaning because some of the old stuff is definitively in the way. It is likely causing some unnecessary confusions at times.

**Comment by lemire** [comment]
> Perhaps the cmake cleanup could be included as well?


Yes. Of course.

**Comment by lemire** [comment]
> Tracking binary size and other metrics over time. There was some effort a while ago (early 2020?) about storing benchmark results somewhere, what happened with that? And could it be appended to include other metrics such as binary size and compilation time?


We are definitively tracking some of our performance metrics in a persistent manner.

Go to our README on Github, there is a badge for Ubuntu 20. Click on it.

It is an Easter egg.

I expect that the DOM code is pretty mature. I don't think we will do much to change it before 1.0. There might be tweaks here and there, but I don't expect a reengineering effort in the near future.

There is a whole lot of tracking we could do, but since we are trying to switch our focus to On Demand, it brings about new challenges. For obvious reasons, we are not tracking On Demand at all... and we are not fuzzing it either.

I think that's where our efforts should go. Given that we lack raw performance tracking and fuzzing... we have low hanging fruits!!!

**Comment by lemire** [comment]
I would say that fuzzing On Demand would be fantastic!

**Comment by pauldreik** [comment]
> > There are also some simdjson api functions that are deprecated, could we put some cmake flag which disables the deprecated part (off by default) so the fuzzers can build without it? That way, the fuzz coverage will be more relevant and it is easier to see what to work on.
> 
> I am not sure what it entails, but it sounds reasonable.

See #1264

**Comment by pauldreik** [comment]
> I would say that fuzzing On Demand would be fantastic!

Yep, waiting for the CI to complete on #1220 and if it's green, it's ready for review and merge!

**Comment by pauldreik** [comment]
> We are definitively tracking some of our performance metrics in a persistent manner.
> 
> Go to our README on Github, there is a badge for Ubuntu 20. Click on it.
> 
> It is an Easter egg.

Nice! Is there an easy way to insert other data there (like the fuzz coverage)?

**Comment by lemire** [comment]
@pauldreik 

> Nice! Is there an easy way to insert other data there (like the fuzz coverage)?

There isn't at the moment. In fact, we have no public API whatsoever. All we do is generate a static web page using a cron job. If there was a public API, then this web page could retrieve such data and display it, but that's the extend of what would be doable cheaply.

**Comment by pauldreik** [comment]
Now when simdjson runs on power as well, we should have a fuzzer (just like we have on arm). I think it is responsible to fuzz, as simdjson often is used on untrusted input.

**Comment by danlark1** [comment]
Let me implement the fuzzer then

**Comment by pauldreik** [comment]
> Let me implement the fuzzer then

Sure! The fuzzers are platform agnostic, it should be sufficient to run it like on arm:

https://github.com/simdjson/simdjson/blob/500e4c3572715700915d151545eeea1fa55d91db/.drone.yml#L391-L410

The workaround on arm for sanitizers not working fully is hopefully not needed.

**Comment by lemire** [comment]
I am growing more and more convinced that making document_stream more robust is a key step for release 0.7.

**Comment by jkeiser** [comment]
That would be more than enough to justify a release. I am making progress in fits and starts but don't know exactly when I will be finished with on demand updates; if parse many robustness happens first, don't delay the release on my account :)

**Comment by lemire** [comment]
@jkeiser My thinking too.

I will budget my time focusing on making document_stream more usable and robust.

It wasn't clear before @pauldreik's work, but my own finding and his work, plus other discussions suggest that document_stream really needs to be more finely tuned.

Thankfully, it is not super hard.

**Comment by pauldreik** [comment]
> Let me implement the fuzzer then

@danlark1 Do you mind if I have a go at this?

**Comment by danlark1** [comment]
> > Let me implement the fuzzer then
> 
> @danlark1 Do you mind if I have a go at this?

I am doing this project together with my student and it was their responsibility. I can nudge them right now. Is it necessary to put fuzzing in the current release? If yes, probably you should take it then but I just wanted to give some real experience with fuzzing to my student

**Comment by pauldreik** [comment]
> > > Let me implement the fuzzer then
> > 
> > 
> > @danlark1 Do you mind if I have a go at this?
> 
> I am doing this project together with my student and it is their responsibility. I can nudge them right now. Is it necessary to put fuzzing in the current release? If yes, probably you should take it then but I just wanted to give some real experience with fuzzing to my student

No problem, I just want that the new powerpc addition is not released un-fuzzed.

**Comment by lemire** [comment]
@jkeiser  I moved every fancy thing related to ondemand to 0.8 or later. Please ping me if this feels wrong. The goal is to focus on document_stream fixes for 0.7.

**Comment by pauldreik** [comment]
See a failed attempt at fuzzing power here: https://github.com/simdjson/simdjson/pull/1326
Won't have time to fix that fast enough for the 0.7 timeframe.

The stream parser is now up on oss-fuzz, see https://storage.googleapis.com/oss-fuzz-coverage/simdjson/reports/20201203/linux/file_view_index.html
There does not seem to be any pending crashes not yet reported.
That means I am happy with stream parser for now (the thread sanitizer issues are to be solved later).

So, from my point of view, 0.7 is ready!

**Comment by lemire** [comment]
@pauldreik 

Good.

I have been experimenting and I suspect that the clang thread sanitizers has false positives. It is not smart enough to figure out what we are doing. A blog post will follow.

**Comment by jkeiser** [comment]
I'm on board with moving on demand improvements to 0.8, especially since I'm not done with them :) I got time to bring it a lot closer this week, though--should have something to show soon.

**Comment by lemire** [comment]
@jkeiser Excellent.
