### ISSUE TITLE
Look into tailor-made Docker images

### ISSUE THREAD

**Issue by friendlyanon** [simdjson/simdjson#1270]
Currently there is a lot of repeated `apt-get` usage that download a lot of things in the project's CI workflows. Here is one example from the `i386-gcc` operation:
```
After this operation, 115 MB of additional disk space will be used.
After this operation, 279 MB of additional disk space will be used.
```

Personally I don't have any experience with Docker, but I think this is something worth looking into.  
From what I understand, Docker can build ready-to-go images that have to be downloaded just once, which would save on the CPU and IO operations necessary for installing via `apt-get`.

**Comment by jkeiser** [comment]
Certainly having something that runs faster is Good :) I think we'd mainly need two things: a place to host them (docker.io?) and a way to keep them up to date when base images and relevant packages change.

**Comment by friendlyanon** [comment]
Personally I'm less interested in speed and more interested in avoiding unnecessary environmental impact. simdjson does run a lot of CI tasks with each push, so it'd be nice to gain a little on that end.

I am hopeful that Docker images can be cached and reused without having to make many many roundtrips to set up the environment for the actually meaningful tasks.

**Comment by lemire** [comment]
Possibly a duplicate of https://github.com/simdjson/simdjson/issues/757

> Personally I'm less interested in speed and more interested in avoiding unnecessary environmental impact.

I am sure @jkeiser did not mean "faster" in a purely restrictive sense. Faster is a proxy for other things like energy, environmental impact and so forth.

**Comment by friendlyanon** [comment]
Ah, I made a fool of myself. I did not search for a similar issue. I'll close this and continue in the aforementioned one.
