### ISSUE TITLE
Our bash amalgamation script is ridiculously slow

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1277]
On a powerful laptop... our amalgamate.sh script takes 4 seconds. That is not acceptable. It runs regularly as part of our tests. It looks to be IO heavy with 1.5 s in system space, but even the user time is high (2.5 s).

Why is it so incredibly slow? Yes... we have over a megabyte of textfiles... but it shouldn't take seconds to process a megabyte of text.

```
$ time ./amalgamate.sh

Giving final instructions:
Try :
c++ -O3 -std=c++17 -pthread -o amalgamate_demo amalgamate_demo.cpp  && ./amalgamate_demo ../jsonexamples/twitter.json ../jsonexamples/amazon_cellphones.ndjson

real	0m4.018s
user	0m2.463s
sys	0m1.469s
```

cc @friendlyanon @pauldreik

**Comment by lemire** [comment]
Profiling is doable...

https://stackoverflow.com/questions/5014823/how-to-profile-a-bash-shell-script-slow-startup

**Comment by pauldreik** [comment]
I am giving a shot at writing it in python

**Comment by friendlyanon** [comment]
Is Python already in use in the CI workflow? If not then maybe it's not too wise to introduce it as a dependency.

CMake allows for writing scripts, maybe that alternative could be explored first before reaching for Python or something else.

**Comment by friendlyanon** [comment]
I tried the CMake script approach.  
Shell script time:
```
real    0m12.233s
user    0m4.725s
sys     0m4.393s
```
CMake script time:
```
real    0m8.508s
user    0m4.309s
sys     0m1.712s
```
Python script time:
```
real    0m1.505s
user    0m0.131s
sys     0m0.581s
```
Yeah, I think the Python script is fine.

**Comment by lemire** [comment]
We have at least established that we can save many seconds of computing.

**Comment by pauldreik** [comment]
@friendlyanon would you like to share your script? I have never seen such a thing.

**Comment by friendlyanon** [comment]
I have deleted the CMake script after measuring the times, as it did not look anywhere near as good as the Python one, but it was basically a 1:1 port of the Python script.

**Comment by myd7349** [comment]
https://github.com/myd7349/Ongoing-Study/blob/master/notes/Amalgamation.md
