### ISSUE TITLE
Use a PPA for a ppc64le build of CMake for Travis CI

### ISSUE THREAD

**Issue by friendlyanon** [simdjson/simdjson#1294]
Related: https://github.com/simdjson/simdjson/pull/1293#issuecomment-722859038  
It seems the green checkmarks suddenly turning red strike again.

I have looked around on the web and it seems there is not a single apt repository that has a CMake build anywhere near recent enough.

For this reason I have put this [demo](https://github.com/friendlyanon/test-cmake-ppa) together of a PPA hosted on Github containing CMake 3.18.4 built for ppc64le and verified by running it on [Travis CI](https://travis-ci.org/github/friendlyanon/test-cmake-ppa/builds/741959978).  
The main purpose of the test script on Travis CI is to test the ability of the package to connect to HTTPS hosts and to extract `zip` files.

I can compile the steps I took to make a ppc64le CMake package if there is demand, however it wasn't a very straightforward process to do so on an x86_64 host.

@lemire the steps to set the PPA up were taken from [this blogpost](https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html) or if you are fine with me owning the private key, then I can just copy the demo over.

**Comment by lemire** [comment]
>  if you are fine with me owning the private key, then I can just copy the demo over.

At a glance, it does not sound too scary. The consequence is that you and you alone can change the PPA, correct?

If that is all there is to it, then it is fine.

Assuming that you are an evil maniac, the worse you could do is temporarily cripple our tests.
