### ISSUE TITLE
Expose in parse_many the location of the end of the last document

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1299]
Some users who use the parse_many API would like to be told about the location of the end document. Possibly we would also want to allow users to stop processing the current chunk with the last complete document.

(Could be a patch release?)

cc @jkeiser

**Comment by jkeiser** [comment]
Oh! Stopping at the last (partial) document does seem important, too :)

**Comment by lemire** [comment]
So we want something whereas you are given a chunk of data, you want to find the last complete element and then start to iterate on the chunk. It almost feels like this would be a distinct function. It could do away with multithreading for now.

Maybe we can discuss the API issue first, because I don't expect that the implementation is tricky. We have the underlying infrastructure given @jkeiser's last revision.

**Comment by jkeiser** [comment]
I could imagine a document_stream::truncate_last_partial_document(), which returns the new length (which is the index at the start of the last partial document, or the end of the buffer if all documents are complete). That would handle both problems at once.

**Comment by lemire** [comment]
hmmm...

**Comment by lemire** [comment]
Still on my "soon to do". I want to at least prototype something.

**Comment by lemire** [comment]
@jkeiser 

Ok. Our existing API almost handles this already except for truncated strings.

https://github.com/simdjson/simdjson/pull/1301

Truncated strings are going to be a nasty problem, generally. But I am hopeful that we can do a small change to our API to offer a workable fix to this problem.

**Comment by lemire** [comment]
@jkeiser  I think that introducing a ` document_stream::truncate_last_partial_document()` function is going to add a lot of complexity... hence by "hmmm..." answer. I would love to fix this issue by adding almost nothing new.
