### ISSUE TITLE
Naked document_stream iterators can trigger infinite loops when not dereferencing the JSON contents (odd edge case)

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1302]
The following will loop endlessly:

```C++
    auto json = R"([1,23]  {"key":"value}  )"_padded;
    simdjson::dom::parser parser;
    simdjson::dom::document_stream stream;
    ASSERT_SUCCESS( parser.parse_many(json).get(stream) );
    size_t count = 0;
    // We do not touch the document, intentionally.
    for(auto i = stream.begin(); i != stream.end(); ++i) { 
      count++; 
    }
```

I think it is a bug. It is unlikely to affect users per se, since this is an uncommon use, that we do not document, but it should still be fixed.

I am submitting a PR to verify the issue.

cc @jkeiser

**Comment by pauldreik** [comment]
Is the code in the proposed fuzzer sufficiently "not touching the document" for this? Otherwise, I could modify it slightly.

See https://github.com/simdjson/simdjson/pull/1304/files#r525423908

**Comment by lemire** [comment]
@pauldreik It is an API usage usage and unrelated to the JSON content. I can put any stream of JSON documents. The key point is that if you do not dereference the iterator, you end up with an infinite loop. Of course, it makes little sense to use the iterator that way, but...

So... it is not an issue that we need fuzzing for, I think.

(Note: I expect that it is a tiny issue.)

**Comment by lemire** [comment]
Ok. It is a small issue. The problem is that the ++ operator would not check for general errors, just empty documents. I think my PR fixes the issue now.
