### ISSUE TITLE
ndjson - null ptr dereference

### ISSUE THREAD

**Issue by pauldreik** [simdjson/simdjson#1311]
Use the fuzzer in https://github.com/simdjson/simdjson/pull/1304

To reproduce, checkout that branch and then:
```shell
fuzz/build_fuzzer_variants.sh
mkdir -p out/ndjson
build-sanitizers-O0/fuzz/fuzz_ndjson out/ndjson
```
It should crash easily, within seconds.

This happened when running the fast fuzzer (without sanitizers)
```
paul@ink:~/code/delaktig/simdjson$ build-fast/fuzz/fuzz_ndjson out/ndjson/
INFO: Seed: 36919529
INFO: Loaded 2 modules   (3918 inline 8-bit counters): 3726 [0x7fe6e792f0c8, 0x7fe6e792ff56), 192 [0x471fb8, 0x472078), 
INFO: Loaded 2 PC tables (3918 PCs): 3726 [0x7fe6e792ff58,0x7fe6e793e838), 192 [0x472078,0x472c78), 
INFO:     1871 files found in out/ndjson/
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 1871 min: 1b max: 593b total: 172231b rss: 24Mb
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==27958==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004532f4 bp 0x7fe6e58c2e90 sp 0x7fe6e58c2e40 T27974)
==27958==The signal is caused by a READ memory access.
==27958==Hint: address points to the zero page.
    #0 0x4532f3 in simdjson::dom::stage1_worker::start_thread()::'lambda'()::operator()() const (/home/paul/code/delaktig/simdjson/build-fast/fuzz/fuzz_ndjson+0x4532f3)
    #1 0x7fe6e79fab2e  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbbb2e)
    #2 0x7fe6e773efa2 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7fa2)
    #3 0x7fe6e76444ce in clone (/lib/x86_64-linux-gnu/libc.so.6+0xf94ce)

UndefinedBehaviorSanitizer can not provide additional info.
==27958==ABORTING
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x35,0x23,0x30,0x5b,0x5b,0x30,0xc,0xfc,
5#0[[0\x0c\xfc
artifact_prefix='./'; Test unit written to ./crash-fd2c53ca6156191e371e6ecb11bf1c60f7fc4da5
Base64: NSMwW1swDPw=
```

**Comment by lemire** [comment]
It seems that the following returns an error condition... 

``` C++    
     simdjson::dom::parser parser;
     simdjson::padded_string input = decode_base64("NSMwW1swDPw=");
     print_hex(input);
     simdjson::dom::document_stream stream;
     auto error = parser.parse_many(input).get(stream);
 ```

The base64 "NSMwW1swDPw=" string decodes to something that is not valid.

And it looks to run fine with sanitizers.

Reference:
https://github.com/simdjson/simdjson/pull/1318/files

**Comment by lemire** [comment]
Accidentally, one could set the batch size to an unreasonable value (e.g., 0): let us guard against it: https://github.com/simdjson/simdjson/pull/1319

**Comment by pauldreik** [comment]
The fuzzer consumes part of the fuzz data to setup parameters, so your code example is not doing the same thing as the fuzzer. You will have to use the fuzzer to reproduce it. I put a break in the debugger and ran, it uses batch_size 3.
If I manually set the batch size to something bigger (I picked 10000), the fuzzer stops finding things! This suggests that the issue is not limited to having a ridiculously low batch size but rather when it is smaller than the total document size.

The fix in #1319 is not sufficient to fix this issue (but other fixes I have yet not looked at may be fine)

**Comment by jkeiser** [comment]
Is there a way to reproduce the exact parameters the fuzzer created, for a repro?

**Comment by pauldreik** [comment]
> Is there a way to reproduce the exact parameters the fuzzer created, for a repro?

Yes!
Let's see how my instructions work. follow "reproducing" at https://github.com/simdjson/simdjson/blob/master/fuzz/Fuzzing.md

Please give me feedback on what to improve in case the above instructions wont work or are difficult to follow!

The difficulty is that the crash data is parsed by the fuzzer to split it into parameters. In this case, batch size and alleged json (aka garbage). Some of the fuzzers interpret all the fuzz data as json, so it is easier to see what the input is.

The next step is to show the input of the api parameters to json. You have at least two options, printf style debugging or use a debugger. 

# printf style
Once it crashes on you, easiest is probably to add a printout (```std:cerr<<batch_size<<'\n';```) above row 18 https://github.com/simdjson/simdjson/blob/6b02b0658105ae39f3eef0aee7a2c3fa880c2537/fuzz/fuzz_ndjson.cpp#L18 
Then recompile and run the fuzzer again on the crash data.

# using a debugger
What I do, is put a break in the debugger at the above line 18 and then export the data from the debugger inspection of the variables. I use qtcreator.

**Comment by lemire** [comment]
These have apparently not resurfaced, so I am going to close for now.
