### ISSUE TITLE
Enable [skip ci] for Github workflows and encourage its use

### ISSUE THREAD

**Issue by friendlyanon** [simdjson/simdjson#1313]
At the moment, every change is checked via CI, however not all changes require a CI, especially not from all services.

One example is https://github.com/simdjson/simdjson/pull/1295.  
This PR only made trivial changes to the Github workflows that totally did not necessitate a CI run from all the services.

All currently used services - besides Github - support the message of the head commit in a push to prevent a run if it contains `[skip ci]`.  
This feature is not natively supported by Github, however it can be trivially added via an `if:` property. See [this community thread](https://github.community/t/github-actions-does-not-respect-skip-ci/17325).  
The first answer says how to do it, but I'd personally add an extra check for `[skip github]`. Some of the other services also support a similar feature.

Personally, I would not add this to all the workflows, e.g. the `Detect trailing whitespace` workflow is generally useful and its runtime is short.

This kind of change should also be documented in HACKING.md and should encouraged for use whenever a change happens that doesn't need a full CI run, e.g. trivial changes to workflows, changes to documentation, changes in misc files.  
The additional benefit is that this would reduce the wait times for certain services that are slow (Appveyor) or tend to hit request limits (Drone).

**Comment by lemire** [comment]
Looks good. We should do this.
