### ISSUE TITLE
How to parse Complex Nested JSON File

### ISSUE THREAD

**Issue by GODFATHER23** [simdjson/simdjson#1316]
While parsing complex nested JSON file it is difficult to access/search value of the object.

Here is the json file which I'm working on --

```
{
"statuses": [
{
"metadata": {
"result_type": "recent",
"iso_language_code": "ja"
},
"created_at": "Sun Aug 31 00:29:15 +0000 2014",
"id": 505874924095815700,
"id_str": "505874924095815681",
"text": "@aym0566x \n\n名前:前田あゆみ\n第一印象:なんか怖っ！\n今の印象:とりあえずキモい。噛み合わない\n好きなところ:ぶすでキモいとこyumsparklessparkles\n思い出:んーーー、ありすぎblushheart\nLINE交換できる？:あぁ……ごめんhand\nトプ画をみて:照れますがなkissing_heartsparkles\n一言:お前は一生もんのダチsparkling_heart",
"source": "<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone",
"truncated": false,
"in_reply_to_status_id": null,
"in_reply_to_status_id_str": null,
"in_reply_to_user_id": 866260188,
"in_reply_to_user_id_str": "866260188",
"in_reply_to_screen_name": "aym0566x",
"user": {
"id": 1186275104,
"id_str": "1186275104",
"name": "AYUMI",
"screen_name": "ayuu0123",
"location": "",
"description": "元野球部マネージャー❤︎…最高の夏をありがとう…❤︎",
"url": null,
"entities": {
"description": {
"urls": []
}
}
}
}
]
}
```

Using the sample code of your's I was able to parse whole json file but while searching for an object and it's value I wasn't able to search it just shows no such object/object value.
Please help me with the code as in how and what to do.

Here is the code

```
#include "simdjson.h"
int main(void) {
  simdjson::dom::parser parser;
  simdjson::dom::element tweets = parser.load("twitter.json");
  std::cout << "Value of ID " << tweets["statuses"]["id"] << std::endl;
}
```
Here is the output which I'm getting

```
~/simdjson-master$ c++ strt.cpp simdjson.cpp
~/simdjson-master$ ./a.out 
terminate called after throwing an instance of 'simdjson::simdjson_error'
  what():  The JSON element does not have the requested type.
Aborted (core dumped)
```
This is the output I'm expecting

```
~/simdjson-master$ c++ strt.cpp simdjson.cpp
~/simdjson-master$ ./a.out 
Value of ID 505874924095815700
```

**Comment by lemire** [comment]
Without looking at the simdjson API at all, just looking at your example in abstract terms...

What is `tweets["statuses"]["id"] ` supposed to return in this case? 

So `tweets["statuses"]["id"] ` should return the value associated with the key `"statuses", correct? That value is an array...

```
[ {"metadata": {... ]
```

You are indexing into an array using the key `"id"`. It is not clear what one would like in such cases.

Furthermore, the JSON you provide does not appear to be valid JSON.

**Comment by lemire** [comment]
Maybe you mean to use the following?

```C++
#include "simdjson.h"

int main(void) {
  simdjson::dom::parser parser;
  simdjson::dom::element tweets;
  auto error = parser.load("twitter.json").get(tweets);
  std::cout << tweets["statuses"].at(0)["id"] << std::endl;
}

```

**Comment by lemire** [comment]
If you value safety... here is a better code example...

```C++
#include "simdjson.h"

int main(void) {
  simdjson::dom::parser parser;
  simdjson::dom::element tweets;
  auto error = parser.load("twitter.json").get(tweets);
  if(error) { std::cerr << error << std::endl; return EXIT_FAILURE; }
  uint64_t identifier;
  error = tweets["statuses"].at(0)["id"].get(identifier);
  if(error) { std::cerr << error << std::endl; return EXIT_FAILURE; }
  std::cout << identifier << std::endl;
  return EXIT_SUCCESS;
}
```

**Comment by lemire** [comment]
Let me be clearer. For the code that you wanted to run to be correct, you would have needed to have an object nested in an object, like so...

```C++
{
"statuses": {
   "id": 505874924095815700
 }
}
```

But instead you have...


```C++
{
"statuses": [
  {
    "id": 505874924095815700. 
  }
 ]
}
```

This is not simdjson specific. No DOM API that I know will allow to skip the array.

**Comment by GODFATHER23** [comment]
Thank you for your guidance it solved my confusion as well as I'm able execute the code.

**Comment by GODFATHER23** [comment]
How to iterate if there are n number of nested objects created.We can't always give the path so that it can iterate it.
Is there any function to directly search value within the JSON file without giving path of it.

**Comment by lemire** [comment]
> How to iterate if there are n number of nested objects created.We can't always give the path so that it can iterate it.

This is not simdjson specific. If I give you a DOM tree and you do not know where your data is in the tree, you will have to explore the tree to find out.
