### ISSUE TITLE
Allow multiple key lookups on value/document

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1333]
Even if you don't convert to object, you should be able to look up more than one key. This is a reasonably large footgun at the moment, because release builds won't warn you when you mess this up.

This fails with a weird "bad tape structure" error message:

```c++
for (auto tweet : doc["statuses"]) {
  cout << string_view(tweet["id"]) << ": " << string_view(tweet["text"]) << endl;
}
```
An alternative would be to make the second lookup fail fast in release mode (probably not possible to make it fail to compile).

This applies after PR #1330. You can't even *use* `["key"]` on values on master, so it doesn't presently fail.

**Comment by lemire** [comment]
@jkeiser What is the suggested workaround code?

**Comment by jkeiser** [comment]
Replace `auto` with `ondemand::object`.

**Comment by lemire** [comment]
+1 for the short but informative answer.

**Comment by jkeiser** [comment]
Phone typing :)

**Comment by jkeiser** [comment]
This is fixed.
