### ISSUE TITLE
Move Travis.ci jobs to new CI

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#1335]
I'd mentioned this was likely to happen before, but they've done it sooner than expected. Travis is now suspending all open-source credits. Need to move travis steps ASAP or move to a paid plan.

Some discussion on HN, https://news.ycombinator.com/item?id=25338983

**Comment by lemire** [comment]
Does anyone have a pointer to their paid plans?

**Comment by TkTech** [comment]
Paid plans are on the `.com` instead of `.org`. https://travis-ci.com/plans.

**Comment by lemire** [comment]
I see it now...

https://travis-ci.com/organizations/simdjson/plan

The price is not unreasonable.
