### ISSUE TITLE
external use of json_iterator

### ISSUE THREAD

**Issue by ljmarks** [simdjson/simdjson#1347]
Hi,

I'm trying to understand the best way to construct my own tree datastructure representing an entire parsed JSON document. For context, I am working with datatypes for another language. 
It is possible to do with a recursive procedure via  `dom` api but this seems wasteful for a number of reasons. 

I noticed the `json_iterator` gadget which seems like it could do the trick - is this safe for external use? My current idea is to basically copy the `tape_builder` but with my own callbacks which will build up a tree-like datastructure as each element of the document is parsed.

**Comment by lemire** [comment]
> I noticed the json_iterator gadget which seems like it could do the trick - is this safe for external use? 

It is not part of our public API at this time:

```C++
/**
 * Iterates through JSON tokens, keeping track of depth and string buffer.
 *
 * @private This is not intended for external use.
 */
class json_iterator {
```


> My current idea is to basically copy the tape_builder but with my own callbacks which will build up a tree-like datastructure as each element of the document is parsed.

What you describe seems challenging. If you provide your own callbacks that are hooks into another programming language, then your performance would, in most instances, drop to the floor.

Function inlining is critical to good performance in such a context if most programming languages do not have such a great integration with C++ that everything gets inlined.

**Comment by ljmarks** [comment]
Totally missed the `@private` in there! Thanks.

> What you describe seems challenging. If you provide your own callbacks that are hooks into another programming language, then your performance would, in most instances, drop to the floor.

The language runtime is written in C, and as such the datastructures can be created and updated with native code.
