### ISSUE TITLE
Split out validate_utf8

### ISSUE THREAD

**Issue by chessai** [simdjson/simdjson#1348]
Problem
=======
I'm unable to find a good C/C++ library for validating UTF-8 (with intrinsics) that provides _only_ the validation. Currently, in my projects, I'm depending on simdjson for this task. simdjson is too heavy a dependency most of the time (I really only need to validate text as UTF-8).

Proposed Solution
==============
Create a separate library that exposes just validate_utf8 (potentially in the same repo). simdjson could depend on this library, and external users could depend on only the validate library.

Alternatives
=========
Continue to force users of my code to transitively depend on simdjson, when my code is only calling validate_utf8.

Are you willing to contribute code or documentation toward this new feature?
==========================================================
I would be willing to implement this if the maintainers approve of such a change.

**Comment by lemire** [comment]
@chessai Sure. Branching it out as a distinct package makes sense. It could even go into a distinct repository.

I am willing to support this work, but let us be clear... it requires work:

1. It is not a simple matter of copying a function or two, there is an entire runtime dispatching system to reproduce.
2. Testing, including fuzz testing, needs to be reproduced as well. We currently test over a wide range of platforms and systems.
3. Documentation needs to be provided.
4. Ultimately, one needs to provide package support (e.g., brew, Conan and so forth).

So I am not discouraging this work, on the contrary. However, whoever embarks on this project needs to be willing to spend days getting this to a production-level quality.

**Comment by chessai** [comment]
> @chessai Sure. Branching it out as a distinct package makes sense. It could even go into a distinct repository.
> 
> I am willing to support this work, but let us be clear... it requires work:
> 
> 1. It is not a simple matter of copying a function or two, there is an entire runtime dispatching system to reproduce.
> 2. Testing, including fuzz testing, needs to be reproduced as well. We currently test over a wide range of platforms and systems.
> 3. Documentation needs to be provided.
> 4. Ultimately, one needs to provide package support (e.g., brew, Conan and so forth).
> 
> So I am not discouraging this work, on the contrary. However, whoever embarks on this project needs to be willing to spend days getting this to a production-level quality.

This is what I expected. Sounds great

**Comment by lemire** [comment]
@chessai Here is what I suggest, create a new repository, maybe under your own account... bring it to a viable level (ping me if needed). Then we can move it under the simdjson organization and publish it from there as a distinct package.

**Comment by lpinca** [comment]
A possible alternative could be introducing some flags to remove everything but UTF-8 validation at compile time. What do you think?

**Comment by lemire** [comment]
> Create a separate library that exposes just validate_utf8 (potentially in the same repo). simdjson could depend on this library, and external users could depend on only the validate library.

I consider this issue to be solved by the publication of the simdutf library. Please give it a try!

https://github.com/simdutf/simdutf

Closing.

**Comment by lpinca** [comment]
https://github.com/simdutf/simdutf is great but it is still too heavy for my needs. I really only need UTF8 validation. My use case is  validating the payload data of WebSocket frames. For context: https://github.com/websockets/utf-8-validate/pull/101.
