### ISSUE TITLE
ondemand_assert_out_of_order_values fails on g++-10 on Release Mode

### ISSUE THREAD

**Issue by furkanusta** [simdjson/simdjson#1350]
**Describe the bug**
ondemand_assert_out_of_order_values fails on g++-10 when compiled with CMAKE_BUILD_TYPE=Release
I've tested with
- g++ (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
- clang version 11.0.0 (Fedora 11.0.0-2.fc33)

Both are tested with in Debug and Release and only g++ in Release fails.

Output of the failing test

> error getting x: The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.
> error getting y: Problem while parsing a number

Although not exactly an error, g++ in Debug has an extra output as well.

> error getting x: The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.

The above line appears only in gcc-debug while the below appears in all three (clang-debug, clang-release, gcc-debug)

> ondemand_assert_out_of_order_values: ../include/simdjson/generic/ondemand/value_iterator-inl.h:419: void simdjson::fallback::ondemand::value_iterator::assert_at_start() const: Assertion `_json_iter->token.index == _start_index' failed.

**Comment by jkeiser** [comment]
You need to run with -LE explicit only to exclude that test: it should fall on any release build and is only run on debug builds. If there's a better way to exclude it from running by default, I'm all ears, too :)

It should be running on done ci in debug builds, against both g++-10 and clang-10, however ...

**Comment by furkanusta** [comment]
I saw -LE on CI config files but wasn't sure if I needed to pass since it was built as part of "make && make test"
There is EXCLUDE_FROM_ALL in CMake but I am not sure how it works with tests, I will check.

**Comment by jkeiser** [comment]
It's also possible to make it so it passes on release builds ... but since it's there to test asserts and release builds don't assert, the test kinda doesn't even make sense and having a green result might be misleading? I guess one could argue the tests should just be disabled and since it runs zero tests, it should be green (zero failures) ...

Were you saying you saw this on debug builds, though? That would be an issue no matter what.
