### ISSUE TITLE
Use runtime selection for stage 1 in On Demand

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1358]
Stage 1 produces the same output no matter what architecture your computer is. Presently, however, if you compile On Demand without `-march=native`, it will generally use the slower fallback implementation for stage 1. We should have it use the most advanced runtime-selected implementation instead.

This still means that architecture-specific frontend code--string parsing in particular--will use the fallback version; but it will mitigate a *lot* of the parsing time for users that use the default flags, or who need to compile a program that will be run on arbitrary hosts.

**Comment by lemire** [comment]
I agree that it would be a great step forward and could even buy us most of the gains we want while minimizing engineering complexity.

Stage 2 is mostly about the big "switch/case" (type determination) and then you have number parsing... which is mostly the same in all kernels... but my one reservation is our string parsing routine... but OnDemand mostly does "exact string matching" (without decoding) so...

Right... it seems likely that a "fallback" stage 2 would be mostly fine for OnDemand. You might even be able to optimize it further if we find it is a drag.

So this seems like a pretty neat step forward.

Nice idea.

**Comment by jkeiser** [comment]
And with luck, simple :) Would make it so people doing naive benchmarks are more likely to get meaningful results.
