### ISSUE TITLE
re-wrire flatten_bits to reduce number of memory writes

### ISSUE THREAD

**Issue by Licenser** [simdjson/simdjson#136]
The original implementation of `flatten_bits` writes to the `structural_indexes` for each of the (possibly) 64 indexes it found. When profiling this in rust that caused a high number of writes to memory - it might be that c++ optimizes this better but the function can be re-written using a single `_mm256_storeu_si256` operation for each iteration of 8 indexes reducing writes by 1/8th.

Code(again in rust):  https://github.com/Licenser/simdjson-rs/blob/ea0700222b59b0f2c61f93a645916201d7cd5f91/src/stage1.rs#L252

PS: I'm quite new to SIMD so I might have missed obvious reasons why not to do this.

**Comment by lemire** [comment]
@Licenser 

I doubt that any of this is language specific. There might be differences in 

What is your expectation of how this line gets implemented?

```Rust
let v: __m256i = _mm256_set_epi32(v7, v6, v5, v4, v3, v2, v1, v0);
```

In a credible interpretation of this code, you have 8 registers that you must combine into one wide register. Maybe we can agree that it is unlikely to become one instruction (indeed, there are no 9-parameter instruction on x64).

> I might have missed obvious reasons why not to do this

Well... I don't think it is obviously wrong, but why does your intuition suggests that it might be more efficient?

My own intuition is that it is either the same speed or slower than doing the work naively.

Let us look at the assembly

```Rust
pub fn flatten_bits(v: &mut Vec<i32>, base: &mut Vec<u32>) {
          unsafe {  
          let v: __m256i = _mm256_set_epi32(v[7], v[6], v[5], v[4], v[3], v[2], v[1], v[0]);
            _mm256_storeu_si256(base[0..].as_mut_ptr() as *mut __m256i, v);
}}
```

```
core::coresimd::x86::avx::_mm256_set_epi32:
        vmovd   xmm0, r8d
        vpinsrd xmm0, xmm0, ecx, 1
        vpinsrd xmm0, xmm0, edx, 2
        mov     rax, rdi
        vpinsrd xmm0, xmm0, esi, 3
        vmovd   xmm1, dword ptr [rsp + 24]
        vpinsrd xmm1, xmm1, dword ptr [rsp + 16], 1
        vpinsrd xmm1, xmm1, dword ptr [rsp + 8], 2
        vpinsrd xmm1, xmm1, r9d, 3
        vinsertf128     ymm0, ymm1, xmm0, 1
        vmovaps ymmword ptr [rdi], ymm0
        vzeroupper
        ret

core::coresimd::x86::avx::_mm256_storeu_si256:
        vmovaps ymm0, ymmword ptr [rsi]
        vmovups ymmword ptr [rdi], ymm0
        vzeroupper
        ret

example::flatten_bits:
        push    rbp
        mov     rbp, rsp
        push    r15
        push    r14
        push    rbx
        and     rsp, -32
        sub     rsp, 64
        mov     rdx, qword ptr [rdi + 16]
        cmp     rdx, 7
        jbe     .LBB2_1
        mov     r15, rsi
        mov     rax, qword ptr [rdi]
        mov     esi, dword ptr [rax + 28]
        mov     edx, dword ptr [rax + 24]
        mov     ecx, dword ptr [rax + 20]
        mov     r8d, dword ptr [rax + 16]
        mov     r9d, dword ptr [rax + 12]
        mov     r10d, dword ptr [rax + 8]
        mov     ebx, dword ptr [rax]
        mov     eax, dword ptr [rax + 4]
        sub     rsp, 8
        lea     r14, [rsp + 8]
        mov     rdi, r14
        push    rbx
        push    rax
        push    r10
        call    core::coresimd::x86::avx::_mm256_set_epi32
        add     rsp, 32
        mov     rdi, qword ptr [r15]
        mov     rsi, r14
        call    core::coresimd::x86::avx::_mm256_storeu_si256
        lea     rsp, [rbp - 24]
        pop     rbx
        pop     r14
        pop     r15
        pop     rbp
        ret
```
https://godbolt.org/z/pl53at


What are your thoughts given this assembly output?

**Comment by Licenser** [comment]
I had the hope that it'd translate to 8 registers getting converted into a single register, I looked at the assembly but honestly, am not entirely sure what it does.

```
+0xa5	    addl                $-64, %r12d
+0xa9	    blsrq               %r13, %r9
+0xae	    blsrq               %r9, %r10
+0xb3	    blsrq               %r10, %rdi
+0xb8	    blsrq               %rdi, %rax
+0xbd	    blsrq               %rax, %rcx
+0xc2	    blsrq               %rcx, %rdx
+0xc7	    blsrq               %rdx, %r8
+0xcc	    nopl                (%rax)
+0xd0	        tzcntq              %r8, %r11
+0xd5	        tzcntq              %rdx, %rdx
+0xda	        tzcntq              %rcx, %rcx
+0xdf	        tzcntq              %rax, %rax
+0xe4	        tzcntq              %rdi, %rdi
+0xe9	        tzcntq              %r10, %r10
+0xee	        tzcntq              %r9, %rsi
+0xf3	        tzcntq              %r13, %rbx
+0xf8	        addl                %r12d, %ebx
+0xfb	        addl                %r12d, %esi
+0xfe	        addl                %r12d, %r10d
+0x101	        addl                %r12d, %edi
+0x104	        addl                %r12d, %eax
+0x107	        addl                %r12d, %ecx
+0x10a	        addl                %r12d, %edx
+0x10d	        vmovd               %eax, %xmm0
+0x111	        vpinsrd             $1, %ecx, %xmm0, %xmm0
+0x117	        addl                %r12d, %r11d
+0x11a	        vpinsrd             $2, %edx, %xmm0, %xmm0
+0x120	        vpinsrd             $3, %r11d, %xmm0, %xmm0
+0x126	        vmovd               %ebx, %xmm1
+0x12a	        vpinsrd             $1, %esi, %xmm1, %xmm1
+0x130	        vpinsrd             $2, %r10d, %xmm1, %xmm1
+0x136	        vpinsrd             $3, %edi, %xmm1, %xmm1
+0x13c	        movq                (%r15), %rax
+0x13f	        vinserti128         $1, %xmm0, %ymm1, %ymm0
+0x145	        leaq                -1(%r8), %r13
+0x149	        vmovdqu             %ymm0, (%rax,%r14,4)
```

When I got to this is that when I profiled the original code about ~3.5% of the time was spent in writing to memory (again rust might be more expensive here due to range checks being performed).

That said, I didn't see much change in the benchmarks one way or the other after the change (but that might be an issue with my setup, I'm hitting some odd barrier on my system). What I did saw was a reduction in time spent in flatten_bits to ~2.4% so that might have been a blip.

I've some new benchmark setup and will give it a go with swapping between the two versions and see if they make a difference I can measure

**Comment by geofflangdale** [comment]
Not a bad idea, at all! We could make this go faster by replacing those 8 add instructions with a single SIMD add, too.

**Comment by Licenser** [comment]
Adding some (local) benchmarks:

Going back to the (rust addopted) naive implementation drops throughput between 7.5% and 14%:
```
     Running target/release/deps/parse-897f906c0740489c
apache_builds/simdjson  time:   [295.27 us 299.99 us 305.44 us]
                        thrpt:  [397.40 MiB/s 404.62 MiB/s 411.08 MiB/s]
                 change:
                        time:   [+2.1648% +9.7559% +15.609%] (p = 0.00 < 0.05)
                        thrpt:  [-13.502% -8.8887% -2.1189%]
                        Performance has regressed.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe

canada/simdjson         time:   [10.027 ms 10.115 ms 10.207 ms]
                        thrpt:  [210.33 MiB/s 212.23 MiB/s 214.10 MiB/s]
                 change:
                        time:   [+12.161% +14.121% +16.483%] (p = 0.00 < 0.05)
                        thrpt:  [-14.151% -12.374% -10.843%]
                        Performance has regressed.
Found 8 outliers among 100 measurements (8.00%)
  5 (5.00%) high mild
  3 (3.00%) high severe

citm_catalog/simdjson   time:   [3.1724 ms 3.2098 ms 3.2509 ms]
                        thrpt:  [506.68 MiB/s 513.18 MiB/s 519.23 MiB/s]
                 change:
                        time:   [+11.758% +14.477% +17.377%] (p = 0.00 < 0.05)
                        thrpt:  [-14.804% -12.646% -10.521%]
                        Performance has regressed.
Found 9 outliers among 100 measurements (9.00%)
  6 (6.00%) high mild
  3 (3.00%) high severe

log/simdjson            time:   [4.1125 us 4.2372 us 4.3972 us]
                        thrpt:  [471.72 MiB/s 489.54 MiB/s 504.37 MiB/s]
                 change:
                        time:   [+4.2068% +8.1655% +12.280%] (p = 0.00 < 0.05)
                        thrpt:  [-10.937% -7.5491% -4.0370%]
                        Performance has regressed.
Found 5 outliers among 100 measurements (5.00%)
  1 (1.00%) high mild
  4 (4.00%) high severe

twitter/simdjson        time:   [1.2047 ms 1.2331 ms 1.2633 ms]
                        thrpt:  [476.75 MiB/s 488.40 MiB/s 499.91 MiB/s]
                 change:
                        time:   [+8.7185% +12.638% +16.863%] (p = 0.00 < 0.05)
                        thrpt:  [-14.430% -11.220% -8.0193%]
                        Performance has regressed.
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) high mild
  3 (3.00%) high severe
```

That said the implementation of `flatten_bits` was adopted to be more rusty:

https://github.com/Licenser/simdjson-rs/blob/5dd0db87278c23db7fa3ae4b7a79923f4359cec5/src/stage1.rs#L253

**Comment by Licenser** [comment]
Oh that's a good idea! I'll give that a try! :D

**Comment by Licenser** [comment]
I gave the vectorized add a go: https://github.com/Licenser/simdjson-rs/commit/51839ba4b48ec346b9df753a15421e4bec606e40 looks quite nice nearly 6% more throughput on the best case!

**Comment by lemire** [comment]
This does reduce the instruction count a tiny bit, but it does not seem to be any faster. And the gain in instruction count is tiny.

I am thinking about closing this issue. 

cc @jkeiser

**Comment by jkeiser** [comment]
@lemire I've been thinking about this as well, but in the context of lookup tables to get rid of all the darn `if` statements. Is there a reason we use the leading zeroes method instead of the [lookup table method](https://lemire.me/blog/2018/03/08/iterating-over-set-bits-quickly-simd-edition/)?

**Comment by jkeiser** [comment]
@lemire if we can do the adds all at once too, it feels like it'd reduce the instruction count enough to matter. At any rate, if we can reduce instructions with no effect on performance, we generally should. We *know* that even if we haven't hit them, there will be thresholds where the decoder can get far enough ahead to start running instructions it wouldn't otherwise, or even engage the loop stream detector. And it might well be an anecdotal fluke, but a few few times I've noticed decreasing instruction count in a loop (but not branch conditions or targets) improved branch prediction rates elsewhere in the loop.

**Comment by lemire** [comment]
@jkeiser 


>  if we can do the adds all at once too, it feels like it'd reduce the instruction count enough to matter. 

Right. Maybe I was too pessimistic. 

See this Godbolt experiment... It looks like the savings could be non-trivial...

https://godbolt.org/z/CEpBGG



>  Is there a reason we use the leading zeroes method instead of the lookup table method?

Table lookup for bit decoding works really well if the bits are dense. That is, decoding 101000111110011111 works well with tables. Decoding 000000000000000000000001000000000000000000000000000000000000000000000010100000000000000000000000 with tables quickly grows wasteful.

Also, if your tables need to be a bit large, this steals bandwidth from under you. It may not matter, and I am usually in favor of large tables to save instructions, but it is still a cost.


Another way to go about it is pdep/pext, but that's strictly Intel-specific. It will be dog slow on AMD, and there is no fast equivalent on ARM. (That's the way @geofflangdale  had it originally...)

**Comment by jkeiser** [comment]
> See this Godbolt experiment... It looks like the savings could be non-trivial...

Yeah, that's actually a lot fewer instructions. I bet it's faster too. This is definitely a long pole.

> Table lookup for bit decoding works really well if the bits are dense.

I'll see if I can get an average, but my memory says we're sitting at an average of 6-12 structurals every 64 bytes, which is above the threshold you found on your post at least. It'd open up scenarios where we send more information like escape and end string indices, speeding up stage 2 on the cheap.

**Comment by lemire** [comment]
> my memory says we're sitting at an average of 6-12 structurals every 64 bytes

Yes. This is correct.

**Comment by lemire** [comment]
This could be revisited, but I don't think we need to track this issue. If someone wants to work on it... please do.
