### ISSUE TITLE
Use an older version of cmake

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [simdjson/simdjson#1365]
I had to use snap to install the latest version of cmake, and do it as sudo, because it modifies my system. Previous versions of cmake do not require this.

Please switch to an older version of cmake than 3.19 that doesn't introduce security vulnerabilities.

Thanks.

**Comment by lemire** [comment]
I am not aware of security vulnerabilities with CMake 3.19, but if there is, you can use more recent versions of CMake.

We are not going to lower the CMake version requirements. Users who wish to use simdjson in their projects do not need to use CMake at all. Folks who want to contribute to simdjson should use an up-to-date CMake.

> I had to use snap to install the latest version of cmake, and do it as sudo, because it modifies my system.

There is no need to do so. You can setup a convenient system using docker.
See
https://lemire.me/blog/2020/05/22/programming-inside-a-container/
