### ISSUE TITLE
[Q] Element and its representation types trivially_copyable property

### ISSUE THREAD

**Issue by ngrodzitski** [simdjson/simdjson#1374]
Would it be safe to rely that `simdjson::dom::element`, `simdjson::dom::object` and `simdjson::dom::array` will hold the trivially_copyable property in future (so I can always pass it by value)?

**Comment by lemire** [comment]
They are meant to be passed by value and I would recommend you do so.

We do not currently have tests regarding the trivially_copyable property. I would think that adding such tests would be good.

Are you willing to contribute such tests?

**Comment by ngrodzitski** [comment]
@lemire 
If it can wait for couple of days, then yes, sure.

**Comment by lemire** [comment]
Great.
