### ISSUE TITLE
[usage] Can't find simdjson.cpp when using simdjson on cmake

### ISSUE THREAD

**Issue by JonLiu1993** [simdjson/simdjson#1383]
Hi guys,
I'm vcpkg maintainer.
Recently I tried to update simdjson in vcpkg but some issues happend when I tried to use it after build.

**Host Environment**
- OS: [Windows10]
- Compiler: VS2019

**To Reproduce**
1. `git clone https://github.com/microsoft/vcpkg.git`
2. `./vcpkg install simdjson:x86-windows`
3. Write sample `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.0)
project(test)

add_executable(test test.cpp)

find_package(simdjson CONFIG REQUIRED)
target_link_libraries(test PRIVATE simdjson::simdjson simdjson::simdjson-flags simdjson::simdjson-source simdjson::simdjson-headers)
```
4. Configure the sample project

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
```
1> CMake generation started for configuration: 'x86-Debug'.
1> Command line: "cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 16 2019" -A Win32  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\usr\source\repos\CMakeProject20\out\install\x86-Debug" -DCMAKE_TOOLCHAIN_FILE=F:/test6/vcpkg/scripts/buildsystems/vcpkg.cmake "C:\Users\usr\source\repos\CMakeProject20" 2>&1"
1> Working directory: C:\Users\usr\source\repos\CMakeProject20\out\build\x86-Debug
1> [CMake] -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17134.
1> [CMake] -- Configuring done
1> [CMake] CMake Error at F:/test6/vcpkg/scripts/buildsystems/vcpkg.cmake:454 (_add_executable):
1> [CMake]   Cannot find source file:
1> [CMake] 
1> [CMake]     //simdjson.cpp
1> [CMake] 
1> [CMake]   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
1> [CMake]   .hpp .hxx .in .txx
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeProject20/CMakeLists.txt:4 (add_executable)
1> [CMake] -- Generating done
1> [CMake] CMake Generate step failed.  Build files cannot be regenerated correctly.
1> 'cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 16 2019" -A Win32  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\usr\source\repos\CMakeProject20\out\install\x86-Debug" -DCMAKE_TOOLCHAIN_FILE=F:/test6/vcpkg/scripts/buildsystems/vcpkg.cmake "C:\Users\usr\source\repos\CMakeProject20" 2>&1"' execution failed with error: ''cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 16 2019" -A Win32  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\usr\source\repos\CMakeProject20\out\install\x86-Debug" -DCMAKE_TOOLCHAIN_FILE=F:/test6/vcpkg/scripts/buildsystems/vcpkg.cmake "C:\Users\usr\source\repos\CMakeProject20" 2>&1"' returned with exit code: 1'.
```

**Additional context**
1. 
https://github.com/simdjson/simdjson/blob/920f5355001f053ae98f87d391d69bda0a886a5e/src/CMakeLists.txt#L20
Here, the `INTERFACE` target set the property `BUILD_TARGET` but missing `INSTALL_TARGET` (or it should be `INSTALL_TARGET`?), that caused the expoted `simdjson-config.cmake` missing the source file `simdjson.cpp`'s absoutly path:
```cmake
add_library(simdjson::simdjson-source INTERFACE IMPORTED)

set_target_properties(simdjson::simdjson-source PROPERTIES
  INTERFACE_LINK_LIBRARIES "simdjson::simdjson-include-source"
  INTERFACE_SOURCES "/simdjson.cpp"
)
```

2. The source file `simdjson.cpp` isn't installed to the install directory, that caused the user can't use that source file.

Can anyone take a look?

Thanks.

**Comment by JonLiu1993** [comment]
Relate to  [#13761](https://github.com/microsoft/vcpkg/issues/13761)

**Comment by lemire** [comment]
I think this should be reported upstream at https://github.com/microsoft/vcpkg 

We are happy to help, but we don't control vcpkg  packaging.

**Comment by lemire** [comment]
@myd7349 can you help?

**Comment by lemire** [comment]
> The source file simdjson.cpp isn't installed to the install directory, that caused the user can't use that source file.

Why would we install the source file `simdjson.cpp`? We install the compiled sources and the header (simdjson.h), but not the source files.

You configure your project with...

```CMake
find_package(simdjson CONFIG REQUIRED)
target_link_libraries(test PRIVATE simdjson::simdjson simdjson::simdjson-flags simdjson::simdjson-source simdjson::simdjson-headers)
```

I am not a vcpkg expert but this looks wrong. I think it should be something like

```
target_link_libraries(test PRIVATE simdjson)
```

or maybe 


```
target_link_libraries(test PRIVATE simdjson::simdjson)
```

**Comment by lemire** [comment]
The following works for me...

```CMake
cmake_minimum_required(VERSION 3.0)
project(test)

add_executable(test test.cpp)

find_package(simdjson CONFIG REQUIRED)
find_package(Threads REQUIRED)
target_link_libraries(test PRIVATE simdjson::simdjson)
```

I am going to close this issue and open an issue with downstream.

**Comment by lemire** [comment]
So I commented at https://github.com/simdjson/simdjson/blob/master/cmake/simdjson-flags.cmake instead of opening a new issue.

I think that the instructions that users receive need to be updated.

**Comment by lemire** [comment]
Reopening because I think our CMake build is bad.

cc @Neumann-A

**Comment by myd7349** [comment]
Sorry for the long delay. I will look into it this weekend.

**Comment by lemire** [comment]
@myd7349 I think we solve it via https://github.com/simdjson/simdjson/pull/1385 

Please have a look at the PR if you can. I will take all the advice I can get.
