### ISSUE TITLE
Only compile the builtin On Demand implementation

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1395]
Until we actually decide to handle user-driven runtime selection (see #1161), we're wasting a lot of compile time compiling multiple backends when you really only want the one. We should only compile the implementation the user will use.

They still need to be directly includeable by our src/ directory, of course, so that it can compile multiple backends.

**Comment by lemire** [comment]
I have closed 1161. Your solution is so good that if we are going to pursue it, we need to define the problem a lot better (so the motivation is clear). For one thing, we need to identify when and where it would be helpful.

**Comment by jkeiser** [comment]
Agreed! I don't think it rises to the level of something I'd want in 1.0--I'd much rather have some of my compile time back :)

**Comment by jkeiser** [comment]
Putting in for consideration for 1.0. It would be nice to take any truly large compile-time reductions we can, even though it's probably not the 1.0 focus.

**Comment by jkeiser** [comment]
I think this may be critical to avoiding forking of ondemand: not only should we compile just one single ondemand per compile, it should use the native target options rather than try to add its own. It should include haswell / westmere / whatever is appropriate, but only *detect*, not set, target options. Then all inlining problems disappear. Not 100% sure how to make that play with the actual `src/` generation correctly yet, but I'm quite sure we can come up with something. Possibly (probably?) having "builtin" actually compile the appropriate kernel into a new namespace.
