### ISSUE TITLE
More in depth comparison to other libarries 

### ISSUE THREAD

**Issue by arsnyder16** [simdjson/simdjson#1399]
simdjson is very focused on parsing time from what i can tell. 

What about the memory overhead of the DOM elements compared to the other libaries? It would be useful to see that chart as well.  

Are there plans for adding support to write json from the simdjson dom elements?

**Comment by lemire** [comment]
This is more discussion than an issue, please consider moving some of these to:
https://github.com/simdjson/simdjson/discussions

> What about the memory overhead of the DOM elements compared to the other libaries? It would be useful to see that chart as well.

Note that we invite everyone to produce their  JSON benchmarks, and there are many excellent benchmarks out there reporting on energy usage, memory usage, time, etc. If you would like to contribute benchmarks to the simdjson project, please do so: pull requests are invited.

> Are there plans for adding support to write json from the simdjson dom elements?

There is a DOM builder issue at : https://github.com/simdjson/simdjson/issues/1386

**Comment by jkeiser** [comment]
I would be super excited to see both persistent and burst memory usage in the stata reported by bench-ondemand (our current primary benchmark). Energy usage too, as that's one of the biggest reasons I want to see performance, and it turns out energy usage varies based on a lot more than simple speed.

**Comment by jkeiser** [comment]
And yeah, we feel write support, at least at a basic level, is likely a needed feature for 1.0.

**Comment by lemire** [comment]
The benchmarks can definitively be better instrumented.

Memory usage is a complicated topic, and requires great care. The following code `a = new char[x]` does not use `x` bytes. In fact, it may use no memory at all! (It is system-specific how much memory is actually used.) So you want to instrument your code to see how many physical pages are assigned to the process.

**Comment by jkeiser** [comment]
That makes sense. Is there any reason one would worry about how much virtual memory is allocated, even if not used or physically allocated?

**Comment by lemire** [comment]
Note that the converse is true, by the way, that is calling `delete[] a` may not actually free the physical memory that was allocated. Allocating pages is super expensive so you do not want to release then back to the system if you expect to use them again soon.

So a good performance usage pattern is to do big allocations in chunks and live within that for as long as possible. That's how JavaScript, C# or Java will tend to work: the virtual machine will try to maintain a constant memory usage.

@jkeiser I cannot imagine a scenario where you'd be concerned with anything but the physical pages in C++. Never heard of it... but then I'd love to be surprised. On a 64-bit system, you just have a ton of virtual memory space.

**Comment by jkeiser** [comment]
So presumably you want peak physical memory as well as stasis (between iterations) memory? Or is the stasis memory not even a reliable measure?

**Comment by lemire** [comment]
... Not sure...
