### ISSUE TITLE
Add RapidJSON and nlohmann_json SAX to benchmarks

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1401]
Now that we have real-world usage benchmarks, we can realistically compare SAX performance to non-SAX performance. This is particularly interesting when benchmarked against On Demand.

Of the implementations we currently benchmark, nlohmann_json and RapidJSON both have SAX implementations. As far as I can tell, these are the most popular. If anyone has other, faster SAX-for-JSON implementations to recommend, please note them so we can add them!

We also probably need to rename bench_ondemand to bench_scenarios or something. While On Demand is the fastest implementation, it's really not an ondemand-oriented benchmark in any way.

**Comment by lemire** [comment]
Good issue.

**Comment by jkeiser** [comment]
Upon investigation, it's worth noting that both of the mentioned sax parsers actually parse all values, including those that are unused. The main benefit is that they don't have to deserialize objects or arrays, or store variant types.

Rapidjson's iterative sax parse might be one of the simpler apis to work with, because instead of keeping track of context through state variables, you can use a different callback handler when you go to a new context (such as a tweet object).

**Comment by jkeiser** [comment]
I feel like this is going to be more important to compare against a "read this json and turn it into a custom dom" benchmark where context isn't as important. The use case being something like a binding, which wants to serialize into the target language's structures.

**Comment by lemire** [comment]
@NicolasJiaxin  is working on this issue.

**Comment by lemire** [comment]
@NicolasJiaxin Effectively closed this issue. We now have extensive SAX benchmarks.
