### ISSUE TITLE
extend the ondemand::value interface with get type function ".type()"

### ISSUE THREAD

**Issue by Tibbel** [simdjson/simdjson#1410]
just like in the dom::parser, a function "type()" to get the type of ondemand::value

something like:
simdjson::dom::element ondemand::value::type() const;

**Comment by jkeiser** [comment]
Agreed :) It seems critical for recursive cases like turning it into a generic tree, at the very least.

**Comment by jkeiser** [comment]
Given that this is fairly easy and supports a really important scenario, it seems reasonable to ensure it gets into 1.0.

**Comment by jkeiser** [comment]
PR #1472 adds `.json_type()` which does this. I kinda like the word `type()` better, but am rather worried that people will make define macros and such that use that word.

**Comment by jkeiser** [comment]
OK, I gave up on json_type due to a conflict and renamed it type(). We'll see what happens! :)

**Comment by jkeiser** [comment]
Fixed with #1472.
