### ISSUE TITLE
Add enum value unknown or notset to simdjson::dom::element

### ISSUE THREAD

**Issue by Tibbel** [simdjson/simdjson#1411]
Add an enum value for uninitalized status of the simdjson::dom::element enum like "UNKNOWN" or "NOTSET" or something like that, with the value zero = 0

**Comment by lemire** [comment]
I am going to close this. If you have a proposal, please provide a full rationale for it.

**Comment by Tibbel** [comment]
The value is or can be useful in the following cases:

1. it allows the simdjson::dom::element to hold a valid enum-value, but to indicate that no valid json value is available.
At the moment a second variable is needed to indicate that, because only enum values for valid data types exists.

2. It's possible to indicate that no valid json value is available without the need for extra error checking, for example:
```
val = get.type();
if ( val.error == false ) {
switch( val.type ) {
case STRING: break;
case ...
break;
}
} else {
//errors goes here
}
```
changes to
```
switch( get.type() ) {
case STRING: break,
case ...
case NOTSET : 
    //errors goes here
break;
}
```
3. it's possible to extend the ondemand parser to indicate END_OF_TAPE errors or corrupted values only by querying the type
