### ISSUE TITLE
On Demand incorrectly parses int64(9223372036854775808) as -9223372036854775808

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1415]
When parsing the JSON document `9223372036854775808` using `parser.iterate(json).get_int64()`, simdjson yields a result of -9223372036854775808. It should instead yield an INCORRECT_TYPE error.

See ondemand_error_tests.cpp, wrong_type_int64_overflow for the commented-out test.

**Comment by lemire** [comment]
This should be a priority.

**Comment by lemire** [comment]
Fixed.
