### ISSUE TITLE
Library fails to compile

### ISSUE THREAD

**Issue by vadi2** [simdjson/simdjson#1423]
**Describe the bug**
I've added the library to my project with:

```cpp
include(FetchContent)

FetchContent_Declare(
  simdjson
  GIT_REPOSITORY https://github.com/simdjson/simdjson.git
  GIT_TAG  v0.8.1
  GIT_SHALLOW TRUE)

set(SIMDJSON_JUST_LIBRARY ON CACHE INTERNAL "")
set(SIMDJSON_BUILD_STATIC ON CACHE INTERNAL "")

FetchContent_MakeAvailable(simdjson)

target_link_libraries(mudlet simdjson)
```

Then included in my file:

```cpp
#include "simdjson.h"
using namespace simdjson;
```

And tried to get it to parse a file:

```cpp
    dom::parser parser;
    dom::element simd_doc = parser.load(source.toStdString()); 
```

But compilation on a modern compiler using C++17 fails:

```
[build] In file included from /media/vadi/SSDer/Programs/Mudlet/build/_deps/simdjson-src/include/simdjson.h:49,
[build]                  from /media/vadi/SSDer/Programs/Mudlet/src/TMap.cpp:44:
[build] /media/vadi/SSDer/Programs/Mudlet/build/_deps/simdjson-src/include/simdjson/dom/array.h:98:23: error: expected unqualified-id before ‘)’ token
[build]    98 |   inline size_t slots() const noexcept;
[build]       |                       ^
[build] In file included from /media/vadi/SSDer/Programs/Mudlet/build/_deps/simdjson-src/include/simdjson.h:63,
[build]                  from /media/vadi/SSDer/Programs/Mudlet/src/TMap.cpp:44:
[build] /media/vadi/SSDer/Programs/Mudlet/build/_deps/simdjson-src/include/simdjson/dom/array-inl.h:64:27: error: expected unqualified-id before ‘(’ token
[build]    64 | inline size_t array::slots() const noexcept {
[build]       |                           ^
```

**To Reproduce**
No

**Configuration (please complete the following information if relevant):**
 - OS: Ubuntu 20.04 LTS
 - Compiler: GCC 9.3.0
 - Version: 0.8.1

We support up-to-date 64-bit ARM and x64 FreeBSD, macOS, Windows and Linux systems. Please ensure that your configuration is supported before labelling the issue as a bug. In particular, we do not support legacy 32-bit systems.

**Indicate whether you are willing or able to provide a bug fix as a pull request**

If you plan to contribute to simdjson, please read our
* CONTRIBUTING guide: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md and our
* HACKING guide: https://github.com/simdjson/simdjson/blob/master/HACKING.md

**Comment by lemire** [comment]
Please provide a complete reproducible test for your issue. The simdjson library is extensively tested and it does compile.

You may want to start from a single CMake example such as this one:

```CMake
# Copy this file as CMakeLists.txt in
# some directory. With a recent CMake
# (at least 3.15), in this directory do
#
# cmake -B build .
# cmake --build build
# ./build/repro
#
#
cmake_minimum_required(VERSION 3.15)

project(issue1423 VERSION 0.1.0 LANGUAGES CXX)


include(FetchContent)

FetchContent_Declare(
  simdjson
  GIT_REPOSITORY https://github.com/simdjson/simdjson.git
  GIT_TAG  v0.8.1
  GIT_SHALLOW TRUE)


FetchContent_MakeAvailable(simdjson)



file(WRITE main.cpp "
  #include \"simdjson.h\"
  using namespace simdjson;
  #include <iostream>
  int main(void) {
    dom::parser parser;
    std::cout << \"the following should crash with an exception if the file is not around:\" << std::endl;
    dom::element simd_doc = parser.load(\"somefile.json\");
    return EXIT_SUCCESS;
  }")



add_executable(repro main.cpp)
target_link_libraries(repro PUBLIC simdjson)
```


Closing. The user should open a new issue that provides a reproducible test case.

**Comment by vadi2** [comment]
That kind of cool reception doesn't endear one to use the library.

Upon investigation it turns out despite all the testing, the Qt framework was not tested with. It already defines `slots` macro, which explains why simdjson was failing to compile. Thanks to the kind people at #include for pointing to this trick:

```cpp
#undef slots
#include "simdjson.h"
#define slots
```

**Comment by lemire** [comment]
See https://github.com/simdjson/simdjson/pull/1425

**Comment by jkeiser** [comment]
@vadi2 note @lemire literally meant "we'd love a reproducible solution but I even tried to reproduce it with the information given and couldn't." And once you sent the Qt information (thanks for that) we've got a solution merged. Qt really ought to try and avoid non-namespaced macros, but eh, them's the breaks!

Agreed verbage sounded harsh, sorry--sometimes precise, facts-only wording can make it hard not to read emotional content into.
