### ISSUE TITLE
How to test an object for the presence of a key?

### ISSUE THREAD

**Issue by vadi2** [simdjson/simdjson#1424]
I've looked through basics.md and the doxygen docs, but I can't find the answer: how can one test an object for a presence of a key?

**Comment by lemire** [comment]
Using the DOM API, you can the `[]` operator on the `dom::object` instance. If the key is missing, then you will get an error condition, if not you will get access to the corresponding value. You can do it like so... 

```C++
  auto json = R"({"key":1})"_padded;
  simdjson::dom::parser parser;
  simdjson::dom::element elem;
  auto error1 = parser.parse(json)["key"].get(elem); // do the parsing
  if (error1) {
    std::cout << error1 << std::endl;
  } else {
    std::cout << "parse valid: " << elem << std::endl;
  }
  auto error2 = parser.parse(json)["badkey"].get(elem); // do the parsing
  if (error2) {
    std::cout << error2 << std::endl;
  } else {
    std::cout << "parse valid: " << elem << std::endl;
  }
```

You can also iterate over the content of the object and examine the keys and values...

```C++
  for(auto key_value : object) {
    std::cout << "key " << key_value.key << std::endl;
    std::cout << "value " << key_value.value << std::endl;
   }
```

where you can create the object like so... `simdjson::dom::object(parser.parse(json))` (for example).

Using the On Demand front-end, the answer is similar though the code samples will differ a bit.
