### ISSUE TITLE
Creating instead of Parsing ?

### ISSUE THREAD

**Issue by sdmg15** [simdjson/simdjson#1426]
I've read the documentation but seems it's focused on parsing mostly than creating JSON.
I've been going through the classes but I'm still wondering how to create a JSON structure from the code directly, means the JSON is not coming from outside.
Is it something possible with simdjson? Thanks

**Comment by lemire** [comment]
Currently, the simdjson is focused on parsing JSON files, it is a parser. From the parsed result, you can reserialize, but we do not offer functions to build a JSON document from scratch.

See https://github.com/simdjson/simdjson/issues/1386
