### ISSUE TITLE
Add ondemand::iterate() without requiring copy

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1433]
padded_string requires a copy, and the only ondemand::iterate() requires a padded_string. Many users own their own buffers and would like to avoid that copy.

I like the explicitness of padded_string, as it forces the user to add the word "padded" in their code, so they won't accidentally make a too-small buffer. So perhaps for cases where the user has their own buffer, we could have an non-owned `already_padded()` type they can pass in instead. Then the call would be:

```c++
auto doc = ondemand::iterate(already_padded(buf, len));
```

**Comment by valkmit** [comment]
Looking forward to this feature! In my opinion, the intersection of users who care about the speed increase of ondemand over the traditional parser and users who wish to avoid a memcpy is quite high.

**Comment by lemire** [comment]
Right. And it is easy to implement. In fact, it is a good first issue for anyone who would like to contribute.

**Comment by jkeiser** [comment]
> Looking forward to this feature! In my opinion, the intersection of users who care about the speed increase of ondemand over the traditional parser and users who wish to avoid a memcpy is probably quite high.
> 
> One more thing to add - perhaps I'm just not clear on the internals of the ondemand API, but there doesn't seem to be a way to make the ondemand parser preallocate memory either, like one can do with the traditional parser. Does the ondemand parser not require any internal memory for its data structures?

It does :) It should really have a set_capacity() method like dom::parser, yeah. And a set_max_capacity(), to limit automatic allocation growth.

**Comment by lemire** [comment]
Marking this 1.0 so we get to it.

**Comment by lemire** [comment]
This requires us to be careful regarding the content of the padding to avoid accidental overruns: when starting with an array or object, make sure we end with one. (reminded by @jkeiser offline)

**Comment by jkeiser** [comment]
Fixed by #1473 .
