### ISSUE TITLE
Should on demand be used if you're parsing the full json?

### ISSUE THREAD

**Issue by vadi2** [simdjson/simdjson#1436]
I see the on demand mode is being touted as the best new thing - but in case of you reading _all_ of the data from the JSON file (so not selectively), is it still worthwhile to use?

**Comment by lemire** [comment]
Ping @jkeiser

**Comment by jkeiser** [comment]
Yep! It should be faster in all circumstances where you read the file once, particularly if you know the schema of the json (but in many cases even if you don't, I suspect). Benchmarks so far bear this out.

**Comment by vadi2** [comment]
Thanks!
