### ISSUE TITLE
How to use get_() functions without exceptions?

### ISSUE THREAD

**Issue by vadi2** [simdjson/simdjson#1440]
The library promises a lot of use but as an intermediate C++ user, I'm struggling a fair bit, even after having read over the docs many times.

One question is how to use the `get_<type>()` functions without incurring exceptions - that is, with the `error =` model?

**Comment by lemire** [comment]
The general exception-free usage goes as follows...

```C++
uint64_t x;
auto error = elem.get(x);
// check the error here
```

Please see
https://github.com/simdjson/simdjson/blob/master/doc/basics.md#error-handling

**Comment by vadi2** [comment]
Actually I already came from that... https://github.com/simdjson/simdjson/issues/1435#issuecomment-775462313

So the only way is with casting, then?

**Comment by lemire** [comment]
> So the only way is with casting, then?

Casting will throw on error.

**Comment by jkeiser** [comment]
Long story short, to run without exceptions you need to get() into one of the supported types, at the moment. uint64_t, int64_t,, double, bool, string_view, object, array.

No reason not to add accessors for smaller types, I suppose!

Also: if you want to ensure you never get an exception, compile with SIMDJSON_EXCEPTIONS=0. That will remove any interfaces that throw so you get a compile error if you try (i.e. no accidental casting).

**Comment by vadi2** [comment]
Had no idea that existed! It seems to have escaped the docs. I've added https://github.com/simdjson/simdjson/pull/1443 to help fix it.
