### ISSUE TITLE
Simdjson with other string types

### ISSUE THREAD

**Issue by vadi2** [simdjson/simdjson#1441]
Reading a key without exceptions takes three lines for a string - I'm sure I am doing is wrong, could this be done any better? Trying to integrate with Qt.

```cpp
    std::string_view temp;
    error = simd_doc["defaultAreaName"].get<std::string_view>(temp);
    mDefaultAreaName = QString::fromUtf8(temp.data(), temp.size());
```

**Comment by lemire** [comment]
Your code looks fine.

If you'd like to discuss, I encourage you to use the corresponding section:  https://github.com/simdjson/simdjson/discussions


Issues should be bugs, proposals, and so forth.

**Comment by lemire** [comment]
Note that you should benchmark `QString::fromUtf8`. It may be surprisingly expensive.
