### ISSUE TITLE
tape dump output does not match tape docs

### ISSUE THREAD

**Issue by jhalliday** [simdjson/simdjson#1446]
docs/tape.md contains example tape dump output for parse of jsonexamples/small/demo.json which begins as

0	r // pointing to 38 (right after last node)
1	{ // pointing to next tape location 38 (first node after the scope)

However, when executing ./tools/json2json -d jsonexamples/small/demo.json the observed output is

0 : r	// pointing to 39 (right after last node)
1 : {	// pointing to next tape location 4294967334 (first node after the scope)

with other 'tape location' values likewise incorrect. Missing mask for the high byte?

sidenote: Having the dump include the raw int value of the tape element would be useful too, but that's a feature request rather than a bug...  Likewise having a way to dump the binary tape(s).

4c63a92  built on fedora 33 x86_64  gcc version 10.2.1

**Comment by lemire** [comment]
Yes. The tape dump function is untested and has obviously gone out of sync. This should get fixed.

**Comment by lemire** [comment]
It is a good first issue: something someone can address without deep knowledge of the library.

Thanks for the report.

Pull requests are invited.
