### ISSUE TITLE
document_stream::iterator is not copyable

### ISSUE THREAD

**Issue by rychale** [simdjson/simdjson#1447]
Hello,

I'm not sure if I should report this, but AFAIK most of the time when dealing with iterators users expects them to provide:

* copy-constructor
* operator=
* value_type

At the moment document_stream::iterator doesn't support copying, because it stores a reference to underlying document_stream, but not a pointer.

The use case I'm stuck with is:

```
struct json_reader_t
{
   simdjson::dom::document_stream::iterator doc_;

   json_reader_t(const std::string_view _filename)
   {
      ...
      parser_.parse_many(static_cast<const std::uint8_t*>(addr_), sz_).get(stream_);
      doc_ = stream_.begin();
   }

   std::optional<simdjson::simdjson_result<simdjson::dom::element>> next()
   {
      simdjson::simdjson_result<simdjson::dom::element> json {*doc_};

      ++doc_;
      return json;
   }
}
```

Kind regards,
Alexey

**Comment by lemire** [comment]
Thanks for reporting. Marking this issue as 0.9.
