### ISSUE TITLE
OnDemand should support ndjson (document_stream)

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1464]
We did discuss this issue, and it seems like a low-hanging fruit. I cannot find a corresponding issue.

**Comment by jkeiser** [comment]
Weird that there's no issue. Completely agree!

**Comment by lemire** [comment]
@jkeiser There might be a non-trivial API design issue: do you view it as one stream (one iterator) or a series of streams (each time triggering a new iterator). Currently, we work this...

```C++
for (document in stream) {
  for(iterator in document) {
  }
}
```

One possibility with something like ndjson is just to view it as a "relaxed" form of JSON where the root is, implicitly, an array. So there might be no difference between...
```JSON
{"x":1, "y":2}
{"x":1, "y":2}
{"x":1, "y":2}
{"x":1, "y":2}
```

and

```JSON
[{"x":1, "y":2},
{"x":1, "y":2},
{"x":1, "y":2},
{"x":1, "y":2}]
```

As with all design issues, there are probably pros and cons.

**Comment by jkeiser** [comment]
Good point. I'd love in the future to stream the input, but for now I think we could make it similar to the current design. The document_stream would keep track of the index buffer, and would produce `ondemand::document`s starting at the right place. You would iterate those naturally, and when they complete the document_stream would notice where they finished and start the next document there. (Documents with skipped values present a minor challenge, but all the information we need is there in the json_iterator, so it's probably not much of a challenge).

As for the suggestion at the bottom, I would have guessed people would expect this to parse as one document?

```json
[{"x":1, "y":2},
{"x":1, "y":2},
{"x":1, "y":2},
{"x":1, "y":2}]
```

**Comment by lemire** [comment]
@jkeiser I think you have answered my question clearly.

Let me make my own comments clearer. I meant that we could make it so that the two JSON inputs (that I provide) appear undistinguishable. But I understand that you have basically answered "no" which is a perfectly good answer.

**Comment by jkeiser** [comment]
Ah! You mean, someone could take a JSON document, descend into an array, and use the same interface to process the elements that they do to process the documents in a document stream?

I think once we've got an interface that supports actual streaming, that will indeed be the case: the value interface and document stream interface both let you iterate over a series of JSON values.

I imagine we could have document stream act like an array and produce a series of value objects instead of documents. It would be nice, as a user, not to have two distinct value types to deal with just because we're using one of them as storage.

It could work, nicely in fact!

**Comment by jkeiser** [comment]
The issue would be the last document: to use the same value class we either need to make it aware of when it is at the end of the document, or we need a guarantee the last document is not a bare number or boolean  (or at least that it has space characters after it).

**Comment by jkeiser** [comment]
Yeah, I think we could do that with what we have right now, with those constraints.

**Comment by jkeiser** [comment]
@lemire (If I wasn't clear, you changed my mind as to the API, at least!)

I think I now understand what you were getting at with your suggestion to treat each element of the array as a separate document:

```c++
[
  {"x":1, "y":2},
  {"x":1, "y":2},
  {"x":1, "y":2},
  {"x":1, "y":2}
]
```

Basically, to avoid having to solve the large document problem in the general case, you're proposing we essentially allow the user to specify a jsonpath to an array, and then we treat each element of that array as a separate document, allowing us to use document_stream on it?

**That** I'm down with, and think is a really good compromise solution without having to support multi-buffer documents. I don't think I understood it properly before--it would be weird if we did it by *default* since users would expect a single array to be a single document by default.

**Comment by lemire** [comment]
@jkeiser The JSON pointer approach might require special handling for very large document because, currently, we would just index the whole document and then do a JSON Pointer query... and then we would iterate over the arrays that is found. That's wasteful. So you probably want something like this...

```C++
    auto doc = parser.iterate_from_pointer(json, "/statuses");
    for (auto tweet : doc[]) {
     
    }
```

where "/statuses" is your JSON pointer. What this might do is open the JSON document, find (using stupid code) the array pointed at, and then start a json stream from that point forward. This would allow you to process gigantic documents in a multithreaded manner.

If someone has documents that span gigabytes and that could not be handled this way, I'd like to know about it.

@matteo392  Can you comment ? It seems that you are dealing with large files... can you comment on their structure? (No need to reveal company secrets.)

**Comment by matteo392** [comment]
Hi,

actually the files I'm considering are not private.
You can find them at the following link
https://www.roadef.org/challenge/2020/en/instances.php

there, you can find the set of files A, the larger ones are in the mentioned github repository.
This latter set is the B set (the last two json files B are those I have problem with).

**Comment by matteo392** [comment]
I think a general description of structure of the json files is in section 3.1.1 of the "Official Rules" available here 
[https://www.roadef.org/challenge/2020/en/rules.php](url)

**Comment by lemire** [comment]
@matteo392 That's useful.

**Comment by NicolasJiaxin** [comment]
I have been looking into this and want to make sure that I understand what needs to be added to implement this feature. Based on what was done for DOM, all we really need for On Demand is the ability to create a document stream and iterate through it, as well as to be able to parallelize stage 1 and stage 2. As for indexing in stage 1, I see that the work has already been note in `find_next_document_index.h`, so we can already reuse that. Is that correct @lemire?

**Comment by lemire** [comment]
Indeed. I am sure it is more complex than it sounds… but yeah… you can go a long way with copy-paste initially.

**Comment by lemire** [comment]
A design issue:

1. We assume that we have direct access to the last structural element via peek_last(). This is used  by `start_root_element()`:

https://github.com/simdjson/simdjson/blob/374de826ab07e57522f36ea8d935886f1d45d662/include/simdjson/generic/ondemand/value_iterator-inl.h#L19-L24

We have something similar with `start_root_array()`.

If your stage 1 covers a range of documents, this breaks. So it appears that (contrary to what I thought), On Demand 'stage 2' requires that we know the first and last structural index when `iterate` is called.

2. Sadly, this might mean that we need to first scan the structural indexes in a stream context to find the end of the document, before we allow the user to iterate over it. This means scanning the document twice. I suggest we start with this (and I think that's what @NicolasJiaxin had in mind).


But I think we should be more efficient. 

@jkeiser ... I'd like your feedback on two questions...

1. Can we wave or delay these peek_last() checks, at least in the document stream mode? E.g., in the document stream, we will have to find the end of the document anyhow, so we will know, sooner or later, that there is a mismatch. I'd like to go for an optimistic approach. When you iterate on a document, you might access some values and only later find out that the document is invalid... (e.g., mismatch { or[), but that would be ok. The contract would be that whatever you have access to in the current document, within a stream, is only to be committed once you are done with the document. (I.e., be optimistic.)
2. So we scan the document only once, I think we need a system whereas the user is given an iterator. The user does their work. If no error is encountered, then the iterator unwinds and goes automatically at the end of the document (possibly finding an error) and hopefully allows us to locate the start of a new document.

**Comment by jkeiser** [comment]
The end check is to prevent buffer overrun with numbers. However, this requirement is still fulfilled as long as the last document is an array or object, so if we require that, we could just check the very last token and make sure it's an end object or array (we don't really care which) ...

The "get rid of the need for padding" pr leans into this even more heavily, though it doesn't have to. It makes it so we don't have to check whether we're at the end on every token as we iterate. It *could* just check whether it's at eof before each token, and it might not be that bad?

I agree it would be best to not have to jump to the end at all, obviously--I'd like us to be able to process documents piece by piece too, which means we can't even rely on future tokens already being parsed.

**Comment by jkeiser** [comment]
And to add, there is no reason, *ever,* that we actually need to check if the end brace matches the starting brace. 
Honestly, it doesn't even need to be a brace. As long there is a non-numeric (1-9.eE-+) character as the last character of the document, or anywhere in the padding, we're safe.

**Comment by jkeiser** [comment]
Actually. We could fix this by checking whether the last character of the document is numeric, and doing `n_structural_indexes--` if so. Then treat that last token we skipped as the start of a new document. That way we can't accidentally hit it while we're inside an array or object. And since it's the last token, the only way it could possibly be valid is if the last document *is* just that token. We have special processing for the root token anyway :)

This would solve the problem for processing large documents in chunks too ... I'm loving it.

**Comment by jkeiser** [comment]
Obviously have to special case if there is only one token :) Otherwise we never progress.

**Comment by jkeiser** [comment]
Oh, the nice thing about the -- is, even if the prior token is also a number (and thus vulnerable), by backing up we guarantee there is a whitespace or structural in between.

**Comment by jkeiser** [comment]
A crazy idea building on top of it, we could even skip the algorithm where we skip backwards past the last partial document ... as long as we are checking for eof, we can have the eof error branch attempt to get / wait for more tokens before continuing.

**Comment by jkeiser** [comment]
That last idea probably would destroy a lot of inlining optimizations the compiler was able to do though, since the function to get more tokens would cause a discontinuity where the next structural is not `*(current_structural+1)`.

**Comment by lemire** [comment]
> A crazy idea building on top of it, we could even skip the algorithm where we skip backwards past the last partial document ... 

Though @NicolasJiaxin will not start with a parallel version, if you want a parallel to work, you need for stage 1 to do its thing independently of the front-end. Now, it would be possible not to do this (this == we skip backwards past the last partial document) and to later 'glue' the structural indexes (something we did contemplate) but it gets more complicated than it sounds.... especially if you want to preserve the ability to support very large documents (beyond 4 GB).

**Comment by lemire** [comment]
@jkeiser 

My last comment should not be viewed as me ditching your proposal. I am only saying that I think @NicolasJiaxin should, for now, seek to emulate the DOM approach as closely as possible.

**Comment by jkeiser** [comment]
Oh! Yes. Porting something like this is more than enough challenge; I definitely wouldn't invite trouble by trying to change the algorithm at the same time.

**Comment by lemire** [comment]
@jkeiser But his work is also an excuse to improve the front-end... as we will no doubt find... :-)

**Comment by jkeiser** [comment]
No doubt! :)

**Comment by lemire** [comment]
@jkeiser What I did in @NicolasJiaxin 's PR is to add a flag in the json_iterator so it knows whether it is in streaming mode. It only does the peek_last check when *not* in streaming mode. I kind of hate these hacks, but it turns out that it changes very little code.
