### ISSUE TITLE
raw_json_string operator== return true for unqeual keys (OnDemand API)

### ISSUE THREAD

**Issue by apanloco** [simdjson/simdjson#1480]
TLDR: 

```
simdjson_unused simdjson_really_inline bool operator==(const raw_json_string &a, std::string_view b) noexcept {
  return !memcmp(a.raw(), b.data(), b.size());
}
```

if a is "version_major" and b is "version" it will return true! because it only compares up to the size of b.

Full example:

```
#include <simdjson.h>

namespace example
{
    void parse(const std::string_view contents)
    {
        simdjson::ondemand::parser parser;
        simdjson::padded_string padded(contents);
        auto document = parser.iterate(padded);
        for (auto field : document.get_object())
        {
            auto key = field.key().value();
            if (key == "version")
            {
              // this will trigger for two keys!
            }
        }
    }
}

TEST_CASE("example")
{
    std::string json = R"({"name": "something", "version": "0.13.2", "version_major": 0})";
    example::parse(json);
}
```

if key points to a field called "version_major", the if-statement will trigger, because the operator== only compares the first 7 chars.

- OS: Windows 10
- MSVC 19.28.29337 for x64 
- simdjson 0.8.0

**Comment by lemire** [comment]
Used within `value_iterator::find_field_unordered_raw(const std::string_view key)` and  `value_iterator::find_field_raw(const std::string_view key)`.

**Comment by lemire** [comment]
@apanloco You could do...

```C++
    for(auto field : doc.get_object())  {
      std::string_view keyv = field.unescaped_key();
      if(keyv == "version") { .... }
    }
```

**Comment by lemire** [comment]
@jkeiser I will prepare a PR to handle this issue. Soon.

**Comment by apanloco** [comment]
@lemire thank you! that works well.

**Comment by jkeiser** [comment]
Well crud, did I forget to add a compare for the terminal `"` somehow??? That's a ridiculous flaw. Sorry.

**Comment by lemire** [comment]
Bug verified. PR upcoming.
