### ISSUE TITLE
Move ondemand to the top level

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1482]
Users should be able to use our primary API with the `simdjson::` prefix alone.

```c++
#include "simdjson.h"
using namespace simdjson;
void main(void) {
  parser parser;
  auto doc = parser.iterate("[[1,2,3]]"_padded);
  for (array a : doc) {
    for (uint64_t i : a) {
      cout << i;
    }
  }
}
```

This suggests we should *either* move the public portions of the ondemand API into the simdjson namespace, *or* at the very least move parser. We would move the ones from the builtin namespace.

Creating this issue as much for discussion as anything else :)

**Comment by jkeiser** [comment]
A very real con here: this will break anyone who is using DOM like this:

```c++
#include "simdjson.h"
using namespace simdjson;
using namespace simdjson::dom;
void main(void) {
  parser parser;
  auto doc = parser.parser("[[1,2,3]]"_padded);
  for (array a : doc) {
    for (uint64_t i : a) {
      cout << i;
    }
  }
}
```

Because now "parser," "object," and "array" are ambiguous, with one in `simdjson::` and one in `simdjson::dom`.

**Comment by jkeiser** [comment]
Also: I am not 100% sure what was causing it, but this has been working (the readme example uses it):

```c++
#include "simdjson.h"
using namespace simdjson;
int main(void) {
    parser parser;
    padded_string json = padded_string::load("twitter.json");
    document tweets = parser.iterate(json);
    std::cout << uint64_t(tweets["search_metadata"]["count"]) << " results." << std::endl;
}
```

I really, really think we shouldn't have dom::parser and dom::document at the top level at 1.0, but clearly we already (unintentionally?) do, so we're going to have to deprecate first, I guess. This is a hard one ...

**Comment by jkeiser** [comment]
It also makes this ambiguous:

```c++
static dom::parser parser{};

bool parse_double(const char *j, double &d) {
  auto error = parser.parse(j, std::strlen(j))
        .at(0)
        .get(d);
  if (error) { return false; }
  return true;
}
```

Because apparently C++ doesn't consider a variable higher priority than a class.

**Comment by lemire** [comment]
We can break it before 1.0 if we explain it well.

**Comment by jkeiser** [comment]
@lemire I'm having trouble deciding right now. Part of the reason I moved dom into its own namespace is I figure a new frontend / api was likely. I'm less sure now, but it's still possible we'll provide multiple subtly different front ends.

Maybe it's best to leave it this way for 1.0 until we explore the implications of incremental parsing, padding removal and ndjson (editing could potentially introduce design changes as well).

**Comment by lemire** [comment]
By default, I'd leave things be.

**Comment by jkeiser** [comment]
Closing! We'll work it out when we know more :)
