### ISSUE TITLE
On Demand API lacks serializer

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1498]
We can do `cout << doc` with a DOM document or any DOM element but not, currently, with the result of the On Demand API.

It should not be hard to do. Obviously, `parser.iterator(json); cout << json;` would be silly code, but there would be less trivial and more useful scenarios.

**Comment by jkeiser** [comment]
The only thing I wasn't able to easily decide, was whether this should advance the iterator or not. It probably should.
