### ISSUE TITLE
Prototype RcppSimdJson OnDemand wrapper

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1510]
Currently, wrappers such as RcppSimdJson are relying on our DOM API. I think we should at least write up a prototype On Demand implementation. Ideally, we would also show some performance (or other) benefit.

The main difference between our examples and what RcppSimdJson does is the ability to rewind. So given....
```JSON
[[0,1],
[2,1]
]
```

I think that what RcppSimdJson does is to check whether it might be a matrix. If it is, it figures out the shape. Then it goes back and constructs the matrix, with full knowledge of the shape. I am not sure that the On Demand examples cover such a use case but we can now rewind a document.

We should prove the maturity of the ondemand front end by writing up an ondemand implementation of rcppsimdjson. I recently proposed a port of the wrapper to 0.9 and I think we want to show that we can do it with ondemand

cc @eddelbuettel @jkeiser

**Comment by jkeiser** [comment]
Yeah, I'm thinking if rcppsimdjson lets people write c++ to read their format, it might not be hard to let them iterate forward only with knowledged of their schema.

On demand doesn't have rewind right now; but it would be easy to add, especially if there remains only one iterator when you do it.

**Comment by lemire** [comment]
@jkeiser Right. So we probably want to add some form of rewind for use cases where the user wants to scan first to identify the schema, and then populate a data structure. As you say, there is no reason for it to be difficult. It should be doable with a few lines of code.

**Comment by lemire** [comment]
My PR is at https://github.com/eddelbuettel/rcppsimdjson/pull/70

**Comment by lemire** [comment]
Ping @NicolasJiaxin This is a reasonable issue you could work on. It is most useful if someone with a fresh pair of eyes looks at this problem since they can more readily expose problems in our assumptions.

**Comment by NicolasJiaxin** [comment]
Working on this now.

**Comment by lemire** [comment]
@NicolasJiaxin That's great. It is important work.

**Comment by lemire** [comment]
I think that @NicolasJiaxin is basically done with this issue. We should close this issue once a pull request is made to  the original repository.
