### ISSUE TITLE
In ARM version, revisit the bitset decoding routine

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#152]
See comments on this post...

https://lemire.me/blog/2019/05/03/really-fast-bitset-decoding-for-average-densities/

**Comment by lemire** [comment]
Quoting Wilco  Dijkstra

> I did an experiment to reduce the amount of unnecessary work in stage 1. Rather than flatten the bitmap in flatten_bits, we can just write the whole bitmap as is. Stage 2 then decodes it in UPDATE_CHAR one bit at a time. A simplistic implementation shows the following speedups on an AArch64 server for the 4 json files: 0.8%, -2.4%, 5.1%, 7.1%. Branch mispredictions are higher of course, but it's still faster overall. While stage 1 achieves a great IPC of ~3 with very few branch mispredictions, the work it performs doesn't seem to be worthwhile enough to really help stage 2. Like I mentioned before, adding code to skip spaces in the parser should simplify stage 1 considerably and give larger speedups.

cc @jkeiser

**Comment by jkeiser** [comment]
Nice, I was wondering about that! It also gives the opportunity to send over more information, and best of all, it's usually going to take less memory.

**Comment by lemire** [comment]
@jkeiser This is likely processor specific and so should be studied accordingly...

Wilco is working on small ARM cores which have shallow pipelines (so small branch misprediction penalties) and little superscalarity.

**Comment by zwegner** [comment]
Interesting, I was playing with that same idea last week, but only benchmarking on my Haswell laptop (running macOS, where I can't use PMUs). I was getting worse performance after lots of tweaking so I set the idea aside (probably not worth using a completely different high-level structure for each arch...).

One big advantage of the idea is much less extra memory usage (the indices table becomes 1/8th the size of the input, rather than 4x bigger).

One thing to try here (if it hasn't been already) is putting a 1-index lookahead to hide latency. This was a nice improvement for me on Haswell. Here's a snippet:
```c
#define UPDATE_CHAR()                                                          \
  {                                                                            \
    idx = next_idx;                                                            \
    c = next_c;                                                                \
    next_idx = trailing_zeroes(i->bits) + i->idx;                              \
    i->bits = clear_lowest_bit(i->bits);                                       \
    i += (--i->cnt == 0);                                                      \
    next_c = buf[next_idx];                                                    \
  }
```
...where `i` is now a pointer to this struct:
```c
struct indices_t {
    uint64_t bits;
    uint32_t idx;
    int32_t cnt;
};
```
This allows all of the storing/decoding to be done branchlessly, since you're just incrementing a pointer whenever some structural bits are nonzero. The `cnt` parameter would probably be counterproductive on ARM since there's no fast popcnt.

**Comment by lemire** [comment]
@jkeiser @zwegner 

Regarding memory usage, we will have a PR soon from @piotte13 that significantly reduces the memory usage of the indices.

Basically, instead of running stage 1 over the whole file, we can work over windows of fixed size. 

Once Jérémie is done, it should not longer be the case that you need out-of-cache indices.

**Comment by jkeiser** [comment]
There is still an argument to be made that the serial process of
calculating indices belongs in the place we're walking serially. It would
also eliminate even more branches from stage 1, and place them in stage 2
which is already branchy, and might absorb them better. Removing the index
calculation from stage 1 reduces the loop size, which I've noticed tends to
improve branch prediction inside the loop. Finally, it might actually
become feasible to move utf8 processing out of the loop at that point,
which would make the structural loop literally 100% branch free.

**Comment by lemire** [comment]
@jkeiser We are definitively moving UTF-8 validation out of stage 1 in the near future.

> There is still an argument to be made that the serial process of calculating indices belongs in the place we're walking serially. 

You potentially have up to one branch misprediction per index decoded. That's more than 10 cycles for each structural character.

**Comment by lemire** [comment]
Note: I am not saying that this is not the right direction. I have created the issue myself. I am merely pointing out that it is not trivial. The resulting high performance code might very well end up being super simple, but conceptually, if you want to get good results on big cores, it is not easy.

**Comment by zwegner** [comment]
> Regarding memory usage, we will have a PR soon from @piotte13 that significantly reduces the memory usage of the indices.
> Basically, instead of running stage 1 over the whole file, we can work over windows of fixed size.

Awesome! I had wanted to try that but hadn't gotten around to it.

> You potentially have up to one branch misprediction per index decoded. That's more than 10 cycles for each structural character.

With the approach I described earlier, there are no branches whatsoever for decoding, just conditional moves (in both stage 1 and 2). That means there's always a non-zero bitset waiting. The approach still has plenty of data-dependent memory accesses though, which I think is one reason it wasn't performing as well on Haswell.

(In fact my code was even messier by using arithmetic shift right of the count minus one, to get the 1/0 increment from the sign bit: `i -= (cnt >> 31);`. This was faster than the zero/setnz instructions GCC was generating...)

One downside to the decode-in-stage-2 approach is that the latency of all the scalar tzcnts etc can't be hidden by the vector ops of stage 1. Not sure how much this really matters, I've only done some really basic measuring so far.

**Comment by lemire** [comment]
@zwegner 

> With the approach I described earlier, there are no branches whatsoever for decoding, just conditional moves (in both stage 1 and 2). That means there's always a non-zero bitset waiting.


Accessing the next set bit in an N-word bitset may require N steps (it is "O(N)") in the worst case. How do you cope with that?

**Comment by lemire** [comment]
@zwegner Oh! I think I understand now what you did.

You are mapping the bitset to a data structure where you omit the zero words. It is unclear to me whether you save memory... you might not. And you still need to do some branchy decoding is stage 1, just less of it since you are hunting for non-zero words instead of individual bit indexes.

I don't think that's what Wilco had in mind.

**Comment by lemire** [comment]
(Of course, it may have merit.)

**Comment by zwegner** [comment]
> Accessing the next set bit in an N-word bitset may require N steps (it is "O(N)") in the worst case. How do you cope with that?

Well, technically, that isn't true with PDEP, as noted here: https://stackoverflow.com/a/27453505
It's just `_pdep_u64(1ULL << n, x)`. Without PDEP, you're right--I thought for a while about how to vectorize the tzcnts on NEON, and couldn't come up with anything nearly as fast.

Have to rewrite the rest of my post since you just figured it out :)

The stage1 part is branchless too using the same conditional increment check:
```c
   indices_t *tail;
   really_inline void write_indexes(uint32_t idx, uint64_t bits) {
     this->tail->bits = bits;
     this->tail->idx = idx;
     this->tail->cnt = hamming(bits)-1;
     this->tail += (bits != 0);
   }
```
(The `cnt` parameter is hamming - 1 for the `cnt >> 31` trick I mentioned earlier).

**Comment by zwegner** [comment]
> You are mapping the bitset to a data structure where you omit the zero words. It is unclear to me whether you save memory... you might not.

For this, unless I misunderstand, current simdjson allocates a 4-byte index for every byte of input. With my method, you allocate a 16 byte struct for every 64 bytes of input. So 1/4 instead of 1/8 like I said earlier (I forgot to count `idx` and `cnt`), but 16x less extra memory than the current method.

**Comment by lemire** [comment]
@zwegner 

> Well, technically, that isn't true with PDEP

If all of your words are non-zero...

**Comment by lemire** [comment]
(Note that we don't use PDEP since it is a dog under AMD.)

**Comment by lemire** [comment]
> or this, unless I misunderstand, current simdjson allocates a 4-byte index for every byte of input. With my method, you allocate a 16 byte struct for every 64 bytes of input. 

You are correct, you are allocate far fewer bytes. I was thinking about the accessed memory.

**Comment by jkeiser** [comment]
@zwegner I might be misunderstanding you, too, but ... if you emit zero words too, does that cause problems? That would cut the memory in half, to just the bits ...

**Comment by zwegner** [comment]
> @zwegner I might be misunderstanding you, too, but ... if you emit zero words too, does that cause problems? That would cut the memory in half, to just the bits ...

That would work, but would require UPDATE_CHAR to use a loop to find the next non-zero word. Probably a pretty hard-to-predict branch. But, the stage 1 writes would be simpler. Worth a try I suppose...

**Comment by jkeiser** [comment]
> That would work, but would require UPDATE_CHAR to use a loop to find the next non-zero word. Probably a pretty hard-to-predict branch. But, the stage 1 writes would be simpler. Worth a try I suppose...

@zwegner Hmm, I don't think the branch is as hard to predict as it seems, as long as you handle strings differently (which happens in stage 2). The 3 places it is possible to have 64 bytes of non-structurals, in decreasing likelihood:

1. 64 string characters
2. 64 whitespace characters
3. 65 numeric characters

I would argue that almost no files anywhere will contain 2 or 3, so those branches will be ridiculously predictable. For strings, we don't even need a new branch: we already check for the end quote, and advance n bytes if we don't find it. We can just advance the UPDATE_CHAR pointer along with it.

It's better in stage 2 in this case, because in stage 1 we can't hitch a ride on another branch. Also, if stage 1 eliminates all branches, there is an actual chance of invoking Intel's loop stream detectors--I don't know how much that matters, but I hear it does.

**Comment by jkeiser** [comment]
Here's what it looks like:

Stage 1 Write:

```c++
pj.structurals = new uint64_t[len/64+1];
uint64_t* structurals_out = pj.structurals;
...
pj.structurals[block] = structurals;
block++;
```

Stage 2 Read (note this is destructive, but we don't need to use these afterwards):

```c++
#define UPDATE_CHAR()                                                \
  {                                                                  \
    block += (pj.structurals[block] == 0);                           \
    while (pj.structurals[block] == 0) {                             \
      block++;                                                       \
    }                                                                \
    idx = block*64 + trailing_zeroes(pj.structurals[block]);         \
    pj.structurals[block] = clear_lowest_bit(pj.structurals[block]); \
    c = buf[idx];                                                    \
  }
```

And the string special case (can be done with number, too), piggybacking off the branch that already exists:

```
      // quote_dist is already in parse_string(), when we have found the end quote
      auto quote_dist = trailing_zeroes(helper.quote_bits);
      block = (src + quote_dist + 1 - buf) % 64;
```

**Comment by zwegner** [comment]
Ah yes, good point about the rarity of a structural block being zero--I haven't thought too much about common input data patterns here yet. So I think you're right about prediction not being an issue. The only caveat here is that if you're special-casing string handling like that, then you can't do the lookahead latency hiding I suggested earlier. On that same note, in your code it's probably worth updating to the next block after reading the character and not before, to reduce the dependency chain leading to the actual parsing work that happens for each character.

**Comment by jkeiser** [comment]
> The only caveat here is that if you're special-casing string handling like that, then you can't do the lookahead latency hiding I suggested earlier.

Ooh, you know what, I think we can deal with that too.

1. In stage 1 write, use your trick of `structurals_out += (structurals != 0);`
2. In stage 2, store a `block_idx` that is the index of the current block.
3. In strings and numbers, update `block_idx` explicitly to account for "missing blocks" in the middle of the number or string.
4. For whitespace:
   - Read the next structural character, regardless of whether there is a missing block.
   - In the if() statement that already exists and looks at the character, check for whitespace.
   - If it is whitespace, `block_idx += 64`, read the next character and use `goto` to try again.

Literally no new branches.

> On that same note, in your code it's probably worth updating to the next block after reading the character and not before, to reduce the dependency chain leading to the actual parsing work that happens for each character.

Good point, thanks! Maybe that explains the branch misses I am seeing, even when I don't add branches ...

**Comment by lemire** [comment]
Related issue https://github.com/lemire/simdjson/issues/322

**Comment by lemire** [comment]
This could be revisited, but I don't think we need to track this issue.
