### ISSUE TITLE
The 404 link on the https://simdjson.org 

### ISSUE THREAD

**Issue by ateska** [simdjson/simdjson#1538]
Hi there,

There is a 404 link on the https://simdjson.org, specifically in the following sections:

**On Demand API** to reach massive speeds (4 GB/s). We think it is a better way to parse JSON documents.

^- "On Demand API" points to 404

Sorry for not using the template.

**Comment by lemire** [comment]
Thanks.

**Comment by lemire** [comment]
Fixed https://simdjson.org/?v=100

There is no more link because On Demand is now our default API. 

Thanks for the report.
