### ISSUE TITLE
Latest release does not include the regen of the single header.

### ISSUE THREAD

**Issue by cculianu** [simdjson/simdjson#1543]
Your latest release fixes a bug -- but the single-header is still 0.9.1.

I'd like to be able to use the single header with the latest fix.  How do I regenerate it here?

**Comment by lemire** [comment]
To get release v0.9.2, access the corresponding git tag...
https://github.com/simdjson/simdjson/tree/v0.9.2

or grab one of the archives...

https://github.com/simdjson/simdjson/blob/c6c29c28278aeb29998e89f008908d951bb40c39/singleheader/simdjson.h#L2081


Do not rely on the main branch for serious work.

The version numbers you see in the main branch do not reflect an actual release. Grab the release itself. The main branch is a development branch.

**Comment by cculianu** [comment]
Oh darn. Ok.

**Comment by lemire** [comment]
That's fine. Note that the main branch does have the same fix. It will report a bogus version number, however.

**Comment by cculianu** [comment]
Ok, thanks for the clarification & tip.  

Hmm. Most repos have a dev branch for .. dev :) -- but your house; you set the rules I guess... :)

**Comment by cculianu** [comment]
> That's fine. Note that the main branch does have the same fix. It will report a bogus version number, however.

So I can just use the main branch? I already imported master (and rebuilt the singleheader myself using the instructions) off of master latest commit.  Is that fine?  Or should I re-import the singleheader again into my sources? (I want to avoid commit noise.. heh).

**Comment by lemire** [comment]
> So I can just use the main branch? I already imported master (and rebuilt the singleheader myself using the instructions) off of master latest commit. Is that fine? Or should I re-import the singleheader again into my sources off of v0.9.2? (I want to avoid commit noise.. heh).

No, you should only use the main branch if you plan to contribute to the project. If you are a user, you should consume a release.

You should grab release 0.9.2. You can either grab the zip/tar files or use the tag v0.9.2 on git. The library is also available on a wide range of package management systems which you can use as well.

Of course, I cannot prevent you from working from our main branch, but you are not doing yourself any good by doing so. Our releases receive special attention and we work hard to provide bug-free code.

Furthermore, the main branch evolves and so if you track it, your code might change. The best way to get a stable codebase is to point at specific releases.

> Most repos have a dev branch for .. dev 

I am sure some reserve their main branch for releases, but let us look at some of the most popular C++ projects...

https://github.com/tensorflow/tensorflow
https://github.com/electron/electron
https://github.com/opencv/opencv

They all send commits to their main branch and have distinctly tagged releases.

We do have multiple branches, but our main branch is still made of code that is not designed for library users.

**Comment by cculianu** [comment]
> Of course, I cannot prevent you from working from our main branch, but you are not doing yourself any good by doing so.

Hey man thanks for the tip. Ok, I will just use v0.9.2 release... there go my neat commits :)

No worries -- thanks a lot man. This lib is absolutely incredibly fast. Thanks for all the hard work.
