### ISSUE TITLE
Accessing escaped key with on-demand API

### ISSUE THREAD

**Issue by marmeladema** [simdjson/simdjson#1562]
Hello and thank you for the awesome work you've been doing!

I am considering using simdjson to parse potentially truncated JSON data and I did some poking around the on-demand API and it works very well.

However, one thing that is currently blocking me is the ability to access the value of a potentially escaped key given a trusted non-escaped input key:
* I want to access the value associated with the key `key` in the following document `{"k\u0065y": {...}}`

I wonder what would be the best approach?

Right now, I am considering iterating over all object's properties and un-escaping manually each key in order to select the correct one.

Is there a better way of doing this?

**Comment by jkeiser** [comment]
Unfortunately, I think iterating is what you have to do; however, you can use field.unescaped_key to get the unescaped key--no need to do it manually.

**Comment by lemire** [comment]
This prints the raw unescaped strings...

```C++
    for (auto field : element.get_object()) {
      cout << field.key();
    }
```


This prints the strings that have been unescaped as needed...

```C++
    for (auto field : element.get_object()) {
      cout << unescaped_key();
    }
```

**Comment by lemire** [comment]
Here is a complete example:

```
#include <iostream>
#include "simdjson.h"
using namespace simdjson;
int main() {
    auto json = R"({"k\u0065y": 1})"_padded;
    ondemand::parser parser;
    auto doc = parser.iterate(json);
    ondemand::object object = doc.get_object();
    for(auto field : object) {
      std::string_view keyv = field.unescaped_key();
      if(keyv == "key") {
         std::cout << uint64_t(field.value());
      }
    }
}
```

**Comment by marmeladema** [comment]
Thank you very much! I managed to implement what I needed with your help :+1:
