### ISSUE TITLE
Parsing std::string - compilation errors

### ISSUE THREAD

**Issue by KordianD** [simdjson/simdjson#1579]
I have some strange problems in parsing std::string.

I am looking at the docs.

    Output to sstrings: Given a document or an element (or node) out of a JSON document, you can output a string version: 
    simdjson::to_string(element) returns a simdjson::simdjson_result<std::string> instance. You can cast it to std::string and it will 
    throw when an error was encountered (std::string(simdjson::to_string(element))). 

And I am trying to use it.

    #include "simdjson.h"

    using namespace simdjson;
    int main(void) {

        ondemand::parser parser;
       auto cars_json = R"( { "test": "result"  }  )"_padded;
       auto doc = parser.iterate(cars_json);

       const std::string result = std::string(simdjson::to_string(doc.find_field("test")));
    }

My gcc version:

    gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Command compilation:

    c++ -std=c++17 -o string  string.cpp simdjson.cpp

Compilation errrors: (only parts of it pasted here)

    In file included from string.cpp:1:
    simdjson.h: In instantiation of ‘std::string simdjson::to_string(T) [with T = simdjson::fallback::ondemand::value; std::string = 
    std::__cxx11::basic_string<char>]’:
    simdjson.h:6025:21:   required from ‘std::string simdjson::to_string(simdjson::simdjson_result<T>) [with T = 
    simdjson::fallback::ondemand::value; std::string = std::__cxx11::basic_string<char>]’
    string.cpp:11:85:   required from here
    simdjson.h:6017:5: error: no matching function for call to 
    ‘simdjson::internal::string_builder<>::append(simdjson::fallback::ondemand::value&)’
     6017 |     sb.append(x);
          |     ^~
     In file included from string.cpp:1:
    simdjson.h:8965:13: note: candidate: ‘void simdjson::internal::string_builder<T>::append(simdjson::dom::element) [with formatter 
    = simdjson::internal::mini_formatter]’
     8965 | inline void string_builder<serializer>::append(simdjson::dom::element value) {
          |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from string.cpp:1:
    simdjson.h:5872:45: note:   no known conversion for argument 1 from ‘simdjson::fallback::ondemand::value’ to 
    ‘simdjson::dom::element’
     5872 |   inline void append(simdjson::dom::element value);
          |                      ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
    In file included from string.cpp:1:
    simdjson.h:9111:13: note: candidate: ‘void simdjson::internal::string_builder<T>::append(simdjson::dom::array) [with formatter = 
    simdjson::internal::mini_formatter]’
     9111 | inline void string_builder<serializer>::append(simdjson::dom::array value) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from string.cpp:1:
    simdjson.h:5874:43: note:   no known conversion for argument 1 from ‘simdjson::fallback::ondemand::value’ to 
    ‘simdjson::dom::array’
     5874 |   inline void append(simdjson::dom::array value);
          |                      ~~~~~~~~~~~~~~~~~~~~~^~~~~
    In file included from string.cpp:1:
    simdjson.h:9096:13: note: candidate: ‘void simdjson::internal::string_builder<T>::append(simdjson::dom::object) [with formatter = 
    simdjson::internal::mini_formatter]’
     9096 | inline void string_builder<serializer>::append(simdjson::dom::object value) {
          |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from string.cpp:1:
    simdjson.h:5876:44: note:   no known conversion for argument 1 from ‘simdjson::fallback::ondemand::value’ to 
    ‘simdjson::dom::object’
     5876 |   inline void append(simdjson::dom::object value);
          |                      ~~~~~~~~~~~~~~~~~~~~~~^~~~~
    In file included from string.cpp:1:
    simdjson.h:9126:29: note: candidate: ‘void simdjson::internal::string_builder<T>::append(simdjson::dom::key_value_pair) [with 
    formatter = simdjson::internal::mini_formatter]’
     9126 | simdjson_really_inline void string_builder<serializer>::append(simdjson::dom::key_value_pair kv) {
           |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from string.cpp:1:
    simdjson.h:5888:68: note:   no known conversion for argument 1 from ‘simdjson::fallback::ondemand::value’ to 
    ‘simdjson::dom::key_value_pair’ 
     5888 |   simdjson_really_inline void append(simdjson::dom::key_value_pair value);
          |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

What am I doing wrong?

**Comment by lemire** [comment]
> string_builder<serializer>::append(simdjson::dom::element value) {

It is mixing up DOM with ondemand.

**Comment by KordianD** [comment]
@lemire Thanks for answering.

Is there  "simdjson::to_string" version for ondemand?

**Comment by lemire** [comment]
See https://github.com/simdjson/simdjson/pull/1580

The workaround is to do something like...

```
ondemand::value v;
doc.find_field("test").get(v);
to_string(v);
```

... but my PR will do that for you.

**Comment by KordianD** [comment]
That was quick! Thank you very much

**Comment by lemire** [comment]
> That was quick! Thank you very much

We take software seriously. We really want the next big release of simdjson to be smooth.

**Comment by lemire** [comment]
Thanks for reporting it. It should now be fixed but I encourage you to verify my fix.

**Comment by KordianD** [comment]
I can confirm it is working, thanks.
