### ISSUE TITLE
Split sources and json test data

### ISSUE THREAD

**Issue by ivan-volnov** [simdjson/simdjson#1581]
Hello!

Currently the repo takes 33 Mb of disk space.
It's not the best idea to include it to a project as a submodule.

How about splitting json test data into another project or CI and make this project a ready to use library?

Usage scenario:
Submodule + CMake add_subdirectory()

**Comment by lemire** [comment]
Note that we have an import dependency function.

https://github.com/simdjson/simdjson/blob/95b4870e20be5f97d9dcf63b23b1c6f520c366c1/dependencies/import.cmake

We *do not want to use submodules*.

**Comment by lemire** [comment]
> If you add a submodule, it downloads all the history. How would you fix it?

We do not use submodules and will not use them. However, it is possible to grab a submodule without all of the history.

No matter: submodules are slow.

**Comment by ivan-volnov** [comment]
Yes of course. You don't use submodules.
The users of the library can use submodules to add simdjson to their projects. It's the goal of this issue.

Ok, may be it's possible to grab a submodule without all of the history. I'll check it later.

**Comment by lemire** [comment]
> may be it's possible to grab a submodule without all of the history

It is definitively possible.

https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt---depth

Using submodules for dependencies is still bad. I have stopped doing it. I recommend strongly against it. It is always much slower than needed.

**Comment by lemire** [comment]
And using submodules is not even convenient. So you have both inconvenience and slowness.

**Comment by ivan-volnov** [comment]
Ok, I do accept your advice as soon I find a reasonable alternative.

But, anyway, you can convince me, but you can't convince the whole world not to use submodules. As a library developer you have a responsibility to make all user scenarios working.

For instance, currently I wrote a custom section in my cmake file for compiling amalgamated sources into a static library, and every single update I do a pull into a separate directory, run amalgamation and copy the two files into my project, replacing existing files. Than create a updating commit. It's a ten times slower than just use a git submodule.
