### ISSUE TITLE
Review tests requiring compilation of the library twice

### ISSUE THREAD

**Issue by friendlyanon** [simdjson/simdjson#1604]
In my last PR #1512 some comments were made about the solution to pass properties that the main library target is built with to the test targets `numberparsingcheck` and `stringparsingcheck`.

These test targets basically overwrite some functionality in the code, based on my understanding.

Is there a way to do this testing without having to compile the library twice and passing properties around like they are now?  
I haven't looked at the code closely, but link time dependency injection could solve such things AFAIK.

Resolving this would allow the props thing to be removed and I can continue working on the build files.

**Comment by lemire** [comment]
Are you sure that the library is built more than once? I do not see that and I build this code daily.

**Comment by friendlyanon** [comment]
https://github.com/simdjson/simdjson/blob/master/tests/dom/numberparsingcheck.cpp#L170

https://github.com/simdjson/simdjson/blob/master/tests/dom/stringparsingcheck.cpp#L296

**Comment by lemire** [comment]
As far as I can tell, there is no library build there. That is, there is not simdjson.dll or simdjson.lib. 

For some specific tests, we build instrumented versions of the code where we intercept the number and string parsing, to check it as it happens.

> link time dependency injection could solve such things AFAIK

Can you elaborate?

**Comment by lemire** [comment]
Can you sketch your proposed solution ?

**Comment by friendlyanon** [comment]
> That is, there is not simdjson.dll or simdjson.lib.

I meant that as in the same code is compiled multiple times, which an `#include "simdjson.cpp"` achieves.

> Can you elaborate?

You can build the library with an option to use weak symbols for the functions you want to override. On Unix systems, this is a fairly well understood thing. For Windows, I haven't had much success in finding concrete examples, but supposedly `__declspec(selectany)` can achieve the same thing.

**Comment by lemire** [comment]
> You can build the library with an option to use weak symbols for the functions you want to override. 

Pull request invited !

Please make sure that the functions do get inline as needed. These are functions that are possibly called hundreds of thousands of times, we'd hate for them not to be inlined.

**Comment by friendlyanon** [comment]
The weak symbol markers would only conditionally be added for testing purposes, otherwise in normal builds people would be able to override functions. I took a closer look at options and it turns out that `__declspec(selectany)` only works on data, not functions, but the [`/ALTERNATENAME`](https://devblogs.microsoft.com/oldnewthing/20200731-00/?p=104024) linker flag can be used to achieve the weak symbol mechanism for functions with C linkage. But then again, I'm not too familiar with the way Windows handles `.lib` and `.obj` files when linking.

**Comment by friendlyanon** [comment]
Actually, weak symbols would overcomplicate things. The most portable and straightforward thing would be to have such a target structure, where the parts that the tests want to override are declared as extern and components of the library are exposed internally as multiple object libraries. This would avoid having to compile the library multiple times and you simply would have to link the appropriate object targets depending on what you are building.

**Comment by jkeiser** [comment]
Note that at this point it is probably possible to run these tests without linking to the simdjson library source at all, since number parsing and string parsing are now in headers. This also means you can declare the special callbacks before including simdjson.h and it will work.

i.e. I don't think it's strictly necessary to use the #include simdjson.cpp version of these tests anymore, and we can link to simdjson the same as any other test.

**Comment by friendlyanon** [comment]
Can you look into doing that? If `#include "simdjson.cpp"` could be dropped from those tests, then that would simplify things greatly.

**Comment by jkeiser** [comment]
Sure. #1605 ought to do it.

**Comment by friendlyanon** [comment]
Fantastic! I'll work in making the build tooling very much gooder in the near future!

I'll quickly make a PR for the props thing, as it is not needed anymore.
