### ISSUE TITLE
simdjson::to_string does not work with ondemand API?

### ISSUE THREAD

**Issue by radex** [simdjson/simdjson#1607]
**Describe the bug**

According to https://github.com/simdjson/simdjson/blob/master/doc/basics.md , simdjson::ondemand::value can be converted into a JSON string using `simdjson::to_string`, however as far as I can tell, that's not actually possible, and only works with the older simdjson::dom APIs

**To Reproduce**

```cpp
void test() {
    using namespace simdjson;
    auto cars_json = R"( { "test": "result"  }  )"_padded;
    ondemand::parser parser;
    ondemand::document doc = parser.iterate(cars_json);
    std::cout << simdjson::to_string(doc["test"]) << std::endl;
}
```

This triggers a compiler error:

```
No matching member function for call to 'append'
In instantiation of function template specialization 'simdjson::to_string<simdjson::arm64::ondemand::value>' requested here
In instantiation of function template specialization 'simdjson::to_string<simdjson::arm64::ondemand::value>' requested here
Candidate function not viable: no known conversion from 'simdjson::arm64::ondemand::value' to 'simdjson::dom::element' for 1st argument
Candidate function not viable: no known conversion from 'simdjson::arm64::ondemand::value' to 'simdjson::dom::array' for 1st argument
Candidate function not viable: no known conversion from 'simdjson::arm64::ondemand::value' to 'simdjson::dom::object' for 1st argument
Candidate function not viable: no known conversion from 'simdjson::arm64::ondemand::value' to 'simdjson::dom::key_value_pair' for 1st argument
```

Is there something I'm missing or is the documentation incorrect and it's simply not possible to do this?

**Configuration (please complete the following information if relevant):**

Xcode 12.2

**Indicate whether you are willing or able to provide a bug fix as a pull request**

I don't feel confident in my C++ skills but if the fix is reasonably simple, I can give it a try with some basic guidance

**Comment by lemire** [comment]
Thanks for the report.
I have added a test based on your code sample in PR
https://github.com/simdjson/simdjson/pull/1608

and it looks like it is going to pass our tests. It certainly does build.


Please note that you do not specify the simdjson version that you are using, but you are referencing the documentation in our main branch. If you are using our main branch, please be mindful that it is not meant for production use.

If you are working from a release, please refer to the documentation of the release.

**Comment by radex** [comment]
Ah, I see my confusion now. I'm using version 0.9.5, and since it was just recently released, I incorrectly assumed that the documentation on `master` is up to date, but I can see now that the bit about `to_string` is not present on 0.9.5 tag...

I'd suggest that you consider tagging new releases as `latest` (or merging in release commits to a `release` branch) so that it's trivially easy to point to latest _release_ documentation in README. Hopefully that would avoid confusing future users with pre-release features

**Comment by lemire** [comment]
Point taken. I am adding a "versions" section to our documentation.

https://github.com/simdjson/simdjson/pull/1611
