### ISSUE TITLE
Determine commit rev in master from release version

### ISSUE THREAD

**Issue by ivan-volnov** [simdjson/simdjson#1620]
Hello,

I can't figure it out how to determine commit rev in master from release version.
There are no tags in master. And [actual tags](https://github.com/simdjson/simdjson/commits/v0.9.6) have nothing in common with the master branch.

**Comment by lemire** [comment]
The releases as well as their commit hash appear are provided in the release page:

https://github.com/simdjson/simdjson/releases

Releases are not necessarily created out of the `master` branch.
