### ISSUE TITLE
INCORRECT_TYPE can mask actual structure problems

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1632]
We presently treat `INCORRECT_TYPE` errors as *ignoreable*; that is, if you get it, iteration won't stop.

Two things are possible here:
1. Set the contract so that if you get INCORRECT_TYPE, you must EITHER try again with a different type, OR stop iterating. (i.e. treat INCORRECT_TYPE as a recoverable error, but not an ignorable one).
2. Add code in the INCORRECT_TYPE case to check for structure (open/close/comma/colon) and if those are found, return TAPE_ERROR (since it is in fact not a recoverable error). This will increase cold path code size and inlining complexity, but ... shouldn't? ... impact main path performance much.

### Example

Presently, this code will trigger a TAPE_ERROR because the iterator

```c++
ondemand::parser parser;
auto doc = parser.iterate(R"({
  "a": { "x": },
  "b": { "x": 1 }
}");
uint64_t a;
if ( doc["a"]["x"].get(a) == INCORRECT_TYPE ) { std::cout << "You might want to change x to be something this program can read! Continuing ..."; }
```

I would expect either:
1. For `doc["a"]["x"].get(a)` to yield TAPE_ERROR
2. For simdjson to yield INCORRECT_TYPE but then succeed in `doc["b"]["x"]` (this is possible if we don't advance until the value is actually parsed).
3. For the user to somehow know that parsing cannot continue after an error, and not write this code at all.

This has impact on #1511 , because we can't switch to a (probably) more performant method of detecting the end of the buffer if ondemand is allowed to ignore `]` or `}` when the user gets a non-terminal error.

**Comment by lemire** [comment]
Marked for 1.0 since we obviously do not want to release without a fix of some kind.

**Comment by jkeiser** [comment]
I'm going to try the route of reporting TAPE_ERROR (really should be something like MISSING_VALUE) instead of INCORRECT_TYPE and stopping iteration.

**Comment by jkeiser** [comment]
It's not entirely unreasonable, mind you, to tell the user that they must not continue when they get an error. But we *try* to protect users that don't do this (for example, we have code that exits iteration on error, even though the user ought to call `break`).

**Comment by lemire** [comment]
@jkeiser No, it is not unreasonable. Of course, it needs to be explained and documented.

**Comment by jkeiser** [comment]
Yep! I'm going to try the other possible fixes and see if we can get through without a performance hit (the one where we emit TAPE_ERROR is promising because all the new code goes in the error case). Then we can decide whether to take one or document and move on.

**Comment by jkeiser** [comment]
Note: the top two commits in https://github.com/simdjson/simdjson/commits/jkeiser/no-padding-2 implement the TAPE_ERROR method. However, I got some kind of failure. Between work and travel this week I may not get back to it till the weekend or after, but it's next up on my plate whenever that is.

**Comment by jkeiser** [comment]
(It has been a few days, but IIRC the failures are actually just due to the fact that I haven't finished fixing the tests--AFAIK the code is correct.)

**Comment by strager** [comment]
I noticed that we do get TAPE_ERROR if we ask for the `value`'s type (`simdjson::ondemand::value::type()`), but not if we cast (`simdjson::ondemand::value::get_object()`, etc.). To distinguish invalid JSON from unexpected types, I call `value::type()` to get a useful error code.

I wrote a test case documenting what I would prefer from simdjson (before I saw that this issue was filed): https://gist.github.com/2719c1151c40158542709375c8216ad3

**Comment by lemire** [comment]
@jkeiser So @strager identified to scenarios where the problem occur. For that to happen, you need a malformed JSON document, and you need to access the document with wrong type.

Case 1.

Given `{"globals":{"a":{"shadowable":[}}}}`, you can have the following code...

```

      ASSERT_SUCCESS(global_object["shadowable"].get(shadowable));
      ASSERT_ERROR(shadowable.get_bool(), INCORRECT_TYPE);
      ondemand::value badvalue;
      auto error = global_object["writable"].get(badvalue);
```

It leads to this sequence...

```
===========
|         match        | "shadowable":[}}}}             | :[}}}}     |     4 | shadowable |
|         bool         | [}}}}                          | }}}}       |     4 |  |
|         ERROR: Not a boolean | [}}}}                          | }}}}       |     4 |  |
===========
|       -object        | }}}}                           | }}}        |     3 |  |
|       +object        | {"shadowable":[}}}}            | "shadowabl |     3 |  |
|         no match     | "shadowable":[}}}}             | :[}}}}     |     4 | writable |
|         +skip        | [}}}}                          | }}}}       |     4 |  |
|         -skip        | }}}}                           | }}}        |     4 |  |
```

Another example is `({"":],"global-groups":[[]}})`, with the following code sequence...

```
    simdjson::ondemand::object global_groups;
    ASSERT_ERROR(doc["global-groups"].get(global_groups), INCORRECT_TYPE);
    simdjson::ondemand::object globals;
    ASSERT_ERROR(doc["globals"].get(globals), TAPE_ERROR);
```

You get the following log...

```
===========
|     no match         | "":],"global-groups":[[]}}     | :],"global |     2 | global-groups |
|     -skip            | ],"global-groups":[[]}}        | ,"global-g |     2 |  |
|     match            | "global-groups":[[]}}          | :[[]}}     |     2 | global-groups |
|     +object          | [[]}}                          | []}}       |     2 |  |
|     ERROR: Not an object | [[]}}                          | []}}       |     2 |  |
===========
|     +skip            | []}}                           | ]}}        |     2 |  |
|     -skip            | ]}}                            | }}         |     2 |  |
|   -object            | }}                             | }          |     1 |  |
|   +object            | {"":],"global-groups":[[]}}    | "":],"glob |     1 |  |
|     no match         | "":],"global-groups":[[]}}     | :],"global |     2 | globals |
|     -skip            | ],"global-groups":[[]}}        | ,"global-g |     2 |  |
|     no match         | "global-groups":[[]}}          | :[[]}}     |     2 | globals |
|     +skip            | [[]}}                          | []}}       |     2 |  |
|     +skip            | []}}                           | ]}}        |     2 |  |
|       -skip          | ]}}                            | }}         |     3 |  |
|     -skip            | }}                             | }          |     2 |  |
```

**Comment by lemire** [comment]
@strager I have conceptually merged your two tests with this issue, and I have marked the issue as a 'bug' (upgraded from 'bug (unverified)' since you have provided the independent verification.

I think we should fix all of that in one unified manner.

**Comment by lemire** [comment]
Current status (for people reading this)... @jkeiser has identified the bug, he started working on a fix... I believe that @strager effectively stumbled on it independently...

It feels like the approach taken by @jkeiser is the right one.

So we have a bug, but also a good path to fix the issue.

I believe @strager describes a decent workaround...

> I noticed that we do get TAPE_ERROR if we ask for the value's type (simdjson::ondemand::value::type()), but not if we cast (simdjson::ondemand::value::get_object(), etc.). To distinguish invalid JSON from unexpected types, I call value::type() to get a useful error code.

Evidently, we want to do better than that.


@strager : please note that I am *not* dismissing the issues you raised. Your tests will be included in simdjson in the future.

**Comment by strager** [comment]
> I believe @strager describes a decent workaround...
> 
> > I noticed that we do get TAPE_ERROR if we ask for the value's type (simdjson::ondemand::value::type()), but not if we cast (simdjson::ondemand::value::get_object(), etc.). To distinguish invalid JSON from unexpected types, I call value::type() to get a useful error code.

To be clear: this workaround doesn't apply for #1661. I haven't found a workaround for #1661, so I stopped fuzz-testing my project.

**Comment by lemire** [comment]
> To be clear: this workaround doesn't apply for #1661. I haven't found a workaround for #1661, so I stopped fuzz-testing my project.

Please elaborate.

In issue 1661, you are grabbing the value matching key `"global-groups"` and assuming it is an object. If you first check its type, it will not report back that it is an object.

Here is a new test I added...

```
    ondemand::parser parser;
    padded_string docdata = R"({"":],"global-groups":[[]}})"_padded;
    ondemand::document doc;
    ASSERT_SUCCESS(parser.iterate(docdata).get(doc));
    ondemand::value global_groups;
    ASSERT_SUCCESS(doc["global-groups"].get(global_groups));
    ondemand::json_type global_type;
    ASSERT_SUCCESS(global_groups.type().get(global_type));
    ASSERT_EQUAL(global_type, ondemand::json_type::array);
    TEST_SUCCEED();
````

**Comment by lemire** [comment]
@strager This is important, if you are getting issues without triggering an INCORRECT_TYPE, then that would be something else, but both test cases you provided trigger than INCORRECT_TYPE.

For reference here is your code for 1661...

```C++
 
  bool strager_bug() {
    TEST_START();

    simdjson::ondemand::parser parser;
    simdjson::padded_string docdata = R"({"":],"global-groups":[[]}})"_padded;
    simdjson::ondemand::document doc;
    ASSERT_SUCCESS(parser.iterate(docdata).get(doc));

    simdjson::ondemand::object global_groups;
    ASSERT_ERROR(doc["global-groups"].get(global_groups), INCORRECT_TYPE);
    simdjson::ondemand::object globals;
    ASSERT_SUCCESS(doc["globals"].get(globals));

    TEST_SUCCEED();
  }
```


The issue as I understand it is that if the underlying JSON document is invalid *and* you trigger an INCORRECT_TYPE, then you get in trouble. If that's not the issue then we need to discuss some more to make sure it is well described.

**Comment by lemire** [comment]
> Note: the top two commits in https://github.com/simdjson/simdjson/commits/jkeiser/no-padding-2 implement the TAPE_ERROR method. However, I got some kind of failure. Between work and travel this week I may not get back to it till the weekend or after, but it's next up on my plate whenever that is.

I took those two commits and created PR https://github.com/simdjson/simdjson/pull/1663

**Comment by lemire** [comment]
@strager I would be really interested in an test case where you get a bad result by first asking for the type and then asking for the value.

One way to understand the current simdjson (prior to our current attempts) is that INCORRECT_TYPE is an unrecoverable condition. Once you have hit INCORRECT_TYPE, then you should give up.

If I am wrong, I would like to know.
