### ISSUE TITLE
document_stream truncated_bytes missing from header-only version

### ISSUE THREAD

**Issue by oysstu** [simdjson/simdjson#1641]
Hi,

The truncated_bytes function of document_stream is not present in the header-only version of the library (master).
https://github.com/simdjson/simdjson/blob/2abcc35031152ac4a8d867775b035203a8ae7541/include/simdjson/dom/document_stream.h#L112

Best,
Øystein

**Comment by lemire** [comment]
It is a new function which will be part of our next release.

We do not backport new functions on previous releases.
