### ISSUE TITLE
FetchContent broken as of v0.9.3

### ISSUE THREAD

**Issue by dirocco** [simdjson/simdjson#1656]
**Describe the bug**% 
cmake .
[ 11%] Performing update step for 'simdjson-populate'
fatal: invalid upstream 'origin/v0.9.3'
fatal: No rebase in progress?
CMake Error at /home/dirocco/code/tmp/simdjsontest/_deps/simdjson-subbuild/simdjson-populate-prefix/tmp/simdjson-populate-gitupdate.cmake:102 (message):
  

  Failed to rebase in:
  '/home/dirocco/code/tmp/simdjsontest/_deps/simdjson-src/'.

  You will have to resolve the conflicts manually

**To Reproduce**
`
cmake_minimum_required(VERSION 3.16)
project(simdjsontest)

include(FetchContent)

FetchContent_Declare(
        simdjson
        GIT_REPOSITORY https://github.com/simdjson/simdjson.git
        GIT_SHALLOW TRUE
        GIT_TAG v0.9.3
        )
FetchContent_MakeAvailable(simdjson)
`

**simjson release:**
Works in v0.9.2, broken for all releases afterwards.

**Configuration (please complete the following information if relevant):**
 - OS: Ubuntu 20.04.2 LTS
 - Compiler: cmake 3.16.3, git 2.25.1

**Comment by lemire** [comment]
Thank you.  I recommend you use the following...

```
GIT_TAG tags/v0.9.6
```

You may also provide the git hash instead when working with `FetchContent_Declare` which has its own benefits...

```
GIT_TAG  e9b893ff1b13c6a70135827c62b3f3d65938d135 # version 0.9.6
```
