### ISSUE TITLE
Assert failure when compiling in debug mode (with assertions) on invalid JSON during object lookup after cast-to-object failure (On Demand)

### ISSUE THREAD

**Issue by strager** [simdjson/simdjson#1661]
**Describe the bug**
 I'm parsing the following invalid JSON:
```json
{"":],"hello":[[]}}
```

I look up `hello` and cast it to an `object`. After, I look up `world`. This second lookup crashes.

**To Reproduce**
https://gist.github.com/011728dca24a3ab03a9e34eaac2371e3

Output:
```
[snip]
> Running strager_bug ...
ondemand_misc_tests: ../include/simdjson/generic/ondemand/value_iterator-inl.h:292: simdjson_result<bool> simdjson::fallback::ondemand::value_iterator::find_field_unordered_raw(const std::string_view): Assertion `has_value' failed.
```

**simjson release:** v0.9.6 and master (774999ee95a8fbca36c7d914ae47c676b58f7938)

**Configuration:**
 - OS: Linux Mint 20 Ulyana (based on 20.04 Focal)
 - Compiler: clang version 11.0.0 (176249bd6732a8044d457092ed932768724a6f06) x86_64-unknown-linux-gnu

**Indicate whether you are willing or able to provide a bug fix as a pull request**
Willing: Yes. Planning: No.

**Comment by strager** [comment]
This crash looks similar to #1660. It might have a different root cause, so I filed a separate issue.

**Comment by lemire** [comment]
Yeah. I am going to close this issue and merge it with 1660. If it proves like a distinct issue, we could always revisit, but I expect it is the same issue.

**Comment by lemire** [comment]
Great contribution by the way. Keep the reports coming.
