### ISSUE TITLE
Using locale dependent std::to_string function in various places

### ISSUE THREAD

**Issue by jardik** [simdjson/simdjson#1681]
In "JSON Pointer" category of "The Basics" document, the json "path" is composed using locale dependent std::to_string function, which can add spaces or other thousand separators into the resulting string-number. This could probably lead to failures if non-C locale is used by the application.

The same function is used in various tests and even in code itself (simdjson/generic/ondemand/json_iterator-inl.h). I believe json parsing should be locale-independent.

**Comment by lemire** [comment]
If you suspect that there is a bug in the library, then please suggest a verifying test. Locale-independence is important but one still has to illustrate the bug in simdjson.

We, of course, want our documentation to work for as many users as possible. Can you tell us what is your locale, so we can verify your issue? I cannot find this important information in your issue. 

You say that you are seeing spaces inside the serialized integers… Which locales behave this way?

Otherwise pull requests are always invited. Note that we are a C++11 library.

**Comment by lemire** [comment]
> The same function is used in various tests and even in code itself (simdjson/generic/ondemand/json_iterator-inl.h). I believe json parsing should be locale-independent.

The simdjson library abides by the standard, so it processes JSON in a locale-independent manner. Any deviation from that would be a bug, and I urge you to report it.

I looked at the usage you reported in the library and it is used as part of our logging. I have a hard time imagining how it caused you problems.


I cannot stress this enough: bug reports need to be accompanied with reproducing tests, system descriptions and so forth.

**Comment by jardik** [comment]
Probably because I am dumb and/or documentation of std::to_string on cppreference website is misleading.
It says "std::to_string relies on the current locale for formatting purposes" ([link](https://en.cppreference.com/w/cpp/string/basic_string/to_string)].

So with my system locale (cs_CZ.UTF-8) if I use std::cout to print an integer, it will use thousand separator (space) and for value of 1000, it will print "1 000". My thoughts were that std::to_string for an integer will also add this thousands separator. But after I actually tried it, it does NOT add the thousand separator.

Then it also states: Converts a signed integer to a string with the same content as what std::sprintf(buf, "%d", value) would produce for sufficiently large buf.

Trying sprintf after setting my locale, and it also does NOT add thousand separator.

If I try using floats, both will use locale-dependent decimal separator, but not thousand separator. I am quite confused by this. Can someone point me where this is explained and why both std::to_string and sprinf ignore thousand separator of the locale, but not decimal separator, and why std::cout is using both?

Anyway, I am sorry about this bug report if this is indeed expected standard behavior.

**Comment by lemire** [comment]
Thanks. Note that to_string is not used for JSON generation and thus simdjson should not be locale dependent (if I am wrong, please report it as s bug).

I will close this. We do invite bug reports. Make sure that we can reproduce the issue.
