### ISSUE TITLE
Extract utf-8 characters

### ISSUE THREAD

**Issue by kostya** [simdjson/simdjson#1682]
Library provide validation function: https://github.com/simdjson/simdjson/blob/master/doc/basics.md#utf-8-validation-alone. But is it possible to get all utf-8 characters from string? If it possible would be nice to have that feature.

**Comment by lemire** [comment]
Can you sketch the API you have in mind?

**Comment by kostya** [comment]
may be like this
```c++
    char * some_string = "[ 1, 2, 3, 4] ";
    size_t length = std::strlen(some_string);

    uint32_t buffer[10];
    int buffer_extracted_count;
    while(simdjson::utf8_extract_chars(&some_string, &length, buffer, 10, &buffer_extracted_count)) {
       // do something with buffer
    }
```

some_string and length updated after each batch.

**Comment by lemire** [comment]
So you want UTF-8 to UTF-32 transcoding?

**Comment by kostya** [comment]
yes, looks like that, close it here, as you open it in simdutf
