### ISSUE TITLE
The "Server Loops: Long-Running Processes and Memory Capacity" section of the performance notes is a dead link

### ISSUE THREAD

**Issue by isiahmeadows** [simdjson/simdjson#1718]
[This commit](https://github.com/simdjson/simdjson/commit/6dc98561a9e186e60c6a205fa03848275c24750d#diff-ee0b2d5b5f2b4e801f38f6bb8d3049a0c5839ebb247d77f709b9bd964824ec2e) turned the "Server Loops: Long-Running Processes and Memory Capacity" section of the [performance notes](https://github.com/simdjson/simdjson/blob/master/doc/performance.md) into a dead link, as it removed that section without removing that TOC entry. Should this have been removed, or does it still apply to on demand parsers?

**Comment by lemire** [comment]
Thanks. This section was misplaced in our document. I am moving it back via https://github.com/simdjson/simdjson/pull/1719
