### ISSUE TITLE
weird bug?

### ISSUE THREAD

**Issue by zalmoxis2019** [simdjson/simdjson#1723]
Hello, when i remove the comment for the commented line bellow, the code will crush at get_uint64_in_string(), why? Is this some weird feature?

simdjson::ondemand::array bids = elem.find_field("contents").find_field("bids").get_array();
**//simdjson::ondemand::array asks = elem.find_field("contents").find_field("asks").get_array();** 
for (auto aux : bids)
{
    uint64_t id = aux["offset"].get_uint64_in_string();
    double price = aux["price"].get_double_in_string();
    double size = aux["size"].get_double_in_string();

    ...
}

**Comment by lemire** [comment]
Do not write the code this way...

```C++
simdjson::ondemand::array bids = elem.find_field("contents").find_field("bids").get_array();
simdjson::ondemand::array asks = elem.find_field("contents").find_field("asks").get_array();
```

You are doing two accesses to the `"content"` key. It is inefficient.

**Comment by lemire** [comment]
Note that `simdjson` will not just "crush". It will return an error code or throw an exception.

Please provide a complete error report with a reproducible test case.

Be aware that `find_field` will seek fields in order.

I am going to close this. We are eager to help, but we need to complete error report.

**Comment by lemire** [comment]
Here is a working example that might look like what you are trying to do...

```C++

    simdjson::ondemand::parser parser;
    simdjson::padded_string docdata =  R"({
    "contents":
    {
      "bids":[
         {"offset":"1", "price":"1.1", "size":"4.1"}
      ],
      "asks":[
        {"offset":"1111", "price":"1.100", "size":"114.1"}
      ]

    }
    })"_padded;
    simdjson::ondemand::document doc;
    auto error = parser.iterate(docdata).get(doc);
    if(error) { return false; }
    ondemand::object content;
    error = doc.get_object().find_field("contents").get(content);
    if(error) { return false; }
    ondemand::array bids;
    error = content["bids"].get_array().get(bids);
    if(error) { return false; }
    for (auto aux : bids) {
      uint64_t id;
      error = aux["offset"].get_uint64_in_string().get(id);
      if(error) { return false; }
      double price;
      error = aux["price"].get_double_in_string().get(price);
      if(error) { return false; }
      double size;
      error = aux["size"].get_double_in_string().get(size);
      if(error) { return false; }
      std::cout << id << " " << price << " " << size << std::endl;
    }
    ondemand::array asks;
    error = content["asks"].get_array().get(asks);
    if(error) { return false; }
    for (auto aux : asks) {
      uint64_t id;
      error = aux["offset"].get_uint64_in_string().get(id);
      if(error) { return false; }
      double price;
      error = aux["price"].get_double_in_string().get(price);
      if(error) { return false; }
      double size;
      error = aux["size"].get_double_in_string().get(size);
      if(error) { return false; }
      std::cout << id << " " << price << " " << size << std::endl;
    }
    return true;
```

(It does not use exceptions.)

**Comment by lemire** [comment]
With exceptions,  you may do it this way...

```C++
    simdjson::ondemand::parser parser;
    simdjson::padded_string docdata =  R"({
    "contents":
    {
      "bids":[
         {"offset":"1", "price":"1.1", "size":"4.1"}
      ],
      "asks":[
        {"offset":"1111", "price":"1.100", "size":"114.1"}
      ]

    }
    })"_padded;
    simdjson::ondemand::document doc = parser.iterate(docdata);
    ondemand::object content = doc.get_object().find_field("contents");
    ondemand::array bids = content["bids"].get_array();
    for (auto aux : bids) {
      uint64_t id = aux["offset"].get_uint64_in_string();
      double price = aux["price"].get_double_in_string();
      double size = aux["size"].get_double_in_string();
      std::cout << id << " " << price << " " << size << std::endl;
    }
    ondemand::array asks = content["asks"].get_array();
    for (auto aux : asks) {
      uint64_t id = aux["offset"].get_uint64_in_string();
      double price = aux["price"].get_double_in_string();
      double size = aux["size"].get_double_in_string();
      std::cout << id << " " << price << " " << size << std::endl;
    }
```

**Comment by lemire** [comment]
More details:

A new field access makes unsafe previous fields retrieved on the same object. Thus
  if you have retrieved `content["bids"].get_array()` and you later call `content["asks"].get_array()`, then the first array should no longer be accessed. On the same object, you can only consume one field at a time.

**Comment by zalmoxis2019** [comment]
thank you very much for the detailed explanation and the examples!

**Comment by lemire** [comment]
Thank you for reporting the issue you encountered. I will be adding some documentation.

Note: I do not believe that there is a bug. However, I think we can always improve our documentation... so I thank you for reporting the issue.

**Comment by lemire** [comment]
If you were running your code in debug mode, then it is likely that you got OUT_OF_ORDER_ITERATION error. This would tell you that you are accessing fields 'out of order' (you access one, move to the next one, and then come back to the previous one).

**Comment by zalmoxis2019** [comment]
How can i debug this? It seems i get some random memory accessing in the background that crushes my debugger, using your code? (

Also what is the difference between, they all seem to do the same job?
ondemand::object content = doc.get_object().find_field("contents");
ondemand::object content = doc.find_field("contents").get_object();
auto content = doc["contents"];
auto content = doc["contents"].get_object();

2) The simdjson::dom seemed more stable but lacks these features. What exactly is the purpose of dom vs ondemand?

thank you.

**Comment by lemire** [comment]
> How can i debug this? It seems i get some random memory accessing in the background that crushes my debugger, using your code? (tested the "with exceptions" variant)

If you have encountered what you believe is a bug, please provide a reproducible test case.
