### ISSUE TITLE
Java-version of the project planned?

### ISSUE THREAD

**Issue by JohannesLichtenberger** [simdjson/simdjson#1725]
Do you have any plans to port the project to Java? Maybe it's possible with the new Vector API :-)

**Comment by lemire** [comment]
Duplicate of https://github.com/simdjson/simdjson/issues/121

**Comment by saudet** [comment]
@JohannesLichtenberger BTW, it shouldn't be too hard to get this working with JavaCPP, see https://github.com/bytedeco/javacpp-presets/issues/931.
