### ISSUE TITLE
iterate_many fails with UTF8_ERROR although validate_utf8 passes

### ISSUE THREAD

**Issue by Andersama** [simdjson/simdjson#1729]
I've been able to parse this structure of json with the ondemand parser going over a stream, but I spotted the iterate_many function and thought it would be a good fit. Here's the relevant json that broke things.

```c++
std::string example_json = R"raw({"t": 5649,
  "ng": 5,
  "lu": 4086,
  "g": [
        {
          "t": "Temps",
          "xvy": 0,
          "pd": 60,
          "sz": 3,
          "l": [
                "Low Temp",
                "High Temp",
                "Smooth Avg"
          ],
          "c": [
                "green",
                "orange",
                "cyan"
          ],
          "d": [
                80.48750305,
                80.82499694,
                80.65625
          ]
        },
        {
          "t": "Pump Status",
          "xvy": 0,
          "pd": 60,
          "sz": 3,
          "l": [
                "Pump",
                "Thermal",
                "Light"
          ],
          "c": [
                "green",
                "orange",
                "cyan"
          ],
          "d": [
                0,
                0,
                0
          ]
        },
        {
          "t": "Lux",
          "xvy": 0,
          "pd": 60,
          "sz": 4,
          "l": [
                "Value",
                "Smooth",
                "Low",
                "High"
          ],
          "c": [
                "green",
                "orange",
                "cyan",
                "yellow"
          ],
          "d": [
                2274.62939453,
                2277.45947265,
                4050,
                4500
          ]
        },
        {
          "t": "Temp Diff",
          "xvy": 0,
          "pd": 60,
          "sz": 4,
          "l": [
                "dFarenheit",
                "sum",
                "Low",
                "High"
          ],
          "c": [
                "green",
                "orange",
                "cyan",
                "yellow"
          ],
          "d": [
                0,
                0,
                0.5,
                10
          ]
        },
        {
          "t": "Power",
          "xvy": 0,
          "pd": 60,
          "sz": 3,
          "l": [
                "watts (est. ligth)",
                "watts (1.9~gpm)",
                "watts (1gpm)"
          ],
          "c": [
                "green",
                "orange",
                "cyan"
          ],
          "d": [
                181.78063964,
                114.88922882,
                59.35943603
          ]
        }
  ]
})raw";
```
For whatever reason when using the example from iterate_many it fails almost immediately with a UTF8_ERROR, I'm assuming what's happening is there's supposed to be some other function calls to clear the error and do the validation, I had to do a similar pattern for the ondemand::parser like this:

```c++
ondemand::parser parser;
ondemand::document doc;

bool ok_utf8 = simdjson::validate_utf8(ptr, sz);
padded_string_view json(ptr, sz, capacity);

auto err = parser.iterate(json).get(doc);
if (ok_utf8 && !err) {
//one would assume you could start parsing data here I had to do this
  std::string_view v;
  auto error = simdjson::to_json_string(doc).get(v);
  if (error) {
      return false;
  }
  //now we're ok to parse, if we tried using the rest of the api it'd explode in our face with an error
  //although now we've definitely gone through the json at least once, probably not ideal
}
```
I'm ok with validating the input, but at the very least for something like iterate_many I think there should probably be an accompanying function like `valid_utf8_length()` to work with truncated bytes at the end of a stream.

Edit: may have gotten it working with a different iterate_many example, may have been user error the example I originally followed was using a document_reference like:
```c
for (auto i = stream.begin(); i != stream.end(); ++i) {
  ondemand::document_reference doc;
  auto err = (*i).get(doc);
  if (!err) {
  //
  }
}
}
```
vs now
```c
    for (auto i = stream.begin(); i != stream.end(); ++i) {
        auto doc = *i;
        auto err = i.error();
        if (!err) {
        //
        }
    }
```
I'm not exactly clear on what's happened, I might've followed a test example that was supposed to fail.

**Comment by Andersama** [comment]
Ah sorry, I was busy I could've added more context, the json is valid utf8. The issue was the rest of the data, I was running this function over a serial stream that was spitting out json objects, but also had extraneous characters for the serial communication inbetween, it wasn't the json itself it was what followed after.

**Comment by jkeiser** [comment]
Yeah, we only accept whitespace between documents in parse_many. Our system treats any non-whitespace character as part of a JSON document. There also isn't a way to configure a non-whitespace separator--and if there was, a non-UTF8 separator would be even harder, as UTF-8 validation is presently done in bulk alongside the bulk tokenization step, with a bespoke algorithm designed for speed.

**Comment by Andersama** [comment]
Ah well, given what I know is going in the stream it's not particularly hard to avoid, the stuff that goes between the json objects looks absolutely nothing like json. Stops me from reasonably using iterate_many, but going one by one as fast as this library allows is honestly plenty more than enough for what I'm doing.
