### ISSUE TITLE
Cannot compile with CUDA NVCC 

### ISSUE THREAD

**Issue by ShoeRider** [simdjson/simdjson#1735]
I already tracked the issue down, but I thought I would post a Bug Report for reference, and potential help.
### Goal:
    I am attempting to compile the simdjson library with the NVCC compiler. (Note: I have no desire to run this code on the GPU)

### System info
nvcc --version:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243` 

nvidia-smi:
` NVIDIA-SMI 470.74       Driver Version: 470.74       CUDA Version: 11.4  ` 

### Issue

When including the single Header .h file([simdjson.h](https://github.com/simdjson/simdjson/blob/master/singleheader/simdjson.h)) within a .CU file, or attempting to compile using nvcc with the following command: `nvcc -o amalgamate_demo amalgamate_demo.cu  && ./amalgamate_demo ../jsonexamples/twitter.json ../jsonexamples`

Gives the following error:
```
simdjson.h(2511): warning: attribute does not apply to any entity

simdjson.h(4731): warning: attribute does not apply to any entity
`

simdjson.h(6192): warning: attribute does not apply to any entity

simdjson.h(26881): warning: variable "error" was set but never used

simdjson.h(14050): error: a value of type "__m256i" cannot be used to initialize an entity of type "long long"
          detected during instantiation of "simdjson::haswell::<unnamed>::simd::base8<T, Mask>::base8() [with T=__nv_bool, Mask=simdjson::haswell::<unnamed>::simd::simd8<__nv_bool>]" 
(14096): here

simdjson.h(18765): error: a value of type "__m128i" cannot be used to initialize an entity of type "long long"
          detected during instantiation of "simdjson::westmere::<unnamed>::simd::base8<T, Mask>::base8() [with T=__nv_bool, Mask=simdjson::westmere::<unnamed>::simd::simd8<__nv_bool>]" 
(18811): here

2 errors detected in the compilation of "/tmp/tmpxft_00001f3b_00000000-8_amalgamate_demo.cpp1.ii".
```

As discussed within this Overstack thread, [Can't use __m128i in Cuda kernel](https://stackoverflow.com/questions/63503620/cant-use-m128i-in-cuda-kernel),  I'm assuming "__m256i" has this issue as well. 

Are there any potential workarounds for this ? 

Thank you for your time,

Anthony Schroeder

**Comment by lemire** [comment]
We support 64-bit processors (ARM, x64, Power). CUDA is not a supported platform. Given that CUDA is not SIMD-based, we are unlikely to ever support it.

I am going to close this. If you believe that there is a bug, please demonstrate it using a supported platform.
