### ISSUE TITLE
JSON document ended early in the middle of an object or array 

### ISSUE THREAD

**Issue by jrch2k20** [simdjson/simdjson#1745]
updating to any version of simdjson after 0.9.6(0.9.6 works perfectly) breaks my code and give the following error:

**terminate called after throwing an instance of 'simdjson::simdjson_error'
  what():  JSON document ended early in the middle of an object or array.
Aborted (core dumped)**

CODE:

` std::string_view l_result_holder;

    simdjson::ondemand::parser parser;
    simdjson::padded_string l_padded_jwk { jwk };
    simdjson::ondemand::document l_document;

    auto error = parser.iterate(l_padded_jwk).get(l_document);
    if (unlikely(error)) {
        return false;
    }
for (auto items : l_document["keys"]) {
        if (unlikely(items["kty"].get_string() != "RSA" && items["use"].get_string() != "sig")) {   // GDB bt implies error triggers here
            continue;
        }

        l_result_holder = items["alg"].get_string();
        std::cout <<  l_result_holder << std::endl;
        l_result_holder = items["use"].get_string();
        std::cout <<  l_result_holder << std::endl;
        l_result_holder = items["kty"].get_string();
        std::cout <<  l_result_holder << std::endl;
        l_result_holder = items["n"].get_string();
        std::cout <<  l_result_holder << std::endl;
        l_result_holder = items["e"].get_string();
        std::cout <<  l_result_holder << std::endl;
}
`
JSON: 
https://www.googleapis.com/oauth2/v3/certs

Compiler:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.1.0 (GCC) 

Tyvm for your time

**Comment by lemire** [comment]
Please see https://github.com/simdjson/simdjson/pull/1746

It does not appear like I can reproduce the issue.

Please note that your should not consume a value twice: in this instance you access the keys for `"use"` and `"kty"` twice. Even so, that does not appear to be an issue.

**Comment by lemire** [comment]
I am going to make it clearer in the documentation that you are not expected to access values more than once. Doing `object["use"]` followed by `object["use"]` again is an error. You should capture the `string_view` and refer to it again.

I have marked this as a documentation issue. I will improve the documentation.

If you disagree, then please provide a failing test.

**Comment by lemire** [comment]
The following has been added to our tests and it works without any problem:

```C++

    auto json = R"({
  "keys": [
    {
      "kid": "bbd2ac7c4c5eb8adc8eeffbc8f5a2dd6cf7545e4",
      "e": "AQAB",
      "alg": "RS256",
      "use": "sig",
      "n": "y930dtGTeMG52IPsKmMuEpPHLaxuYQlduZd6BqFVjc2-UFZR8fNqtnYzAjbXWJD_Tqxgdlj_MW4vogvX4sHwVpZONvdyeGoIyDQtis6iuGQhQamV85F_JbrEUnEw3QCO87Liz5UXG6BK2HRyPhDfMex1_tO0ROmySLFdCTS17D0wah71Ibpi0gI8LUi6kzVRjYDIC1oE-iK3Y9s88Bi4ZGYJxXAbnNwbwVkGOKCXja9k0jjBGRxZD-4KDuf493lFOOEGSLDA2Qp9rDqrURP12XYgvf_zJx_kSDipnr0gL6Vz2n3H4-XN4tA45zuzRkHoE7-XexPq-tv7kQ8pSjY2uQ",
      "kty": "RSA"
    },
    {
      "kty": "RSA",
      "n": "zMHxWuxztMKXdBhv3rImlUvW_yp6nO03cVXPyA0Vyq0-M7LfOJJIF-OdNoRGdsFPHVKCFoo6qGhR8rBCmMxA4fM-Ubk5qKuUqCN9eP3yZJq8Cw9tUrt_qh7uW-qfMr0upcyeSHhC_zW1lTGs5sowDorKN_jQ1Sfh9hfBxfc8T7dQAAgEqqMcE3u-2J701jyhJz0pvurCfziiB3buY6SGREhBQwNwpnQjt_lE2U4km8FS0woPzt0ccE3zsGL2qM-LWZbOm9aXquSnqNJLt3tGVvShnev-GiJ1XfQ3EWm0f4w0TX9fTOkxstl0vo_vW_FjGQ0D1pXSjqb7n-hAdXwc9w",
      "alg": "RS256",
      "kid": "85828c59284a69b54b27483e487c3bd46cd2a2b3",
      "e": "AQAB",
      "use": "sig"
    }
  ]
}
  })"_padded;
    ondemand::parser parser;
    ondemand::document doc = parser.iterate(json);
    for (auto items : doc["keys"]) {
      std::string_view kty_value = items["kty"].get_string();
      std::string_view use_value = items["use"].get_string();
      if (kty_value != "RSA" && use_value != "sig") { continue; }
      std::string_view str = items["alg"].get_string();
      if(str != "RS256") { return false; }
      if(use_value != "sig") { return false; }
      if(kty_value != "RSA") { return false; }
      str = items["n"].get_string();
      if(str.size() != 342) { return false; }
      str = items["e"].get_string();
      if(str != "AQAB") { return false; }
    }
```

I do not parse the values corresponding to keys "kty" and "use" twice, as it is an error.
