### ISSUE TITLE
Fallback parser raises TAPE_ERROR when other kernels raise UTF8_ERROR for some inputs

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#1755]
Affects 1.0.2, but has most likely been an issue for awhile.

The pysimdjson test suite found this one as it now tests the fallback parser on i686. All other DOM implementations raise UTF8_ERROR as expected when parsing an invalid UTF-8 document with a legal structure, however the fallback parser will instead raise a TAPE_ERROR.

Document: https://github.com/TkTech/pysimdjson/blob/master/jsonexamples/test_parsing/n_array_invalid_utf8.json

**Comment by lemire** [comment]
I have retitled the issue.

The fallback kernel works entirely differently from the other kernels and so it does not identify the same errors for some inputs.

I did not look at your particular issue, but let me explain it roughly.

Most kernels scan the entire input *and* validate it for UTF-8. *If* it is not UTF-8, then it immediately returns an UTF-8 error.

However, the fallback kernel proceeds byte-by-byte, and so it will prioritize error indicating a structure problem (which in our odd terminology is a tape error), and only after that an UTF-8 error (within strings).

I could be wrong about the following, but I think that's correct: if there is no string, you will never get an UTF-8 error with the fallback kernel, you will always get some other kind of error.

This is not a true example, but let me illustrate with an example... suppose that you have the following....

```{"key"<invalid UTF-8 sequence....```

Is this an UTF-8 error, or did you try to access ':' and found something else instead? It is ambiguous.

So we do not always return the same error for the same input for all kernels.

If you go back up a level, you realize that we do not have a formal model that specify exactly which error code should be returned given a specific invalid input. We try to give a meaningful error code, but it is mostly indicative, it is not derived from a formal model.

**Comment by lemire** [comment]
Regarding your comment regarding the version: this should have always be so. It is not new. We never had a formal model of the error code so it has always been possible for different kernels to return different error codes.

The important point is that they must all return an error, of some kind, given an incorrect input.

**Comment by TkTech** [comment]
This is perfectly reasonable. I believe it needs to be very, very clearly stated in the documentation hat the same input is only guaranteed to produce the same output in the case of a valid document. My expectation is that the selected implementation would be completely transparent, and this breaks that assumption.

**Comment by lemire** [comment]
@TkTech Fair point. Our documentation (i.e., the markdown files) only refers to the specific error codes in passing. In some instances, specific error codes are mentioned, but otherwise there is intentionally little detail. That is partly because we do not commit to keeping these error codes unchanged. They could evolve. For example, TAPE_ERROR is an ugly placeholder.

Irrespective of the kernel abstraction which you refer to, I would say that, in general, code that refers to our specific error conditions is discouraged. I will add an explicit note to this effect in our documentation for the future releases.

**Comment by lemire** [comment]
PR https://github.com/simdjson/simdjson/pull/1756 should address the issue.

We should have been clearer previously. 

It is actually very likely that future versions could return different error codes. Writing code that depends on specific error codes today is bad.

**Comment by lemire** [comment]
(Note that we do check for specific error codes in our own tests... but that's somewhat different... We don't want our customers to do the same...)
