### ISSUE TITLE
Please provide a pkg-config file

### ISSUE THREAD

**Issue by Tachi107** [simdjson/simdjson#1763]
**Is your feature request related to a problem? Please describe.**
simdjson currently provides a CMake config-file package, but unfortunately not all tools and build systems can use them to discover system-installed dependencies.

**Describe the solution you'd like**
If possible, it would be great if simdjson could generate and ship a pkg-config file, so that tools other than CMake ([Meson](https://mesonbuild.com/Dependencies.html), [CMake](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html), plain makefiles, [muon](https://github.com/annacrombie/muon)) can find simdjson when it is installed on the system.

CMake currently doesn't support pkg-config files generation, but it is a [planned feature](https://gitlab.kitware.com/cmake/cmake/-/issues/22621). To generate pkg-config files, users typically create a packagename.pc.in template file and configure it at build time so that the appropriate flags are set for the host platform. A different approach has also been proposed on [CMake's GitHub repository](https://github.com/Kitware/CMake/pull/343/commits/397634993b44f40bfd566131f4567901386149c0) that generates a .pc file "dynamically" (without providing a template file).

**Are you willing to contribute code or documentation toward this new feature?**
Yes, but not immediately. First, I'd like to hear your feedback here, and I've been quite busy lately so I don't have time to look into this right now (but I may in a few weeks).

**Comment by lemire** [comment]
This is fine. Pull request invited.

The main challenge is to actually *test* it out (on different systems). This would need to be covered by a pull request. Ideally, we would need to test support as part of the pull request.
