### ISSUE TITLE
On demand parser fails to parse a simple numbers array

### ISSUE THREAD

**Issue by qinix** [simdjson/simdjson#1764]
**Describe the bug**

The on demand parser fails to parse a simple json like `[1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,10000000,100000]`, while the DOM parser is working well.

**To Reproduce**

```cpp
#include <simdjson.h>
#include <string>
#include <iostream>

int main() {
    std::string json = "[1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,10000000,100000]";
    simdjson::padded_string padded_json{json};
    simdjson::ondemand::parser parser;
    simdjson::ondemand::document doc = parser.iterate(padded_json);
    simdjson::ondemand::array doc_arr = doc.get_array();
    std::cout << "count_elements: " << doc_arr.count_elements() << std::endl;
    std::cout << doc_arr.at(0).get_double() << " "
        << doc_arr.at(1).get_double() << " "
        << doc_arr.at(2).get_double() << " "
        << doc_arr.at(3).get_double() << " "
        << doc_arr.at(4).get_double() << " "
        << doc_arr.at(5).get_double() << " "
        << doc_arr.at(6).get_double() << " "
        << doc_arr.at(7).get_double() << " "
        << doc_arr.at(8).get_int64() << " "
        << doc_arr.at(9).get_int64() << std::endl;
    return 0;
}
```

The program above results as:

```
count_elements: 10
terminate called after throwing an instance of 'simdjson::simdjson_error'
[1]    1833662 segmentation fault (core dumped)  bin/simdjson_errorcase
```

I also tried the DOM parser with the code below:

```cpp
#include <simdjson.h>
#include <string>
#include <iostream>

int main() {
    std::string json = "[1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,10000000,100000]";
    simdjson::dom::parser parser;
    simdjson::dom::element doc = parser.parse(json);
    simdjson::dom::array doc_arr = doc.get_array();
    std::cout << "size: " << doc_arr.size() << std::endl;
    std::cout << doc_arr.at(0).get_double() << " "
        << doc_arr.at(1).get_double() << " "
        << doc_arr.at(2).get_double() << " "
        << doc_arr.at(3).get_double() << " "
        << doc_arr.at(4).get_double() << " "
        << doc_arr.at(5).get_double() << " "
        << doc_arr.at(6).get_double() << " "
        << doc_arr.at(7).get_double() << " "
        << doc_arr.at(8).get_int64() << " "
        << doc_arr.at(9).get_int64() << std::endl;
}
```

Which works as expected:

```
size: 10
1.1 1.1 1.1 1.1 1.1 1.1 1.1 1.1 10000000 100000
```

BTW, I found that with the same string `"[1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,10000000,100000]"` passed as argument, the `simdjson::ondemand::parser.iterate` will throw an exception saying `simdjson requires the input JSON string to have at least SIMDJSON_PADDING extra bytes allocated, beyond the string's length. Consider using the simdjson::padded_string class if needed.`. So I have to write another `simdjson::padded_string` for ondemand parser. The DOM parser won't complain this. Shouldn't I expect the same behavior with ondemand parser?

**simjson release**

v1.0.2

**Configuration (please complete the following information if relevant)**
 - OS: Ubuntu 20.04 LTS
 - Compiler g++ (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
 - Optimization setting -O2

**Comment by lemire** [comment]
You can only call `at` a single time on an array.

https://github.com/simdjson/simdjson/blob/e27558983290d89db6134e7876830c413902fa3f/include/simdjson/generic/ondemand/array.h#L105-L112

If you try to execute your program in debug mode, with our assertions enabled, you will get the following error indicating that your usage is not supported:

```
count_elements: 10
Assertion failed: (_json_iter->_depth == _depth + 1), function assert_at_child, file /usr/local/include/simdjson.h, line 26785.
1.1 zsh: abort      ./a.out
```


```
#include <simdjson.h>
#include <string>
#include <iostream>

int main() {
    std::string json = "[1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,10000000,100000]";
    simdjson::dom::parser parser;
    simdjson::dom::element doc = parser.parse(json);
    simdjson::dom::array doc_arr = doc.get_array();
    for (double x : doc_arr) {
       std::cout << x << std::endl;
    }
}
```

**Comment by lemire** [comment]
In the DOM API though your approach technically works, it is discouraged:

```C++
   * Get the value at the given index. This function has linear-time complexity and
   * is equivalent to the following:
   *
   *    size_t i=0;
   *    for (auto element : *this) {
   *      if (i == index) { return element; }
   *      i++;
   *    }
   *    return INDEX_OUT_OF_BOUNDS;
   *
   * Avoid calling the at() function repeatedly.
```

**Comment by qinix** [comment]
I see. Really appreciate for explaining!

**Comment by lemire** [comment]
I am making the documentation more explicit... https://github.com/simdjson/simdjson/pull/1765

@qinix Note that while I am sure there are bugs... the latest release (1.0) has been thoroughly stress tested. It is used in production without any bug report. I encourage you to report issues, of course.

**Comment by qinix** [comment]
> I am making the documentation more explicit... #1765
> 
> @qinix Note that while I am sure there are bugs... the latest release (1.0) has been thoroughly stress tested. It is used in production without any bug report. I encourage you to report issues, of course.

In fact, I am using the library with DOM parser in production since v0.8. It really helps me a lot.  Thank you for making this.

**Comment by lemire** [comment]
> In fact, I am using the library with DOM parser in production since v0.8. It really helps me a lot. Thank you for making this.

Fantastic. 

The On Demand front-end requires a bit more care.
