### ISSUE TITLE
operator<< should use ADL

### ISSUE THREAD

**Issue by madhur4127** [simdjson/simdjson#1768]
**Description:**

Currently simdjson defines `operator<<` in the global namespace for its types such as `ondemand::object`. Because of how unqualified namespace lookup works in C++, that global definition can sometimes not be considered as a candidate. This causes compilation failures.

**Example:**
```cpp
#include "simdjson.h"
#include <iostream>

using namespace std;

namespace NA {

template <typename T> void f(const T &a) { std::cout << a; }

template <typename T> std::ostream &operator<<(std::ostream &os, const T &a) {
  a.er;
  return os;
}

} // namespace NA

int main() {
  simdjson::ondemand::object obj;
  NA::f(obj);
}
```

The `NA::operator<<` is an invalid candidate and the compiler stops looking for more candidates in the global namespace where simdjson's `operator<<` resides.

**simjson release**
affects master

**solution**:
Instead of defining in global namespace define the `operator<<` in `serialization-inl` define in inside the namespace so that compiler can find the candidate using ADL.

```c++
namespace simdjson::SIMDJSON_IMPLEMENTATION::ondemand {

inline std::ostream& operator<<(std::ostream& out, simdjson::SIMDJSON_IMPLEMENTATION::ondemand::object value);
#if SIMDJSON_EXCEPTIONS
inline std::ostream& operator<<(std::ostream& out, simdjson::simdjson_result<simdjson::SIMDJSON_IMPLEMENTATION::ondemand::object> x);
#endif

}
```

**Comment by lemire** [comment]
I love this issue. See https://github.com/simdjson/simdjson/pull/1769

**Comment by lemire** [comment]
Thanks @madhur4127. I have adopted your proposal. It will be part of our next release.
