### ISSUE TITLE
WASM Module

### ISSUE THREAD

**Issue by loretoparisi** [simdjson/simdjson#1770]
Any plan to compile the C++ library and headers to a WASM module with EMScripten?

**Comment by lemire** [comment]
We have no plan to support WASM. It is unlikely to be a good platform for simdjson.

You should feel free to investigate the issue if you are interested.

**Comment by loretoparisi** [comment]
> We have no plan to support WASM. It is unlikely to be a good platform for simdjson.
> 
> 
> 
> You should feel free to investigate the issue if you are interested.

Got it, I think that the WASM use case could actually been interesting for electron based web apps and similar that work with mid and big size JSON files.
Another use can is with web based data cruncher apps, that recently can run into the browser to load big datasets based on json files, like for training datasets for platforms like Tensorflow JS, etc.

**Comment by jbourassa** [comment]
For anyone searching about Wasm support, simdjson compiles to Wasm just fine now using [wasi-sdk](https://github.com/WebAssembly/wasi-sdk). Here's how I got the [singleheader](https://github.com/simdjson/simdjson/tree/master/singleheader) demo compiled: 

```
/opt/wasi-sdk/bin/clang++ --sysroot=/opt/wasi-sdk/share/wasi-sysroot --target=wasm32-wasi -fno-exceptions amalgamate_demo.cpp simdjson.cpp
```

**Comment by thewtex** [comment]
@jbourassa we have to use the `-msimd128` flag. E.g.:

```
$CXX -std=c++17 -O3 -flto -msimd128 -fno-exceptions -o amalgamate_demo.wasm amalgamate_demo.cpp simdjson.cpp
```

Verified with:


```sh
$ wasm-objdump -x amalgamate_demo.wasm
# [...]
Custom:
 - name: "target_features"
  - [+] mutable-globals
  - [+] simd128
  - [+] bulk-memory
  - [+] sign-ext
 ```
