### ISSUE TITLE
Parsing JSON in Initialization Stage (static global)

### ISSUE THREAD

**Issue by chenhao94** [simdjson/simdjson#1771]
**Describe the bug**
If parsing JSON in the initialization stage (e.g., to read values from JSON doc and assign them to global variables), we may `see signal SIGSEGV (Address boundary error)`. That may be because that some global variables defined in simdjson are initialized later than the variables we try to initialize.

**To Reproduce**

```
> cat simdjson_test.cc; clang++-12 simdjson_test.cc -std=c++20 -Wno-ambiguous-reversed-operator -I simdjson/singleheader/ simdjson/singleheader/simdjson.cpp -o simdjson_test; ./simdjson_test
#include <simdjson.h>
#include <iostream>
#include <string>
#include <optional>

using namespace std;

using namespace simdjson;
using namespace simdjson::ondemand;

int getv() {
    parser p;
    document d;
    int64_t v;
    padded_string json(string("{\"my_int\": 123}"));

    p.iterate(json).get(d);
    d["my_int"].get(v);
    return v;
}

static int v = getv();

int main() {
    cout << "v: " << v << endl;
    return 0;
}
fish: './simdjson_test' terminated by signal SIGSEGV (Address boundary error)
```

The issue may go away if we put `simdjson/singleheader/simdjson.cpp` before `simdjson_test.cc`. However, since the global variable initializing order is undefined, we cannot rely on this. Also, sometimes it is not easy to determine the order when we use simdjson in a large project.

**simjson release**

v0.9.7

**Configuration (please complete the following information if relevant)**
 - OS: Ubuntu 20.04.2 LTS
 - Compiler Ubuntu clang version 12.0.0-3ubuntu1~20.04.3
 - Optimization setting No

**Indicate whether you are willing or able to provide a bug fix as a pull request**

Yes

**Comment by lemire** [comment]
Pull request invited!

**Comment by lemire** [comment]
Great work @chenhao94 

This was a great issue.

**Comment by lemire** [comment]
Added your name to https://github.com/simdjson/simdjson/blob/master/CONTRIBUTORS

**Comment by chenhao94** [comment]
Thanks very much @lemire
