### ISSUE TITLE
Disable fallback implementation by default for AArch64?

### ISSUE THREAD

**Issue by strager** [simdjson/simdjson#1772]
**Is your feature request related to a problem? Please describe.**
I statically link simdjson into my application. On AArch64 (macOS Apple Silicon), simdjson consumes non-trivial space according to the Bloaty tool:

```
    FILE SIZE        VM SIZE    
 --------------  -------------- 
   2.4%  14.6Ki   0.0%     128    simdjson::internal::unsupported_singleton
   1.7%  10.2Ki   1.7%  10.2Ki    simdjson::internal::power_of_five_128
   1.4%  8.65Ki   1.4%  8.65Ki    simdjson::arm64::dom_parser_implementation::stage2()
   1.4%  8.62Ki   1.4%  8.62Ki    simdjson::arm64::dom_parser_implementation::stage2_next()
   1.4%  8.14Ki   1.3%  8.14Ki    simdjson::fallback::dom_parser_implementation::stage2()
   1.3%  8.11Ki   1.3%  8.11Ki    simdjson::fallback::dom_parser_implementation::stage2_next()
```

I see the fallback implementation, but I don't think this will ever be used on AArch64. From what I understand, NEON is always supported on AArch64. (I might be wrong.)

**Describe the solution you'd like**
By default, disable the fallback implementation on AArch64.

**Describe alternatives you've considered**
In my own CMakeLists.txt (which includes simdjson's CMakeLists.txt), I could disable the fallback implementation myself. However, I think all projects using simdjson should benefit from this size and compile time optimization.

** Are you willing to contribute code or documentation toward this new feature? **
Yes.

**Comment by lemire** [comment]
Yes... This is a good idea. Do you want to take a stab at a pull request? This needs to be specific to AArch64.

**Comment by spnda** [comment]
Why is this commented out? And wouldn't what is commented out essentially address this issue?
https://github.com/simdjson/simdjson/blob/9444c1a04ff92cf46508d67a994559c2680f77db/include/simdjson/implementations.h#L76-L78

**Comment by lemire** [comment]
> Why is this commented out? And wouldn't what is commented out essentially address this issue?

Because it is incorrect. `!SIMDJSON_CAN_ALWAYS_RUN_ARM64` is true in two instances, when `SIMDJSON_CAN_ALWAYS_RUN_ARM64` is set to false, and when `SIMDJSON_CAN_ALWAYS_RUN_ARM64` is undefined. So we need to be more careful, like...

```

#ifndef SIMDJSON_IMPLEMENTATION_FALLBACK
#if SIMDJSON_CAN_ALWAYS_RUN_ARM64 || SIMDJSON_CAN_ALWAYS_RUN_ICELAKE || SIMDJSON_CAN_ALWAYS_RUN_HASWELL || SIMDJSON_CAN_ALWAYS_RUN_WESTMERE || SIMDJSON_CAN_ALWAYS_RUN_PPC64
#define SIMDJSON_IMPLEMENTATION_FALLBACK 0
#else
#define SIMDJSON_IMPLEMENTATION_FALLBACK 1
#endif
#endif
```

A pull request is invited. It is not difficult but one needs to make sure that the macro logic is sound.

**Comment by lemire** [comment]
I can try to do it.
