### ISSUE TITLE
armv7l architecture is 32-bit however NEON ALU on BeagleBone Cortex-A8 has supra-scalar 64 bit ALU: can simdjson be made to work?

### ISSUE THREAD

**Issue by memetb** [simdjson/simdjson#1774]
I'm building simdjson on a beaglebone and it works great, however it uses the fallback kernel.

It did come to my attention that the beaglebone has a 64 bit ALU and `int64_t` is natively supported, and in fact 128 bit operations are also supported. https://developer.arm.com/ip-products/processors/cortex-a/cortex-a8

Naïvely adding `-D_M_ARM64` to a g++ build yields the following compilation errors:
- missing `vaddv_u8` - suggested alternative `vaddw_u8`
- missing `vpaddq_u8` - suggested alternative `vpaddlq_u8`
- missing `vmaxvq_u8` - suggested alternative `vmaxq_u8`
- missing `vminvq_u8` - suggested alternative `vminq_u8`

instructions with no alternatives suggested: `vqtbl1q_u8`, however the NEON ISA on the [arm](https://developer.arm.com/documentation/ihi0073/h) site does list `vqtbl1q_u8` as an existing instruction.

`__uint128_t` is not available, though there seems to be some optimizations out there in the wild.

My question is whether this path was looked at and deemed unfeasible, or whether it's worth investing some effort investigating this platform.

BeagleBones are a very capable industrial control platform, and I would be thrilled seeing the full capabilities of simdjson on them.

Thanks for great library.

**Comment by lemire** [comment]
The simdjson expects 64-bit systems and only supports 32-bit systems with a fallback kernel.

As far as I can tell, the ARM Cortex-A8 is a 32-bit processor from 2005. https://en.wikipedia.org/wiki/ARM_Cortex-A8

The link you offer supports this view...

> The Cortex-A8 was first introduced in 2005 and was the first processor to support the Armv7-A architecture. Since its introduction, the Cortex-A8 processor has been superseded by the Cortex-A15 and Cortex-A17 processors, but it represents a turning point upwards in the race for efficient high-performance 32-bit compute, and it is still widely deployed in many embedded applications.


If you'd like to contribute a 32-bit ARM kernel, we have a dropped pull request that could serve as a starting point:
https://github.com/simdjson/simdjson/pull/330

**Comment by memetb** [comment]
Thanks. I have bookmarked #330. It seems like it's mostly done. I have a small fleet of beagles that I could test on.
