### ISSUE TITLE
Array index doesn't work with type specification but works without it

### ISSUE THREAD

**Issue by Evador** [simdjson/simdjson#1781]
Hello,

I can't understand why this simple example doesn't work:

```
simdjson::ondemand::parser parser;
auto json = R"([1,2])"_padded;
simdjson::ondemand::document doc = parser.iterate(json);

std::cout << doc.at(0).get_double() << std::endl;
std::cout << doc.at(1).get_double() << std::endl;
```

The error on the second item is `The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.`.

On the other hand this example works fine:
```
simdjson::ondemand::parser parser;
auto json = R"([1,2])"_padded;
simdjson::ondemand::document doc = parser.iterate(json);

std::cout << doc.at(0) << std::endl;
std::cout << doc.at(1) << std::endl;
```

Is this what is described in documentation as `Array Index: Because it is forward-only, you cannot look up an array element by index by index. Instead, you should iterate through the array and keep an index yourself.`?
If yes I don't quite understand the purpose of `.at()` method and why the second example works fine.

**Comment by lemire** [comment]
From the documentation:

> The `at` method can only be called once on an array. It cannot be used to iterate through the values of an array.

The `at` method is meant for the use cases where you only want to access one entry.

This is deliberate, we absolutely do not want you to use array accesses. Of course, you can grab the numbers and then store them in an array of your own.

**Comment by Evador** [comment]
What I can't understand is why the second example works. Can you please help me with that?

**Comment by lemire** [comment]
> What I can't understand is why the second example works. Can you please help me with that?

It might work accidentally. We want you to iterate over the array. The `at` should only ever used once.

I have not checked that it does actually work.

**Comment by lemire** [comment]
Your example does not work. Please compile the code in debug, you should get the following assert errors:

```
ondemand::value_iterator::assert_at_container_start() const: Assertion `_json_iter->_depth == _depth' failed.
```
