### ISSUE TITLE
GCC 11.1.0 and CLang 12.0.0 complain on 'and' operator in padded_string-inl.h

### ISSUE THREAD

**Issue by agritsiuk** [simdjson/simdjson#1784]
Release 1.0.2

https://github.com/simdjson/simdjson/blob/v1.0.2/include/simdjson/padded_string-inl.h#L54

```
/include/simdjson.h: In constructor ‘simdjson::padded_string::padded_string(const char*, size_t)’:
/include/simdjson.h:3689:24: error: expected ‘)’ before ‘and’
 3689 |   if ((data != nullptr) and (data_ptr != nullptr)) {
```

if operator gets replaced with && -- it would compile.
Compilation is done with ```-fno-operator-names```.

**Comment by lemire** [comment]
@agritsiuk Please propose a pull request.
