### ISSUE TITLE
Conan install failed

### ISSUE THREAD

**Issue by meftunca** [simdjson/simdjson#1797]
Error Message: 
ERROR: Missing binary: simdjson/1.0.2:0ceb8568b902441fd2e44492a2a13034b8c85355
ERROR: Missing prebuilt package for 'simdjson/1.0.2'

**Comment by lemire** [comment]
You really ought to raise the issue with conan. Though we helped, we do not produce the conan packages.

**Comment by meftunca** [comment]
Thank you for answer
