### ISSUE TITLE
Ensure that CMake build follows best guidelines

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#180]
cc @aytekinar

**Comment by aytekinar** [comment]
I will have a look at this at the weekend.

**Comment by lemire** [comment]
:-)

**Comment by willson-chen** [comment]
@lemire @aytekinar Hi, maybe I can offer some help to this issue. But could you please specify what we want?

**Comment by lemire** [comment]
@willson-chen I think we just need someone who actually knows CMake to have a look at our build setup to make sure that we are a good citizen.

There is no bug or issue that I am aware of...

**Comment by lemire** [comment]
We may not be perfect, but I think that this was much improved. Closing.
