### ISSUE TITLE
Explode/Flatten to CSV example?

### ISSUE THREAD

**Issue by tooptoop4** [simdjson/simdjson#1801]
Do you have an example of this?
https://stackoverflow.com/questions/54210389/is-there-a-generic-way-to-read-the-multiline-json-in-spark-more-specifically-sp

**Comment by lemire** [comment]
Did you check our related documentation at https://github.com/simdjson/simdjson/blob/master/doc/basics.md#newline-delimited-json-ndjson-and-json-lines
