### ISSUE TITLE
cmake: unable to disable `SIMDJSON_DEVELOPER_MODE` in CI

### ISSUE THREAD

**Issue by Tachi107** [simdjson/simdjson#1803]
**Describe the bug**

When building simdjson as a Meson subproject in GitHub's CI, `SIMDJSON_DEVELOPER_MODE` is forcefully set to `true`, even if I pass `-DSIMDJSON_DEVELOPER_MODE=false`.

**To Reproduce**

[Add simdjson as a Meson subproject](https://github.com/Tachi107/cloudflare-ddns/blob/5f280263b5fea2960fbb01f3d1e4199cb8057b55/meson.build#L74-L93) and build it. Logs [here](https://github.com/Tachi107/cloudflare-ddns/runs/6140722909?check_suite_focus=true).

I think that the issue here is that `is_top_project` is reporting `true` because Meson first configures simdjson on its own as a CMake project and then adds it as a Meson subproject.

While Meson is making things difficult here, users have no way of disabling `SIMDJSON_DEVELOPER_MODE` when building simdjson as a top project in a CI job.

**simjson release**

1.0.2

**Indicate whether you are willing or able to provide a bug fix as a pull request**

Yes. I think that this line

https://github.com/simdjson/simdjson/blob/e4ddc5446bc6c29beda7520bd802b10fa390e23c/CMakeLists.txt#L49

could be changed to 

```cmake
if(is_top_project AND (NOT DEFINED SIMDJSON_DEVELOPER_MODE OR SIMDJSON_DEVELOPER_MODE))
```

so that if the user explicitly defined `SIMDJSON_DEVELOPER_MODE` to `false` the `if` evaluates to `false` too.

**Comment by lemire** [comment]
How is SIMDJSON_DEVELOPER_MODE to true? Can you point at where this happens?

The code you link to does not appear to set it to true, in fact it is set to a default value of OFF as far as I can tell.

**Comment by Tachi107** [comment]
> How is SIMDJSON_DEVELOPER_MODE to true? Can you point at where this happens?

It happens near the line I linked earlier:

https://github.com/simdjson/simdjson/blob/e4ddc5446bc6c29beda7520bd802b10fa390e23c/CMakeLists.txt#L49-L56
 
> The code you link to does not appear to set it to true, in fact it is set to a default value of OFF as far as I can tell.

And that's what I'm reporting as an issue. I manually set it to `false`, but simdjson's CMakeLists.txt overrides my choice and sets it to `ON` instead, because `$ENV{CI}` evaluates to true

**Comment by lemire** [comment]
I think I better understand the issue, thanks.

I wonder why we have this check for CI in the first place?

Let me see what happens when I remove it:
https://github.com/simdjson/simdjson/pull/1804
