### ISSUE TITLE
Wrong get_number_type() when number is out of range of int64_t or uint64_t

### ISSUE THREAD

**Issue by xiaoyong-z** [simdjson/simdjson#1820]
**Describe the bug**
```c++
int main()
{
    auto json = R"(  { "key":  -9223372036854775809}  )"_padded;
    ondemand::parser parser;
    ondemand::document doc = parser.iterate(json);
    ondemand::object obj = doc.get_object();
    auto f = obj["key"];
    std::cout << f.type() << std::endl;
    std::cout << f.get_number_type() << std::endl;
    std::cout << f.get_int64() << std::endl;
}

// print
number
integer in [-9223372036854775808,9223372036854775808)
libc++abi: terminating with uncaught exception of type simdjson::simdjson_error: The JSON element does not have the requested type.
zsh: abort      ./quickstart
```

```c++
int main()
{
    auto json = R"(  { "key":  18446744073709551617}  )"_padded;
    ondemand::parser parser;
    ondemand::document doc = parser.iterate(json);
    ondemand::object obj = doc.get_object();
    auto f = obj["key"];
    std::cout << f.type() << std::endl;
    std::cout << f.get_number_type() << std::endl;
    std::cout << f.get_uint64() << std::endl;
}

// print
number
unsigned integer in [9223372036854775808,18446744073709551616)
libc++abi: terminating with uncaught exception of type simdjson::simdjson_error: The JSON element does not have the requested type.
zsh: abort      ./quickstart
```

**Configuration (please complete the following information if relevant)**
 - OS: MacBook Pro (14-inch, 2021)
 - Compiler Apple clang version 13.1.6 (clang-1316.0.21.2)
 - Version b169dc2ea71bc8e9296de9749c42d78f80c8a633
 - Optimization setting  c++ -o quickstart quickstart.cpp simdjson.cpp -std=c++11

**Comment by xiaoyong-z** [comment]
For value < -9223372036854775808, it cannot be parsed by int64_t, but get_number_type() still prints integer in [-9223372036854775808,9223372036854775808).

For value >= 18446744073709551616, it cannot be parsed by uint64_t, but get_number_type() still prints unsigned integer in [9223372036854775808,18446744073709551616).

**Comment by xiaoyong-z** [comment]
Maybe we can throw the exception in the get_number_type() for these out of range case, or give them another new type?

**Comment by lemire** [comment]
`get_number_type()` does not parse the number and is definitively non validating.

It would be inefficient to have it be validating because it would entail effectively parsing the number twice, for people who later want to retrieve that actual value. If you want validation, you can use `get_number()`.

I will improve the documentation.

**Comment by lemire** [comment]
If you are planning to retrieve the value or you need full validation,  consider using the get_number() method instead: it will fully parse and validate the input, and give you access to the type: get_number().get_number_type().

**Comment by xiaoyong-z** [comment]
I get it, Thank you for the explanation.

By the way, it is better to write these into document, and tell them to catch the exception for get_int64() and get_uint64()

> An ondemand::number instance may contain an integer value or a floating-point value. Thus it is a dynamically typed number. 
Before accessing the value, you must determine the detected type: number.get_number_type() has value number_type::signed_integer if we have a integer in [-9223372036854775808,9223372036854775808). You can recover the value by the get_int64() method applied on the ondemand::number instance. 
When number.get_number_type() has value number_type::signed_integer, you also have that number.is_int64() is true. Calling get_int64() on the ondemand::number instance when number.get_number_type() is not number_type::signed_integer is unsafe. You may replace get_int64() by a cast to a int64_t value.
number.get_number_type() has value number_type::unsigned_integer if we have a integer in [9223372036854775808,18446744073709551616). You can recover the value by the get_uint64() method applied on the ondemand::number instance. When number.get_number_type() has value number_type::unsigned_integer, you also have that number.is_uint64() is true. Calling get_uint64() on the ondemand::number instance when number.get_number_type() is not number_type::unsigned_integer is unsafe. You may replace get_uint64() by a cast to a uint64_t value.
number.get_number_type() has value number_type::floating_point_number if we have and we have a floating-point (binary64) number. You can recover the value by the get_double() method applied on the ondemand::number instance. When number.get_number_type() has value number_type::floating_point_number, you also have that number.is_double() is true. Calling get_double() on the ondemand::number instance when number.get_number_type() is not number_type::floating_point_number is unsafe. You may replace get_double() by a cast to a double value.

**Comment by lemire** [comment]
I do appreciate your feedback and you do find actual problems. In this case, I did not properly document what the function did. 

I am now going to downplay it because it is meant for limited applications.
