### ISSUE TITLE
simdjson 2.0.1 does not compile with GCC 8

### ISSUE THREAD

**Issue by striezel** [simdjson/simdjson#1831]
**Describe the bug**

simdjson 2.0.1 does not compile on GCC 8. GCC 8 complains that `_mm512_set_epi8` was not declared:

```
In file included from simdjson.cpp:3:
simdjson.h: In constructor 'simdjson::icelake::{anonymous}::simd::simd8<signed char>::simd8(int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)':
simdjson.h:14329:15: error: '_mm512_set_epi8' was not declared in this scope
     ) : simd8(_mm512_set_epi8(
               ^~~~~~~~~~~~~~~
simdjson.h:14329:15: note: suggested alternative: '_mm512_set1_epi8'
     ) : simd8(_mm512_set_epi8(
               ^~~~~~~~~~~~~~~
               _mm512_set1_epi8
simdjson.h: In constructor 'simdjson::icelake::{anonymous}::simd::simd8<unsigned char>::simd8(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t)':
simdjson.h:14384:15: error: '_mm512_set_epi8' was not declared in this scope
     ) : simd8(_mm512_set_epi8(
               ^~~~~~~~~~~~~~~
simdjson.h:14384:15: note: suggested alternative: '_mm512_set1_epi8'
     ) : simd8(_mm512_set_epi8(
               ^~~~~~~~~~~~~~~
               _mm512_set1_epi8
```

Since the quickstart section of the readme currently says ...

> Prerequisites: `g++` (version 7 or better) or `clang++` (version 6 or better), and a 64-bit
   system with a command-line shell (e.g., Linux, macOS, freeBSD).

... one would think that GCC 8 (and even 7) is supported.

For reference: Version 1.1.0 of simdjson still compiles with GCC 8. I guess the problem is the new AVX512 support / IceLake implementation added in simdjson version 2.0.0.

**To Reproduce**

Try to build the following `Dockerfile`:

```
FROM gcc:8.5

RUN apt-get update && apt-get install -y wget
RUN wget https://raw.githubusercontent.com/simdjson/simdjson/v2.0.1/singleheader/simdjson.h \
         https://raw.githubusercontent.com/simdjson/simdjson/v2.0.1/singleheader/simdjson.cpp \
         https://raw.githubusercontent.com/simdjson/simdjson/v2.0.1/jsonexamples/twitter.json
SHELL ["/bin/bash", "-c"]
RUN echo $'#include <iostream> \n#include "simdjson.h" \n\
using namespace simdjson; \n\
int main(void) {\n\
    ondemand::parser parser;\n\
    padded_string json = padded_string::load("twitter.json");\n\
    ondemand::document tweets = parser.iterate(json);\n\
    std::cout << uint64_t(tweets["search_metadata"]["count"]) << " results." << std::endl;\n\
}' > quickstart.cpp
RUN cat quickstart.cpp
RUN g++ --version
RUN g++ -o quickstart quickstart.cpp simdjson.cpp
CMD ./quickstart
```

It downloads the singleheader version of simdjson 2.0.1, the twitter.json example and attempts to build the quickstart example with it.
The build step should show an error message similar to the one above.

How to use:

0. Install Docker on your system.
1. Create a file named `Dockerfile` in a new directory, paste the content from above into it and save it.
2. Run `docker build . -t simdjson` from terminal in that directory.
3. Watch the output of the compile step (`RUN g++ -o quickstart quickstart.cpp simdjson.cpp`) to see the error messages. 

**simjson release**

v2.0.1

**Configuration**
 - OS: Docker container based on `gcc:8.5` which is based on Debian 10(?)
 - Compiler: g++ (GCC) 8.5.0

**Indicate whether you are willing or able to provide a bug fix as a pull request**

Easiest "fix" would be to change the minimum supported GCC version to something newer. I didn't test it extensively, but GCC 9.4.0 and GCC 10.3.0 seem to work. GCC 9.3.0 does __not__ compile (although with a different error message than GCC 8.5.0). So I guess the first working version of GCC is 9.4.0.

You can test other versions of GCC by changing the version number in the first line of the Dockerfile, e. g. replace `FROM gcc:8.5` by `FROM gcc:9.4` to test with GCC 9.4.0. Then just build the Dockerfile again to test with that version of GCC.

A better fix, if you still want to support older GCC versions, would be to either disable the AVX512 / IceLake implementation on older GCC versions or to provide some workaround / fallback. However, I do not know whether this is feasible. It certainly requires more work than the "easy fix".

**Comment by lemire** [comment]
It definitively should work. I will investigate.

**Comment by lemire** [comment]
Ok. A patch release is upcoming. We support GCC 7 and GCC 9+ but not GCC 8 in the latest release (2.0.1) for two reasons having to do with the limited support for AVX-512 in GCC 8. The issues are minor and amenable to workarounds.

We definitively support GCC 7, although not with AVX-512 support...  people who want fancy AVX-512 support need to update their compilers.

Thanks for the report.

**Comment by xkszltl** [comment]
We hit this issue as well, when we try to build on Ubuntu 18.04 with gcc 8.
Same build on Debian 11 with gcc 10 works just fine.

I wonder if `_mm512_set_epi8` has problem similar to this:
https://stackoverflow.com/questions/53604986/error-mm512-loadu-epi64-was-not-declared-in-this-scope

**Comment by lemire** [comment]
Please upgrade to 2.0.2 which contain a patch for GCC 8.

> I wonder if _mm512_set_epi8 has problem similar to this:

It is similar in the sense that AVX-512 support has been improved over time. In GCC 8, we were still missing a few components. Note that we will not support AVX-512 under GCC for versions earlier than 8. That's why building under gcc 7 is fine (because then AVX-512 is automatically deactivated).
