### ISSUE TITLE
Increased GCC minimum version requirements as of simdjson v2.0.0.

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#1838]
Currently, the minimum specified GCC version is 7.4.0, however this version does not have support for the `_mm512_set_epi8` intrinsic, among others required for the current AVX 512 implementation.

The new minimum version required to build simdjson appears to be gcc 9.0.0. I'm creating this issue instead of updating the documentation because I don't know if you want to work around this intrinsic to maintain gcc 7.40.0 compatibility, or if it's time to bump the minimum version.

Current minimum requirement implementation: https://github.com/gcc-mirror/gcc/blob/releases/gcc-7.4.0/gcc/config/i386/avx512fintrin.h
First version to implement `_mm512_set_epi8': https://github.com/gcc-mirror/gcc/blob/releases/gcc-9/gcc/config/i386/avx512fintrin.h

It would seem like a good idea to change the test toolchain to at least test the build stage against the minimum specified versions.

**Comment by lemire** [comment]
I do not think that this is correct. We have CI tests using GCC 7, GCC 8 and so forth. We fid not change the compiler requirements. Of course, there could be a bug, and if so, please report it.

The AVX-512 code is disabled under GCC 7 for the reason you explain… but other kernels will work fine.

The net result is that compiling with GCC 7 may lead to an inferior build compared to what you get with a more recent compiler but that cannot be helped. Generally speaking, more recent compilers produce better binaries.

**Comment by lemire** [comment]
I am closing the issue. If you are encountering issues with GCC 7, please report them.
