### ISSUE TITLE
Is there an escape api

### ISSUE THREAD

**Issue by inaryart** [simdjson/simdjson#1850]
I need to insert json data into database, but database doesn't recognize json, it has to be escaped:
```
{ "Column1": "222222222222", "Column2": "{\"" }
```
must be
```
{ "Column1": "222222222222", "Column2": "{\\\"" }
```

**Comment by lemire** [comment]
The core team is unlikely to support such variations on JSON. However, if you are interested in coding the solution and submitting a pull request, we will consider it.
