### ISSUE TITLE
Cannot inline due to function body not available

### ISSUE THREAD

**Issue by undisputed-seraphim** [simdjson/simdjson#1851]
OS: Debian 11
Compiler: gcc 10.2.1-6
simdjson tag: v2.0.4
simdjson compile flags: `-DSIMDJSON_SANITIZE=ON -DSIMDJSON_SANITIZE_UNDEFINED=ON -DSIMDJSON_DISABLE_DEPRECATED_API=ON -DSIMDJSON_EXCEPTIONS=OFF -DSIMDJSON_AVX512_ALLOWED=OFF`

Sample reproduction:
```
#include <simdjson.h>
int main() {
        simdjson::error_code ec;
        simdjson::dom::object obj;
        for (const auto& field : obj) {
                const auto value = field.value.get_object().value(ec);
        }
}
```

Error:
```
/home/user/.usr/include/simdjson.h:2382:35: error: inlining failed in call to ‘always_inline’ ‘const T& simdjson::internal::simdjson_result_base<T>::value(simdjson::error_code&) const & noexcept [with T = simdjson::dom::object]’: function body not available
 2382 |   simdjson_really_inline const T &value(error_code &error) const & noexcept;
      |                                   ^~~~~
```

Notes: Did not encounter this problem when compiling with fewer flags

**Comment by lemire** [comment]
Thanks. You are triggering dead code that should have been removed. We are going to be removing it. Thanks for reporting the issue.

The correct usage when you want to disable exceptions is...

```
simdjson::dom::object myobj;
simdjson::error_code err = field.value.get_object().get(myobj);
```
