### ISSUE TITLE
Binary integer literal  is C++14 feature, they should be replaced with hex literal

### ISSUE THREAD

**Issue by wqking** [simdjson/simdjson#1854]
In version 2.1.0, the single simdjson.cpp file, there are some integer literal such as `0b10000000` in line 5284 in function `is_continuation`.
Binary integer literal is [a feature in C++14](https://en.cppreference.com/w/cpp/language/integer_literal), while I think simdjson only requires C++11?
We may change them to hex literals

Another question, is there benchmark for dom vs ondemand in simdjson?

**Comment by lemire** [comment]
Would you produce a pull request?

**Comment by striezel** [comment]
PR is there: #1855

Let's just hope I made no mistake in the conversion from binary to hexadecimal.

**Comment by lemire** [comment]
Thanks!
