### ISSUE TITLE
simdjson - not working(not compile) on VS2019, С++17

### ISSUE THREAD

**Issue by Latorius** [simdjson/simdjson#1860]
Hello,

Simdjson - not working(not compile) on VS2019, С++17, x64, release.

I just put files in my project - simdjson.cpp and simdjson.h and try to compile the code:

```
#include <iostream>
#include <string>

#include "simdjson.h"

using namespace simdjson;


int main()
{

    ondemand::parser parser;

    std::string my_string;  

    ondemand::document tweets = parser.iterate(my_string);

}
```

But VS2019 throws an error:

`Error LNK2001 unresolved external symbol "struct simdjson::internal::error_code_info const * const simdjson::internal::error_codes" (?error_codes@internal@simdjson@@3QBUerror_code_info@12@B).`

`Error LNK2001 unresolved external symbol "class simdjson::internal::atomic_ptr<class simdjson::implementation const > & __cdecl simdjson::get_active_implementation(void)" (?get_active_implementation@simdjson@@YAAEAV?$atomic_ptr@$$CBVimplementation@simdjson@@@internal@1@XZ).`

**Comment by lemire** [comment]
Thanks for your report. Closing.
