### ISSUE TITLE
get_string yields invalid UTF-8 string when input only contains low surrogate escape sequence.

### ISSUE THREAD

**Issue by MashPlant** [simdjson/simdjson#1870]
**Describe the bug**

The comment of `get_string` says "The string is guaranteed to be valid UTF-8." However, if the input only contains low surrogate escape sequence, it may return a string that is rejected by its own `simdjson::validate_utf8`.

**To Reproduce**

```c++
#include "simdjson.h"
#include <iostream>

using namespace simdjson;

int main() {
  ondemand::parser parser;
  auto json = R"("\uDC00")"_padded;
  auto doc = parser.iterate(json);
  auto str = doc.get_string().value();
  std::cout << validate_utf8(str) << '\n';
}
```

The expected behavior of the code is throwing an exception at `get_string().value()` since `\uDC00` is not really a valid escape sequence: valid surrogate pairs must consist of one high surrogate character (0xD800–0xDBFF) followed by one low surrogate character (0xDC00–0xDFFF), but it only has the low surrogate character.

The actual behavior is outputting a `0`, since the result is not a valid UTF-8 string, both logically and in the eyes of `simdjson::validate_utf8`.

**simjson release**

v1.1.0 (commit 8c1bfe782b718d128fd655f2070971b52abfc9b0).

**Configuration (please complete the following information if relevant)**
 - OS: macOS Monterey
 - Compiler Apple clang version 13.0.0 (clang-1300.0.29.3) x86_64-apple-darwin21.4.0
 - Version: 12.3.1
 - Optimization setting: None

**Comment by lemire** [comment]
I will review.

**Comment by lemire** [comment]
It is an actual bug. Thanks for the great report.

**Comment by jkeiser** [comment]
Kudos, it's incredibly rare to find a json parsing bug around here :)

**Comment by lemire** [comment]
It was interesting. It is a very old bug and we had no way of finding it!
