### ISSUE TITLE
Migrating from Rapidjson

### ISSUE THREAD

**Issue by paulocoutinhox** [simdjson/simdjson#1872]
Hi,

Im migrating my project from old rapidjson to simdjson. Im reading the docs but not understand somethings.

I have this three methods to start migrate:

```
void SimpleSharedDataPlatformService::save(simdjson::ondemand::document &doc, const std::string &groupName)
{
    auto rawData = doc.raw_json();

    std::string homeDir = FileHelper::join(FileHelper::getHomeDir(), baseDir);
    homeDir = FileHelper::join(homeDir, "shared-data");

    std::string filename = groupName + ".json";
    std::string filePath = FileHelper::join(homeDir, filename);

    FileHelper::createFileWithStringContent(filePath, std::string(rawData.value()));
}

simdjson::ondemand::document  SimpleSharedDataPlatformService::create(const std::string &groupName)
{
    // reset data
    auto json = "{}"_padded;
    simdjson::ondemand::parser parser;
    auto doc = parser.iterate(json);

    // prepare data
    std::string homeDir = FileHelper::join(FileHelper::getHomeDir(), baseDir);
    FileHelper::createDir(homeDir);

    homeDir = FileHelper::join(homeDir, "shared-data");
    FileHelper::createDir(homeDir);

    std::string filename = groupName + ".json";
    std::string filePath = FileHelper::join(homeDir, filename);

    // create file to check errors
    if (!FileHelper::isFile(filePath))
    {
        FileHelper::createFile(filePath);
    }

    // if at the end the file exists then continue
    if (FileHelper::isFile(filePath))
    {
        auto error = parser.iterate(FileHelper::getFileContentAsString(filePath)).get(json);

        if (error)
        {
            doc = parser.iterate(json);
        }
    }

    return doc;
}

// the method setInteger is not migrated yet
void SimpleSharedDataPlatformService::setInteger(const std::string &groupName, const std::string &key, int32_t value)
{
    auto json = create(groupName);

    if (json.HasMember(key.c_str()))
    {
        rapidjson::Value &jsonValue = json[key.c_str()];
        jsonValue.SetInt(value);
    }
    else
    {
        auto jsonKey = rapidjson::Value(key.c_str(), json.GetAllocator());
        rapidjson::Value jsonValue;
        jsonValue.SetInt(value);

        json.AddMember(jsonKey, jsonValue, json.GetAllocator());
    }

    save(json, groupName);
}
```

Questions:

1 - The `create` method is correct return that type of object to other methods find (read) and write inside it?
2 - The `save` method has the correct and safe way to get raw json string?
3 - The `setInteger` method need be migrated from rapidjson too, but i need some help to make something similar. In rapidjson i check it it exists and call `setInt`, else, i add a new member and finally save the raw json to a file with `save` method. How it can be ported to `simdjson`?

Thanks for any help.

**Comment by lemire** [comment]
At a glance, you seek to create JSON documents. The simdjson library is focused on *parsing* (giving you access to the content of a document). We have plans to allow the creation and the edition of JSON documents, but it is not currently done.

See the following open issue:

* https://github.com/simdjson/simdjson/issues/1386

**Comment by lemire** [comment]
I will close this. A `simdjson::ondemand::document` instance is immutable. You can certainly use it as a basis to construction new JSON documents, but there is no `AddMember` or `SetInt` currently.

We welcome contributions if folks would like to contribute to a JSON builder (https://github.com/simdjson/simdjson/issues/1386).
