### ISSUE TITLE
Calling count_fields on an empty document, and then instantiating an object over the document might be unsafe.

### ISSUE THREAD

**Issue by IosifSpulber** [simdjson/simdjson#1876]
The following test passes just fine:

```
TEST(SimdJsonIssue, CountNonEmptyAndIterate) {
  std::string jsonStr = R"json({
      "9": 13.0,
      "-11": 5.0,
      "asdf": 17.2,
      "12": 14,
      "xyz": 3.14
    })json";
  simdjson::ondemand::parser parser;
  simdjson::padded_string paddedStr(jsonStr);
  simdjson::ondemand::document doc = parser.iterate(paddedStr);

  std::unordered_map<std::string, double> result;
  size_t jsonSize = doc.count_fields();
  result.reserve(jsonSize);

  for (auto field : doc.get_object()) {
    std::string_view key = field.unescaped_key();
    double value = field.value().get_double();

    result[std::string(key)] = value;
  }

  EXPECT_EQ(5, result.size());
}
```

However, with an empty object this breaks:

```
TEST(SimdJsonIssue, CountEmptyAndIterate) {
  std::string jsonStr = R"json({
  })json";
  simdjson::ondemand::parser parser;
  simdjson::padded_string paddedStr(jsonStr);
  simdjson::ondemand::document doc = parser.iterate(paddedStr);

  std::unordered_map<std::string, double> result;
  size_t jsonSize = doc.count_fields();
  result.reserve(jsonSize);

  for (auto field : doc.get_object()) {
    std::string_view key = field.unescaped_key();
    double value = field.value().get_double();

    result[std::string(key)] = value;
  }

  EXPECT_EQ(5, result.size());
}
```

Assertion break:

```
simdjson/include/simdjson.h:28654: void simdjson::haswell::ondemand::value_iterator::assert_at_container_start() const: Assertion `_json_iter->token._position == _start_position + 1' failed.
```

Is this valid usage or am I misusing the API somehow?

**simjson release**

 - OS: CentOS Stream 8
 - Compiler: g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-13)
 - Version: simdjson 2.2.1

**Comment by lemire** [comment]
I will review.

**Comment by lemire** [comment]
There does seem to be a bug ! I need to verify some more.

Note however that your usage is discourage. If you can count_fields, you are asking the parser to scan the whole document, and then all you do with it is to call 'reserve' which is an optimization hint. It will almost surely make your code slower.

Still... it should work, I think.

**Comment by lemire** [comment]
Though this is code that I discourage using, you could do the following (which is simpler):

```C++

  simdjson::ondemand::parser parser;
  simdjson::padded_string paddedStr(jsonStr);
  simdjson::ondemand::document doc = parser.iterate(paddedStr);

  std::unordered_map<std::string, double> result;
  ondemand::object obj = doc.get_object()
  size_t jsonSize = obj.count_fields(); // WARNING: This is almost surely a terrible idea.
  result.reserve(jsonSize);

  for (auto field : obj) {
    std::string_view key = field.unescaped_key();
    double value = field.value().get_double();

    result[std::string(key)] = value;
  }

  EXPECT_EQ(5, result.size());
}
```

**Comment by lemire** [comment]
It looks like  my fix works.  Thanks for the report. Meanwhile, I suggest you 1) use count_fields sparingly... do not compute the number of fields for performance hints... 2) first grab an object and then operate on it.

A patch release should soon follow.

https://github.com/simdjson/simdjson/pull/1877

**Comment by lemire** [comment]
Please upgrade to version 2.2.2.

Thanks again for the report.

https://github.com/simdjson/simdjson/releases/tag/v2.2.2

**Comment by IosifSpulber** [comment]
Thank you @lemire for looking at this! Glad to see it's fixed.

I will update to the newest version, and in the meanwhile I will grab the object as you said.

**Comment by lemire** [comment]
Your analysis looks correct, I stand corrected. It reflects the fact that you are not bound by the JSON speed in your benchmark.

**Comment by lemire** [comment]
You could probably speed things up more with a heuristic. Take the JSON input size, predict/guest the number of components, reserve accordingly.
