### ISSUE TITLE
Weird issue with simdjson behaviour after 0.9.6

### ISSUE THREAD

**Issue by jrch2k20** [simdjson/simdjson#1881]
Currently i'm using simdjson 2.2.2 headers version.

Currently this happens with ondemand API, all my code started giving this error up.

**JSON document ended early in the middle of an object or array**

After going crazy and dumping every involved variable value and verify the json data is there and simdjson have access to it and is valid, nothing this error always happens on every function.

I decided to go nuclear, full scorched earth and print the content of the document of every function to see what the document is seeing, so i added to my code 

`std::cout << doc.raw_json() << std::endl;` 

I put this just after iterate() call, to my surprise all my functions start working perfectly (outside of the tons of json data on the terminal).

So, my question is. something changed on the API that is not documented? might be a missing compiling flag? or any tip on how to debug it?

gdb seems to like these 2

#8  0x00007ffff706be46 in simdjson::haswell::implementation_simdjson_result_base<simdjson::haswell::ondemand::value>::take_value() && (this=0x7fffffffccd0)
#9  simdjson::haswell::implementation_simdjson_result_base<simdjson::haswell::ondemand::value>::operator simdjson::haswell::ondemand::value&&() && (this=0x7fffffffccd0)

Compiler
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.1.1 20220730 (GCC) 

ArchLinux

Tyvm for your time

**Comment by lemire** [comment]
Thanks for the report. Please provide a reproducible test case. There are many causes to a problem such as the one you describe and without code we can run and test, we have no hope of answering your query.

**Comment by jrch2k20** [comment]
> Thanks for the report. Please provide a reproducible test case. There are many causes to a problem such as the one you describe and without code we can run and test, we have no hope of answering your query.

ok, ill try to extract some code and json and test it

**Comment by jrch2k20** [comment]
Well, for reference when i extract it, it bloody works when using a preset string.

maybe libcurl is sending something weird, ill check that

**Comment by lemire** [comment]
I will close for now. Reopen a new issue when you have a reproducible test case.
