### ISSUE TITLE
Asking for comments on `Muon` design

### ISSUE THREAD

**Issue by vshymanskyy** [simdjson/simdjson#1882]
I would really appreciate it if the authors of `simdjson` could take a glance at [`µON` format](https://github.com/vshymanskyy/muon).
The structure of muon is very similar to JSON, so similar techniques (SIMD) could be applied to Muon parsing in the future.

As muon is still in design stage, I'd like to get some feedback on:
- General `Muon` idea and structuire.
- Anything we could improve in Muon (over JSON) that could greatly increase performance or simplify the future SIMD parser implementation.

Thanks in advance!
@lemire @jkeiser

**Comment by lemire** [comment]
@vshymanskyy  

LEB128 is a problem. You pay for the small compression benefits with substantial complexity when you want to go at high speed.

**Comment by vshymanskyy** [comment]
Thanks, yes I was suspecting this, but https://github.com/as-com/varint-simd looks promising enough.

In general, the amount of LEB128-encoded data should be fairly low compared to the document size, but it's a good idea to collect the actual stats on this. Btw, UTF-8 encoding itself uses variable-length code points, and `simdjson` tackled it, right?

**Comment by vshymanskyy** [comment]
I just came up with a better question:
- If there was something you could change in JSON format to make `simdjson` even better, what would it be? :nerd_face:

**Comment by lemire** [comment]
> Btw, UTF-8 encoding itself uses variable-length code points, and simdjson tackled it, right?

The simdjson library does not actually decode the UTF-8, it only validates it, an easier problem. Even so, decoding UTF-8 when it occurs in sufficiently long strings or is mostly ASCII can be done fast. The problem you have here is that you have isolated values that need to be decoded individually. It makes optimization difficult.  You are correct that https://github.com/as-com/varint-simd looks like great work, but read carefully, it works best when you know the destination type. I have worked personally on this problem, and the author of varint-simd cites me.

**Comment by vshymanskyy** [comment]
Thank you, appleciate your inputs. I'll try to collect some stats on LEB128 usage in real documents.
