### ISSUE TITLE
Is performance different between DOM and Ondemand mode?

### ISSUE THREAD

**Issue by jayden5414** [simdjson/simdjson#1884]
Is performance different between DOM and On Demand mode?
Is the benchmark result based on DOM or On Demand?
I just saw On Demand is faster than DOM on page `https://ibireme.github.io/yyjson/doc/doxygen/html/index.html`
btw, I like DOM rather than On Demand. On Demand seems hard to use.
Could you provide both benchmark for DOM and On Demand?
thanks.

**Comment by lemire** [comment]
We have these benchmarks (e.g., bench_ondemand). You should be able to run them on your own systems.

When used correctly and for the right problems, On Demand is definitely faster. Though it may require a bit more effort, we believe that it might be worth it if performance is important to you. The exact gains depend on your use case and programming skills.

There are independent benchmarks, see

https://github.com/kostya/benchmarks#json

We are going to publish more documentation later this year.

Thanks for the feedback.
