### ISSUE TITLE
simdjson::to_string not compiling with ondemand::object

### ISSUE THREAD

**Issue by karlisolte** [simdjson/simdjson#1889]
I'm experiencing #1579 with recent versions (2.2.2, 2.0.0).

`doc/basics.md` suggests that `simdjson::to_string()` should work with `ondemand::object`:
```
for(ondemand::object elem: test_array) {
   std::cout << simdjson::to_string(elem);
}
```
However this does not compile:
```
#include "simdjson.h"
using namespace simdjson;
int main() {
    ondemand::object obj;
    simdjson::to_string(obj);
}
```

> error: no matching function for call to ‘simdjson::internal::string_builder<>::append(simdjson::fallback::ondemand::object&)’
> note:   no known conversion for argument 1 from ‘simdjson::fallback::ondemand::object’ to ‘simdjson::dom::element’

**Comment by lemire** [comment]
The documentation refers to to_json_string, but there is indeed one error in the documentation where one example mistakenly uses `to_string` instead. I will fix it with a pull request. Thanks.

Your example is incorrect as your are pointing at an uninitialized object instance, you should use...

```C++
#include "simdjson.h"
#include <iostream>
#include <string>
using namespace simdjson;

using namespace simdjson;

int main() {
  auto json = R"( {"key":"value"} )"_padded;
  ondemand::parser parser;
  ondemand::document doc;
  if(parser.iterate(json).get(doc) != simdjson::SUCCESS) {
    return -1;
  }
  ondemand::object obj;
  if(doc.get_object().get(obj) != simdjson::SUCCESS) {
    return -1;
  }
  std::cout << simdjson::to_json_string(obj) << std::endl;
}
```
