### ISSUE TITLE
Add a helper method to check if ondemand parsing has no trailing tokens after end of document?

### ISSUE THREAD

**Issue by TysonAndre** [simdjson/simdjson#1904]
**Is your feature request related to a problem? Please describe.**
After looking through document api docs (and example code, and benchmarks), there's no convenient way to check if there is no trailling content after iterating over an entire ondemand document, because the get_root_value_iterator() is a protected method using a protected field.

There's a comment in the ondemand documentation that this validation isn't done, but no examples of how to add validation that there are no trailing tokens yourself (correctly)

Subclassing can be used as a workaround to access protected properties - I'm not sure if that's the intent for properties declared as `protected`?

**Describe the solution you'd like**
`simdjson_result<bool> document::is_at_document_end()`/has_trailing_content(), calling get_root_value_iterator.at_end()

For use cases similar to json2msgpack, where the entire document is parsed with ondemand, it would be useful to check if there was any trailing content (to provide validation guarantees similar to the dom api)

Maybe return an error code if the iteration isn't started yet or is in progress, or add development checks to assert those conditions

**Describe alternatives you've considered**
I see there's also iterate_many(), which may work, but I'm not sure at first glance if that adds performance overhead (e.g. if there would be extra buffers allocated or extra copying done), and would want to disable threading if I only plan to parse a single document in a use case

**Additional context**
Noticed when looking into whether migrating simdjson_php to the ondemand parser would have a performance benefit - the way to properly check for trailing tokens was initially unclear and was an API I would have assumed would exist

**Are you willing to contribute code or documentation toward this new feature?**
yes

**Comment by lemire** [comment]
Please provide a concrete example, ideally with a JSON document and code.

By design, the On Demand front-end is lazy: it only validates what you access. If you consume fully the document.

If you fully consume the document, then it should be fully validated.

**Comment by TysonAndre** [comment]
> If you fully consume the document, then it should be fully validated.
Right - the json file is a valid document followed by tokens. This would be rejected by the dom parser, but is allowed by the ondemand parser and the examples using it.

(There's a special case I see in the implementation for numbers and null, but other token types allow tokens after the document)

```sh
» echo '[] {x' > example.json
» tools/json2json --file example.json --ondemand
[]%
» tools/json2json --file example.json
 Parsing failed. Error is 'The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.'.
```

```sh
» echo '"string" "x"' > example.json
» tools/json2json --file example.json
 Parsing failed. Error is 'The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.'.
» tools/json2json --file example.json --ondemand
"string"
```

```sh
» echo 'true true' > example.json
» tools/json2json --file example.json --ondemand
true
» tools/json2json --file example.json
Parsing failed. Error is 'The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.'.
```

**Comment by lemire** [comment]
Thanks.

**Comment by TysonAndre** [comment]
As documentation for how to use the library, benchmarks such as json2msgpack could have commented out code with the checks for the end of the document that were omitted (this is probably the most obvious example in the source code of how to use the ondemand parser recursively, other than third party bindings)

(should that be part of the benchmark, for a comparison with similar functionality in dom?)

> this worked for the data types I tested (string, number, array, object, boolean, null)

Though I do have to call is_null() explicitly to advance the pointer for null. and so would benchmark/json2msgpack/simdjson_ondemand.h for `doc.is_null()`

**Comment by lemire** [comment]
> (should that be part of the benchmark, for a comparison with similar functionality in dom?)

It is not computationally meaningful. It is very, very cheap.

> As documentation for how to use the library, benchmarks such as json2msgpack could have  ...

Would you contribute such code (enabled) as a pull request?
