### ISSUE TITLE
"Just Wondering" regarding the Simdjson academic paper.

### ISSUE THREAD

**Issue by RealTimeChris** [simdjson/simdjson#1917]
I was just wondering - I noticed in this paper that there is a line that goes like this on page 7:
```cpp
// add B to ES , yielding carries on backslash sequences with even starts
___111____________________1______________________________111____ : EC = B + ES
```
Which operation produces the "carried" values from the horizontally-related elements? Is it an intrinsic or a combination of them?

**Comment by lemire** [comment]
Thanks for your interest.

You should start a discussion if you want to chat about such things. Look for the tabs at the top of the page.

This being said, look for code like this in our source code... `bool add_overflow(uint64_t value1, uint64_t value2, uint64_t *result)`. It is indeed implemented with intrinsic functions (though which one depends on your platform). It can be implemented in pure C/C++: there is a carry whenever `value1 + value2 < value1`.

**Comment by RealTimeChris** [comment]
Awesome thanks!
