### ISSUE TITLE
`dom::object::raw_json`, `dom::array::raw_json`

### ISSUE THREAD

**Issue by edgarsi** [simdjson/simdjson#1920]
`ondemand` classes (object, array) offer the `raw_json` method. However, `dom` does not. We seem to be forced to use `string_builder`, with its overheads. The proposed `raw_json` implementation appears to be simply `tape_ref->get_string_view()`. Am I missing something?

Specific use case: parsing a larger json, with a mixed use of contents - some parts needed parsed, some as raw json. Parsing all using `dom` is an acceptable overhead, as a simplicity tradeoff. Using `minify` to reconstruct json may also be acceptable, but seems easily avoidable, if `dom` classes had `raw_json`.

**Comment by lemire** [comment]
In the DOM model, you materialize an in-memory data structure representing your data. It is then independent from the source. After the parsing is realized, you can throw away the input, they have no relationship. There is indeed a 'tape' but this tape does not have references to the input.

With On Demand, you are iterating over the input so we have direct access to the input string (which is what raw json provides). There is no tape at all.

> parsing a larger json, with a mixed use of contents - some parts needed parsed, some as raw json. 

This seems an ideal use case for On Demand !


> Parsing all using dom is an acceptable overhead

We have two distinct models, DOM and On Demand. In theory, we could build hybrids where some of the parsing is DOM-like and some is On Demand. But it would require non-trivial design work.


If you have ideas, pull requests are invited.
