### ISSUE TITLE
How can I change any value on the JSON.

### ISSUE THREAD

**Issue by meftunca** [simdjson/simdjson#1923]
Hi @lemire, How can I change any value on the JSON. That issue is a critical problem in my own project. My project is a multi-dimensional database management system and I must use a parallel process instead of a scalar. Your research has inspired me. Maybe you can bring the data update feature for those who need your project like me. 

Briefly the features of my project
1. NoSql-based data management
2. MultiFactoriel Indexing Model
3. RealTime Communication
4. Encrypted Data Models
5. High Using Memory/File Processes
6. Will support Syntax: JS, SQL, Rest, and maybe graphql
7. Also MultiDimensional Relation in the collections
8. Will Supported Functions: Geo, Crypto, Aggregation, and any SQL functions
9. And Non-central Database management System For All Device Type

**Comment by lemire** [comment]
The simdjson library parses JSON strings and gives you access to the content. The expectation is that you then store the results you need in your own data structures.

There is a long standing request for a counterpart, where people want to serialize content from their data structures to JSON. We do not yet support that component.

It would not be unreasonable to support applications where one needs to ingest JSON and then immediately and efficiently produce a new JSON output (we offer 'some' support for that).

What we will probably never support is simdjson as a database backend.

For now, I am going to close this issue. The simdjson library is a community-drive project. We welcome new pull request.
