### ISSUE TITLE
Failed to build : simdjson.h:14096:14: error: the last argument must be an 8-bit immediate

### ISSUE THREAD

**Issue by lailoken** [simdjson/simdjson#1950]
Failed to build simdjson.cpp :
Error:

> simdjson.h: In member function 'simdjson::icelake::{anonymous}::simd::simd8<T> simdjson::icelake::{anonymous}::simd::base8<T, Mask>::prev(simdjson::icelake::{anonymous}::simd::simd8<T>) const [with int N = 3; T = unsigned char; Mask = simdjson::icelake::{anonymous}::simd::simd8<bool>]':
> /home/wei/mimid5/3rdparty/simdjson/simdjson.h:14096:14: error: the last argument must be an 8-bit immediate
> 14096 |       return _mm512_alignr_epi8(*this, _mm512_permutex2var_epi64(prev_chunk, _mm512_set_epi64(13, 12, 11, 10, 9, 8, 7, 6), *this), 16 - N);
>       |              ^~~~~~~~~~~~~~~~~~

**To Reproduce**

Build on specific OS/compiler version. Swapping the relevant `#if` seems to fix it for that compiler (which is GCC 9 not 8)

**simjson release**

Used quickstart, thus wget the singleheader source files h+cpp directly.

**Configuration (please complete the following information if relevant)**

> /opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: warning: libgfortran.so.3, needed by /lib/../lib64/libblas.so, may conflict with libgfortran.so.4
> [100%] Built target SimMatrix
> (mimid) [wei@dev-stego mimid5]$ gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
> Target: x86_64-redhat-linux
> Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-9/root/usr --mandir=/opt/rh/devtoolset-9/root/usr/share/man --infodir=/opt/rh/devtoolset-9/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-9.3.1-20200408/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
> Thread model: posix
> gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)

**Comment by lemire** [comment]
Verified. See https://github.com/simdjson/simdjson/pull/1951
