### ISSUE TITLE
std::string example / missing example

### ISSUE THREAD

**Issue by MyraBaba** [simdjson/simdjson#1956]
Hi,

I didn't find a clear example for std::string that includes nested objects like below:

How we can extract the below : 
ZuluBBox all subobject ZuluDetection 
and timestamp & buffer offset? 

Confused to iterate over them.

Best

> {"ZuluROI": {"ZuluBBox": {"xmin": 0.0, "ymin": 0.0, "width": 1.0, "height": 1.0}, "SubObjects": [{"ZuluDetection": {"label": "car", "class_id": 3, "confidence": 0.7587034106254578, "ZuluBBox": {"xmin": 0.3843536376953125, "ymin": 0.4532909393310547, "width": 0.09115534275770187, "height": 0.04127710685133934}, "SubObjects": []}}, {"ZuluDetection": {"label": "car", "class_id": 3, "confidence": 0.6718865633010864, "ZuluBBox": {"xmin": 0.7500002980232239, "ymin": 0.5212296843528748, "width": 0.07592231780290604, "height": 0.038947589695453644}, "SubObjects": []}}, {"ZuluDetection": {"label": "car", "class_id": 3, "confidence": 0.5806200504302979, "ZuluBBox": {"xmin": 0.9025363922119141, "ymin": 0.5925348401069641, "width": 0.05478987470269203, "height": 0.046337299048900604}, "SubObjects": []}}, {"ZuluDetection": {"label": "traffic light", "class_id": 10, "confidence": 0.5357877612113953, "ZuluBBox": {"xmin": 0.5545986890792847, "ymin": 0.49969416856765747, "width": 0.015063842758536339, "height": 0.03487000986933708}, "SubObjects": []}}, {"ZuluDetection": {"label": "car", "class_id": 3, "confidence": 0.47930410504341125, "ZuluBBox": {"xmin": 0.22609397768974304, "ymin": 0.4541673958301544, "width": 0.04265553131699562, "height": 0.021219024434685707}, "SubObjects": []}}, {"ZuluDetection": {"label": "traffic light", "class_id": 10, "confidence": 0.4149819314479828, "ZuluBBox": {"xmin": 0.3016183376312256, "ymin": 0.4038545787334442, "width": 0.011902295984327793, "height": 0.025463752448558807}, "SubObjects": []}}, {"ZuluDetection": {"label": "car", "class_id": 3, "confidence": 0.38408881425857544, "ZuluBBox": {"xmin": 0.7797638773918152, "ymin": 0.5051795244216919, "width": 0.047182291746139526, "height": 0.02821175940334797}, "SubObjects": []}}, {"ZuluDetection": {"label": "car", "class_id": 3, "confidence": 0.37718817591667175, "ZuluBBox": {"xmin": 0.1640324592590332, "ymin": 0.46047958731651306, "width": 0.06431010365486145, "height": 0.0334194079041481}, "SubObjects": []}}, {"ZuluDetection": {"label": "traffic light", "class_id": 10, "confidence": 0.3711782693862915, "ZuluBBox": {"xmin": 0.2702745199203491, "ymin": 0.47526323795318604, "width": 0.016945095732808113, "height": 0.023342732340097427}, "SubObjects": []}}, {"ZuluDetection": {"label": "car", "class_id": 3, "confidence": 0.36078837513923645, "ZuluBBox": {"xmin": 0.7514436841011047, "ymin": 0.5031861662864685, "width": 0.029214726760983467, "height": 0.019939783960580826}, "SubObjects": []}}, {"ZuluDetection": {"label": "traffic light", "class_id": 10, "confidence": 0.33807194232940674, "ZuluBBox": {"xmin": 0.7327495217323303, "ymin": 0.4540327489376068, "width": 0.008852947503328323, "height": 0.015110337175428867}, "SubObjects": []}}, {"ZuluDetection": {"label": "car", "class_id": 3, "confidence": 0.3290960490703583, "ZuluBBox": {"xmin": 0.8066381812095642, "ymin": 0.475168377161026, "width": 0.029214726760983467, "height": 0.020788194611668587}, "SubObjects": []}}]}, "timestamp (ms)": 1677085594421, "buffer_offset": 35673}

**Comment by lemire** [comment]
Here is a version without error handling (it throws on error):

```C++
/// #include "simdjson.cpp" // if you use the singleheader version
#include "simdjson.h"
#include <iostream>
using namespace simdjson;

struct ZuluBBox {
  double xmin;
  double ymin;
  double width;
  double height;

  void print() {
    std::cout << xmin << ", " << ymin << ", " << width << ", " << height
              << std::endl;
  }
};

int main(int argc, char *argv[]) {

  auto json = R"+( {
  "ZuluROI": {
    "ZuluBBox": {
      "xmin": 0,
      "ymin": 0,
      "width": 1,
      "height": 1
    },
    "SubObjects": [
      {
        "ZuluDetection": {
          "label": "car",
          "class_id": 3,
          "confidence": 0.7587034106254578,
          "ZuluBBox": {
            "xmin": 0.3843536376953125,
            "ymin": 0.4532909393310547,
            "width": 0.09115534275770187,
            "height": 0.04127710685133934
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "car",
          "class_id": 3,
          "confidence": 0.6718865633010864,
          "ZuluBBox": {
            "xmin": 0.7500002980232239,
            "ymin": 0.5212296843528748,
            "width": 0.07592231780290604,
            "height": 0.038947589695453644
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "car",
          "class_id": 3,
          "confidence": 0.5806200504302979,
          "ZuluBBox": {
            "xmin": 0.9025363922119141,
            "ymin": 0.5925348401069641,
            "width": 0.05478987470269203,
            "height": 0.046337299048900604
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "traffic light",
          "class_id": 10,
          "confidence": 0.5357877612113953,
          "ZuluBBox": {
            "xmin": 0.5545986890792847,
            "ymin": 0.49969416856765747,
            "width": 0.015063842758536339,
            "height": 0.03487000986933708
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "car",
          "class_id": 3,
          "confidence": 0.47930410504341125,
          "ZuluBBox": {
            "xmin": 0.22609397768974304,
            "ymin": 0.4541673958301544,
            "width": 0.04265553131699562,
            "height": 0.021219024434685707
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "traffic light",
          "class_id": 10,
          "confidence": 0.4149819314479828,
          "ZuluBBox": {
            "xmin": 0.3016183376312256,
            "ymin": 0.4038545787334442,
            "width": 0.011902295984327793,
            "height": 0.025463752448558807
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "car",
          "class_id": 3,
          "confidence": 0.38408881425857544,
          "ZuluBBox": {
            "xmin": 0.7797638773918152,
            "ymin": 0.5051795244216919,
            "width": 0.047182291746139526,
            "height": 0.02821175940334797
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "car",
          "class_id": 3,
          "confidence": 0.37718817591667175,
          "ZuluBBox": {
            "xmin": 0.1640324592590332,
            "ymin": 0.46047958731651306,
            "width": 0.06431010365486145,
            "height": 0.0334194079041481
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "traffic light",
          "class_id": 10,
          "confidence": 0.3711782693862915,
          "ZuluBBox": {
            "xmin": 0.2702745199203491,
            "ymin": 0.47526323795318604,
            "width": 0.016945095732808113,
            "height": 0.023342732340097427
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "car",
          "class_id": 3,
          "confidence": 0.36078837513923645,
          "ZuluBBox": {
            "xmin": 0.7514436841011047,
            "ymin": 0.5031861662864685,
            "width": 0.029214726760983467,
            "height": 0.019939783960580826
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "traffic light",
          "class_id": 10,
          "confidence": 0.33807194232940674,
          "ZuluBBox": {
            "xmin": 0.7327495217323303,
            "ymin": 0.4540327489376068,
            "width": 0.008852947503328323,
            "height": 0.015110337175428867
          },
          "SubObjects": []
        }
      },
      {
        "ZuluDetection": {
          "label": "car",
          "class_id": 3,
          "confidence": 0.3290960490703583,
          "ZuluBBox": {
            "xmin": 0.8066381812095642,
            "ymin": 0.475168377161026,
            "width": 0.029214726760983467,
            "height": 0.020788194611668587
          },
          "SubObjects": []
        }
      }
    ]
  },
  "timestamp (ms)": 1677085594421,
  "buffer_offset": 35673
} )+"_padded;
  ondemand::parser parser;
  ondemand::document doc = parser.iterate(json);
  ondemand::object root_object = doc.get_object();
  ondemand::object roi_object = root_object["ZuluROI"];

  ondemand::object box_roi_object = roi_object["ZuluBBox"];
  ZuluBBox box = {
      double(box_roi_object["xmin"]), double(box_roi_object["ymin"]),
      double(box_roi_object["width"]), double(box_roi_object["height"])};
  box.print();

  for (ondemand::object value : roi_object["SubObjects"]) {
    ondemand::object detect = value["ZuluDetection"];
    std::cout << detect["label"].get_string() << std::endl;
    std::cout << detect["class_id"].get_uint64() << std::endl;
    std::cout << detect["confidence"].get_double() << std::endl;

    ondemand::object vbox_roi_object = detect["ZuluBBox"];
    ZuluBBox vbox = {
        double(vbox_roi_object["xmin"]), double(vbox_roi_object["ymin"]),
        double(vbox_roi_object["width"]), double(vbox_roi_object["height"])};
    vbox.print();
  }

  std::cout << root_object["timestamp (ms)"].get_uint64() << std::endl;
  std::cout << root_object["buffer_offset"].get_uint64() << std::endl;
  return EXIT_SUCCESS;
}

```

To make it more robust, and if you prefer to avoid exceptions, you can code it like so...

```C++
ondemand::object root_object;
if(doc.get_object().get(root_object) != simdjson::SUCCESS} { /* handle the error */}
```

... it makes the code a bit longer. If the schema varies, you may need to handle the 'errors' (e.g., missing keys and so forth).

Does this help?

**Comment by MyraBaba** [comment]
@lemire  Thank you for your kind answer and help. I will try and let you know .

I have std::string coming from zeromq channel.

**Comment by lemire** [comment]
I am going to close this issue for now. Please open a new issue or a discussion point if you need more help.

**Comment by MyraBaba** [comment]
@lemire  Hi,

It gives error  

> imdjson requires the input JSON string to have at least SIMDJSON_PADDING extra bytes allocated, beyond the string's length.

what is the correct way to make a std::string with padding extra bytes?

related code:
```

`            stream << contents.to_string().c_str() << '\n';
                QString data = QString(contents.to_string().c_str()) ;

                std::string te_data = contents.to_string().c_str();
                //simdjson::padded_string json = simdjson::padded_string::~padded_string(te_data);

                std::vector<std::string_view> mystrings;
                char json_x[te_data.size ()+SIMDJSON_PADDING];
                strcpy(json_x, te_data.c_str ());




                ondemand::parser parser;
                ondemand::document doc = parser.iterate(json_x);`
```

**Comment by MyraBaba** [comment]
@lemire  found :)

                te_data.reserve (te_data.size () + SIMDJSON_PADDING);

**Comment by lemire** [comment]
Yep. This will work.
