### ISSUE TITLE
Error compiling tests with GLIBCXX assertions enabled

### ISSUE THREAD

**Issue by bertptrs** [simdjson/simdjson#1968]
**Describe the bug**
When compiling with certain security flags, compiling the tests results in an error.

The error is as follows:

```
In file included from /usr/include/c++/12.2.1/string_view:41,
                 from /home/bert/Downloads/simdjson/include/simdjson/common_defs.h:229,
                 from /home/bert/Downloads/simdjson/include/simdjson/base.h:5,
                 from /home/bert/Downloads/simdjson/include/simdjson/dom.h:4,
                 from /home/bert/Downloads/simdjson/include/simdjson.h:38,
                 from /home/bert/Downloads/simdjson/tests/ondemand/ondemand_misc_tests.cpp:1:
In static member function ‘static std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)’,
    inlined from ‘static void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12.2.1/bits/basic_string.h:423:21,
    inlined from ‘std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12.2.1/bits/basic_string.tcc:532:22,
    inlined from ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12.2.1/bits/basic_string.h:1647:19,
    inlined from ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12.2.1/bits/basic_string.h:815:28,
    inlined from ‘bool misc_tests::test_raw_json_token(std::string_view, std::string_view, int)’ at /home/bert/Downloads/simdjson/tests/ondemand/ondemand_misc_tests.cpp:534:13:
/usr/include/c++/12.2.1/bits/char_traits.h:431:56: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ accessing 9223372036854775810 or more bytes at offsets -4611686018427387902 and [-4611686018427387903, 4611686018427387904] may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
```

**To Reproduce**

I've tried to reduce it to the minimum number of flags that I could. This appears to be the minimum

```bash
git clone https://github.com/simdjson/simdjson
cd simdjson
export CXXFLAGS="-Wp,-D_GLIBCXX_ASSERTIONS"
cmake . -DCMAKE_INSTALL_PREFIX="/usr/" -DBUILD_SHARED_LIBS=On -D SIMDJSON_DEVELOPER_MODE=On -D SIMDJSON_ALLOW_DOWNLOADS=Off
make
```

It's possible to speed up compilation by setting `-D SIMDJSON_ALLOW_DOWNLOADS=Off` but it reproduces without.

This flag is part of the Arch Linux default compilation flags, applied to all packages. They are, in their entirety:

```
-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS
```

**simjson release**

Noticed on 3.1.5, though it's been present before and reproduces on the current master.

**Indicate whether you are willing or able to provide a bug fix as a pull request**

I am looking into this as a packager and I've been out of the C++ business for a while, though I could assist in tracking down the issue.

**Comment by lemire** [comment]
@bertptrs What do you have at line 534, column 13 in /home/bert/Downloads/simdjson/tests/ondemand/ondemand_misc_tests.cpp ?

What we have in the repo, at...
https://github.com/simdjson/simdjson/blob/e0dcf8adc93fe445730f4f98b1001126ddb72aa7/tests/ondemand/ondemand_misc_tests.cpp#L534

is basically

```C++
std::string title = "'";
```

**Comment by lemire** [comment]
I have removed the potential bug label. Some tool, somewhere, will always be issuing a warning for a given piece of non-trivial code. It is important to distinguish that from a bug. We need to determine whether there is a bug.

**Comment by bertptrs** [comment]
Can confirm I have the same line there. For reproducibility, this is happening on GCC 12.2.1:

```console
$ gcc --version
gcc (GCC) 12.2.1 20230201
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

It's possible that there is a bug with this flag, though as stated in the original issue, all Arch Linux C++ packages are compiled with this flag so I'm inclined to trust it at least a little.

**Comment by lemire** [comment]
I cannot reproduce the issue. I will be adding CI tests. See https://github.com/simdjson/simdjson/pull/1969

Note that it is not possible to pass all our tests with these assertions because we forbid aborts in the simdjson library. So running `ctest` will fail, assuredly.

**Comment by lemire** [comment]
As you can see, we pass our tests with GLIBCXX_ASSERTIONS set. Not that you need to skip two tests because include GLIBCXX_ASSERTIONS introduces abort into our library (which we forbid in our tests). So run `ctest . -E avoid_`.

[![Ubuntu 22.04 CI GCC 12 with GLIBCXX_ASSERTIONS](https://github.com/simdjson/simdjson/actions/workflows/ubuntu22-glibcxxassertions.yml/badge.svg)](https://github.com/simdjson/simdjson/actions/workflows/ubuntu22-glibcxxassertions.yml)

If your results disagree, please elaborate. But I am now relatively confident that GLIBCXX_ASSERTIONS does not reveal any issue.

Closing. The reporter should reopen if they think there is an issue.

**Comment by lemire** [comment]
@bertptrs The error you get does not seem to make much sense. I suggest you examine your setup and make sure it is compatible with glibcxx_assertions. As you can see, they are not causing us any problem on their own.
