### ISSUE TITLE
Crash when parsing the "json" string "+0"

### ISSUE THREAD

**Issue by juhaszp-uhu** [simdjson/simdjson#1972]
**Describe the bug**

I get a crash (core dump) when attempting to parse the string `+0`.

**To Reproduce**
```
#include <iostream>
#include "simdjson.h"
using namespace simdjson; // optional

int main() {
  padded_string json = R"(+0)"_padded;

  ondemand::parser parser;
  ondemand::document doc = parser.iterate(json); 
  if (doc.is_scalar()) {
    std::cerr << "scalar" << std::endl;
  } else {
    std::cerr << "not scalar" << std::endl;
  }
  return 0;
}
```

**simjson release**

3.1.5

**Configuration (please complete the following information if relevant)**
 - OS: Fedora Linux 37
 - Compiler gcc
 - Version: gcc version 12.2.1 20221121 (Red Hat 12.2.1-4) (GCC)
 - Optimization setting: -Og
 - Implementation: AVX2

**Indicate whether you are willing or able to provide a bug fix as a pull request**

no

**Comment by lemire** [comment]
The string `+0` is not a valid JSON document. We follow RFC 8259:

> A number is represented in base 10 using decimal digits. It contains an integer component that may be prefixed with an optional minus sign, which may be followed by a fraction part and/or an exponent part. Leading zeros are not allowed. A fraction part is a decimal point followed by one or more digits. An exponent part begins with the letter E in uppercase or lowercase, which may be followed by a plus or minus sign. The E and optional sign are followed by one or more digits.

Please refer to the grammar in the RFC.
