### ISSUE TITLE
How do I Execute Benchmark on Linux?

### ISSUE THREAD

**Issue by jijiwawa** [simdjson/simdjson#1973]
When I compile bencmark on Ubuntu 20.04, a message is displayed indicating that bencmark depends on simdjson-windows-headers/test-data. Is there a detailed document describing how to use bencmark?
![image](https://user-images.githubusercontent.com/33614409/226860530-249eb15d-ca5b-48d5-96b2-43d94d383dff.png)

Can I use it only on Windows? I found that the CI environment supports ubuntu 20.04.

**Comment by lemire** [comment]
The simdjson project follows the standard of a CMake project.

Under Linux and macOS, you may build it like so...

```
 cmake -B build -DSIMDJSON_DEVELOPER_MODE=ON
cmake --build build
```

The executable files are then in `/build/benchmark/`.


For Visual Studio, it is much the same except that you need to specify `--config Release`.

Please refer to our documentation:


https://github.com/simdjson/simdjson/blob/master/HACKING.md#usage-cmake-on-64-bit-platforms-like-linux-freebsd-or-macos


https://github.com/simdjson/simdjson/blob/master/HACKING.md#usage-cmake-on-64-bit-windows-using-visual-studio-2019

Note that recent versions of Visual Studio support CMake natively if you include the proper extensions.
