### ISSUE TITLE
Ondemand::value allows iterating over invalid documents 

### ISSUE THREAD

**Issue by juhaszp-uhu** [simdjson/simdjson#1974]
**Describe the bug**

Consider the invalid JSON document `{"key":111`. Obviously, the closing `}` is missing.

Putting this string in the "iterating over an object without exceptions" example in the documentation, I get the "JSON document ended early" error, which is reasonable. However, when the document is converted to an ondemand::value first and then that value is converted to an ondemand::object, there is no error at first, and the program fails when trying to parse the number.

This matters to me, because I'm writing a generic parser that needs to accept any input, so I can't assume that the top-level container is an object, and I can't see any way other than to convert the document into a value and feed it into a recursive parsing function.
Ideally, I'd like to provide an informative error message if the document is not valid. In this case the real error is not with the number but the missing closing brace. 

If this is not a bug, how can I work around this behavior and get a better error location?

**To Reproduce**
This is a slightly modified version of an example program.
```
#include <iostream>
#include "simdjson.h"
using namespace simdjson; // optional

#define CHECK_ERROR \
  do { \
    if (error) { \
      std::cerr << "Error: " << error << \
        " near '" << doc.current_location() << \
        "' at line " << __LINE__ << std::endl; \
      return 1; \
    } \
  } while (0);

int main() {
 auto json = R"({"key": 111)"_padded;
  ondemand::parser parser;
  ondemand::document doc;
  auto error = parser.iterate(json).get(doc);
  CHECK_ERROR;

#ifdef GET_OBJECT_DIRECTLY
  ondemand::object object; // invalid until the get() succeeds
  error = doc.get_object().get(object);
  CHECK_ERROR;
#else
  ondemand::value val;
  error = doc.get_value().get(val);
  CHECK_ERROR;

  ondemand::object object; // invalid until the get() succeeds
  error = val.get_object().get(object);
  CHECK_ERROR;
#endif

  for(auto field : object) {
    ondemand::raw_json_string keyv;
    error = field.key().get(keyv);
    CHECK_ERROR;

    if(keyv == "key") {
      uint64_t intvalue;
      error = field.value().get(intvalue);
      CHECK_ERROR;

      std::cout << intvalue << std::endl;
    }
  }
  return 0;
}
```
When compiling it normally (without a define), I get `Error: Problem while parsing a number near '111' at line 44`.

When compiling with -DGET_OBJECT_DIRECTLY, I get `Error: JSON document ended early in the middle of an object or array. near '{"key": 111' at line 25`.

**simjson release**
3.1.5

**Configuration (please complete the following information if relevant)**
 - OS: Fedora 37
 - Compiler: gcc
 - Version gcc version 12.2.1 20221121 (Red Hat 12.2.1-4) (GCC) 
 - Optimization setting: -Og (but doesn't matter really)

**Indicate whether you are willing or able to provide a bug fix as a pull request**
I'd be willing, but I'm not sure I'm up to it

**Comment by juhaszp-uhu** [comment]
One more thought about the reasoning given above:

The parser knows the length of the original document, doesn't it? Either from the std::string(_view) instance, or in my C string case, from an explicit argument. So the document ends at `...111`, the null byte is not part of it. So why does the parser consider it as part of the token? 

The more I look at this, the less correct it appears.

**Comment by lemire** [comment]
> To phrase it more constructively, is it possible to have it detect the "JSON document ended early" condition while using ondemand::value?


The root object/array is treated differently. You are correct that it is surprising that going through a get_value() and then grabbing an object or an array leads to a different error and I am preparing a PR that will uniformize that. Should be out in the next hour, and it will be part of the next release.

> So the document ends at ...111 (...)

Our grammar is that an integer that is not part of a scalar JSON document (e.g., a document that is not bad entirely on a single integer) cannot terminate a JSON document. That's an error. I am going to make sure that it is clearly stated in the documentation.

Your integer cannot end the document. It is not possible. It is symptomatic of a truncated document.

> The parser knows the length of the original document, doesn't it?

It does not need this information.

>  "how should I change my document for it to be valid?" 

If the document has hit an error, you can ask it for the error condition like you did with `doc.current_location()`. In this case, it gives you a pointer to near the end of the object that is in error.


> The more I look at this, the less correct it appears.

We could make error reporting smoother. Your pull requests are invited !!!

**Comment by juhaszp-uhu** [comment]
Thanks, the modification seems to fix my issue!

However, you may want to put the warn_unused_result attribute on ondemand::document's get_value().get(), because with the added check it may return an error that may cause a crash later when not handled. This is for the no exception mode, of course.

**Comment by lemire** [comment]
> you may want to put the warn_unused_result attribute on ondemand::document's get_value().get(),

The `get()` method returns a `simdjson_result<value>` result. The signature of the `get()` function within `simdjson_result<value>` is...

```C++
simdjson_warn_unused simdjson_inline error_code get(T &value) && noexcept;
```

... which, as you can see, has `simdjson_warn_unused`. This is standard throughout the library.
