### ISSUE TITLE
PR #1975 broke documents with trailing garbage

### ISSUE THREAD

**Issue by juhaszp-uhu** [simdjson/simdjson#1976]
**Describe the bug**

I'm sorry to report that pull request #1975 that fixed my previous issue (#1974) introduced a regression: valid documents with trailing garbage now fail with "JSON document ended early in the middle of an object or array".

**To Reproduce**
```#include <iostream>
#include "simdjson.h"
using namespace simdjson; // optional

int main() {
  padded_string json = R"([1, 2] foo)"_padded;

  ondemand::parser parser;
  ondemand::document doc = parser.iterate(json);
  try {
    ondemand::value val = doc;
    ondemand::array arr = val.get_array();
    for (double value : arr) {
      std::cout << "got element: " << value << std::endl;
    }
    std::cout << "doc.current_location() = '" << doc.current_location() << "', we have more content: " << (doc.current_location().error() == 0) << std::endl;
    return 0;
  } catch (simdjson_error& e) {
    std::cout << "got exception " << e.error() << std::endl;
    return 1;  
  }
}
```
With release version 3.1.6 this does the expected and documented thing.
With the current master it fails with "JSON document ended early in the middle of an object or array".

**simjson release**

current master (59025bc8b1368f17bebc20496d153e2e4981249b)

**Configuration (please complete the following information if relevant)**
 - OS: Fedora 37
 - Compiler: gcc
 - Version: gcc version 12.2.1 20221121 (Red Hat 12.2.1-4) (GCC) 
 - Optimization setting -Og (doesn't matter)

**Indicate whether you are willing or able to provide a bug fix as a pull request**
...

**Comment by lemire** [comment]
Thanks for your useful feedback.

> With release version 3.1.6 this does the expected and documented thing.

We never supported content with trailing garbage though it was possible in some instances that you could bypassing checking with by casting the root object or root array to a value.

But if you ran the following code with 3.1.6...

```C++
#include <iostream>
#include "simdjson.h"
using namespace simdjson; // optional

int main() {
  padded_string json = R"([1, 2] foo)"_padded;
  ondemand::parser parser;
  ondemand::document doc = parser.iterate(json);
  for(int64_t x : doc) {
    std::cout << x << std::endl;
  }
}
```

You would get 

```
terminating with uncaught exception of type simdjson::simdjson_error: JSON document ended early in the middle of an object or array
```

You'd get the same result with a variation such as...

```C++
#include <iostream>
#include "simdjson.h"
using namespace simdjson; // optional

int main() {
  padded_string json = R"([1, 2] foo)"_padded;
  ondemand::parser parser;
  ondemand::document doc = parser.iterate(json);
  ondemand::array arr = doc.get_array();
  for(int64_t x : arr) {
    std::cout << x << std::endl;
  }
}
```

Now, you could sidestep it in the following manner...

```C++
#include <iostream>
#include "simdjson.h"
using namespace simdjson; // optional

int main() {
  padded_string json = R"([1, 2] foo)"_padded;
  ondemand::parser parser;
  ondemand::document doc = parser.iterate(json);
  ondemand::value val = doc.get_value();
  ondemand::array arr = val.get_array();
  for(int64_t x : arr) {
    std::cout << x << std::endl;
  }
}
```

This lead to a PR to should how we could get around the issue...

https://github.com/simdjson/simdjson/pull/1908/files


However, it was never our intention to deliberately allow garbage in the JSON input, without throwing errors.

However, if your document is made of several components, you can use iterate_many which will allow you to access 1, 2 or many JSON documents, in sequence, one after the other. It is not required that they all be correct.

https://github.com/simdjson/simdjson/blob/master/doc/iterate_many.md

I am closing this issue. It works as desired. The JSON specification does not allow garbage content. 

Your string is not going to be recognized as JSON, at least not portably... JavaScript will reject it...

<img width="613" alt="Capture d’écran, le 2023-03-24 à 19 54 00" src="https://user-images.githubusercontent.com/391987/227663755-2ed08fb2-adcd-448d-94d7-9ce63cec4fc4.png">

Python will reject it...

<img width="892" alt="Capture d’écran, le 2023-03-24 à 19 55 59" src="https://user-images.githubusercontent.com/391987/227663833-f7f6fbb7-0c38-4677-8127-68207d134584.png">

**Comment by juhaszp-uhu** [comment]
This is most unfortunate.

While documents with trailing garbage were not explicitly supported, they were not explicitly *un*supported either, and they were supported in practice. It was possible to parse such a document correctly and even get a pointer to the start of the unparsed part. In my opinion this was a useful and valid use case. All that verbiage in the documentation about current_location()'s return value certainly suggested, to me at least, that it was intended to be, or at least could be used with such documents. And now that possibility is gone.

> JavaScript will reject it...
> Python will reject it...

However, Perl's JSON::XS, which I'm using as a baseline, has a mode where it supports such documents:
```
perl -MJSON::XS -MData::Dumper -le 'print Dumper(JSON::XS->new->decode_prefix("[1] foo"));'
$VAR1 = [
          1
        ];
$VAR2 = 3;
```
With simdjson before PR #1975, I could replicate this functionality with little extra effort. 

May I ask you to reconsider?
Or at least, would it be possible to add either a new get_value_without_root_check() or similar that does what get_value used to do, or an optional boolean parameter to get_value() that disables the root check?

Barring that, I have the following choices, all bad:

- freeze the bundled simdjson version at 3.1.6 forever
- maintain a private fork of simdjson that restores the functionality
- make my program significantly more complex and less perfomant
- abandon the project entirely.

**Comment by lemire** [comment]
> However, Perl's JSON::XS, which I'm using as a baseline ...

The following...

```Perl
use JSON::XS;
 
my $json_text = '[1, 2] fafa';
$perl_scalar = JSON::XS->new->utf8->decode ($json_text)
```
Fails with 
```
garbage after JSON object, at character offset 7 (before "fafa") at test2.pl line 4.
```

You are calling `decode_prefix`....

> This works like the decode method, but instead of raising an exception when there is trailing garbage after the first JSON object, it will silently stop parsing there and return the number of characters consumed so far.

The equivalent in simdjson is `iterate_many` which solves the same kind of problem...

https://github.com/simdjson/simdjson/blob/master/doc/iterate_many.md

... which seeks to decode streams of JSON documents, one after the other in sequence.

> I have the following choices, all bad

If you have specific needs that are not covered by our current code base, then we invite your pull requests. If your team can justify the features, and they bring no burden on other users, and you provide good code with tests, then you can expect your code to be seriously considered.
