### ISSUE TITLE
Trailing content not consistently detected: test cases

### ISSUE THREAD

**Issue by juhaszp-uhu** [simdjson/simdjson#1977]
**Describe the bug**

The On Demand parser does not consistently fail on documents with trailing content in single document mode (parser.iterate()).
E.g. `[1, 2] foo ]`.

Additionally, iterate_many() mode does not detect a scalar document with certain, specific trailing content. E.g. `1111 }`. This document results in an EMPTY error.

**To Reproduce**
```
#include <iostream>
#include <string>
#include "simdjson.h"
using namespace simdjson; // optional

int main() {
  std::string test_cases[] = {
    R"([1, 2] foo)",
    R"([1, 2] foo ])",
    R"([1, 2] foo ] )",
    R"([1, 2] foo })",
    R"([1, 2} foo ])",
    R"([1, 2] [3])",
    R"({"1": 2} foo)",
    R"({"1": 2} foo })",
    R"({"1": 2} foo } )",
    R"({"1": 2} foo ])",
    R"({"1": 2] foo })",
    R"({"1": 2} {"3": 4})",
  };

  for (auto test : test_cases) {
    auto json = padded_string(test);
    ondemand::parser parser;
    ondemand::document doc = parser.iterate(json);
    try {
      ondemand::value val = doc;
      std::cout << "     '" << json << "', parsed value as '" << val << "', doc.current_location() = '" << doc.current_location() << "', we have more content: " << (doc.current_location().error() ? "no" : "yes") << std::endl;
    } catch (simdjson_error& e) {
      std::cout << "*    '" << json <<  "', got exception: " << e.error() << std::endl;
    }
  }
  return 0;
}
```
*Output:*
```
*    '[1, 2] foo', got exception: JSON document ended early in the middle of an object or array.
     '[1, 2] foo ]', parsed value as '[1, 2]', doc.current_location() = 'foo ]', we have more content: yes
     '[1, 2] foo ] ', parsed value as '[1, 2]', doc.current_location() = 'foo ] ', we have more content: yes
*    '[1, 2] foo }', got exception: JSON document ended early in the middle of an object or array.
     '[1, 2} foo ]', parsed value as '[1, 2}', doc.current_location() = 'foo ]', we have more content: yes
     '[1, 2] [3]', parsed value as '[1, 2]', doc.current_location() = '[3]', we have more content: yes
*    '{"1": 2} foo', got exception: JSON document ended early in the middle of an object or array.
     '{"1": 2} foo }', parsed value as '{"1": 2}', doc.current_location() = 'foo }', we have more content: yes
     '{"1": 2} foo } ', parsed value as '{"1": 2}', doc.current_location() = 'foo } ', we have more content: yes
*    '{"1": 2} foo ]', got exception: JSON document ended early in the middle of an object or array.
     '{"1": 2] foo }', parsed value as '{"1": 2]', doc.current_location() = 'foo }', we have more content: yes
     '{"1": 2} {"3": 4}', parsed value as '{"1": 2}', doc.current_location() = '{"3": 4}', we have more content: yes
```

*Comments:*
In the output, test cases that generated a "JSON document ended early" exception are marked with an asterisk. In all the cases where the last token is a structural character that matches the first structural character, the check that's done when getting the top-level structure fails, and retrieves the object/array as a value. In the cases where the first part of the document is a valid JSON (e.g. `[1, 2] foo ]`, it is possible to fully parse the valid part, call at_pointer() on it etc.

I hesitate to offer suggestions at this point, but it seems to me that if we accept the axiom that On Demand parsing validates the document "as we go", to the extent that we use it, then calling check_root_object or check_root_object on the top_level structure is a not a good idea. Merely checking whether the last token matches the first is not enough, and not a proper check, because it makes an implicit assumption about the as-of-yet unvalidated part of the document (that it is balanced and correct).

I'm not sure about the way forward.
- Always scan through the object/array, validating it? That would incur a significant performance penalty.
- Abandon the heuristics to tell anything about the object/array before actually processing it? That may be perceived by users as a limitation. 
- Offer both ways, a fast, non-validating path and a slow, validating one? Additional complexity. 
- Keeping it like this? Then the state of affairs should be documented.

**simjson release**

Current master (9bef628982fed89e5e4efb6b3eecdd43fcadb91d)

**Configuration (please complete the following information if relevant)**
 - OS: Fedora 37 Linux
 - Compiler: gcc
 - Version: gcc version 12.2.1 20221121 (Red Hat 12.2.1-4) 
 - Optimization setting: -Og

**Indicate whether you are willing or able to provide a bug fix as a pull request**
I'd be willing...

**Comment by lemire** [comment]
Thanks for the excellent examples. I will be adding an `at_end()` method, and the corresponding documentation, so that users may check for these unusual but potential important cases. Much appreciated.

Your analysis is correct: we could check that the document is balanced, but that would generally too expensive. It is perfectly sensible in my view to offer concerned users the possibility to do one small check at the end of the processing. The performance impact is nil.

> calling check_root_object or check_root_object on the top_level structure is a not a good idea

It is essential to check the end of the document matches our expectations. Either we check that the document in balanced (which we do in the case of the last document in a stream, with iterate_many) or else we have to check the end of the document. It is one or the other.

> Additionally, iterate_many() mode does not detect a scalar document with certain, specific trailing content. E.g. `1111 }`.

 
If you try to iterate over a stream of documents where the input is `1111 }`, then it will immediately return and the `current_index` will be set at zero. 

If you wish the process such inputs with simdjson, I recommend you sanitize them first, to ensure that you do have something that looks like a stream of documents.
