### ISSUE TITLE
The invalid scalar document 'falseA' is not rejected, but parsed as a boolean

### ISSUE THREAD

**Issue by juhaszp-uhu** [simdjson/simdjson#1981]
**Describe the bug**

Consider the document that contains the string "false" plus exactly one non-structural or non-whitespace character. Example: "false\x00" or "falseA" (but not "false}"). Simdjson doesn't reject this document as invalid, but parses it as the boolean value false.

This seems to affect only scalar documents with this very specific content.

**To Reproduce**

```
#include <iostream>
#include "simdjson.h"
using namespace simdjson; // optional

int main() {
  padded_string json = R"(falseA)"_padded;

  ondemand::parser parser;
  ondemand::document doc = parser.iterate(json);
  try {
    bool b = doc.get_bool();
    std::cout << "got boolean: " << (b ? "true" : "false") << std::endl;
    return 0;
  } catch (simdjson_error& e) {
    std::cout << "got exception " << e.error() << std::endl;
    return 1;  
  }
}
```

**simjson release**

3.1.6

**Configuration (please complete the following information if relevant)**
not relevant

**Indicate whether you are willing or able to provide a bug fix as a pull request**
I think the problem is that in value_iterator::get_root_bool() you prepare a temporary buffer for exactly 5+1 characters, so after that json_iterator::copy_to_buffer() copies only 5 characters from the input and sets the last character to a space and thus the last, offending character from the input never gets checked.

Perhaps the fix is as simple as this?
```diff --git a/simdjson.h b/simdjson.h
--- a/simdjson.h
+++ b/simdjson.h
@@ -28846,7 +28846,7 @@ simdjson_warn_unused simdjson_inline sim
 simdjson_warn_unused simdjson_inline simdjson_result<bool> value_iterator::get_root_bool(bool check_trailing) noexcept {
   auto max_len = peek_start_length();
   auto json = peek_root_scalar("bool");
-  uint8_t tmpbuf[5+1];
+  uint8_t tmpbuf[6+1];
   if (!_json_iter->copy_to_buffer(json, max_len, tmpbuf)) { return incorrect_type_error("Not a boolean"); }
   auto result = parse_bool(tmpbuf);
   if(result.error() == SUCCESS) {
```

**Comment by lemire** [comment]
Verified.

**Comment by lemire** [comment]
I believe it is sufficient to uncomment the line that I had commented out earlier. There is no need for a larger buffer I expect.

Fix in https://github.com/simdjson/simdjson/pull/1982
