### ISSUE TITLE
JSON::SIMD: a Perl module that uses simdjson

### ISSUE THREAD

**Issue by pjuhasz** [simdjson/simdjson#1990]
I recently released JSON::SIMD, a perl module forked from JSON::XS, that uses simdjson for decoding. It is available at [https://metacpan.org/pod/JSON::SIMD](https://metacpan.org/pod/JSON::SIMD). I'd appreciate if you included a link to it in the Bindings section of the documentation.

Thanks for your work that made this module possible!

**Comment by lemire** [comment]
@pjuhasz Would you be willing to do a PR, this way, you'd have the link the way you want it!!!
