### ISSUE TITLE
Enable error logging

### ISSUE THREAD

**Issue by yongxiangng** [simdjson/simdjson#2003]
Related issue #506 

### Feature Request

To enable logging of errors only. Currently, setting `SIMDJSON_VERBOSE_LOGGING` will log errors and other info. It would be nice to differentiate the logs into different levels and configure the log levels to be logged via an environment variable / compile option.

Is this a feature that would be desired? Should we implement this with an environment variable or compile option?

### Other notes

The motivation behind this is because I'd like to know the key passed in when we receive `NO_SUCH_FIELD` error code is returned. Enabling verbose logging would be too expensive, because I only need the logs when an error occurs.

### Possible Implementation

I am willing to help and make the changes.

My proposal is to use a environment variable `SIMDJSON_LOG_LEVEL`, which defaults to `INFO`. To log error messages only, we compile with `SIMDJSON_VERBOSE_LOGGING` and set the env variable `SIMDJSON_LOG_LEVEL` to `ERROR`.

1. Add enum class `log_level` in the logger with 2 levels, `INFO`, `ERROR`
2. Add method `should_log(log_level)` in the logger class. It will fetch the env variable on first invocation.
3. Modify `log_line` to take in `log_level` as an additional param (should I default this to `INFO`?)
4. inside `log_line` do something like
```c++
if (LOG_ENABLED && simdjson_unlikely(should_log(log_level)))
{
  // logging impl ...
}
```

**Comment by lemire** [comment]
The PR, at a glance, looks reasonable.

**Comment by lemire** [comment]
I am going to have to remove the PR. It can have a large negative performance effect.

**Comment by lemire** [comment]
Fixed by https://github.com/simdjson/simdjson/pull/2030
