### ISSUE TITLE
enum name  `LOG_INFO` `LOG_ERROR`  too common,  easy to cause conflict with other project's  Macro declaration, for example ClickHouse

### ISSUE THREAD

**Issue by byronhe** [simdjson/simdjson#2021]
many C++ projects defines their own `LOG_INFO` or `LOG_ERROR` macro to do their own logging, when they import simdjson, it unavoidable to cause symbol conflict compile error.

like:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/logger_useful.h#L61

https://github.com/search?q=%22define+LOG_INFO%22+language%3AC%2B%2B&type=code&l=C%2B%2B

https://grep.app/search?q=LOG_INFO&case=true&words=true&filter[lang][0]=C%2B%2B

**Comment by lemire** [comment]
Yes, do you want to issue a PR to fix this?

**Comment by lemire** [comment]
I am going to close this since our code is correct in this respect and follows good practices. The variables are scoped within namespaces. Pull request are invited, however.

**Comment by byronhe** [comment]
https://github.com/simdjson/simdjson/pull/2022
