### ISSUE TITLE
slowdown during switch from 3.1.8 to 3.2.0 version

### ISSUE THREAD

**Issue by slidertom** [simdjson/simdjson#2028]
Hi,
I get slowdown after version upgrade from 3.1.8 till 3.2.0.
Mine custom tests: (json parse time it's only about 50%)
3.2.0: 66.745324 s
3.1.8: 45.268451 s
(I simply change cpp/h simdjson files)

simdjson::ondemand
const size_t len = json.length();
doc = parser.iterate(json.c_str(), len, len + simdjson::SIMDJSON_PADDING);

Visual Studio 17.6.4
64 bit

Maybe some new  define is introduced?
https://github.com/simdjson/simdjson/releases/tag/v3.2.0 

Maybe some pipelines can be found to detect, that new versions produces similar results?
(maybe it's simply duplicate of https://github.com/simdjson/simdjson/issues/1687)

**Comment by lemire** [comment]
Yes. The problem is with https://github.com/simdjson/simdjson/pull/2004

**Comment by lemire** [comment]
@slidertom Please verify. The issue should be fixed in the latest release.

**Comment by slidertom** [comment]
Yes, the issue is fixed in the latest release and 3.2.1 version works even faster vs. 3.1.8.
Thank you!

**Comment by lemire** [comment]
Thanks for confirming the fix.
