### ISSUE TITLE
Compiling with SIMDJSON_DEVELOPER_MODE=OFF is missing some internal definitions

### ISSUE THREAD

**Issue by bgemmill** [simdjson/simdjson#2037]
**Describe the bug**
From a clean checkout, configuring simdjson with `-DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSIMDJSON_DEVELOPER_MODE=OFF` and then building produces a simdjson.h file that's missing some internal definitions. 

The most notable missing entry is `simdjson::internal::instruction_set`. There's a comment just above where the missing symbol is referenced, saying `/* skipped duplicate #include "simdjson/internal/instruction_set.h" */`

Compiling with developer mode on seems to produce a correct simdjson.h file.

It looks like there's a false positive check somewhere that this file was all ready included when developer mode is off.

**To Reproduce**
```
//git clone a checkout of simdjson somewhere
cmake -DCMAKE_INSTALL_PREFIX:PATH=/somewhere/to/examine/output -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSIMDJSON_DEVELOPER_MODE=OFF
make install
// examine install output's simdjson.h for references to simdjson::internal::instruction_set
```

**simjson release**
Using simdjson 3.2.1

**Configuration**
 - OS: Ubuntu 22.04.2 LTS
 - Compiler: clang 16.0.6, cmake 3.26.4

**Comment by lemire** [comment]
Please do the following...

```
 wget https://github.com/simdjson/simdjson/archive/refs/tags/v3.2.1.zip
 unzip v3.2.1.zip
 cd simdjson-3.2.1/
 cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSIMDJSON_DEVELOPER_MODE=OFF
 cmake --build build
```

I cannot verify an issue.

**Comment by lemire** [comment]
The header files should not depend on whether you have SIMDJSON_DEVELOPER_MODE set or not.

**Comment by lemire** [comment]
I did the following...

```
wget https://github.com/simdjson/simdjson/archive/refs/tags/v3.2.1.zip
unzip v3.2.1.zip
cd simdjson-3.2.1/
cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSIMDJSON_DEVELOPER_MODE=OFF -DCMAKE_INSTALL_PREFIX:PATH=destination
cmake --build build
cmake --install build
echo -e '#include <simdjson.h>\nint main(int argc,char**argv) {simdjson::dom::parser parser;simdjson::dom::element tweets = parser.load(argv[1]); }' > tmp.cpp
c++ -Idestination/include -Ldestination/lib64 -std=c++17 -Wl,-rpath,destination/lib -o linkandrun tmp.cpp -lsimdjson
```

It builds.

**Comment by lemire** [comment]
The same routine works from our main branch. Can you provide a reproducible test case?

Please provide complete instructions.

**Comment by lemire** [comment]
I have removed the tag "bug (unverified)" tag.

**Comment by bgemmill** [comment]
Looks like I was pulling from head rather than 3.2.1, so everything looks good with the current release.

On head, everything looks good on the command line; my usage of simdjson is through cmake's `ExternalProject_Add`, where I see the issue with:
```
    set(SIMDJSON_ROOT "/tmp/simdjson") # put it somewhere for this example

    ExternalProject_Add(
            dependency-simdjson
            GIT_REPOSITORY https://github.com/simdjson/simdjson
            UPDATE_COMMAND ""
            CONFIGURE_COMMAND ${CMAKE_COMMAND} -DCMAKE_INSTALL_PREFIX:PATH=${SIMDJSON_ROOT} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSIMDJSON_DEVELOPER_MODE=OFF
            BUILD_COMMAND ""
            BUILD_IN_SOURCE true
            INSTALL_COMMAND ${CMAKE_COMMAND} -E rm -r ${SIMDJSON_ROOT}
            COMMAND $(MAKE) install
            INSTALL_DIR ${SIMDJSON_ROOT}
    )
```

The command line appears to works perfectly fine:
```
git clone https://github.com/simdjson/simdjson.git
cd simdjson
cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/simdjson -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSIMDJSON_DEVELOPER_MODE=OFF
rm -r /tmp/simdjson
make install
```

I'm not sure why these two approaches would produce a different simdjson.h file.

**Comment by lemire** [comment]
We have a working demo using `ExternalProject_Add` and it works with the current code.

https://github.com/simdjson/cmakedemo_externalproject

I am not sure that I understand your `ExternalProject_Add` configuration. What happens if you try something closer to what we have?

**Comment by lemire** [comment]
Our configuration is just this...

```
ExternalProject_Add(simdjson_repo
  GIT_REPOSITORY    https://github.com/simdjson/simdjson.git
  GIT_SHALLOW       TRUE
  INSTALL_DIR ${CMAKE_CURRENT_SOURCE_DIR}/priv
  CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_SOURCE_DIR}/priv
  BUILD_COMMAND ${CMAKE_COMMAND} --build . --config Release
)
```

Of course, you can replace `${CMAKE_CURRENT_SOURCE_DIR}/priv` with anything you like.

**Comment by jkeiser** [comment]
I think I know what this is, and I have a fix coming up shortly.

**Comment by jkeiser** [comment]
@bgemmill could you pull down `jkeiser/more-headers` branch and see if it works for you?

I can't figure out how this didn't fail in CI ... if I read it right, it should happen literally anytime you compile on a non-arm64 machine.

**Comment by bgemmill** [comment]
@jkeiser using `ExternalProject_Add` in my setup, I can confirm that this set of options works:
```
GIT_TAG jkeiser/more-headers
GIT_REMOTE_NAME origin/jkeiser/more-headers
```
While this set of options fails:
```
GIT_TAG master
GIT_REMOTE_NAME origin/master
```

Looking at your commits, I'm curious why master works from the command line at all :smile:

**Comment by jkeiser** [comment]
Thanks! And thanks for reporting.

**Comment by lemire** [comment]
Closing. Please re-open if there is still an issue.
