### ISSUE TITLE
Verify SSE version as part of CI tests using emulator

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#205]
This PR https://github.com/lemire/simdjson/pull/202 introduces support of the SSE instruction set (for older hardware lacking AVX2). To make sure it runs correctly, we need to either test on older hardware or use an emulator approach (e.g., qemu). Or something else (like `-mno-avx`).

**Comment by lemire** [comment]
I don't think it is needed anymore.

**Comment by TkTech** [comment]
Don't forget about https://software.intel.com/content/www/us/en/develop/articles/intel-software-development-emulator.html which lets you test anything including AVX-512.

**Comment by lemire** [comment]
We investigated whether the Intel license allowed us to use it innCI and Intel folks never got back to us which suggest it is not allowed.

Meanwhile qemu does not seem to support SIMD.

However with @jkeiser’s work, we have good non-AVX tests.

**Comment by TkTech** [comment]
The simple solution suggested by an Intel employee was to just hide the download URL in a secret (which GA, travis, etc all support), https://community.intel.com/t5/Intel-ISA-Extensions/SDE-Licensing-Clarification/m-p/1146666/highlight/true#M6441. First stage of the test would just `wget $SDE_URL`.
