### ISSUE TITLE
No consistant coding style in docs

### ISSUE THREAD

**Issue by qbojj** [simdjson/simdjson#2057]
In  the docs there are multiple instances of code snippets that use some sort of mixed coding style, for example:

https://github.com/simdjson/simdjson/blob/cc24bb41145a927bce17a72289be29b8620cc570/doc/basics.md?plain=1#L972-L992

Every `if` statement is formatted differently.

I suggest formatting all code snippets with clang-format with predetermined format and to add a github-action that will check if that format is respected or just reformat the code that is pulled into the repo.

**Comment by lemire** [comment]
We follow a common C++ convention. For example, it is part in the [Google C++ style](https://google.github.io/styleguide/cppguide.html#Formatting_Looping_Branching):

>  the curly braces for the controlled statement or the line breaks inside the curly braces may be omitted if as a result the entire statement appears on either a single line (in which case there is a space between the closing parenthesis and the controlled statement) or on two lines (in which case there is a line break after the closing parenthesis and there are no braces).
