### ISSUE TITLE
Linker error unresolved external symbol simdjson::internal::error_code_info

### ISSUE THREAD

**Issue by rdutta** [simdjson/simdjson#2064]
> 2. A build issue? If so, provide all possible details regarding your system configuration. If we cannot reproduce your issue, we cannot fix it.

Error when trying to build the quickstart example:

`
1>simdjson.obj : error LNK2001: unresolved external symbol "struct simdjson::internal::error_code_info const * const simdjson::internal::error_codes" (?error_codes@internal@simdjson@@3QBUerror_code_info@12@B)`

Configuration
```
OS - Windows x64
Compiler - Visual Studio 2022 (v143)
Standard - C++17
```

Installed with vcpkg as per the wiki

```
simdjson:x64-windows                              3.2.1               A extremely fast JSON library that can parse gig...
simdjson[deprecated]:x64-windows                                      Enable deprecated APIs
simdjson[exceptions]:x64-windows                                      Enable exception-throwing interface
simdjson[threads]:x64-windows                                         Link with thread support
simdjson[utf8-validation]:x64-windows                                 Enable UTF8 validation
```

Edit: Using the `singleheader/` files from master build without errors, but I would like to use vcpkg and have VS treat them as system headers as then I don't need to manually ignore warnings.

**Comment by lemire** [comment]
Please provide a reproducible test case.

We have demonstration complete with continuous integration for testing:

https://github.com/simdjson/simdjson-vcpkg
