### ISSUE TITLE
array::at() method returns INDEX_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by ksandro** [simdjson/simdjson#2069]
I have simple json array that contains 3 elements, I get an error if I try to access to the element with index 2 after accessing the element with index 1 using  at() function.  It works when I only call at(2) without calling at(1)

Here is a simple example that reproduces the issue:

array.json :
`["0","1","2"] `

test.cpp :

```
#include <iostream>
#include "simdjson.h"
using namespace simdjson;
int main(void) {
    ondemand::parser parser;
    padded_string json = padded_string::load("array.json");
    ondemand::document data = parser.iterate(json);

    auto arr = data.get_array();

    std::cout << "array size: " << arr.value().count_elements() << std::endl;

    std::cout << arr.at(1) << std::endl;
    std::cout << arr.at(2) << std::endl;
}

```

output:
```

$ ./test 
array size: 3
"1"

terminate called after throwing an instance of 'simdjson::simdjson_error'
  what():  INDEX_OUT_OF_BOUNDS: Attempted to access an element of a JSON array that is beyond its length.
Aborted (core dumped)

```

I tried to compile using gcc and clang on my Linux x-64 machine.

**Comment by lemire** [comment]
Do you refer to this function in our On Demand API?

```C++
  /**
   * Get the value at the given index. This function has linear-time complexity.
   * This function should only be called once on an array instance.
   */
  simdjson_inline simdjson_result<value> at(size_t index) noexcept;
```

You have taken into account that you should `call once on an array instance`?

This function is very specialized, it is meant to be used only when you need just one entry. We deliberately disallow repeated calls to it.

Maybe you mean to use our DOM API?

https://github.com/simdjson/simdjson/blob/master/doc/dom.md

**Comment by lemire** [comment]
I removed the bug label since the provided code sample violates the function specification.

**Comment by lemire** [comment]
The code sample uses `count_elements()`, please refer to the documentation on its usage:

> Users should be aware that the count_elements method can be costly since it requires scanning the whole array. You should only call count_elements as a last resort as it may require scanning the document twice or more.

**Comment by ksandro** [comment]
Ok, now I see that it is really mentioned in the documentation. Sorry, I didn't see it.
But it is really non intuitive, that this function can not be called two times, and in some cases it works (if I call at(0) than at(1) gives correct result in my example).  Maybe it is possible somehow to forbid incorrect usage, but it is not important I think the issue can be closed.  

I used count_elements() just for debugging, to be sure that array really contains required number of elements, it is not used in production code.

**Comment by lemire** [comment]
Closing.

Pull requests are always invited.
