### ISSUE TITLE
Trailing comma support for array and object

### ISSUE THREAD

**Issue by kuliu** [simdjson/simdjson#2083]
Is there any plan to support trailing comma in array and object?
* no tailing comma `[1, 2, 3]` or `{"a":1}`
* tailing comma `[1, 2, 3,]` or `{"a":1,}`

I know it is not valid in [RFC 8259](https://www.tbray.org/ongoing/When/201x/2017/12/14/rfc8259.html) but somehow is widely used in some scenarios.

**Comment by lemire** [comment]
Python does not accept such broken JSON:

<img width="564" alt="Capture d’écran, le 2023-11-22 à 08 31 08" src="https://github.com/simdjson/simdjson/assets/391987/76c59270-6507-4e57-892d-726190494fc4">


JavaScript does not accept it:

<img width="564" alt="Capture d’écran, le 2023-11-22 à 08 31 08" src="https://github.com/simdjson/simdjson/assets/391987/382758c2-f764-413c-bbed-8c24a907f937">


It is explicitly prohibited by the standard.

The simdjson library seeks to be standard compliant. We want to be rejecting broken JSON.
