### ISSUE TITLE
Add Glace to the benchmarks

### ISSUE THREAD

**Issue by niclar** [simdjson/simdjson#2089]
[Glaze](https://github.com/stephenberry/glaze) make some serious claim to fame
 albeit simdjson ondemand still outperforms it in his benchmarks. Would be nice to get it included in these benchmarks as well as it better reflects the nearest competition.

**Comment by lemire** [comment]
Pull request invited.

I don't think that this needs to be an issue, someone can just add blaze to our benchmarks and create a pull request.
