### ISSUE TITLE
Double parsing can produce incorrect results due to integer overflow.

### ISSUE THREAD

**Issue by chenhao-db** [simdjson/simdjson#2093]
**Describe the bug**

Double parsing can produce incorrect results due to integer overflow. It happens when the integer part is zero and the decimal part is a large integer.

**To Reproduce**

```
#include "simdjson.h"

using namespace simdjson;
using namespace std;

int main() {
  ondemand::parser parser;
  auto json = R"(0.95000000000000000000)"_padded;
  ondemand::document doc = parser.iterate(json);
  double d;
  cout << doc.get_double().get(d) << endl;
  cout << d;
}
```

The expected result of `d` is 0.95, but the actual output is:

```
SUCCESS: No error
0.0276628
```

I believe the root cause is https://github.com/simdjson/simdjson/blob/v3.6.2/include/simdjson/generic/numberparsing.h#L1007. It is incorrect to use `start_digits-src` to determine whether there is an overflow. In the example above, `start_digits-src` is 2, so it is not considered as an overflow, but the value `95000000000000000000` doesn't fit into `uint64_t`.

**simjson release**

Verified on v3.6.2. It should also exist in many older versions.

**Comment by lemire** [comment]
Congratulations. You found a bug! And you also outlined the location of the bug.
