### ISSUE TITLE
get_number().get_double() produces incorrect results, but get_double() is correct

### ISSUE THREAD

**Issue by chenhao-db** [simdjson/simdjson#2099]
**Describe the bug**

Double parsing can produce incorrect results in `get_number().get_double()`. It happens when the number of significant digits is too many. Interestingly, another API `get_double()` can produce correct results in this case.

**To Reproduce**

```
#include "simdjson.h"

#include <iostream>

using namespace simdjson;
using namespace std;

int main() {
  ondemand::parser parser;
  auto json = "1000000000.000000001"_padded;
  ondemand::document doc = parser.iterate(json);

  ondemand::number num = doc.get_number();
  cout << num.get_number_type() << endl;
  cout << num.get_double() << endl;

  cout << doc.get_double() << endl;
}
```

The output is:
```
floating-point number (binary64)
0
1e+09
```

I believe the root cause is https://github.com/simdjson/simdjson/blob/ebd09cb2a3ab421f04b404338c01b593ade5a08c/include/simdjson/generic/numberparsing.h#L482. As the comment says, this makes a copy of the writer and passes it to `slow_float_parsing`. However, the writer, which is an `ondemand::number` in this case, will not be updated and remains the initial value of 0.

**simjson release**

Verified on v3.6.3. It should also exist in many older versions.

**Comment by lemire** [comment]
@chenhao-db Correct. PR in progress at https://github.com/simdjson/simdjson/pull/2100
