### ISSUE TITLE
Wrong version number for release 3.7.0

### ISSUE THREAD

**Issue by striezel** [simdjson/simdjson#2114]
It looks like the version number for [release version 3.7.0](https://github.com/simdjson/simdjson/releases/tag/v3.7.0), currently at commit 88bf5cb6d95324751fc916475c77a53ffba0f1a8, is wrong. The version number [in the code](https://github.com/simdjson/simdjson/blob/v3.7.0/include/simdjson/simdjson_version.h) is still 3.6.4. See https://github.com/simdjson/simdjson/blob/88bf5cb6d95324751fc916475c77a53ffba0f1a8/include/simdjson/simdjson_version.h#L7.

**Comment by lemire** [comment]
We went from 3.6.3 to 3.6.4 but I mistakenly entered 3.7.0 in the GitHub UI. Fixed.

**Comment by striezel** [comment]
Thanks. It was a but confusing. :D

**Comment by lemire** [comment]
I am thankful that you reported it.

**Comment by carlocab** [comment]
The v3.7.0 tag is still around: https://github.com/simdjson/simdjson/releases/tag/v3.7.0

I take it that's on purpose? Yanking it would be a bit rude to your users who have already fetched the tag (especially if it is yanked with the intention of reusing it later on).

**Comment by lemire** [comment]
@carlocab I did not delete the tag, but it was created by mistake.

What do you propose we do at this point?

**Comment by chenrui333** [comment]
> @carlocab I did not delete the tag, but it was created by mistake.

I think it might be good to delete that tag to avoid confusion.

**Comment by lemire** [comment]
Tag deleted.

**Comment by lemire** [comment]
@carlocab I am sorry about the mistake, but it has only been a few hours. I am hoping you can just correct the tags without too much difficulty.

**Comment by chenrui333** [comment]
Thanks for the tag deletion!
