### ISSUE TITLE
Fallback parser missing on aarch64 + Linux

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#2117]
I may have missed a change note, but it appears the fallback parser is unavailable on aarch64 with the current master branch.

You can see this issue here, https://github.com/TkTech/pysimdjson/actions/runs/7775456262/job/21201468893#step:5:946, where we build the aarch64/linux wheels for pysimdjson. One of the tests we do with every build is ensure that an exception is raised when setting a rubbish implementation, and that the fallback parser can always be set.

The minified simdjson source is not modified and no additional defines are made from the defaults. I base image is https://quay.io/repository/pypa/manylinux2014_aarch64?tab=tags&tag=2024-01-23-12ffabc and I believe it's clang 9.3.

**Comment by jkeiser** [comment]
By default, we only include kernels that could possibly be selected automatically on any machine we could possibly run on. But the arm64 kernel works on all aarch64 machines, so the fallback kernel will never be selected, and thus doesn't get compiled.

If you want the kernel for tests or for some other reason, you can include it with a flag. On phone so I don't know which flag offhand, but I believe it's in the build documentation.

**Comment by TkTech** [comment]
Ah I see, that's changed at some point then. Looks like this is the block responsible:

```c++
// Default Fallback to on unless a builtin implementation has already been selected.
#ifndef SIMDJSON_IMPLEMENTATION_FALLBACK
#if SIMDJSON_CAN_ALWAYS_RUN_ARM64 || SIMDJSON_CAN_ALWAYS_RUN_ICELAKE || SIMDJSON_CAN_ALWAYS_RUN_HASWELL || SIMDJSON_CAN_ALWAYS_RUN_WESTMERE || SIMDJSON_CAN_ALWAYS_RUN_PPC64
// if anything at all except fallback can always run, then disable fallback.
#define SIMDJSON_IMPLEMENTATION_FALLBACK 0
#else
#define SIMDJSON_IMPLEMENTATION_FALLBACK 1
#endif
#endif
#define SIMDJSON_CAN_ALWAYS_RUN_FALLBACK SIMDJSON_IMPLEMENTATION_FALLBACK
```

Thanks for the point in the right direction. I will include the fallback implementation, as by definition of being the fallback I believe it should always be present (and the documentation mentions it's always available in a few places) so that end-users of the library can also make that assumption safely without having to do platform checks.

**Comment by lemire** [comment]
@TkTech There might be a misunderstanding here. We omit the fallback when it is not needed. NEON is required in aarch64. As you have discovered you can force the fallback to be present even when it is not needed. This will generate a large binary for no practical benefit.

**Comment by TkTech** [comment]
Nope I understand. But documentation and code comments have stated that the fallback parser will always be available, and so that's the behaviour I need to keep and deprecate in a future version. Previous versions of simdjson always had it available even on aarch.

**Comment by lemire** [comment]
@TkTech Fair point. We'll fix that.

**Comment by jkeiser** [comment]
It feels like it would be useful to have a kernel name that represented the
"always available" kernel, even in situations where the fallback kernel
doesn't need to be there. Like, give the arm64 kernel the "fallback" name
when the current fallback kernel is unavailable. We could even rename the
current kernel to "generic" and alias fallback to it when it's present.

This way we don't have to increase binary size but we do give people a
consistent name that will always work with no speed guarantees.

Or, and this is spitballing, we make a kernel alias named "auto" or
something that you can use, which means "run whatever you would select by
default on this machine." That way, if you just need a consistent name, you
aren't forced to select a suboptimal kernel.

I like the latter better, but it depends on the use case. Is there a use
case for "give me the slow kernel, every time"? I can certainly understand
"give me a name that will always work," but that could be auto.

**Comment by lemire** [comment]
@jkeiser Please see https://github.com/simdjson/simdjson/pull/2118

I don't mind adding aliases, that's easy enough... although there is a bit of a design issue... so as not to make things more complicated for the users.
