### ISSUE TITLE
Fail to parse boolean in a truncated document stream.

### ISSUE THREAD

**Issue by chenhao-db** [simdjson/simdjson#2137]
**Describe the bug**

When `iterate_many` is applied to truncate documents, it may fail to parse boolean in the complete part of the documents.

**To Reproduce**

```
#include "simdjson.h"
#include <iostream>

using namespace simdjson;

int main() {
  auto json = "true  {"_padded;
  ondemand::parser parser;
  ondemand::document_stream docs = parser.iterate_many(json);
  for (auto doc : docs) {
    // Try to parse the first doc in the doc stream as boolean.
    std::cout << doc.get_bool().value()  << std::endl;
    break;
  }
}

```

The program will exit with an exception because `get_bool` returns an error. However, if the input is changed into "true {" (removing one space between `true` and `{`), the program will successfully print `1`. It is expected that the boolean parsing should always succeed, just like parsing the complete documents in 
https://github.com/simdjson/simdjson/blob/master/doc/iterate_many.md#incomplete-streams.

The result of `doc.raw_json_token()` will be `true  {`, which is also counter-intuitive to me. The comment https://github.com/simdjson/simdjson/blob/master/include/simdjson/generic/ondemand/document.h#L516 is:

> The string_view will start at the beginning of the token, and include the entire token *as well as all spaces until the next token (or EOF).*

Since it is "until the next token", it should not include the next token in my opinion.

**simjson release**

v3.7.0

**Comment by lemire** [comment]
> When parse_many is applied to truncate documents, it may fail to parse boolean in the complete part of the documents.



The following program returns 

```
1
3 bytes 
```

...


```C++
#include <iostream>
#include "simdjson.h"
using namespace simdjson;


int main(void) {
     auto json = R"(true {  )"_padded;
    simdjson::dom::parser parser;
    simdjson::dom::document_stream stream;
    auto error = parser.parse_many(json,json.size()).get(stream);
    if (error) { std::cerr << error << std::endl; return -1; }
    for(auto doc : stream) {
       std::cout << doc.get_bool().value() << std::endl;
    }
    std::cout << stream.truncated_bytes() << " bytes "<< std::endl; // returns 39 bytes
}
```

So it follows the documentation you refer to.  The code you are using does not call `parse_many`.

**Comment by chenhao-db** [comment]
Oh I'm sorry for the mistake. I should change `parse_many` in my problem description into `iterate_many`.

**Comment by lemire** [comment]
Verified.
