### ISSUE TITLE
Linker error unresolved external symbol simdjson::internal::error_code_info

### ISSUE THREAD

**Issue by hongxinGuo** [simdjson/simdjson#2152]
It is OK when include the simdjson.h and simdjson.cpp into my project directly. The compiler report LNK2001 error when using the vcpkg simdjson package.
os: windows x64
compiler: VS2022
simdjson version: 3.8.0

You can reproduct it by goto https://github.com/hongxinGuo/FireBird, download the branch vcpkg_simdjson_LNK2001_error.

Guo

**Comment by lemire** [comment]
> It is OK when include the simdjson.h and simdjson.cpp into my project directly. 

That's often simple. There is nothing wrong with it.

> You can reproduct it by goto https://github.com/hongxinGuo/FireBird, download the branch vcpkg_simdjson_LNK2001_error.

We are supported by vcpkg. You can check the demonstration at https://github.com/simdjson/simdjson-vcpkg

You can test it out for yourself: CMake will generate a Visual Studio project which you can build.

The most likely explanation of your trouble is that you have a misconfiguration as part of your Visual Studio solution or with vcpkg. If you think that there is a problem with vcpkg and you have followed their instructions, then you should raise an issue with vcpkg.

If you think that there is a bug in simdjson, please provide an example of your issue using CMake, as this is the build system we directly support.

I am not a Visual Studio expert, but let us consider the build settings from your main branch:

<img width="934" alt="Screenshot 2024-03-18 at 7 58 20 PM" src="https://github.com/simdjson/simdjson/assets/391987/905fb88e-5abd-4d9a-81df-d263ed327805">
<img width="948" alt="Screenshot 2024-03-18 at 8 00 36 PM" src="https://github.com/simdjson/simdjson/assets/391987/b1045782-8a26-4ccf-aceb-e915351ea14d">


Here are the new settings...

<img width="747" alt="Screenshot 2024-03-18 at 7 58 26 PM" src="https://github.com/simdjson/simdjson/assets/391987/5b464711-76a7-4d5e-b70e-267d433c4bff">
<img width="1269" alt="Screenshot 2024-03-18 at 8 01 14 PM" src="https://github.com/simdjson/simdjson/assets/391987/8223db67-f709-4bd1-b52b-2546c1f66ca7">


So, at a glance, you have removed entirely simdjson from your Visual Studio configuration.

That means that you *must* rely on Visual Studio integration with vcpkg. This requires some work. You have not provided details. If you have not done some, please review the appropriate documentation : 

https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-msbuild?pivots=shell-cmd

**Comment by lemire** [comment]
I have closed the issue.
