### ISSUE TITLE
Windows with Unicode path

### ISSUE THREAD

**Issue by Haruma-VN** [simdjson/simdjson#2157]
On Windows machine, _wfopen is more recommended to use to read the file. When I tested with an unicode path, example: "D:/打包开始/test.json", an IO_ERROR is thrown. I tried to change it to _wfopen and it works fine later. Below is what I changed.

Microsoft documentation: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170

What I have changed:

![image](https://github.com/simdjson/simdjson/assets/114157573/13857249-049f-4970-ae86-19c74ed4248f)

**Comment by lemire** [comment]
I can use this function to load files that have names with Unicode characters. There should be no problem using std::fopen for this purpose. It is not a deprecated function. 

Here is the [Microsoft documentation](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170):

> The fopen function opens the file specified by filename. By default, a narrow filename string is interpreted using the ANSI codepage (CP_ACP). In Windows Desktop applications, it can be changed to the OEM codepage (CP_OEMCP) by using the [SetFileApisToOEM](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileapistooem) function. You can use the [AreFileApisANSI](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-arefileapisansi) function to determine whether filename is interpreted using the ANSI or the system default OEM codepage.

If you need Unicode support at the system level, you probably should [set your code page to something like UTF-8](https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page). Have you done so?


In my case, AreFileApisANSI indicates that file APIs are not set to ANSI, but you may want to check your configuration. Have you called [SetFileApisToOEM](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileapistooem) prior to using files with Unicode file names to specify that you expect non-ANSI filenames?


> I tried to change it to _wfopen and it works fine later

You can write such a function for your purposes, but it is unnecessary. Windows has full support for UTF-8 natively. You just need to set your code page accordingly.

**Comment by Haruma-VN** [comment]
Thank you for your detailed explaination. Because there is no more issue occured I will close this issue as completed.

**Comment by lemire** [comment]
Thanks.

For people reading this: Windows has full support for UTF-8 and this includes `std::fopen`. Unfortunately, Windows systems are not always configured to use UTF-8 although it should be the default starting with Windows 11.

As an aside, the simdjson offers a function to load the data from disk, but that is just for convenience. In practice, you can load the data using any approach you prefer.
