### ISSUE TITLE
Parsing issue with the attached json

### ISSUE THREAD

**Issue by BadaPZ** [simdjson/simdjson#2166]
[bcpp062_Aws.json](https://github.com/simdjson/simdjson/files/14904802/bcpp062_Aws.json)
please help, what is wrong with the attached json
We receive this json file from 3rd party.
Any help is welcome, thanks

**Comment by lemire** [comment]
The attached JSON looks to be a correct JSON file.

I am closing this issue. If you are encountering a problem with simdjson, please provide a reproducible test case.

**Comment by BadaPZ** [comment]
simdjson::dom::parser parser;
      try
      {
            const auto dom = parser.parse(jsonstring);
            for (const simdjson::dom::object block : dom["Blocks"])
            {
.
.
      catch (const simdjson::simdjson_error& e)
      {
            RTprintf("\n%s\n", e.what());// TAPE_ERROR
            return -1;
      }

**Comment by lemire** [comment]
The file is fine and it parses correctly with simdjson's DOM API:

```
#include "simdjson.h"
#include <iostream>

int main(int argc, char *argv[]) {
  const char *filename = argv[1];
  simdjson::dom::parser parser;
  simdjson::dom::element doc = parser.load(filename);
  for (simdjson::dom::object v : doc["Blocks"]) {
    std::cout << v["BlockType"]["Value"] << std::endl;
  }
  return EXIT_SUCCESS;
}

```

Outputs...

```
"WORD"
"WORD"
"WORD"
"WORD"
"WORD"
"WORD"
...
```

If you are encountering problems with the simdjson, please provide a detailed analysis of your issue.

Marking as resolved.
