### ISSUE TITLE
document_stream::iterator::source misses the trailing character if the last element is scalar.

### ISSUE THREAD

**Issue by chenhao-db** [simdjson/simdjson#2170]
**Describe the bug**

When the last element in a `document_stream` is a scalar value, the result of `document_stream::iterator::source` on this element will miss the trailing character.

**To Reproduce**

The following code is adapted from https://github.com/simdjson/simdjson/blob/master/doc/iterate_many.md#incomplete-streams:

```
#include "simdjson.h"
#include <iostream>

using namespace simdjson;

int main() {
  auto json = R"(1 2 3)"_padded;
  simdjson::ondemand::parser parser;
  simdjson::ondemand::document_stream stream;
  auto error = parser.iterate_many(json).get(stream);
  if (error) { /* do something */ }
  auto i = stream.begin();
  size_t count{0};
  for(; i != stream.end(); ++i) {
    auto doc = *i;
    if (!i.error()) {
      std::cout << "got full document at " << i.current_index() << std::endl;
      std::cout << '"' << i.source() << '"' << std::endl;
      count++;
    } else {
      std::cout << "got broken document at " << i.current_index() << std::endl;
      return false;
    }
  }
}
```

The expected result is:

```
got full document at 0
"1"
got full document at 2
"2"
got full document at 4
"3"
```

The actual result is:

```
got full document at 0
"1"
got full document at 2
"2"
got full document at 4
""
```

Note that the last `source()` output is empty because it misses the trailing character `3`.

If I change the input `1 2 3` into `1 2 34`, the last output will be `"3"` because it misses the trailing character `4`. If I change the input into `1 2 []`, the last output will correctly be `"[]"`.

**simjson release**

Verified on 3.9.1.

**Comment by lemire** [comment]
I will investigate. Thanks for the report.

**Comment by lemire** [comment]
The bug has been verified.

**Comment by lemire** [comment]
Fix upcoming.

**Comment by lemire** [comment]
The fix will be in the next release.
