### ISSUE TITLE
Build failure on AVX2 systems due to forcing AVX512 types

### ISSUE THREAD

**Issue by td5038** [simdjson/simdjson#2174]
Is your issue:
2. A build issue? If so, provide all possible details regarding your system configuration. If we cannot reproduce your issue, we cannot fix it.

[build.log](https://github.com/simdjson/simdjson/files/15214684/build.log)
Yes it is a build issue. I have already filed it with the Gentoo devs [here](https://bugs.gentoo.org/931267)

You can find more info there.

**Comment by td5038** [comment]
@lemire

**Comment by td5038** [comment]
This was in NodeJS

**Comment by lemire** [comment]
This cannot be investigated as-is.

It is not a valid bug report.
