### ISSUE TITLE
[not bug] how to install it on Centos

### ISSUE THREAD

**Issue by batata004** [simdjson/simdjson#2180]
Hi,

I searched a lot and cant find how to enable this library on Centos so I can use it with PHP. I cant find the `dnf` command to install (I found instructions on how to install it on many other package managers, but I cant find a way to install it on centos so I can use it with PHP).

Can you please point me in the right direction?

**Comment by lemire** [comment]
To my knowledge, there is no CentOS package. Further, my impression is that CentOS is facing end-of-life. It is being retired. So I don't expect that there will be new packages.

In any case, if you want to have a package for simdjson on a given platform you have to ask the people managing this platform. We only provide the software, the packaging is handled by the Linux distributions.

Please see:

https://github.com/simdjson/simdjson/wiki/Installing-simdjson-with-a-package-manager
