### ISSUE TITLE
Full stream support, and json pointer support for document_stream

### ISSUE THREAD

**Issue by kfir-firebolt** [simdjson/simdjson#2198]
Hello, I was checking for the past days the possibility of using simdjson lib for a json reader that we ([firebolt](https://www.firebolt.io/)) are about to implement.
I started with benchmarks and I got super surprised by how fast it processed the data. I was super excited to start implementing and ultimately ship very fast json reader. but I started trying to use the lib for our needs and got stuck in the end because of 2 reasons:

1. there is no support for json pointer in document_stream object - we need to parse "json each row" documents that each row is a valid json, and you support it by parse/iterate_many but both returns stream which can be iterated but on each individual value there is no support for json pointer queries. we need something like this to work: 
`
simdjson::ondemand::parser parser;
simdjson::ondemand::document stream = parser.iterate(json.data(),json.size(), simdjson::dom::DEFAULT_BATCH_SIZE);
for(auto doc : stream) {
      doc.at_pointer("/0/a");
}
`

2.  there is no support for proper stream. We need to parse json files while they are being downloaded, and obviously json objects will be cut off mostly every time the stream come to an end and we need to download new data. if that happens there is no way to integrate it to simdjson parsers/documents, example:
`
json1={"a":1}{"a":
json2=2}{"a":3}
`
in order to be able to iterate and parse all of those json documents is to iterate_many the first one, get the truncated bytes, copy the truncated bytes and the json2 to new continues in memory buffer and rerun iterate_many. this is waist of copying the data and loose a lof of the efficiency that you provide.

just wanted to put it here, so if you decide to implement those features in the future I will be aware and we can consider using you lib after all. at the current moment the only lib that gives us everything we need (while its unfortunatly slow) is RapidJson

thanks regardless!

**Comment by lemire** [comment]
Thanks for your comments.

> there is no support for json pointer in document_stream object - we need to parse "json each row

To my knowledge, the JSON Pointer [specification](https://datatracker.ietf.org/doc/html/rfc6901) only applies to individual documents. If there is an extension of JSON Pointer to streams of documents, we will certainly consider (eagerly) an implementation.

> in order to be able to iterate and parse all of those json documents is to iterate_many the first one, get the truncated bytes, copy the truncated bytes and the json2 to new continues in memory buffer and rerun iterate_many. this is waist of copying the data and loose a lof of the efficiency that you provide.


We support incomplete streams explicitly, as documented here:
https://github.com/simdjson/simdjson/blob/master/doc/iterate_many.md#incomplete-streams

A copy is extremely fast and much faster than network access or JSON parsing in my experience. If you are encountering difficulties in this respect, please open a specific issue with reproducible test case were byte copies become the bottleneck. We will gladly have a look.

**Comment by lemire** [comment]
I have closed this issue. The reporter is encouraged to open new specific issues with documentation. If there are performance issue, we would need reproducible test cases.
