### ISSUE TITLE
For more robustness, it seems we should set o's viable_size to 0 in the move ctor of padded_string

### ISSUE THREAD

**Issue by Tunghohin** [simdjson/simdjson#2203]
**The bug appears here:**
![Screenshot from 2024-06-25 23-46-38](https://github.com/simdjson/simdjson/assets/88049360/499b2a2f-f85c-4cc0-b2ac-b7b5e148f010)
**The move ctor for padded_string does not set o's viable_size to 0, but the move copy does.**
![Screenshot from 2024-06-25 23-51-35](https://github.com/simdjson/simdjson/assets/88049360/565c366f-641d-4095-a6a0-b7a4ec122c16)

**Comment by lemire** [comment]
Pull request invited.
