### ISSUE TITLE
A weird simdjson issue from an Android app running on ChromeOS

### ISSUE THREAD

**Issue by ns-yyang** [simdjson/simdjson#2213]
We have an Android app, it uses simdjson to parer JSON. The function is straight forward, like

```
bool build(const std::string& json) 
{
    simdjson::dom::parser parser;  
    simdjson::dom::element recvdJson;
    auto error = parser.parse(json.c_str(), json.size()).get(recvdJson);
    if (error) {
        log("Json parse error %d,  %s", error, error_message(error));
        return false;
    }

    return true;
}
```

From anther function calls this function to parse a json string multiple times

```
std::string jsonStr = "<a sample JSON>";
for (int i=0; i < 15; ++i) {  
        if (!build(jsonStr)) {
            break;
        }
}
```

The parse always failed in about 10 iterations. It's very weird since each time the func use a new parser and the feed in json strings are the same.  After this happened, if call build() to parse other JSON strings, it may fail as well unless restarting the Android app to bring the thing back to normal. But calling build() in a loop, will trigger the issue again. 

We don't see the issue on Android for same app (same code), but seeing  it when the Android app running on ChromeOS 126.0.6478.132 (ARM64).  This code used to work on ChromeOS. Seems it has this issue on this ChromeOS version. 

Any suggestions? Is it a bug need to be fixed?  Thanks in advance!

**Comment by lemire** [comment]
I am going to close this as you are not providing enough information for us to reproduce the issue.

If you believe that there is a bug in ChromeOS, please report it with ChromeOS.

You must either provide us with enough information that we can reproduce the bug, or else, you must identify the bug.

**Comment by ns-yyang** [comment]
Hi @jkeiser  This is the complete C++ example
```
bool build(const std::string json) {
    simdjson::dom::parser parser; 
    simdjson::dom::element recvdJson;
    auto error = parser.parse(json.c_str(), json.size()).get(recvdJson);
    if (error) {
        return false;
    }
    return true;
}

void parse()
{
    std::string jsonStr = R"({"xjd":"lag","name":"qwerty","version":3,"support":false,"lbaas":false,"skip_session":true,"sub":"12345","exp":1720730963,"iat":1720727363,"jti":"124-5353"})";
    for (int i=0 ; i < 45; ++i) {
        if (!build(jsonStr)) {
            break;
        }
    }
}
```
The `parse()` was called from main thread. You can see the JSON string is a pretty common one. The same code ONLY failed in one platform:  ChromeOS (ARM64) (We run it from an Android App on ChromeOS). Even on ChromeOS, the first few iterations to parse the same string has no problem. According to the test, normally the problem happened after 30 iterations.  This is the error message from simdjson "Json parse error code 3,  The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc."
We didn't have code change from our side and started to see the problem on new ChromeOS (126.0.6478.132) recently. So this may due to changes from the new system which triggers the issue from simdjson. We also tried  simdjson 3.9.4, but still has the problem.
Thanks!

**Comment by lemire** [comment]
@ns-yyang 

The most likely explanation here is that you have a bug in your application and it is only getting triggered in the sample code you offer us, accidentally.


The easiest next step for you is run your code with various sanitizers (memory, address, thread, etc.). That would be the first step to help ensure that your application is using safe code.
