### ISSUE TITLE
Depth error while parsing array elements

### ISSUE THREAD

**Issue by agrgat** [simdjson/simdjson#2226]
```
void parse_message(std::string message) {
  simdjson::ondemand::parser parser;
  auto const padded_message {simdjson::padded_string {std::move(message)}};

  auto doc {parser.iterate(padded_message)};
  auto response_array {doc.get_array()};

  auto message_type {response_array.at(0).get_int64().value()};
  auto message_id {response_array.at(1).get_string().value()};
}
```

the code above will fail while trying to parse the message_id. the message we are trying to parse is an ocpp protocol message that looks like this:

`
"[3,\"6020e90f-e844-4526-85d1-7cd4b089a95d\",{\"currentTime\":\"2024-08-04T09:41:23.394Z\"}]"
`

the error that we receive while trying to parse the message is given below:

`
Assertion failed: (_json_iter->_depth == _depth + 1), function assert_at_child, file simdjson.h, line 41476.
`

the error occurs on this line:

`
SIMDJSON_ASSUME( _json_iter->_depth == _depth + 1 );
`

**Comment by lemire** [comment]
The `at` function can only be used once on the array. After that, the array is consumed and you can no longer use it.

You should iterate through the values of the array instead. You can break after two values if you only need the first two values.

![IMG_0512](https://github.com/user-attachments/assets/bb3f20ce-45c1-4307-a8ae-e80746986d9c)
![IMG_0513](https://github.com/user-attachments/assets/d207552c-e1e2-4d86-a79e-20ecf79b4940)
