### ISSUE TITLE
Questions about `document::get() &&`

### ISSUE THREAD

**Issue by the-moisrex** [simdjson/simdjson#2227]
I was trying to get the `tag_invoke` way work for the whole "document" as well that I saw this:

https://github.com/simdjson/simdjson/blob/a33fdc2770549ec1f602736420c2e1b18b7df2f0/include/simdjson/generic/ondemand/document.h#L170-L199

`document::get() &&` is NOT a specialization of `document::get() &` at all.

And also I don't understand why `document::get() &` exists in the first place! Is there a reason why a non-const version of `document::get()` was not enough?

This is concerning since the user now has to specialize 2 things which even the library itself does too for some reason which itself is confusing on multiple levels:

https://github.com/simdjson/simdjson/blob/a33fdc2770549ec1f602736420c2e1b18b7df2f0/include/simdjson/generic/ondemand/document-inl.h#L170-L176

So, if the user wants to specialize a class called `Car` fully, they have to specialize 3 member functions as far as I know, 2 for `document::get` and one for `value::get`; and also all 3 are `noexcept` which itself is another problem that `tag_invoke` can solve.

Is there a reason why I can't replace `document::get() &&` with this or I'd be breaking something?

```c++
  template<typename T> simdjson_inline simdjson_result<T> get() && noexcept {
      return static_cast<document&>(*this).get<T>();
  }
```

And also, are there any tests for `document::get() &&`?

**Comment by lemire** [comment]
> And also, are there any tests for `document::get() &&`?

At a glance, I would answer by the negative. Of course, it is easy to add some but it is concerning that there is no test.

**Comment by lemire** [comment]
I have removed the 'bug' marker because though there might be a mistake that needs fixing, I would not count it a bug but rather a design defect.

(I define a bug as something that would affect our users, not something that gives trouble.)

**Comment by the-moisrex** [comment]
I'll open up a PR soon that includes this and update the docs and some new tests.

**Comment by the-moisrex** [comment]
PR: #2228

**Comment by the-moisrex** [comment]
Since we've decided we would be disabling `document::get() &&` if `tag_invoke` custom type is provided, and keep backward-compatibility and mark `document::get() &&` as deprecated, I'm gonna close this issue.

**Comment by lemire** [comment]
> I'm gonna close this issue.

Sure. Note that you can open _discussion items_.
