### ISSUE TITLE
Cannot cross-compile to Linux ARM from Linux x86_64

### ISSUE THREAD

**Issue by Ravbug** [simdjson/simdjson#2238]
**Describe the bug**
Simdjson fails to compile when using the gcc ARM cross compiler.

**To Reproduce**
1. Install the gcc ARM cross compilers: `apt install gcc-12-aarch64-linux-gnu:amd64 g++-12-aarch64-linux-gnu:amd64`
3. Clone latest simdjson
4. `CC=/usr/bin/aarch64-linux-gnu-gcc-12 CXX=/usr/bin/aarch64-linux-gnu-g++-12 cmake -S . -B build -G Ninja`
5. `cmake --build build --target simdjson`

Errors generated:
```
/usr/bin/aarch64-linux-gnu-g++-12 -DSIMDJSON_AVX512_ALLOWED=1 -DSIMDJSON_THREADS_ENABLED=1 -DSIMDJSON_UTF8VALIDATION=1 -I/home/ubuntu/Desktop/simdjson/include -I/home/ubuntu/Desktop/simdjson/src -O3 -DNDEBUG -std=c++17 -mno-avx256-split-unaligned-load -mno-avx256-split-unaligned-store -MD -MT CMakeFiles/simdjson.dir/src/simdjson.cpp.o -MF CMakeFiles/simdjson.dir/src/simdjson.cpp.o.d -o CMakeFiles/simdjson.dir/src/simdjson.cpp.o -c /home/ubuntu/Desktop/simdjson/src/simdjson.cpp
aarch64-linux-gnu-g++-12: error: unrecognized command-line option ‘-mno-avx256-split-unaligned-load’
aarch64-linux-gnu-g++-12: error: unrecognized command-line option ‘-mno-avx256-split-unaligned-store’
```

**simjson release**
ToT on main branch (615218a3ad5b3a52a1e6b8a6526d5b0de3b95611 was the latest commit I checked)

**Configuration (please complete the following information if relevant)**
 - OS: Ubuntu 24.04 LTS
 - Compiler: arch64-linux-gnu-g++-12
 - Version 12
 - Optimization setting: Defaults (see repro steps)

**Indicate whether you are willing or able to provide a bug fix as a pull request**
I am unable to provide a bug fix for this issue.

**Comment by lemire** [comment]
The CMake documentation states that...

> When cross-compiling, a [CMAKE_TOOLCHAIN_FILE](https://cmake.org/cmake/help/latest/variable/CMAKE_TOOLCHAIN_FILE.html#variable:CMAKE_TOOLCHAIN_FILE) should set the CMAKE_SYSTEM_PROCESSOR variable to match target architecture that it specifies

Your instructions do to indicate anything with respect to `CMAKE_TOOLCHAIN_FILE`.  In particular, this involves setting CMAKE_SYSTEM_PROCESSOR... which are not doing according to your report.

I am closing this issue. If you are still encounting issues after following properly setting the CMAKE_TOOLCHAIN_FILE and you find that there is something incorrect with our CMake, we invite a pull request. Note however that our build setup is being used on a routine basis for cross-compiling...
