### ISSUE TITLE
Missing includes in static builds

### ISSUE THREAD

**Issue by undisputed-seraphim** [simdjson/simdjson#2239]
When doing a cmake install of the static build, the headers are not included as a property in the `simdjson_static` target. As a result, when linking against the `simdjson_static` target in an executable, the compiler can not find the headers.

To demonstrate the problem, build and install to any directory:
```
cmake -B build -S . -DSIMDJSON_BUILD_STATIC_LIB=ON -DCMAKE_INSTALL_PREFIX=build/install
cmake --build build --target install
pushd build/install/lib/cmake/simdjson/
vimdiff simdjsonTargets.cmake simdjson_staticTargets.cmake
```
You will see that the cmake file for the static variant is missing one line that says `INTERFACE_INCLUDE_DIRECTORIES ${_IMPORT_PREFIX}/include`. This line is present in the non-static cmake file.

To fix, simply add `INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"` to [below line 208 of CMakeLists.txt](https://github.com/simdjson/simdjson/blob/master/CMakeLists.txt#L208).

To verify the fix, repeat the steps above to find that the static variant also has that line, and targets that link against simdjson_static can now find the headers.

**Comment by lemire** [comment]
@undisputed-seraphim Pull request invited.

**Comment by undisputed-seraphim** [comment]
Fixed and merge. Thank you!
