### ISSUE TITLE
Issue of "Pointer being freed was not allocated" with dom::parser when externally linking

### ISSUE THREAD

**Issue by a-soll** [simdjson/simdjson#2244]
**Describe the bug**
I have a very simple object that houses a dom::parser. When the project builds my library via cmake along with a simple test exe, the code works fine. However, if I try to use the code via `find_package()` and run the same test executable, I get an error about the `dom::parser` being freed without being allocated. It happens whether the parser gets used or not. 

**To Reproduce**
1. `git clone --recurse-submodules https://github.com/a-soll/ezjson.git && cd ezjson`
2. Build and install the library: 
    a. `bin/build`
    b. `cd build && sudo make install && cd ..`
4. Run the locally linked binary: `build/test/test`. There should be no issues.
5. Build the externally linked binary: `bin/build_external_link`
6. Run the externally linked binary: `test_external/build/ezjson-test`

When running the externally linked binary, you should get the following:
```
➜  ~/ezjson git:(main)
$ test_external/build/ezjson-test
ezjson-test(6542,0x1fa1acf40) malloc: *** error for object 0xffffffff: pointer being freed was not allocated
ezjson-test(6542,0x1fa1acf40) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    6542 abort      test_external/build/ezjson-test
```

![image](https://github.com/user-attachments/assets/79784b61-ad3f-47b0-8480-8bb92d31f6f1)

Inspecting in a debugger shows the last call made is `~parser()`, but only in a release build. It does not happen when building a debug binary.

This doesn't seem to happen if you just put a raw `dom::parser p;` in main.cpp. It seems like it only happens if there's a `dom::parser` as an object member and also only when externally linked. I'm not sure if this is somehow an issue with how I'm using parser in my object or if it's something else, but it only happens when externally linking and also only seems to happen to parser. I have used this simple object for a long time now in a larger project with no issues. I only noticed when trying to build it as a library.

**Comment by lemire** [comment]
You are building a wrapper library around simdjson. Your library includes (part of) simdjson, that is, specifically, part of the simdjson code ends up in `libezjson.a`. Then you also include as a second dependency the simdjson library itself (so `libsimdjson.a`).

This means that many symbols are duplicated. That's not good.

You cannot do this. The problem has nothing to do with simdjson, it is just a generic problem. If you want to wrap a library and provide your own library, then you don't want the users of your wrapped library to use both the original library and the wrapped library... as it causes duplication.

Here is an easy fix:


https://github.com/a-soll/ezjson/pull/1


Note: this is **not a bug** in simdjson.
