### ISSUE TITLE
padded_string's constructor

### ISSUE THREAD

**Issue by void-mian** [simdjson/simdjson#2245]
I've noticed that all of the `padded_string`'s constructors are marked as `noexcept`. How can I detect if an error, such as `std::bad_alloc`, has occurred in this case? (Instead of getting an empty padded_string)
Additionally, I observed that some constructors (e.g., `padded_string(const char *data, size_t length)`) don’t set `viable_size` to zero, unlike others (e.g., `padded_string(std::string_view sv_)`). Is this a bug?

**Comment by lemire** [comment]
> How can I detect if an error, such as std::bad_alloc, has occurred in this case? 

It does not throw. If you want to manage out-of-memory conditions with exceptions, then you can allocate your own memory. Please refer to our documentation:
<img width="903" alt="Screenshot 2024-09-06 at 1 23 36 AM" src="https://github.com/user-attachments/assets/ca8e647a-61e9-43aa-a64e-af174098b67e">
