### ISSUE TITLE
Cannot link correctly simdjson to a project via CPM.

### ISSUE THREAD

**Issue by Arniiiii** [simdjson/simdjson#2246]
It seems to be continuation of https://github.com/simdjson/simdjson/issues/2225

**Describe the bug**
I can compile one code, and not another.

**To Reproduce**
CMakeLists.txt:
```cmake
...
include(cmake/getCPM.cmake)
set(simdjson_VERSION 3.10.1)
cpmaddpackage(
  NAME
  simdjson
  VERSION
  "${simdjson_VERSION}"
  URL
  "https://github.com/simdjson/simdjson/archive/refs/tags/v${simdjson_VERSION}.tar.gz"
  OPTIONS
  "SIMDJSON_ENABLE_THREADS ON"
  "BUILD_SHARED_LIBS ON"
  "SIMDJSON_BUILD_STATIC_LIB OFF" 
)

target_link_libraries(${PROJECT_NAME} PUBLIC simdjson)
...
```
main.cpp version 1 ( compiles successfully in docker with gentoo without gentoo's simdjson. ) taken from examples.:
```cpp
#include <iostream>
#include "simdjson.h"
using namespace simdjson;
int main(void) {
    ondemand::parser parser;
    padded_string json = padded_string::load("twitter.json");
    ondemand::document tweets = parser.iterate(json);
    std::cout << uint64_t(tweets["search_metadata"]["count"]) << " results." << std::endl;
}
```

main.cpp version  2  ( fails ):
```cpp
#include "simdjson/padded_string_view.h"
#include "simdjson/ondemand.h"
#include <iostream>
#include <string_view>
int main(void) {
  std::string_view strv("{\"serverTime\":1499827319559}");
  simdjson::padded_string_view pstrv(strv, strv.size());
  simdjson::ondemand::parser parser;
  simdjson::ondemand::document time = parser.iterate(pstrv);
  std::cout << time["serverTime"] << '\n';
}
```
If use CPM_USE_LOCAL_PACKAGES=1 on a Gentoo Linux system where simdjson is installed:
1. It has only simdjson.h 
2. It compiles and links successfully
3. It gives exception at runtime about not existing padding, which is expected

If use downloaded version:
1. It has bunch of different includes ( I guess it's good )
2. It compiles successfully
3. It doesn't link :
```
|| FAILED: simdjson_experiment-1.0 
|| : && /usr/bin/g++-15 -pipe -march=native -ggdb3 -g  CMakeFiles/simdjson_experiment.dir/main.cpp.o -o simdjson_experiment-1.0  -Wl,-rpath,/home/paxu/code/experiments/simd_experiment/build/GCC_15.0.0_x86_64-pc-linux-gnu/Debug/_deps/simdjson-build:  _deps/simdjson-build/libsimdjson.so.23.0.0 && :
|| /usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/simdjson_experiment.dir/main.cpp.o: in function `main':
main.cpp|8| (.text+0x30f): undefined reference to `simdjson::padded_string_view::padded_string_view(std::basic_string_view<char, std::char_traits<char> >, unsigned long)'
|| /usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/simdjson_experiment.dir/main.cpp.o: in function `simdjson::haswell::ondemand::parser::iterate(simdjson::padded_string_view) &':
/home/paxu/.cache/cpm/simdjson/998e5760f2f512ce2513a14078d84c342e55fcb4/include/simdjson/generic/ondemand/parser-inl.h|52| (.text._ZNR8simdjson7haswell8ondemand6parser7iterateENS_18padded_string_viewE[_ZNR8simdjson7haswell8ondemand6parser7iterateENS_18padded_string_viewE]+0x36): undefined reference to `simdjson::padded_string_view::padding() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /home/paxu/.cache/cpm/simdjson/998e5760f2f512ce2513a14078d84c342e55fcb4/include/simdjson/generic/ondemand/parser-inl.h|54| (.text._ZNR8simdjson7haswell8ondemand6parser7iterateENS_18padded_string_viewE[_ZNR8simdjson7haswell8ondemand6parser7iterateENS_18padded_string_viewE]+0x63): undefined reference to `simdjson::padded_string_view::remove_utf8_bom()'
|| collect2: error: ld returned 1 exit status
```

**simjson release**
It's tested with:
1. via CPM : simdjson versions : 3.10.1 , 3.10.0 , 3.9.5 , static and semi-shared versions are tested too.
2. with [Gentoo's](https://packages.gentoo.org/packages/dev-libs/simdjson) simdjson [3.10.1](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/simdjson/simdjson-3.10.1.ebuild)

**Configuration (please complete the following information if relevant)**
 - OS: Gentoo or Gentoo in docker
 - Compiler: GCC-13.2.1 , GCC-15.0.0 , Clang-19,  Clang-20
 - Version [e.g. 22] version of what? of simdjson maybe 23
 - Optimization setting (e.g., -O3):
   - if via CPM: `-O0 -ggdb3 -pipe -march=native`  ;
   - if local gentoo: ` -O3 -pipe -march=alderlake -mabm -mno-cldemote -mno-kl -mno-pconfig -mno-sgx -mno-widekl -mshstk --param=l1-cache-line-size=64 --param=l1-cache-size=48 --param=l2-cache-size=30720 -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -fgraphite-identity -floop-interchange -floop-strip-mine -floop-nest-optimize -ftree-loop-linear -ggdb3 -frecord-gcc-switches` 
   - if gentoo in docker:  `-O2 -pipe -march=x86_64` I believe

**Indicate whether you are willing or able to provide a bug fix as a pull request**
If it cmake only issue, yes. If it's more -- maybe, idk.

Additional:

whole experiment code:
https://github.com/Arniiiii/simdjson_experiment.git

**Comment by Arniiiii** [comment]
The whole code: 
https://github.com/Arniiiii/simdjson_experiment.git

**Comment by Arniiiii** [comment]
My first assumption was that something wrong in CMakeLists.txt . But I couldn't find anything, everything looks ok.

My second assumption is that something wrong with including cpp files in cpp which gives this strange behaviour. I haven't tested it

My third assumption is it if I can somehow check if simdjson.h and simdjson.cpp from releases are functional, I can confirm that this is something related to second assumption. WIP

**Comment by Arniiiii** [comment]
So, I've tried to download simdjson.h and simdjson.cpp from 3.10.1 release and it works. [Here's link to the code](https://github.com/Arniiiii/simdjson_experiment/tree/third_assumption) .

**Comment by Arniiiii** [comment]
After manually checking the compile command and their result, I got to command that compiles src/simdjson.cpp if via CPM. I've added `-E` flag for gcc to check if haswell.cpp was included. It was included.

I do not know why then it doesn't work correctly. 
Maybe release tools use specific macro definitions?

**Comment by Arniiiii** [comment]
whole process looks compilcated... and it seems all of this was setup to get "amalgamated" simdjson.h and simdjson.cpp ....

I guess cmake for simdjson::simdjson or simdjson::simdjson_static was expected to use similar behaviour, but headers are not setupped or whatever is inconsistent.

I believe there are two solutions:
1. Temprorary create a repo that utilizes amalgamated simdjson.h and simdjson.cpp from releases and make a github workflow that will create a new release of the repo at every release of simdjson , I know an example of such behaviour.
2. A lot of fixing of cmake code to make it use not amalgamated version. Maybe create in cmake scripts a `simdjson::simdjson_amalgamated` or whatever

**Comment by Arniiiii** [comment]
Also, why do we have different version of library and different release version?

**Comment by lemire** [comment]
It is the second time you report what you claim to be a bug without doing the proper work on your end.

I ask that you stop. You can open a discussion (see discussion tab). What you are doing is not ok.

> main.cpp version 2 ( fails ):

This code is incorrect. You should only have one simdjson include:

```cpp
#include "simdjson.h"
```

Please refer to our documentation. We offer multiple examples.

We offer a complete example with CPM:

https://github.com/simdjson/simdjson_cpm

Note that simdjson is also part of the CPM examples (in the CPM repo) and is being tested with every CPM release.

> Also, why do simdjson has different version of library and release version?

The soversion uses the standard Unix conversion where the soversion must be incremented each time the interface changes, which corresponds to either a minor or a major update in semantic versioning.
