### ISSUE TITLE
Basic int support

### ISSUE THREAD

**Issue by a-soll** [simdjson/simdjson#2249]
Is there any reason only 64 bit integers are allowed? For most cases, a basic int will suffice.

**Comment by lemire** [comment]
The int type in C/C++ has between 16-bit

We support 64-bit signed and unsigned integers. If one is confident that there is no overflow, one can do...

```cpp
int my_value = xyz["z"].get_int64()
```

If you want to be more careful, you can check for overflow like so...

```cpp
auto v = xyz["z"].get_int64();
if (v >= INT_MIN && v <= INT_MAX) {
    my_value = v
} else {
    // Handle the case where the value cannot be safely cast
    // You might want to log an error or use a different strategy
}
```

You can add support for custom types (including any integral type you'd like), see our documentation...

https://github.com/simdjson/simdjson/blob/master/doc/basics.md#adding-support-for-custom-types

It would be entirely possible to extend support to other number types. If you'd like to contribute, please consider providing a pull request.

**Comment by a-soll** [comment]
I'm working on the int32_t support right now. I have it successfully building, but I'm unsure about some values. 

I don't know if I'm using the correct mask or what's expected of this:
```cpp
constexpr const uint64_t JSON_VALUE_MASK = 0x00FFFFFFFFFFFFFF;
constexpr const uint32_t JSON_COUNT_MASK = 0xFFFFFF;
constexpr const int32_t JSON_32_MASK = 0x01; // <-- not sure what this needs to be
```

```cpp
simdjson_inline int32_t internal::tape_ref::tape_value32() const noexcept {
  return *(int *)&doc->string_buf[0] & internal::JSON_32_MASK; // <-- used here
}
```

I have the int stored in the first index of the string_buf right now since the string_buf holds 32 bit.

**Comment by lemire** [comment]
@a-soll We are not changing the DOM tape. If you want to retrieve a 32-bit value, you should use casting as I have described above.

If you want to support specific integral types, you can do it with the ondemand API, see my comments above.

**Comment by a-soll** [comment]
Is there a reason for not allowing 32 bit in the DOM? Just for my own understanding. It seems like it could be implemented in a way that doesn't impact 64 bit usage since it would be opt in by specifically casting via `<int32_t>`

**Comment by lemire** [comment]
@a-soll You are abusing the issue system. I have already stated, in a previous issue, that it was not ok. We have discussion tab which I encourage you to use.
