### ISSUE TITLE
Bug in doc/performance.md?

### ISSUE THREAD

**Issue by dan-robertson** [simdjson/simdjson#2271]
In `doc/performance.md`, a problem with padding is described. Because simdjson may read a vector starting at the last byte of your input, you could be doing invalid memory accesses is the bytes after your input are not readable. One way to handle this is to have `simdjson::SIMDJSON_PADDING` bytes (64 at the moment) of padding at the end of your input. When you can’t guarantee this, another proxy is that if the last byte of hypothetical padding is in the same page of memory as the last byte of your buffer, this vector read won’t fail and so copying your input to a padded version is not necessary.

The docs provide a function for this:
```c++
// Returns true if the buffer + len + simdjson::SIMDJSON_PADDING crosses the
// page boundary.
bool need_allocation(const char *buf, size_t len) {
  return ((reinterpret_cast<uintptr_t>(buf + len - 1) % page_size()) <
          simdjson::SIMDJSON_PADDING);
}
```

I think this function is incorrect. Suppose we have 4kb pages, `buf = 8192`, and `len = 5`. I think this should be safe as, if we add some hypothetical padding, the buffer would run from bytes 8192 to 8260 inclusive, which are all in the third page.

However, we compute:
```
need_allocation(8192, 5)
= (8192 + 5 - 1) % page_size() < 64
= 8196 % 4096 < 64
= 4 < 64
= TRUE
```

Similarly, suppose that `buf = 8192` and `len = 4096`. I think this is not safe: we may not be able to read the byte after the end of the buffer. Yet we compute:
```
need_allocation(8192,4096)
= (8192 + 4096 - 1) % page_size() < 64
= 12287 % 4096 < 64
= 4095 < 64
= FALSE
```

This isn’t as simple as getting an inequality the wrong way round: `buf = 8192` and `len = 100` gives `FALSE` which is correct.

I think the thing we want is that, for a page size `P` and integers `n`, `m`, and `0 <= k,l < P`, we have `buf + len - 1 = nP + k`, `buf + len + SIMDJSON_PADDING - 1 = mP + l`, and `n = m`. That is, the last byte of the buffer is on the same page as the last byte we might read.

I guess one could write it as something like
```c++
bool need_allocation(const char *buf, size_t len){
  return ((reinterpret_cast<uintptr_t>(buf + len + simdjson::SIMDJSON_PADDING - 1) % page_size()) <
          simdjson::SIMDJSON_PADDING
}
```
though I haven’t thought very thoroughly about whether this function is exactly right.

**Comment by lemire** [comment]
Please see https://github.com/simdjson/simdjson/pull/2273
