### ISSUE TITLE
Inconsistant result of dom and ondemand interface

### ISSUE THREAD

**Issue by zhanglistar** [simdjson/simdjson#2293]
Code:
```
#include "simdjson.h"
#include <iostream>
#include <string>

int main(int argc, char *argv[]) {
#if 0
  simdjson::dom::parser parser;
std::string json = "not123 a json";
  auto doc = parser.parse(json);
if (doc.error())
{
        std::cerr << "fail to parse" << std::endl;
return 0;
}
std::cerr <<"parse ok" << std::endl;
#endif


#if 1
  simdjson::ondemand::parser parser;
std::string json = "not123 a json";
  auto doc = parser.iterate(json);
if (doc.error())
{
        std::cerr << "fail to parse" << std::endl;
        return 0;
}
simdjson::ondemand::document d = std::move(doc.value());
auto r = d.is_scalar();
if (r.error())
{
        std::cerr << "fail" << std::endl;
        return 1;
}
auto t = d.type();
if (t.error())
{
        std::cerr << "fail" << std::endl;
        return 1;
}
std::cerr <<"parse ok" << std::endl;
#endif
}
```

For dom, output:
`fail to parse`
For ondeman, output:
`parse ok`

**Comment by lemire** [comment]
Please refer to our document. The DOM and On-Demand API are not equivalent, they work differently. In this instance, you never consumed the content with On-Demand, so it is expected that you will not get an error. The error will only occur once you consume it.

You may want to read our research paper presenting the overall design:

- John Keiser, Daniel Lemire, [On-Demand JSON: A Better Way to Parse Documents?](http://arxiv.org/abs/2312.17149), Software: Practice and Experience 54 (6), 2024.

**Comment by zhanglistar** [comment]
Thanks for you reply. I change my parser to dom when validating json instead of ondemand.

**Comment by lemire** [comment]
@zhanglistar You can validate with on-demand, but you need to consume the entire document.

E.g., see https://github.com/simdjson/simdjson/blob/master/benchmark/json2msgpack/simdjson_ondemand.h
