### ISSUE TITLE
Inconsistency array size of DOM and Ondemand API

### ISSUE THREAD

**Issue by zhanglistar** [simdjson/simdjson#2297]
Code:
```
#include "simdjson.h"
#include <iostream>
#include <string>

std::string unhex(const std::string& hex) {
    std::string result;
    for (size_t i = 0; i < hex.length(); i += 2) {
        std::string byte = hex.substr(i, 2);
        char chr = static_cast<char>(std::strtol(byte.c_str(), nullptr, 16));
        result.push_back(chr);
    }
    return result;
}

int main(int argc, char *argv[]) {
    std::string hex = "5B30000E06D7AA5D";
    std::string json = unhex(hex);
/// parse json using ondemand API
    simdjson::ondemand::parser parser;
    auto doc = parser.iterate(json);
        if (doc.error())
        {
                std::cerr << "fail to parse" << std::endl;
        return 0;
        }
auto d = std::move(doc.value());
auto r = d.is_null();
if (r.error())
{
std::cerr << "fail:" << r.error() << std::endl;
return 1;
}
std::cerr <<"parse ok" << std::endl;
auto v = d.get_value();
if (v.error()) std::cerr << "get value fail" << std::endl;
simdjson::ondemand::value v1 = v.value();
auto arr = v1.get_array();
if (arr.error()) std::cerr <<"get array fail" << std::endl;
std::cerr <<"lenth: " << arr.value().count_elements() << std::endl;

/// parse json using dom API
{
    std::cerr << "dom result" << std::endl;
    simdjson::dom::parser parser;

    simdjson::dom::element element;
    auto error = parser.parse(json).get(element);
    if (error) {
        std::cerr << "Error parsing JSON: " << error << std::endl;
        return 1;
    }

    if (element.is_array()) {
        simdjson::dom::array array = element;
        size_t length = array.size();
        std::cout << "Array length: " << length << std::endl;
    } else {
        std::cerr << "The JSON element is not an array." << std::endl;
    }

}
```
Output:
<img width="545" alt="image" src="https://github.com/user-attachments/assets/194d268d-e6ff-4135-9abc-aff9200c0e08">

The ondemand API returns 1 but DOM API returns exception.

**Comment by zhanglistar** [comment]
In my case, the `NUMBER_ERROR` suggests that there is a problem with a numeric value in the JSON data. The `ondemand` API might not have encountered this issue because it didn't fully process the problematic part of the JSON, or it deferred the error until later. To resolve this, I should verify that the JSON data is correctly formatted, especially any numeric values, and ensure that the `unhex` function correctly converts the hex string to valid JSON.
So, I have to handle this myself.

**Comment by lemire** [comment]
The `count_element` function does not consume the content. It may return an error if the JSON content is malformed as a JSON data structure, but the values within the array are not parsed.

**Comment by lemire** [comment]
The On-Demand API only validates the strict minimum. You need to parse each value in the array. If you omit parsing a value, it does not get validated. That is by design.


If you want to write a validator with On-Demand, you must do so by accessing every value in the JSON document.
