### ISSUE TITLE
Since simdjson 3.11, no longer compiled with ndk-r23

### ISSUE THREAD

**Issue by halx99** [simdjson/simdjson#2308]
Before submitting an issue, please ensure that you have read the documentation:

* Basics is an overview of how to use simdjson and its APIs: https://github.com/simdjson/simdjson/blob/master/doc/basics.md
* Performance shows some more advanced scenarios and how to tune for them: https://github.com/simdjson/simdjson/blob/master/doc/performance.md
* Contributing: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md
* We follow the [JSON specification as described by RFC 8259](https://www.rfc-editor.org/rfc/rfc8259.txt) (T. Bray, 2017).

We do not make changes to simdjson without clearly identifiable benefits, which typically means either performance improvements, bug fixes or new features. Avoid bike-shedding: we all have opinions about how to write code, but we want to focus on what makes simdjson objectively better.

Is your issue:

1. A bug report? If so, please point at a reproducible test. Indicate whether you are willing or able to provide a bug fix as a pull request. As a matter of policy, we do not consider a compiler warning to be a bug.

- compile error on ndk-r23c and c++20 enabled
- use singleheader downloaded from 3.11.1 release page
- prev release 3.10.x works

2. A build issue? If so, provide all possible details regarding your system configuration. If we cannot reproduce your issue, we cannot fix it.

![image](https://github.com/user-attachments/assets/6d528bd1-9738-443c-bd08-1b8325ddbc3b)

4. A feature request? Please provide a clear rationale for the feature. Be advised that simdjson is a community-based project: you should consider providing help.

5. A documentation issue? Can you suggest an improvement?

If you plan to contribute to simdjson, please read our
* CONTRIBUTING guide: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md and our
* HACKING guide: https://github.com/simdjson/simdjson/blob/master/HACKING.md

**Comment by lemire** [comment]
The screenshot you offer does not match our code:

<img width="476" alt="Screenshot 2024-12-09 at 9 29 03 AM" src="https://github.com/user-attachments/assets/3243995d-eca1-431a-995f-eacf5bb3fb66">

Here is what our code should look like...

```C++
template <typename T>
concept optional_type = requires(std::remove_cvref_t<T> obj) {
  typename std::remove_cvref_t<T>::value_type;
  { obj.value() } -> std::same_as<typename std::remove_cvref_t<T>::value_type&>;
  requires requires(typename std::remove_cvref_t<T>::value_type &&val) {
    obj.emplace(std::move(val));
    obj = std::move(val);
    {
      obj.value_or(val)
    } -> std::convertible_to<typename std::remove_cvref_t<T>::value_type>;
  };
  { static_cast<bool>(obj) } -> std::same_as<bool>; // convertible to bool
};
```

Notice how you have 'Sstd' while we have 'std'.

Please open a complete bug report.

It is not enough to state 'does not build on my system'. You need to provide at least some analysis to support the view that the bug is in simdjson. We build simdjson on a wide range of systems: LLVM, GCC, Visual Studio. 

You must, for example, demonstrate that the system you using is fully C++20 compliant. It appears that NDK r23 is based on LLVM 12. [Yet support for concepts in LLVM was completed in LLVM 13](https://libcxx.llvm.org/Status/Cxx20.html).

If you want support for C++20, I recommend updating your version of NDK to the current one.

**Comment by halx99** [comment]
> The screenshot you offer does not match our code:
> 
> <img alt="Screenshot 2024-12-09 at 9 29 03 AM" width="476" src="https://private-user-images.githubusercontent.com/391987/393871794-3243995d-eca1-431a-995f-eacf5bb3fb66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTgxMjksIm5iZiI6MTczMzc1NzgyOSwicGF0aCI6Ii8zOTE5ODcvMzkzODcxNzk0LTMyNDM5OTVkLWVjYTEtNDMxYS05OTVmLWVhY2Y1YmIzZmI2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNTIzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzA2ZDM3YmFmMGU3NTE1MjRmM2IyZDYzOTI0NjgxYzMxNjlmNWRmM2VlYjg3NDU3YjkzYTEwNmNjZTdlNGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L3OWMi-lI2vbiT9P_0Aq9FMlwg9Ybk3em0PlJG-zQW8">
> Here is what our code should look like...
> 
> ```c++
> template <typename T>
> concept optional_type = requires(std::remove_cvref_t<T> obj) {
>   typename std::remove_cvref_t<T>::value_type;
>   { obj.value() } -> std::same_as<typename std::remove_cvref_t<T>::value_type&>;
>   requires requires(typename std::remove_cvref_t<T>::value_type &&val) {
>     obj.emplace(std::move(val));
>     obj = std::move(val);
>     {
>       obj.value_or(val)
>     } -> std::convertible_to<typename std::remove_cvref_t<T>::value_type>;
>   };
>   { static_cast<bool>(obj) } -> std::same_as<bool>; // convertible to bool
> };
> ```
> 
> Notice how you have 'Sstd' while we have 'std'.
> 
> Please open a complete bug report.
> 
> It is not enough to state 'does not build on my system'. You need to provide at least some analysis to support the view that the bug is in simdjson. We build simdjson on a wide range of systems: LLVM, GCC, Visual Studio.
> 
> You must, for example, demonstrate that the system you using is fully C++20 compliant. It appears that NDK r23 is based on LLVM 12. [Yet support for concepts in LLVM was completed in LLVM 13](https://libcxx.llvm.org/Status/Cxx20.html).
> 
> If you want support for C++20, I recommend updating your version of NDK to the current one.

The screenshot incorrect, the android sutdio compile error output actually compile `std::`, I don't think the ndk-r23c with fully c++20 support.
