### ISSUE TITLE
Use cmake to generate Makefile

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#288]
Right now, we have to maintain the list of headers and sources in three places: amalgamation, cmake and Makefile. The latter two could be dealt with by making Makefile a fully generated thing.

To ensure they are in sync, we can require the Makefile to be in sync (i.e. regenerate before you check in changes), and have CI fail if "amalgamate" or "cmake" causes the Makefile or singleheader to change.

**Comment by lemire** [comment]
Sure. 

The amalgamation might always require some manual care. 

The Makefile could be dropped.

**Comment by lemire** [comment]
Closing.
