### ISSUE TITLE
Write a proper documentation for our API

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#293]
Especially the iterator...

**Comment by jkeiser** [comment]
@lemire is the combination of the API docs and [this](https://github.com/simdjson/simdjson/blob/master/README.md#code-usage-and-examples) what you're thinking of?

**Comment by jkeiser** [comment]
Either way, I think we have enough to unblock 0.3. Please place back in if you disagree or aren't sure; as the writer of the documentation, my feeling as to its readability is less important than, you know, a reader.

**Comment by lemire** [comment]
Closing. We may not have something "great" or "perfect" but we have something.
