### ISSUE TITLE
Get size of JSON array

### ISSUE THREAD

**Issue by maihuuthien** [simdjson/simdjson#308]
How can I get the size (number of elements) of an array from ParsedJson::Iterator?

**Comment by lemire** [comment]
You can visit the elements of the array with calls to `next()`, it returns `true` on success and `false` on failure. The API does not current provide a way to know directly the size of the array. This could be improved.

**Comment by maihuuthien** [comment]
Great. I'm looking forward to it. Because I need to parse a lot of arrays into std::vector, and it would really help if I could reserve the capacity beforehand.

**Comment by lemire** [comment]
Delaying to release 0.4.

**Comment by TkTech** [comment]
👍 for this. In our Python binding, the cost of reallocs to expand PyList as we iterate over an array is (relatively) very expensive, especially in a new process where CPython's alternative heap hasn't yet grown.

**Comment by lemire** [comment]
This has been solved.
