### ISSUE TITLE
Portable mode with no intrinsics

### ISSUE THREAD

**Issue by michaeleisel** [simdjson/simdjson#329]
It would be nice to have a version of the code without any intrinsics, so that it can be run more portably.

Use case: Swift package manager doesn't support changing which vector extension to use, and by default on MacOS it doesn't use any (https://forums.swift.org/t/modify-vector-extensions/27999). I want to support SPM for ZippyJSON for iOS, which unlike MacOS is fine (I guess by default it allows vector extensions). However, when running in debug in the simulator, it's running with MacOS, where we run into the vector extension issue. So, I need a portable fallback for this case where perf is not an issue anyways

**Comment by jkeiser** [comment]
To pile on a bit, this is also needed to make simdjson a comfortable choice of library for inclusion in many projects. As a project owner, I'm generally uncomfortable restricting the set of machines other people can run my stuff on.

A large amount of the code is already simd-neutral; you "just" need to copy `src/arch/haswell` to `src/arch/64bit` and replace all the functions there. It's work, but maybe not as much you'd think :)

**Comment by lemire** [comment]
Indeed, it may not be a crazy amount of work and it would provide a nice baseline for benchmarking.

**Comment by lemire** [comment]
@michaeleisel You can pass compiler flags to SwiftPM. Just build with "-Xcc -march=native".

**Comment by michaeleisel** [comment]
you can only do arbitrary build flags for top-level projects, not for dependencies

**Comment by michaeleisel** [comment]
to be fair, i found a workaround, so i no longer have a need for this

**Comment by lemire** [comment]
> i found a workaround

What is it?

**Comment by michaeleisel** [comment]
i simply use apple's JSONDecoder under the hood in these circumstances, since the performance isn't as important in the simulator anyways

**Comment by lemire** [comment]
This has actually been resolved. It will solved with release 0.3.

cc @jkeiser
