### ISSUE TITLE
WebAssembly Compile Target

### ISSUE THREAD

**Issue by TheLarkInn** [simdjson/simdjson#35]
Hi there! I'm very limited in my WebAssembly and C++, C knowledge, however if this was something that could be run via WebAssembly and allow JavaScript application's and processes to yield similar (even if slightly degraded results), it would be pretty rad! 

I'm not sure what work would be involved, so at the least, I'd love to request this as a feature so that tools running on NodeJS, or the Web can leverage this awesome piece of work.

**Comment by lemire** [comment]
I doubt that WebAssembly can be used at this time since they do not yet support SIMD.

**Comment by risc12** [comment]
Tools running on NodeJS might benefit more from a C++ Addon:
https://nodejs.org/api/addons.html

**Comment by lemire** [comment]
Indeed, a C++ addon would be the best path forward at this time for Node.

**Comment by svobol13** [comment]
I noticed that SIMD support has just been added under feature flag to V8. Does it change much for this ticket?

https://v8.dev/features/simd

**Comment by lemire** [comment]
@svobol13 It might.

**Comment by lemire** [comment]
Note that there is a Node simdjson https://www.npmjs.com/package/simdjson

**Comment by lemire** [comment]
This might be interesting, but I do not think we need to track this issue. If someone wants to work on it, please do.

**Comment by DrewRidley** [comment]
It might be worth investigating this issue now that canary/experimental versions of browsers commonly ship with SIMD.
