### ISSUE TITLE
minifier should be portable and support runtime dispatch

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#384]
Currrently, the function `json_minify` is SIMD accelerated only on AVX2, it does not support runtime dispatch and there is no fast ARM version.

It is a  low-hanging fruit.

Related: this PR https://github.com/lemire/simdjson/pull/383

cc @jkeiser

**Comment by jkeiser** [comment]
Yeah, genericizing that will be an enlightening exercise!
