### ISSUE TITLE
Offer function to check whether processor is supported 

### ISSUE THREAD

**Issue by DBJDBJ** [simdjson/simdjson#403]
I am trying to fix  simdjson stream. I need a guidance here.

- `find_the_best_supported_implementation()`, is where the problem is ... 
- `best_stage1` and `best_stage2` are not set because this CPU is not supported.
- `JsonStream` constructor which is calling it, simply proceeds even this has happened ..
- I would not like to throw the exception from that constructor.

But. Why doing any of these says I

Can we simply have the function: `simdjson::is_cpu_supported()` and do the check from `main()` ... If CPU happens not to be supported, app can not run. I have done this

```cpp
namespace simdjson
{
bool is_cpu_supported()
{
  if (Architecture::UNSUPPORTED == find_best_supported_architecture())
  {
    return false;
  }
  return true;
}
} // namespace simdjson
```
And this returns the right value and app proceeds.  To fail soon because `JsonStream` constructor, uses `find_the_best_supported_implementation()` which decides the same CPU is not supported ...

Please advise

--------------------------------------------------------------------------------------------------

FINDINGS

--------------------------------------------------------------------------------------------------

Now that I have `SIMDJSON_THREADS_ENABLED` actually undef'd, the #else code in `int JsonStream::json_parse(ParsedJson &pj);`  implementation, kicks-the-bucket  or flips-the-tables

![image](https://user-images.githubusercontent.com/145155/71254717-2553bf00-232c-11ea-84b2-b844a7091ad2.png)

on line 2337 -- this is my amended single header simdjson.cpp

Ant that is simply because `best_stage1` is `nullptr`

**Comment by piotte13** [comment]
Thanks for your work @dbj. 

Being the author of jsonstream, I will look into this as soon as I can, probably somewhere this afternoon.

**Comment by DBJDBJ** [comment]
thanks @piotte13 , however the issue has just popped up in jsonstream, it seems there should be one function deciding is the CPU supported, but there are few.

If I may suggest the general overarching API logic, imposed on customers, should be:

1. check on app startup if CPU is supported
2. elsewhere just assert on that same call

That would impose almost no changes to the existing code, but will improve the resilience.

**Comment by lemire** [comment]
This is good, I have changed the title.

**Comment by DBJDBJ** [comment]
@lemire  In the light of what we have talked yesterday, I have removed the fork and huge PR  from where this change was coming. A function is here in the comment above if problems with GitHub machinery just please copy paste it into `simdjson.h`?

On my side now I have a new fork from where I will be emanating smaller PR's.

**Comment by lemire** [comment]
Given that we now support all processors, this issue is resolved.

cc @jkeiser
