### ISSUE TITLE
fix find_last_json_buf_idx 

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#470]
The find_last_json_buf_idx function is meant to locate the index of the last complete JSON document in a stream of JSON documents. However, if there is just one document, it will run through it and act as if it found no complete JSON document, returning zero.

**Comment by jkeiser** [comment]
Just to clarify for future viewers, I believe this is code cleanup rather than a bug (see discussion in the referenced issue).

**Comment by lemire** [comment]
Correct. It is not a bug, I think that's the expect behaviour of the function right now, but that is not ideal. We would like something cleaner.

**Comment by lemire** [comment]
I am going to close this. We can reopen another issue if we find a better approach.

**Comment by jkeiser** [comment]
The refactored function [doesn't look like it does this anymore](https://github.com/simdjson/simdjson/blob/master/src/generic/stage1/find_next_document_index.h#L57-L60).
