### ISSUE TITLE
Get included in major benchmarks

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#481]
I was just surfing other json libraries, and found this site doing an independent comparison: https://github.com/miloyip/nativejson-benchmark/blob/master/README.md

We should get on there when we are ready for users. It's a good way to advertise.

And in the meantime, we should get on there as beta or something, just to make sure we compare like we think we do :) (And are covering all the important benchmark cases.)

**Comment by lemire** [comment]
Relevant: https://github.com/miloyip/nativejson-benchmark/issues/113

**Comment by DBJDBJ** [comment]
IMHO that is almost irrelevant 2020 Q1.  

HW should be defined and defined in terms of a description of 2 VM 's hosted by AWS, Azure or Google  Cloud.   One for WIN and one for NIX OS. 

Each contender should submit executable or executables.  
Some extremely simple command-line C++  app(s ) with source available in one separate github repo.

In that repo json samples of course, should reside.

For example load JSON, parse it and dump it back to command line ... Time measured is the result of Linux time command. And win equivalent, whatever it is. That schema would allow for simple but true memory consumption measurement too. Of course, API quality or lack of will shine through too.

And lastly, that would eradicate a lot of smoke and mirrors.

That is a project requiring time, people and money...

**Comment by boazsegev** [comment]
> For example load JSON, parse it and dump it back to command line 

FYI:

Dumping the result into the command line will cause benchmarking errors, as system calls and IO procedures may cause performance fluctuations.

Also, as most libraries are fairly fast, benchmarks would need to run a large number of tasks before the noise-data ration would offer meaningful performance results.

**Comment by jkeiser** [comment]
Looking there, prettified output and sax apis are both things they considered important enough to benchmark.

I wasn't able to quickly tell whether the benchmark allows the reuse of memory either.

My big concern with that benchmark, ironically, is that it will likely paint us in an unusually positive light because its files are all 600KB or more. I'd like to see benchmarks showing how a parser handles sample server loads, as well as "partial iteration" scenarios (currently it tests essentially a full walk of the Dom), and small file handling performance on top of the tests it does.

**Comment by jkeiser** [comment]
And echoing @DBJDBJ that it needs to test multiple host and CPU types.

**Comment by lemire** [comment]
Here is a benchmark where simdjson is included...
https://github.com/cppchedy/jsonlibsbench

(I have not looked at it beyond that.)

**Comment by jkeiser** [comment]
Damn, I wish they published results :)

**Comment by Mark407** [comment]
Hi all, I've made a PR or simdjson for the nativejson benchmark mentioned above: 

https://github.com/miloyip/nativejson-benchmark/pull/131 

Below the results vs rapidjson: 

**Benchmarking Performance of simdjson** 

Parse canada.json               ...  3.974 ms      540.204 MB/s
Parse citm_catalog.json         ...  1.039 ms      1585.361 MB/s
Parse twitter.json              ...  0.441 ms      1365.666 MB/s
Stringify canada.json           ... 69.225 ms      31.011 MB/s
Stringify citm_catalog.json     ...  5.887 ms      279.801 MB/s
Stringify twitter.json          ...  7.138 ms      84.374 MB/s
Statistics canada.json          ...  1.221 ms		1758.206 MB/s
Statistics citm_catalog.json    ...  0.436 ms      3777.959 MB/s
Statistics twitter.json         ...  0.155 ms      3885.540 MB/s

**Benchmarking Performance of RapidJSON (C++)**
Parse canada.json               ...  5.153 ms      416.606 MB/s
Parse citm_catalog.json         ...  2.563 ms      642.680 MB/s
Parse twitter.json              ...  1.786 ms      337.211 MB/s
Stringify canada.json           ...  9.878 ms      217.328 MB/s
Stringify citm_catalog.json     ...  1.270 ms      1297.000 MB/s
Stringify twitter.json          ...  0.979 ms      615.177 MB/s
Statistics canada.json          ...  0.781 ms      2748.745 MB/s
Statistics citm_catalog.json    ...  0.234 ms      7039.274 MB/s
Statistics twitter.json         ...  0.092 ms      6546.290 MB/s

**Comment by lemire** [comment]
@Mark407 I think that there is a small error in how you count the numbers. Also, you are working too hard to convert an element to a string.

I have issued a PR
https://github.com/miloyip/nativejson-benchmark/pull/132

**Comment by boazsegev** [comment]
I downloaded the Repo and tried running the benchmarks at [miloyip/nativejson-benchmark](https://github.com/miloyip/nativejson-benchmark).

The benchmarks crashes with a **runtime** exception:

```text
libc++abi.dylib: terminating with uncaught exception of type simdjson::simdjson_error: The JSON element does not have the requested type.
```

As much as I want to get the scoop on the speed here, it fails.

**Comment by lemire** [comment]
@boazsegev I think that the problem existed prior to my pull-request. The issue is that ParseDouble and ParseString are supposed to receive an array with either a string or a double in it. Given that I cannot build the project, I cannot test my work.

It is doubtful that we have a memory leak. If you can reproduce a memory leak, I'd be very interested in your code example and in how you determined that there was a memory leak. Note that when there is an abort (unhandled exception), the destructors are not called, so you will, evidently, have leaks.

**Comment by lemire** [comment]
I have issued a new PR https://github.com/miloyip/nativejson-benchmark/pull/133

**Comment by lemire** [comment]
I consider this issue resolved. If someone wants simdjson to be included in some specific benchmark, please open a specific issue or, better yet, submit a request to the folks handling the benchmark.
