### ISSUE TITLE
Evaluate Google Benchmarks

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#500]
We now have a `cmake -DSIMDJSON_GOOGLE_BENCHMARKS=ON` which builds `benchmark/bench_parse_call`. Turning that on increases "first cmake" time from 3 to 13 seconds, and build time from 28 to 33 seconds, on my machine.

We should evaluate whether Google Benchmarks is worth enough to increase build time a little and spend time fixing up, or whether we should remove it.

Given the nature of this project, we have needs that many projects don't have. This comment from @lemire brought up [some useful criteria](https://github.com/lemire/simdjson/pull/497#issuecomment-587777290):

> * We need to be able to benchmark specific steps in the code. Though this sounds trivial, this makes it hard to work with external frameworks like perf, xperf, vtune... That is, we often need to instrument the code itself to know precisely what we are measuring.
> * We need to be able to control the number of iterations. This is often critical. If you are working with tiny inputs or large inputs, you want as few iterations as possible to deal properly with branches and cache. I frequently vary the number of iterations to see how the metrics behave. If they change with respect to the number of iterations, then I need to understand why.
> * We need to be able to do the aggregates we need... for some problems, an average with a standard deviation is best... often times, a minimum is best, and so forth. So you really want access to the raw numbers.
> * We need low-overhead measures... That is, it is not acceptable for us to call the function many many times to make the overhead go away... because the number of iterations plays into the branch predictions and cache misses...
> * We need to be able to get instrumentation: cycles, branch predictions, instructions... I find it hard to reason from a single number (running time). In this instance, we have what looks like flat numbers, but what if there were a difference...?

**Comment by jkeiser** [comment]
I'll pile on to @lemire's point about aggregates: when you're benchmarking to compare your performance to other libraries, averages are actually the right thing. When you're evaluating whether a change to simdjson is *better than master,* however, the **minimum** often gets you a more stable measurement that can give you the answer more accurately. This is probably unique to simdjson, which has an unusually low amount of variation (deliberately).

**Comment by lemire** [comment]
+1
