### ISSUE TITLE
1.0 Goals

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#503]
We're starting to talk about 1.0 and release quality a lot more, so I think we should write out what we each *want* for simdjson. Even if our thoughts are raw and our goals are entirely personal, it can be super clarifying. A few questions that I ask myself, for example:

* What differentiates simdjson the most?
* What are we *personally* excited about from our simdjson work?
* What are the most important users and scenarios, and how do we make it attractive to them?
* What are "table stakes" things that we can't release without?
* What things would we embarrassed about and want to avoid?
* What is the right performance bar (since obviously, performance is our clearest differentiator)?
* Do we actually want to release a JSON library to users, or a performant JSON reader that is used internally by other JSON libraries? (I assume the former, but I don't know that I've ever heard it stated officially.)

From there, we should discuss what we need (and *don't* need) to do before we release a 1.0. The less steps, the better: the world deserves simdjson goodness sooner rather than later! On the other hand, nothing kills momentum like releasing useless, uninteresting or crappy software, so having a min bar really matters.

I'll kick it off with my thoughts as an example, but I'd *really* like to hear from others.

## My Thoughts: Goals, Scenarios and Steps To Get There

I think we mostly need polish to reach 1.0. Our distinguishing feature (perf) is already solid, sans a little extra benchmarking and maybe large file memory-walk perf.

1. **Insanely Fast:** We need to be not just faster, but *ridiculously* faster, than every shipped JSON parsing library. To stay buzzworthy, We also need to be at least in the ballpark of non-shipped JSON libraries and experiments.
   - [ ] Increase large file memory-walk performance: even if they aren't direct competitors, the 1.0 release will be noisy if we're [2x worse](https://github.com/lemire/simdjson/issues/482) on a major benchmark
   - [ ] Submit to major JSON benchmarking projects, make sure performance measures up
2. **Easy:** The API handles major scenarios with a minimum of fuss, and we're proud of the code examples posted on the internet: we can be used with as few terms (calls, namespaces, includes, operators, etc.) as possible, and all of those terms are words people already reach for when working with json.
   - [ ] doxygen API documentation
   - [ ] Simpler navigation APIs
3. **No Sharp Edges:** The library needs to not have big gotchas that hurt you down the line.
   - [ ] Non-SIMD fallback so people can be assured their programs will run anywhere, even if they aren't faster on older machines
   - [ ] Handle uneven document sizes for long-lived parsers. Servers care about memory usage, but can't fully predict the size of incoming documents. You can't just bump the parser every time you see a document without de-bumping at some point. As a user, I could use some guidance, or better yet, have simdjson handle these situations for me.
4. **No-Fuss Integration:** Super easy to integrate into your project. Single header, package managers (if there are any), use as a sub-module dependency, language integrations encouraged, compiles without fiddly command line flags ...
   - [ ] Not sure, but we should review this story and make sure it's tight :)
5. **Local Read Scenario:** Right now, simdjson's tests, benchmarks and code are focused on local reads of large json, particularly from disk but also from memory.
   - [ ] Define a few customers or scenarios where this would likely happen, just so we know we have users in this solar system :)
   - [ ] Benchmark configuration reading, perhaps? Lots of config is in JSON, and is sometimes large and sprawled across lots of files.
6. **Client/Server Scenario:** This is where I think we can do the most good, where JSON is used a TON. We should be faster than others at looped parsing of 4K+ requests and responses, and not be appreciably worse at "smallish" scale--say on the order of 128 bytes. I think we *can* ship 1.0 without this, but we'll have much less impact on the world if we do.
   - [ ] Benchmark to find the size at which simdjson gets worse than others (I assume it is and always will be slower than others at parsing the document "0", for example :))
   - [ ] Benchmark parsing JSON in a loop (the server scenario) against other parsers

### Non-Goals

These are things we might want to do or talk about doing, but don't really get in the way of getting major adoption of the library and fixing up a bit of global warming. It can be clarifying and even freeing to list these.

It also shouldn't stop us from doing them :) Open source is about following your passion, after all, not slaving your way to a 1.0 release.

- Other performance enhancements. We're in damn good shape, we should give this thing to people!
- &gt; 4GB file support.
- SAX API. I don't think this blocks 1.0, even if it seems important for a performance-focused library. We do need to be faster than SAX parsers.
- No-validation optimization. There are scenarios where people *know* their JSON is valid. But it's not the client/server case, at least.
- JSON Builder APIs. Other libraries have this, and we should eventually for a number of reasons, but I suspect we'll be attractive to a lot of users even without it.
- JSON Schema
- Parsing into structs
- "Relaxed JSON" (comments, trailing commas)
- Generic SIMD parsing libraries and tools (I super want to do this, but it's certainly not a prereq to a simdjson release!)
- Incremental parsing of large documents, especially from network and disk

Obviously, my opinions are not and shouldn't be taken as canon. What are your thoughts?

**Comment by lemire** [comment]
> Do we actually want to release a JSON library to users, or a performant JSON reader that is used internally by other JSON libraries? (I assume the former, but I don't know that I've ever heard it stated officially.)

Oh. I think both are fine. Don't you?

One use case that you are maybe not considering is non-C++ applications: processing JSON at high speed from R, JavaScript, Python...  BTW this is much harder than it sounds.

> I think we mostly need polish to reach 1.0. Our distinguishing feature (perf) is already solid, sans a little extra benchmarking and maybe large file memory-walk perf.

I agree with this assessment of performance.


>  Increase large file memory-walk performance: even if they aren't direct competitors, the 1.0 release will be noisy if we're 2x worse on a major benchmark

For me, the goal with simdjson is to show what is possible (that's my goal but it is fine if others have different goals). If someone can be 2x faster, then it tells me that we are missing out, so it is time to reflect.


>  Submit to major JSON benchmarking projects, make sure performance measures up

That is a worthy goal, and I think you have put this forward as at least one outstanding distinct issue.

>  doxygen API documentation

Doxygen for the public API, right?

> Non-SIMD fallback so people can be assured their programs will run anywhere, even if they aren't faster on older machines

This could be a bit difficult generally speaking. Take the following loop...

```C
for(int i = 0; i < 100; i++) x+=num[i];
```

If you compile it with GNU GCC (-O3) or LLVM clang (-O2) or visual studio (/Ox) or the Intel compiler, you will find that the autovectorizer does its job *even* if you have not specified any target. That is, it is compiling for a "generic" target but it will still vectorize the input code and generate SIMD instructions. This is true whether you are compiling for 64-bit ARM or x64. 

So you probably don't mean "no SIMD". Right now, we support the latest Xbox, the PS4, the iPhone starting with the iPhone 7, and almost all PCs and servers sold in the last decade.

How far back do you want to go? Because if you need to support older systems, then you are likely to find that people are using something like a 32-bit Windows or embedded systems (e.g., 32-bit ARM/Linux)... People who develop for such platforms are stuck with (or prefer) older compilers... that do not even support C++11... yet we are happily marching toward more and more C++17 features... There is a bit of a dissonance here. I was happy to endorse our use of advanced C++17 features, I see the benefits, but this is pretty much killing the legacy compiler support.

And then you have the difficulty (and cost!) of supporting platforms vastly different from the ones you use. Who is going to be debugging simdjson on a Penryn processor running Windows 95? Who is going to support app development for the iPhone 4? We just won't get CI for this. So even if we do debug it, how are we going to support it on the long term? This, honestly, requires access to legacy systems. You need a farm of old systems. As far I can tell, it is not made available to open source projects and even if it were, it is not going to be cheap (time wise).

>  Handle uneven document sizes for long-lived parsers. Servers care about memory usage, but can't fully predict the size of incoming documents. You can't just bump the parser every time you see a document without de-bumping at some point. As a user, I could use some guidance, or better yet, have simdjson handle these situations for me.

I am not exactly sure what you have in mind. Maybe this could become a separate issue.

> No-Fuss Integration: Super easy to integrate into your project. Single header, package managers (if there are any), use as a sub-module dependency, language integrations encouraged, compiles without fiddly command line flags ...

We have much of that. We are on debian, on vpkg, single-header... We don't really support CMake integration as a dependency as we should (or at least, we run no test in this respect) but there is at least one related issue.

>  Define a few customers or scenarios where this would likely happen, just so we know we have users in this solar system :)

We have...
https://github.com/ClickHouse/ClickHouse

And then we have all of the wrappers (Python, JavaScript, R...).


> Client/Server Scenario: This is where I think we can do the most good, where JSON is used a TON. We should be faster than others at looped parsing of 4K+ requests and responses, and not be appreciably worse at "smallish" scale--say on the order of 128 bytes. I think we can ship 1.0 without this, but we'll have much less impact on the world if we do.  Benchmark to find the size at which simdjson gets worse than others (I assume it is and always will be slower than others at parsing the document "0", for example :))  Benchmark parsing JSON in a loop (the server scenario) against other parsers


We have an issue related to this concern and I agree that it should be for the 1.0 milestone.


> Open source is about following your passion, after all, not slaving your way to a 1.0 release.

I'd put it differently. Sometimes side-quests open the way for the main quest.

> 4GB file support.
> SAX API. I don't think this blocks 1.0, even if it seems important for a performance-focused library. We do need to be faster than SAX parsers.

I view something SAX-like a most for even just release 0.3 because if we can't build a SAX-like parser today, then we have the wrong API/design and we should hold on.

> No-validation optimization. There are scenarios where people know their JSON is valid. But it's not the client/server case, at least.

How much faster would we be if we assumed that the input was valid? You made a case that in some instances, we would be faster without UTF-8 validation, but I don't remember you arguing that we would be 2x faster. For this problem to be interesting, I'd like a ballpark estimate of how much speed gain there might be.

Would you be excited by a 20% boost for an unsafe parser? Would you seriously go to your colleagues and recommend an unsafe parser for production use to save 20% on parsing time? I think that's the kind of discussion we should have.

> JSON Builder APIs. Other libraries have this, and we should eventually for a number of reasons, but I suspect we'll be attractive to a lot of users even without it.

Serialization is important but obviously longer term. 

> JSON Schema

High speed schema validation would be great. That is, validate the JSON without even parsing it.

> Parsing into structs

That's probably easy, relatively speaking. It is mostly about defining the problem.

> Incremental parsing of large documents, especially from network and disk

We kind of do this already (stream json).



> Generic SIMD parsing libraries and tools (I super want to do this, but it's certainly not a prereq to a simdjson release!)

Extending beyond JSON is important but longer term, obviously.

**Comment by jkeiser** [comment]
> > Do we actually want to release a JSON library to users, or a performant JSON reader that is used internally by other JSON libraries? (I assume the former, but I don't know that I've ever heard it stated officially.)
> 
> Oh. I think both are fine. Don't you?

The real question for me is the effort level of marketing and maintaining a well-loved and used open source library with a lot of users. Going the implementor-only route, if it's even possible, means getting the ideas out there, saving the world through proxy, but skipping at least some of that headache.

Knowing myself, I tend to push hard while an idea is taking shape and getting it out the door, but lose interest when I stop learning new things. Neither of us necessarily has to be a long term maintainer personality for simdjson to find a place in the world, but if it turns out neither of us *are*, we're going to at least want to keep an eye out for someone long term ...

I suspect both of us would consider simdjson's purpose fulfilled if other major projects used these algorithms internally and got faster. There's a legitimate question whether we could make that happen instead of trying to get simdjson adopted. It's not as simple a question as it seems: it's very possible that we'd have to get simdjson pretty popular before it got on enough peoples' radar.

> One use case that you are maybe not considering is non-C++ applications: processing JSON at high speed from R, JavaScript, Python... BTW this is much harder than it sounds.

Yeah. Do you think that's a 1.0 use case or post-1.0? Bindings can be easy to write, but terribly hard to make performant, especially when you're trying to expose a complex, highly optimized data structure across languages.

> > Increase large file memory-walk performance: even if they aren't direct competitors, the 1.0 release will be noisy if we're 2x worse on a major benchmark
> 
> For me, the goal with simdjson is to show what is possible (that's my goal but it is fine if others have different goals). If someone can be 2x faster, then it tells me that we are missing out, so it is time to reflect.

Agreed :) Another way to put it: simdjson's performance is *qualitatively* different than other parsers, and shows a major deficiency in how we've thought about parsing up to this point. It is not an attempt to make a better JSON parser, or to tweak and optimize existing JSON parsers. I'd find it uninteresting if it was. honestly :)

> > doxygen API documentation
> 
> Doxygen for the public API, right?

Indeed. Just one of the basics I look for when I decide to use a lib: skim a few examples and then poke around in the object model via documentation a bit. I can do that without API docs, but I start to get antsy that the project isn't serious about users if it doesn't have them.

> > Non-SIMD fallback so people can be assured their programs will run anywhere, even if they aren't faster on older machines
> 
> This could be a bit difficult generally speaking. Take the following loop...
> 
> ```c
> for(int i = 0; i < 100; i++) x+=num[i];
> ```
> 
> If you compile it with GNU GCC (-O3) or LLVM clang (-O2) or visual studio (/Ox) or the Intel compiler, you will find that the autovectorizer does its job _even_ if you have not specified any target. That is, it is compiling for a "generic" target but it will still vectorize the input code and generate SIMD instructions. This is true whether you are compiling for 64-bit ARM or x64.
> 
> So you probably don't mean "no SIMD". Right now, we support the latest Xbox, the PS4, the iPhone starting with the iPhone 7, and almost all PCs and servers sold in the last decade.

Hmm. What version does it vectorize to without a target? It seems like we'd want to make sure we support at least that: "sure, it doesn't run on the Apple IIc, but runs on the same machines as 99% of other programs, which compile without targets" seems like a reasonable answer.

> How far back do you want to go? Because if you need to support older systems, then you are likely to find that people are using something like a 32-bit Windows or embedded systems (e.g., 32-bit ARM/Linux)... People who develop for such platforms are stuck with (or prefer) older compilers... that do not even support C++11... yet we are happily marching toward more and more C++17 features... There is a bit of a dissonance here. I was happy to endorse our use of advanced C++17 features, I see the benefits, but this is pretty much killing the legacy compiler support.

It's really not a goal to run on everything ever. I just think we just need to make sure we run on a comparable set of platforms to the majority of other JSON libraries / other C++ libraries :) If I'm thinking about whether to use simdjson, I'm going to see this advanced "SIMD" and think "if I use this in my project, I'm worried that some users will be able to run it because it feels like it uses super advanced instructions." This worry still sits in the back of my head, even though I've read all the places where we say it runs on machines over a decade old. 

Anything that can convince someone "using this library is not going to make my project unusable for anyone except people like NASA who still run 30-year-old hardware on space shuttles."

> > Handle uneven document sizes for long-lived parsers. Servers care about memory usage, but can't fully predict the size of incoming documents. You can't just bump the parser every time you see a document without de-bumping at some point. As a user, I could use some guidance, or better yet, have simdjson handle these situations for me.
> 
> I am not exactly sure what you have in mind. Maybe this could become a separate issue.

Definitely. I'd just like to use this to feel out what sort of work we all think blocks a 1.0 release, we can break the work out any way we want :)

I just don't know how to predict how much to allocate, and if I'm parsing new documents that come over the network in a loop, I need to either pick a fixed value, or increase the allocated buffer size every time I see a bigger document. I'm worried it'll make memory grow and never go back to normal, and as a user I don't know how to handle that. I'll make an issue.

> > Open source is about following your passion, after all, not slaving your way to a 1.0 release.
> 
> I'd put it differently. Sometimes side-quests open the way for the main quest.
> 
> > 4GB file support.
> > SAX API. I don't think this blocks 1.0, even if it seems important for a performance-focused library. We do need to be faster than SAX parsers.
> 
> I view something SAX-like a most for even just release 0.3 because if we can't build a SAX-like parser today, then we have the wrong API/design and we should hold on.

And this is part of why I am glad we're having this discussion :) I guess I can imagine blocking on SAX in case it changes our DOM API; but I'm a teensy bit skeptical, because the way you look up hash values, iterate arrays, and convert JSON values to C++ values seem pretty universal and divorced from the way parsing happens.

(Unless we're saying SAX should be the *main* parser, and DOM the afterthought. I can dig that. SAX-like parsers are likely to be faster overall since you can ditch old parts of the document.)

At any rate, I think we'll have to do more incremental parsing to accomplish the large file walk anyway, and that's a good basis for a performant SAX interface. So the question of whether to block is probably moot :)

> > No-validation optimization. There are scenarios where people know their JSON is valid. But it's not the client/server case, at least.
> 
> How much faster would we be if we assumed that the input was valid? You made a case that in some instances, we would be faster without UTF-8 validation, but I don't remember you arguing that we would be 2x faster. For this problem to be interesting, I'd like a ballpark estimate of how much speed gain there might be.
> 
> Would you be excited by a 20% boost for an unsafe parser? Would you seriously go to your colleagues and recommend an unsafe parser for production use to save 20% on parsing time? I think that's the kind of discussion we should have.

Probably not for 20%. But I bet a parser truly designed against valid documents could do a lot:
* You can treat commas and colons as whitespace, cutting structural indexes in half
* You can you skip UTF-8 checking entirely
* You can skip brace matching and assume that depth will never go below 0. Plenty of machinery here.
* \u escapes get faster--there's a bunch of little branches in there
* number parsing has a ton of structure that needs validating, and while you can't remove all the branches (optional things are still optional), I bet you can remove a fair number of them.

I could see using it in places where performance was critical and where the computer did *all* the JSON writing (no humans).

> > Parsing into structs
> 
> That's probably easy, relatively speaking. It is mostly about defining the problem.

Yeah, I think so too. I'd still leave it on the cut list in this sense: "if everything else we want is done, and struct parsing isn't, we should release 1.0."

> > Incremental parsing of large documents, especially from network and disk
> 
> We kind of do this already (stream json).

I might be misunderstanding: JsonStream requires all the input up front so it can do stage 1 in a single block, right?

**Comment by jkeiser** [comment]
Funny that it should come up right now, but [this](https://github.com/eddelbuettel/rcppsimdjson/issues/7) is one example where a 64-bit fallback would help. Enough other software is working fine on the test machine in question that it was not immediately obvious simdjson would fail.

**Comment by lemire** [comment]
@jkeiser I think that this is one example where we had a Penryn processor. Penryn procesors lacked POPCNT (starts with Nehalem),  and CLMUL (starts with Westmere).

The CLMUL, we can do without. That is, supporting Nehalem is painless. Just do everything we do for Westmere, but drop the CLMUL bit. It is not too bad.

The POPCNT bit is vexing however because we fundamentally need fast population count. Now, you can emulate it with table lookups or functions... Probably you want to do something like this:


```C++
uint64_t c1 = UINT64_C(0x5555555555555555); uint64_t c2 = UINT64_C(0x3333333333333333); uint64_t c4 = UINT64_C(0x0F0F0F0F0F0F0F0F);
uint64_t count(uint64_t x) {
x -= (x >> 1) & c1;
x = (( x >> 2) & c2) + (x & c2); x=(x +(x>>4))&c4;
x *= UINT64_C(0x0101010101010101); return x >> 56;
}
```

This being thing was replaced by one instruction starting with Nehalem.

It is almost certain that you will end up with code that does not make a lot of sense performance-wise on pre-Nehalem processors. I think you need to rewrite the bitset decoding routine to be entirely old school. So you may need to rewrite a good chunk of the code so that it runs fast on these legacy processors. But next you will have the fun problem that you need such a processor (or a good cycle-accurate emulation) if you are going to tune the code even just a little bit.

A more reasonable point of view would be to support it but not tune it. So let it run slowly... just, somehow, make sure it is correct, maybe by running it via an emulator. This won't work in CI, but someone could be tasked with the job of running commits on an emulator from time to time.

Ok. But supporting Penryn is not the end of the game because people are sure to have even older processors... 

Hint: one can download the Intel emulator for free. I can provide instructions on how to use it if someone is interested.

**Comment by jkeiser** [comment]
> @jkeiser I think that this is one example where we had a Penryn processor. Penryn procesors lacked POPCNT (starts with Nehalem), and CLMUL (starts with Westmere).

Just to be clear, I'm not suggesting we go back and specifically support older processors with SIMD. Your comment here reflects what I'm really after:

> A more reasonable point of view would be to support it but not tune it. So let it run slowly... just, somehow, make sure it is correct, maybe by running it via an emulator.

100% agree. It doesn't have to be the fastest, it doesn't even have to be SIMD: it just has to parse JSON so the program won't fail. The implementation I imagine would literally walk the code character by character like a traditional parser. Pretty easy to do with JSON.

**Comment by jkeiser** [comment]
It would almost certainly be worse than other parsers in terms of performance, too, because the naive implementation I have in mind would still be split up into stage 1 and stage 2, and I'm relatively sure a character by character walk will be faster in one pass.

**Comment by lemire** [comment]
Answers to points above:

* Almost all x64 binaries rely on SIMD instructions. One simple reason for this is that 128-bit SSE registers are part of what defines x64. For fun, try to compile code while asking the compiler not to use SSE instructions (something like -mno-sse). It is likely that you can barely compile anything at all.

* The simdjson library is already wrapped and usable in many other programming languages. Yes, it is a challenge to make it run fast. I am not sure it needs to be tied to a specific milestone for simdjson, but it does dictate some of our concerns. To put it differently, there is no need for simdjson to *solve* this problem, I think that it can be outsourced downstream, but we need to be careful and supportive.



> I might be misunderstanding: JsonStream requires all the input up front so it can do stage 1 in a single block, right?

It does stage 1 over small chunks. It does not care whether all of the memory is in RAM. Remember that our systems rely on virtual memory.

**Comment by jkeiser** [comment]
> Almost all x64 binaries rely on SIMD instructions. One simple reason for this is that 128-bit SSE registers are part of what defines x64. For fun, try to compile code while asking the compiler not to use SSE instructions (something like -mno-sse). It is likely that you can barely compile anything at all.

Yep, I understand :) And Penryn has them too. So if we can make the statement "simdjson runs on any 64-bit machine that g++ targets by default" then it's a pretty simple rubrick for people. Right now we run on a subset of that and it can cause unexpected mismatches like this.

I'm not at all *opposed* to making it run fast on Penryn / use SIMD. I just don't think it matters.

> The simdjson library is already wrapped and usable in many other programming languages. Yes, it is a challenge to make it run fast. I am not sure it needs to be tied to a specific milestone for simdjson, but it does dictate some of our concerns. To put it differently, there is no need for simdjson to solve this problem, I think that it can be outsourced downstream, but we need to be careful and supportive.

I think we're on the same page here :)

> It does stage 1 over small chunks. It does not care whether all of the memory is in RAM. Remember that our systems rely on virtual memory.

Oh, [I see](https://github.com/lemire/simdjson/blob/master/include/simdjson/jsonstream.h#L343).

**Comment by lemire** [comment]
Windows 10 probably does not run on Sandy Bridge or older processors... at least, it did not at launch. (We support some of these processors.)


https://www.intel.com/content/www/us/en/support/articles/000006105/processors.html


Windows 10 will simply not run on an Intel processor without SSE2.

**Comment by jkeiser** [comment]
Yeah, it looks like sse2 is the minimum: what I'm reading indicates that all x64 instruction sets include this. Or at least that when you compile using g++ by default, it targets the "base instruction set" x86-64, which includes sse2.

That seems like a pretty reasonable minimum to me.

I still don't feel much necessity to optimize for it, but at least we kind of know what it is.

**Comment by jkeiser** [comment]
So I'm super interested in a lot of the work here, but as I have a lot of experience in API user experience, I'm probably going to focus on that. I've made an [API milestone](https://github.com/lemire/simdjson/milestone/5) that covers what I think needs to be done for existing functionality. @lemire this particularly means I'll have my grubby fingers out of the parser internals for a while, I suspect :)

Apart from API, from what I can see, the most important next steps are fixing the perceived perf problems in page walking (and maybe floats?), maybe SAX, and benchmarking benchmarking benchmarking so we know we're where we think we are.

**Comment by lemire** [comment]
@jkeiser How do we handle SAX or SAX-like parsing? Do you consider that "API" or "internals"? Honestly, it could go into both camps.

**Comment by jkeiser** [comment]
> How do we handle SAX or SAX-like parsing? Do you consider that "API" or "internals"? Honestly, it could go into both camps.

SAX will definitely have an API :) The API milestone work I'm talking about is deliberately scoped to current features. I think we should shore up the existing API till we're happy with it, so we can take those lessons when we're making SAX.

I consider it a new feature, and if we had a bunch of different things to do with it, I'd make it a milestone and fill it with issues / PRs (that seems roughly to be how milestones are used, along with versions).

**Comment by lemire** [comment]
Looks like I will be working on number parsing next. I think that @michaeleisel has been getting impatient. :-)

**Comment by jkeiser** [comment]
Even the linked benchmark checks floating point accuracy, so it's probably a good use of time (and supporting a contributor is a good use of time even if it's not a release-critical issue, so 👍 ).

**Comment by michaeleisel** [comment]
Haha I’m fine, just wanted to agree on a direction forwards. But very glad to hear you’re on it!

**Comment by lemire** [comment]
[I have laid out a project for 1.0](https://github.com/simdjson/simdjson/projects/6).

**Comment by lemire** [comment]
This was a great issue. I think 1.0 will be out soon, let me review @jkeiser 's points...


> Insanely Fast

Yep. We are going to ship 1.0 with On Demand as the default. It should do better over large files. We are doing well on external benchmarks.

 
 >  doxygen API documentation

Yep.

>  Simpler navigation APIs

The API has been refined.

> No Sharp Edges: The library needs to not have big gotchas that hurt you down the line.

Yes. We are good.

> Non-SIMD fallback so people can be assured their programs will run anywhere, even if they aren't faster on older machines

Yes.

>  Handle uneven document sizes for long-lived parsers. Servers care about memory usage, but can't fully predict the size of incoming documents. You can't just bump the parser every time you see a document without de-bumping at some point. As a user, I could use some guidance, or better yet, have simdjson handle these situations for me.

This is documented.

> No-Fuss Integration: Super easy to integrate into your project. Single header, package managers (if there are any), use as a sub-module dependency, language integrations encouraged, compiles without fiddly command line flags ...

I think we nailed that.

> Local Read Scenario: Right now, simdjson's tests, benchmarks and code are focused on local reads of large json, particularly from disk but also from memory.  Define a few customers or scenarios where this would likely happen, just so we know we have users in this solar system :)

We have been lucky in that we have received a lot of feedback from users. We could always receive more, of course.

>  Benchmark configuration reading, perhaps? Lots of config is in JSON, and is sometimes large and sprawled across lots of files.

This was not explored further.

> Client/Server Scenario: This is where I think we can do the most good, where JSON is used a TON. We should be faster than others at looped parsing of 4K+ requests and responses, and not be appreciably worse at "smallish" scale--say on the order of 128 bytes. I think we can ship 1.0 without this, but we'll have much less impact on the world if we do.

This was not benchmarked specifically.

>  Benchmark to find the size at which simdjson gets worse than others (I assume it is and always will be slower than others at parsing the document "0", for example :))

We have found that simdjson scales well (to both small and large sizes).

>  Benchmark parsing JSON in a loop (the server scenario) against other parsers

We have not done this, but we have a ton of benchmarks.
