### ISSUE TITLE
Deprecate document_iterator

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#519]
Followon to #510. document_iterator works great and is fast, and I couldn't have written the new iterators without that pioneering work. But I think it should be deprecated: the new iterators are easier and at least as fast, and we shouldn't provide 2 APIs for the same use cases.

**Comment by lemire** [comment]
Agreed.

**Comment by jkeiser** [comment]
Actually, document_iterator is really ParsedJsonIterator; we renamed it after 0.2. We should name it back, removing document_iterator entirely, and deprecate ParsedJsonIterator. No sense introducing and deprecating something in the same release :)

**Comment by jkeiser** [comment]
document::iterator needs to go, too.

**Comment by jkeiser** [comment]
@lemire as far as I can tell, we never released ParsedJsonIterator. We did have [ParsedJson::Iterator](https://github.com/simdjson/simdjson/blob/v0.2.1/include/simdjson/parsedjson.h#L105), so I'll put document_iterator there. So `ParsedJsonIterator`, `document_iterator` and `document::iterator` shall be excised as names from the codebase, and `ParsedJson::Iterator` only will be used.
