### ISSUE TITLE
Generalize the simdjson::JsonStream parser to handle inputs that are long arrays

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#525]
Currently, if you have line separated JSON inputs, you can use simdjson::JsonStream to parse nearly infinite inputs in a multithreaded way. However, if you just add a starting '[' and a final ']' and separate the JSON documents by commas, you no longer can  call simdjson::JsonStream since it is considered "one JSON document".

This would help solve https://github.com/lemire/simdjson/issues/128

cc @jkeiser @spansh

**Comment by jkeiser** [comment]
Do you think this is the same problem as being able to stop after *any* comma? Or do you think there will be a solution that works better for just a top level array, or just for arrays but not objects?

**Comment by lemire** [comment]
There is no need to stop at the commas actually. You can parse an entire window (though hopefully not the whole file) and then iterate through what you parse... this is post-stage 2, not within stage 2. Though it requires a special stage 2, of course.

**Comment by jkeiser** [comment]
Yeah, I'd love it if we could stop literally anywhere, that would be generic incremental parsing and totally solve a *lot* of problems with memory, large files, etc. etc.

That does require us to remember what state we were in when we stopped parsing (particularly which goto state we were in), and stage 2 seems to melt down every time we touch the goto arrangement. I'm really hoping we can beat that this time!

**Comment by jkeiser** [comment]
ondemand covers this.

**Comment by jkeiser** [comment]
See #947.

**Comment by lemire** [comment]
It does indeed get solved!

**Comment by spansh** [comment]
This looks great, I have some relatively small programs which parse the files from https://spansh.co.uk/dumps (my own stuff has evolved since we mentioned this last).  I'll see about converting one of the smaller ones to this and see how much cleaner the code is, I strongly suspect that it will end up drastically simpler than my current SAX based rapidjson code.

**Comment by jkeiser** [comment]
Let me know how it goes! Let us know if you see any bugs or anything that doesn't work the way you expected it to. It's a work in progress :)

**Comment by jkeiser** [comment]
(By work in progress, I don't mean the API is in major flux, just that I'm still worried there are lurking bugs somewhere underneath as I write more and more tests. It is probably going to work for your scenario, though :)
