### ISSUE TITLE
Test  the document stream parser for the case where the last document ends with an open quote

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#535]
@jkeiser expressed concern that we may have a bug with the specific scenario where we have a stream of JSON documents, all valid, except that the last one is incomplete, and maybe ends with an open quote. I do not think we have tests specific to this scenario.

**Comment by lemire** [comment]
I am going to close this.

**Comment by jkeiser** [comment]
Is it possible I already fixed it? I know I did a bunch of stuff with empty documents and thought about incompleteness a lot.

**Comment by jkeiser** [comment]
Oh, I think I probably did. The last stage 1 call sets partial = false, meaning the parser will check for unclosed quotes and the like.
