### ISSUE TITLE
Rename error_code to something that doesn't conflict with std

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#542]
Right now, if you do:

```c++
using std;
using simdjson;
...
error_code error;
```

You get a compile error because `error_code` is ambiguous. We should not conflict with `std` for names the user might type; no need to create friction where it doesn't need to exist. We're in the clear here, because `error_code` was introduced after 0.2 as part of the move to snake_case; we can freely change this name anytime before we release 0.3.

Suggestions for a replacement name are welcome! @lemire @DBJDBJ thoughts? Prior art?

**Comment by lemire** [comment]
I try to avoid doing "using <namespace>" to avoid precisely these problems.

You have std::vector but it is not reasonable to assume that nobody else is allowed to call a class "vector", right?

**Comment by jkeiser** [comment]
> I try to avoid doing "using " to avoid precisely these problems.

I guess if it's standard practice not to do `using` in C++, then I wouldn't worry so much ... but this sort of sounds like "I make life harder for myself to avoid ambiguity problems caused by other people who weren't thinking about my well-being" :)

> You have std::vector but it is not reasonable to assume that nobody else is allowed to call a class "vector", right?

I would think twice before making a public `vector` class, yes. It's not verboten, but it's a tax on users that do it. You should have a clear reason why users are unlikely to use both at the same time, or why it's *so* important your class be called `vector` that it's worth the headache..

Not a C++ guy, I just don't like making problems for my users :)

**Comment by lemire** [comment]
Ok. I will take this with twitter and see what folks say.

**Comment by lemire** [comment]
> I would think twice before making a public vector class, yes. 

So you would call it "simdjson_vector" then? :-)

**Comment by lemire** [comment]
Josh Simmons (@dotstdy on twitter) writes "people should never be using `using std` it's bad". That is my sentiment as well.

**Comment by lemire** [comment]
Paul Crowley (@ciphergoth on twitter) writes "Does
```
using std;
using simdjson;
using std::error_code;
```
work?

In any case, you shouldn't rename. This is what namespaces are for in the first place."

**Comment by lemire** [comment]
Kiru (@kiru_io on twitter) writes "Generally not, but I try to avoid using standard library class names as well. 
If I read `vector<int> x` in the code I expect `vector` to be from std (not an own implementation). Same could be said about error_code."

**Comment by jkeiser** [comment]
Let's capture some user experience with 0.3. Leaving this open for the moment.

**Comment by jkeiser** [comment]
I haven't heard any issues, and there are ways to disambiguate, so I'm going to say we should leave it as is. I don't think there is a good alternative at hand and I don't want to make people change all their code just for this.

Closing because I'm quite sure @lemire agrees we shouldn't change it; please reopen if I'm wrong about that :)

**Comment by lemire** [comment]
You can always do
```C++
using myerror = simdjson::error_code
```
