### ISSUE TITLE
Consider managing simdjson with an organization

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#552]
I'm not sure what other benefits it gives, but creating an organization lets you have multiple owners who can manipulate its settings, which would sometimes be nice :)

https://github.com/account/organizations/new?coupon=&plan=team_free

**Comment by lemire** [comment]
Agreed.

**Comment by lemire** [comment]
I tried to create a "simdjson" organization and it won't let me.

So I think we need to discuss the name.

**Comment by lemire** [comment]
(Note: we also need a web site/domain name.)

**Comment by jkeiser** [comment]
Yeah, I don't understand what's up with the simdjson name. https://github.com/simdjson doesn't yield anything, so what precisely is going on there?

**Comment by lemire** [comment]
We could go for simdjsonorg. 

Note that I want us to choose carefully because whatever we pick is probably going to stick for a long time.

**Comment by jkeiser** [comment]
Yeah. I'd really like to find out why simdjson is taken. It seems likely it is automatically reserved to keep it from being squatted. It seems very unlikely it was taken for some other purpose.

**Comment by jkeiser** [comment]
This seems like it directs towards the right place, though it's for usernames: https://help.github.com/en/github/site-policy/github-username-policy

**Comment by jkeiser** [comment]
Usernames and organizations share the same namespace, so it's probably the same policy.

**Comment by jkeiser** [comment]
I'll bet someone here did it, to reserve the name: https://api.github.com/orgs/simdjson

```json
{
  "login": "simdjson",
  "id": 49667887,
  "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ5NjY3ODg3",
  "url": "https://api.github.com/orgs/simdjson",
  "repos_url": "https://api.github.com/orgs/simdjson/repos",
  "events_url": "https://api.github.com/orgs/simdjson/events",
  "hooks_url": "https://api.github.com/orgs/simdjson/hooks",
  "issues_url": "https://api.github.com/orgs/simdjson/issues",
  "members_url": "https://api.github.com/orgs/simdjson/members{/member}",
  "public_members_url": "https://api.github.com/orgs/simdjson/public_members{/member}",
  "avatar_url": "https://avatars0.githubusercontent.com/u/49667887?v=4",
  "description": null,
  "is_verified": false,
  "has_organization_projects": true,
  "has_repository_projects": true,
  "public_repos": 0,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "html_url": "https://github.com/simdjson",
  "created_at": "2019-04-16T03:40:12Z",
  "updated_at": "2019-08-30T17:05:51Z",
  "type": "Organization"
```

**Comment by jkeiser** [comment]
An [issue search](https://github.com/lemire/simdjson/issues?q=organization) doesn't turn up any do-gooders, though :)

**Comment by jkeiser** [comment]
If there were any emails to you, they'd likely be around last April, when it was created. I bet we can ask to get this transferred regardless.

**Comment by jkeiser** [comment]
OK @lemire, Github says to [contact user support](https://support.github.com/contact) under their Name Squatting Policy (from a Github support person [a few months ago](https://github.community/t5/How-to-use-Git-and-GitHub/Can-I-claim-a-username-for-an-organization/td-p/33203)). Unless it's all private, I don't think the organization even has any repositories, members or owners right now, which would make it trivial to transfer.

I'd do this, but I think it's best coming from you as the primary repository owner. It's worth a shot, and it's not like we're under time pressure here.

**Comment by lemire** [comment]
<img width="1313" alt="Screen Shot 2020-03-16 at 2 30 24 PM" src="https://user-images.githubusercontent.com/391987/76789192-b521d180-6792-11ea-9f4a-121ee8c70a62.png">

**Comment by lemire** [comment]
@jkeiser I did as you suggested.

Note that whoever might be "squatting" has not been going after corresponding domain names.  There is still a whole lot of good domain names with "simdjson" in the name.

It is not unconceivable that someone might have simply protected the project by setting aside the name.

**Comment by lemire** [comment]
(There is no obvious route from "squat simdjson" to "profit".)

**Comment by jkeiser** [comment]
> It is not unconceivable that someone might have simply protected the project by setting aside the name.

Agreed, I can't imagine another scenario.

**Comment by lemire** [comment]
I'll post an update here the minute I hear back from GitHub.

**Comment by lemire** [comment]
GitHub is on it. I am hopeful that it should get fixed soon.

**Comment by lemire** [comment]
Done: https://github.com/simdjson

Note that migrating will involve updating the documentation slightly and various links will need to be changed.

**Comment by lemire** [comment]
Solved. Closing.
