### ISSUE TITLE
Segfault with parse_many on some platforms

### ISSUE THREAD

**Issue by bill-bateman** [simdjson/simdjson#570]
Hey - I've been investigating using simdjson with ndjson files and ran into the following problem on latest master.

Using the parse_many approach on Linux I get a segfault when trying to get the second document (i.e. second line), but on Mac it works just fine. The JsonStream approach works in both cases.

I traced the segfault to advance_char function in structural_iterator. When it calls current() to access buf, the data that buf points to is not accessible. After that I wasn't sure where to look.

Obviously it's not the biggest problem, as I just switched over to the JsonStream, but figured I'd make an issue so it's known.

More info about setups used:

Mac (laptop):
10.15.3 Catalina
Quad-Core Intel Core i7

Linux (AWS EC2 instance c5d.2xlarge):
Ubuntu 18.04
Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz

Build / run with:
```
$ c++ -O3 -std=c++17 -pthread -o ndjson_demo ndjson_demo.cpp
$ ./ndjson_demo ../jsonexamples/amazon_cellphones.ndjson -1
should segfault
Segmentation fault (core dumped)
$ ./ndjson_demo ../jsonexamples/amazon_cellphones.ndjson -2
should be fine
```

Code:
```
//ndson_demo.cpp
#include <iostream>
#include "simdjson.h"
#include "simdjson.cpp"

int parse_file(const char *filename) {
  simdjson::document::parser parser;
  std::cout << "should segfault" << std::endl;
  for (const document &doc : parser.load_many(filename)) {
    auto iter = simdjson::document::iterator(doc);
    //do something
  }
  return EXIT_SUCCESS;
}

int parse_file_2(const char *filename) {
  std::cout << "should be fine" << std::endl;
  simdjson::padded_string p2 = simdjson::get_corpus( filename );
  simdjson::document::parser parser;
  simdjson::JsonStream js{p2};
  int parse_res = simdjson::SUCCESS_AND_HAS_MORE;

  while (parse_res == simdjson::SUCCESS_AND_HAS_MORE) {
    parse_res = js.json_parse(parser);
    auto iter = simdjson::document::iterator(parser);
    //do something
  }
  return EXIT_SUCCESS;
}

int main(int argc, char *argv[]) {
  if (strcmp(argv[2],"-1")==0) return parse_file(argv[1]);
  if (strcmp(argv[2],"-2")==0) return parse_file_2(argv[1]);
}
```

**Comment by lemire** [comment]
@jkeiser ?

**Comment by lemire** [comment]
Verified : https://github.com/simdjson/simdjson/pull/574

**Comment by jkeiser** [comment]
@bill-bateman there is indeed a bug. Looking at that now. It is freeing the loaded document before it finishes parsing. The workaround is to load the json file into a variable (sorry about that):

```c++
int parse_file(const char *filename) {
  simdjson::document::parser parser;
  simdjson::padded_string json = simdjson::padded_string::load(filename);
  std::cout << "should not segfault" << std::endl;
  for (const document &doc : parser.parse_many(json)) {
    auto iter = simdjson::document::iterator(doc);
    //do something
  }
  return EXIT_SUCCESS;
}
```

**Comment by jkeiser** [comment]
@bill-bateman this should be fixed in master. Can you give it another try? Please absolutely reopen if it's not fixed for you.

**Comment by bill-bateman** [comment]
Verified fixed! Thank you!
