### ISSUE TITLE
README should be updated with navigation API

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#576]
The new document navigation API is super nice and it is illustrated in basictests, but instead we promote something ugly in the README.

cc @jkeiser

**Comment by lemire** [comment]
This would be at least somewhat addressed with https://github.com/simdjson/simdjson/pull/575

**Comment by jkeiser** [comment]
Yes, this is a prereq for any release we do.

**Comment by lemire** [comment]
Added to 0.3 milestone...

**Comment by jkeiser** [comment]
Fixed with #609.
