### ISSUE TITLE
Post-linking optimization

### ISSUE THREAD

**Issue by michaeleisel** [simdjson/simdjson#586]
With Bolt and the recently-released https://github.com/google/llvm-propeller as options, I was curious if one of them was being used for simdjson. If not, it might be helpful: google reported 2-6% improvements for some benchmarks by using this sort of optimization

**Comment by lemire** [comment]
It is an optimization applied to the binaries. We currently do not release binaries (DLL or .so/.a files). We also cannot assume that our users will do profile-guided optimization... we need the code to be fast as-is.

Now, we could provide guidance to our users if we had data as to how profile-guided optimization can help them. I think that this should be done, but it is not something that the core library needs to worry about.

**Comment by michaeleisel** [comment]
Makes sense

**Comment by michaeleisel** [comment]
It could also possibly be helpful to do PGO for a few common cases, eg long strings, mix of data, and lots of floats. But maybe the people who care about 2-6% are quite comfortable doing PGO themselves

**Comment by jkeiser** [comment]
I would love it if there was a way for users to gather pgo data for their use cases and send them to us ...

**Comment by lemire** [comment]
This has been open for many months with no progress. I do not think we need to track this. It is a good idea, and someone should do it, but it is not a must have for the library. Closing.
