### ISSUE TITLE
Publish website for 0.3

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#588]
We need a website (github pages will be fine). It should contain, at a minimum:

* A link to our latest release, changelog, repository, and overview/tutorial. (Link to README satisfies this at a minimum.)
* A link to the 0.3 version of the generated API docs

**Comment by jkeiser** [comment]
This is all that's left. `make api/docs` works now and even link to the readme; it's a matter of putting the html files up and accessible, I think. Very bare minimum fulfillment of this issue, but that's kind of what minimum viable is about :)

Then we get to announce!

**Comment by lemire** [comment]
Closing. See https://simdjson.org

The API is there.
