### ISSUE TITLE
0.3 release notes

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#589]
We need 0.3 release notes, highlighting the changes since 0.2. It should also contain, or link to, release notes for 0.2/0.1 so that people have an overview of what already exists.

Major highlights:
- [ ] Multi-Document Parsing: read many JSON documents at once!
- [ ] Simplified API: Intuitive parsing, DOM navigation, and error handling. Link to deprecation info/backcompat.
- [ ] Performance: 15-20% improvement over 0.2
- [ ] Exact float parsing without compromising speed
- [ ] JSON Pointer

Minor highlights:
- [ ] Fallback implementation: runs anywhere it compiles
- [ ] Runtime selection API gives flexibility and control
- [ ] "string"_pad - minor because it helps testing but isn't super necessary for anything else. Worth highlighting because people should be using padded strings :)

Anything else?

**Comment by lemire** [comment]
> Runtime architecture detection and implementation selection 

Yes, this was in 0.2. In fact, it was the defining feature of release 0.2. Prior to that, simdjson only worked on AVX-capable hardware (when running on x64).

>  JsonStream

This will be new. In fact, it is a big new feature. It is pretty unique. Note that it is threaded (multicore) which is a bit neat in itself.

> Testing: fuzz testing

Release 0.2 had undergone fuzz testing, so that's no new.

https://github.com/simdjson/simdjson/issues/150

What is new since then is the CI version of fuzz testing. So it is more systematic thanks to @pauldreik 


> Simplified API: Intuitive parsing, DOM navigation, and error handling.

Want to include automatic memory allocation?

**Comment by jkeiser** [comment]
> > Runtime architecture detection and implementation selection

> Yes, this was in 0.2. In fact, it was the defining feature of release 0.2. Prior to that, simdjson only worked on AVX-capable hardware (when running on x64).

OK :) The architecture selection API is probably below the top line, it's kinda niche. There's a lot of stuff in this release!

> This will be new. In fact, it is a big new feature. It is pretty unique. Note that it is threaded (multicore) which is a bit neat in itself.

Oh! That sounds like it might be at the top of the top line features, then. That, plus the simplified API, are probably the juiciest things for people.

> Release 0.2 had undergone fuzz testing, so that's no new.

Hmm, probably below the top line features then. The main reason people would want to know about this, IMO, is that they have a deeper guarantee that simdjson will be reliable and correct in all situations. It's certainly a top line feature of simdjson itself, just not this release :)

> Want to include automatic memory allocation?

I hemmed and hawed about whether that was a major feature by itself, or whether its primary purpose was to make the API simpler by requiring less setup :) I was thinking about adding it in Minor Highlights rather than as a top line "marketing" feature, but I could see it in either place.

**Comment by jkeiser** [comment]
Oh also, I think this means we can / should remove JsonStream as a class entirely before we release. No reason to introduce something and deprecate it in the same release ...

**Comment by lemire** [comment]
> Oh also, I think this means we can / should remove JsonStream as a class entirely before we release. No reason to introduce something and deprecate it in the same release ...

It was never released, you are correct. Though we have had some early adopters... they worked from something that was not officially released.

**Comment by jkeiser** [comment]
> It was never released, you are correct. Though we have had some early adopters... they worked from something that was not officially released.

Hmm. The interface is subtly different so they can't just change the name; but I think it's close enough to the original that they can use it. If you have pointers to anyone who's been using it (an issue, or email, or whatever), let me know :) We can decide whether to add-and-deprecate, or not-include, from there.

**Comment by lemire** [comment]
@jkeiser I think we can safely "not release" the non-released API.

**Comment by lemire** [comment]
I think this has been done, right?

**Comment by jkeiser** [comment]
Yep!
