### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#590]
Will try to make a checklist:

- [x] Resolve remaining [0.3 issues/PRs](https://github.com/simdjson/simdjson/milestone/1).
- [x] Produce the release artifact(s).
- [ ] Post a release announcement in ... wherever one posts release announcements

**Comment by lemire** [comment]
I verified that the release script is still functional. On a machine with Python, one only needs to do...

```
cd tools
./release.py 0.3.0
```

Everything should get automatically updated: running the scripts provides the final instructions.

I thought that, at some point, we made a change that I expected would break the release script, but it seems that I was wrong.

So we are good to go on this front.

**Comment by lemire** [comment]
JSON Pointer could be promoted a bit...

```
bool document_iterator<max_depth>::move_to(const char *pointer,
                                                   uint32_t length) 
```

https://github.com/simdjson/simdjson/blob/master/include/simdjson/inline/document_iterator.h#L322

**Comment by jkeiser** [comment]
With the PRs currently in queue, I think we've got all desired code changes and API fixups ready. Release notes and publishing the docs somewhere is all that's left!

**Comment by lemire** [comment]
How do see the release of these "release notes"? It is possible to have them as part of the commit entry. I think you have something else in mind?

**Comment by jkeiser** [comment]
> How do see the release of these "release notes"? It is possible to have them as part of the commit entry. I think you have something else in mind?

Probably a RELEASES.md or an announcement somewhere, with the list of highlights from [the release notes issue](https://github.com/simdjson/simdjson/issues/589), and a little embellishment?

Basically, a lot of projects will summarize and publish the highlights and features since the last release, since the commit history is usually really hard. It's a way of generating excitement and helping people decide whether to bother upgrading. [Here's Rust's release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1420-2020-03-12) and [here is their release announcement](https://blog.rust-lang.org/2020/03/12/Rust-1.42.html). I don't think we need to make two things or categorize it or anything, they are a huge project, but that's the rough level I was thinking about.

**Comment by jkeiser** [comment]
Oh, and by publish the docs I mean run doxygen and publish the API docs :)

**Comment by lemire** [comment]
I could probably create a minimalist web site for the occasion... any insight on the best name for a domain regarding this project?

https://www.namecheap.com/domains/registration/results/?domain=simdjson

**Comment by jkeiser** [comment]
simdjson.org is probably best, that's what most open source projects typically take.

**Comment by lemire** [comment]
@jkeiser We have simdjson.org

There won't be any content there for now, but there can be. I'll also be able to give you access if you have any interest for web hacking.

**Comment by lemire** [comment]
Ok. The site is up with minimal content.

**Comment by jkeiser** [comment]
BAM!

**Comment by lemire** [comment]
Blog post at https://lemire.me/blog/2020/03/31/we-released-simdjson-0-3-the-fastest-json-parser-in-the-world-is-even-better/


@jkeiser  please note the final sentence of the blog post:

> Credit: many people contributed to simdjson, but John Keiser played a substantial role worthy of mention.

If anything, this was a bit too weak... but there you go.
