### ISSUE TITLE
Remove backslashes from JSON pointer implementation

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#604]
Backslashes aren't part of the JSON pointer spec, but [we support them ](https://github.com/simdjson/simdjson/blob/master/include/simdjson/inline/document_iterator.h#L435-L443). I ported the implementation over to the DOM API with backslashes, just in case.

I suspect we did it because of [section 5](https://tools.ietf.org/html/rfc6901#section-5) of the spec. I think that's a misreading though. A [JSON pointer](https://tools.ietf.org/html/rfc6901#section-3) is a Unicode string with ~ and / as special characters, it doesn't say anything about backslashes. Section 5 is just talking about the fact that when you store a JSON pointer in a JSON document, you have to escape some characters.

I think the right thing is to remove backslash support. `iter.move_to("a\\b.txt")` and `doc["a\\b.txt"]` should look up the object field with key `a\b.txt`, but right now it will error out as an invalid JSON pointer (because \b is not a valid escape sequence).

@ioioioio @lemire do you read it the same way?

**Comment by lemire** [comment]
I agree.

**Comment by ioioioio** [comment]
Makes more sense than these horrible escaped escaping characters I had in my tests back then.
https://github.com/simdjson/simdjson/blob/bcabdfc1ae02c8ac031a58a38d3928893fe43cc0/tests/pointercheck.cpp#L8

**Comment by lemire** [comment]
@ioioioio  You worked too hard... :-)
