### ISSUE TITLE
Decide whether to enable URI fragment representation in JSON pointer

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#605]
JSON pointer defines a URI fragment representation, for times when you are encoding JSON pointers in URI fragments. It's not really a JSON pointer thing, though, it's sort of a warning: "hey, if you are putting a JSON pointer in a URI fragment, you are going to have URL encode some characters, because that's how URI fragments work." It doesn't define anything special to JSON pointer, as far as I can tell. It's a little weird they put it either of those sections in at all.

[RapidJSON supports this directly](https://rapidjson.org/md_doc_pointer.html#URIFragment): if I am reading it right, if it finds a `#` at the beginning of the JSON pointer, it treats it as a URL encoded JSON pointer and decodes it.

We have [code in document_iterator to support this](https://github.com/simdjson/simdjson/blob/master/include/simdjson/inline/document_iterator.h#L325-L356) partly for this reason; but it also looked wrong to me: it looks for `%xDD` where x is a literal "x" and D is a hex digit. URL encoding is straight`%DD`.

I think we shouldn't support this directly; most people using URI fragments are already going to be using web frameworks with decoding methods, they should just use those and pass the decoded string. Our JSON pointer implementation should be just that--JSON pointer.

Opinions? @ioioioio?

**Comment by lemire** [comment]
> I think we shouldn't support this directly; most people using URI fragments are already going to be using web frameworks with decoding methods, they should just use those and pass the decoded string. Our JSON pointer implementation should be just that--JSON pointer.

Agreed.

**Comment by jkeiser** [comment]
I'm calling it closed for now, but @ioioioio if you can recall the reasons for it, please feel empowered to reopen it :)
