### ISSUE TITLE
Allow element casting in `tie()` syntax

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#606]
I noticed I had to write this:

```c++
uint64_t year;
car["year"].as_uint64_t().tie(year, error);
```

I see no reason as_uint64_t() needs to be there, the intent is clear. Instead, it should attempt to cast and put INCORRECT_TYPE in error if there is a problem:

```c++
uint64_t year;
car["year"].tie(year, error);
```

**Comment by lemire** [comment]
That sounds very nice indeed.

**Comment by jkeiser** [comment]
I think this is worth dropping into 0.3, but it's also not *necessary*. It's purely additive, and it comes with some risk of taking the API too far into the unknown, but it's not *way* out there.

I actually wonder if it's possible to support it the other way 'round, with `template<typename T> operator std::pair<T, error_code>() { }`, so you can std::tie(a, b) = ... as well. None of this will be easy until we switch from `as_X` to a templatized `get()`, though.

**Comment by jkeiser** [comment]
The more I think, the more I think we should leave it alone. Let's leave auto-casting and generics (besides get()) for later, and see how things shape up with the current code. Moving to 0.4.

**Comment by lemire** [comment]
I do not think that...

```
car["year"].as_uint64_t().tie(year, error);
```

is bad. It is quite readable. And, of course, you still can do

```
auto [year, error] = car["year"].as_uint64_t();
```

**Comment by lemire** [comment]
@jkeiser Do we want to put it in 0.4 or do we delay?

**Comment by jkeiser** [comment]
@lemire Let's see how much time ends up in my timebox. This one seems like a less important one, but it might be easy enough that it's worth just getting done..

**Comment by lemire** [comment]
I think that this is solved. Reopened if not.

**Comment by jkeiser** [comment]
Yep, it is done.
