### ISSUE TITLE
Return root element directly from parser.parse()

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#626]
## Proposal

Make parser.parse() return elements, and make element the containing name of the DOM abstraction.

Instead of:

```c++
document::parser parser;
document doc = parser.parse(json);
document::element root = doc.root();
```

We use:

```c++
element::parser parser;
element root = parser.parse(json);
```

Possibly dom::parser, but I think people will type "element" more often, so it's the main abstraction.

## Explanation

Now that document::parse() is gone, there is much less need to refer to a `document` object. Users' primary interaction is always going to be with *references* such as document::element. parser.parse() may as well return that directly instead of making you pointlessly call `.root()` on the document you get back.

This will decrease the initial API surface you encounter by a large percentage (from 3 concepts to 2): you won't have to encounter documents until later in your life when you want to take ownership of the DOM from the parser.

Since you wouldn't be storing a "document" generally, that would imply the primary interaction will be with `element`, and that's what we should name the top level:

```c++
element::parser parser;
element root = parser.parse();
```

As a barely-related afterthought, I think we should add a <T> to parser.parse(), since most of the time people want a specific type can start using it immediately:

```c++
for (element child : parser.parse<element::array>()) {
  ///
}
```

**Comment by jkeiser** [comment]
This didn't really become clear to me until we removed some deprecated stuff :)

**Comment by lemire** [comment]
Sounds reasonable.

**Comment by jkeiser** [comment]
Fixed by the linked PRs.
