### ISSUE TITLE
Use const char * everywhere

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#636]
Is there a reason we use uint8_t * everywhere? I'm assuming it's historical. I can understand how it would make certain UTF-8 queries easier, but the mismatch causes us a lot of casting fuss and almost everyone in C++ uses const char * (as do the default string/string_view classes). IMO we should use const char * everywhere.

**Comment by lemire** [comment]
@jkeiser 

The "char" type is somewhat under-defined. Is it signed or unsigned?

Furthermore, char * can alias for anything whereas, in principle, uint8_t does not.

The latter seems mostly to be a theoretical consideration (there are instances where, reportedly, clang will optimize something when the type is uint8_t but not what it is a char, but I have not verified it for myself), but the former is a real problem. And it is worse than that, "char", "signed char" and "unsigned char" can be mutually distinct!  I am not making this up!

https://stackoverflow.com/questions/436513/char-signed-char-char-unsigned-char

So if you do...

```
char x = ...

if( x < 0) ...
```

This is a bug waiting to happen!!!

This is well put:

> While most integral types like short and int default to being signed, char does not have a default signage in C++. It's a common mistake that C++ programmers run into when they use char as an 8 bit integer type. (Drew Dormann)

So if you receive a `char` and have to do any kind of arithmetic, then I suggest that you need to cast it (either to unsigned char or signed char) prior to proceeding.

So it is should be safe to refactor uint8_t to unsigned char... but it is not generally safer to refactor uint8_t to be just "char".

The "char" type is weird.

**Comment by lemire** [comment]
And it is not just a matter of compiler... The same compiler can be told to change the signedness... GCC has `-fsigned-char` and `-funsigned-char`. [And Visual Studio has the same](https://docs.microsoft.com/en-us/cpp/build/reference/j-default-char-type-is-unsigned?view=vs-2019).

**Comment by lemire** [comment]
Other than that, yeah... we can get rid of uint8_t. But we one goes through, for safety, it should be converted to unsigned char... or else, we need to run tests, to make sure we have not introduced a nasty hidden bug.

**Comment by jkeiser** [comment]
OK, thanks for the history lesson. I'm fine leaving well enough alone then :)

**Comment by lemire** [comment]
For the record, I agree that the casting back and forth with uint8_t is annoying... so we can definitively fix it.
