### ISSUE TITLE
Consider using `->` for chaining instead of redefining methods

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#641]
## Proposal

Implement error chaining with `->`, reducing the implementation burden and implementing all results with the exact same `simdjson_result<T>` class (without having to use a `simdjson_result_base<T>`.

Code that uses error chaining would look like this:

```c++
auto [value, error] = parser.parse(json)->["result"]->["user"]->["name"]->["first"]->as_string();
```

And the implementation would be way simpler, just adding `operator ->` and maybe `operator *` to `simdjson_result<T>` and letting C++ do all the "method delegation" for us.

## Problem Overview: Error Chaining Today

With our current chaining, now the user can do this:

```c++
auto [value, error] = parser.parse(json)["result"]["user"]["name"]["first"].as_string();
```

If the file fails to parse, each step in the chain will just return the error code; if everything succeeds, they get the string. This is nice from a UX standpoint! Do a bunch of operations and check the error code at the end.

The two drawbacks with the current world:
* Implementation burden: we have to copy all the methods we want from T to `simdjson_result<T>` to make this work. It's extra machinery. It also forces us to build separate _result classes for those types that require extra methods.
* Hidden machinery: I can see some people finding this a little *too* magical, because code that can fail in the middle looks *exactly the same* as code that can't fail. Even idiomatic rust chaining looks like this:
  ```rust
  let result = parser.parse(json)?["result"]?["user"]?["name"]?["first]?.as_string();
  ```

## Cons

The only user-facing problem I can really think of is this makes the user type a little more, but it doesn't really look bad, and IMO it's a good idea to visually distinguish code that can fail from code that doesn't.

From an implementation point of view, we're going to need to do template voodoo to get the two major cases right:
* When you call a method on simdjson_result<T> that returns `int` (or any non-result class), you want the result to be `simdjson_result<int>`.
* However, when you call a method on simdjson_result<T> that returns `simdjson_result<int>`, you want the result to be `simdjson_result<int>`, not `simdjson_result<simdjson_result<int>>`.

This implies we need some sort of mutually exclusive `std::enable_if`, or something.

**Comment by lemire** [comment]
Is this for 0.3?

I like what you did so far, and I am not sure that you make a strong case to throw it away. There is implementation effort, but it seems that you did this hard work already!

**Comment by jkeiser** [comment]
Less implementation effort and more me trying to find every possible place we can shave off a few more methods and minimize surface before we release :)

At any rate, I don't think we can do this for now, as written, because `->` isn't given any information about the actual method you're planning to call, AFAIK, and isn't involved in getting its result.
