### ISSUE TITLE
Remove SUCCESS_AND_HAS_MORE

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#648]
simdjson no longer returns SUCCESS_AND_HAS_MORE in any public (non-deprecated) interface, and it makes error code checking difficult for users. We should return the "has more" state as a separate boolean or parser stored state.

For 0.3, we should deprecate it.

**Comment by jkeiser** [comment]
Marked @private in #647, as users won't be confronted with it. Marking it [[deprecated]] is more complicated, because we still use it internally.

**Comment by lemire** [comment]
Added it as a 1.0 milestone.

**Comment by lemire** [comment]
Has been removed. Closing.
