### ISSUE TITLE
0.4 Outline

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#656]
Let's keep a short list of the highlights we're shooting for next. I imagine we'll release 0.4 before all or even most of these are done, but it's good to keep in sync about our near term plans.

My Thoughts:

- [ ] C++11. Maybe this is a pipe dream, but it would allow us to be used in many projects that still set C++11 as their baseline (for good reason, it's the g++ default). I think we're closer than we think, so I'm going to take a stab.
- [ ] Streaming. In this case, I mean the ability to parse in blocks, not having to load all the JSON into memory at once and having smaller internal parser buffers. This would still materialize a whole DOM tree, so while it'll definitely help with large file speed (probably a *lot*) it doesn't increase the maximum file size we can process.
- [ ] Conan / Package Managers. A lot of people use these, we can help them out by putting simdjson there. Part of becoming a mature project.

Probably Not 0.4:

- [ ] SAJ (SAX for JSON). Done right, with high performance, low memory requirements and supporting fast user code as well (inlining, branch reduction ...). I think streaming has to work first, so this is probably the release after.
- [ ] AVX-512. We've cracked the problem for the current generation of SIMD, but AVX-512 is truly something else, and I'll feel more comfortable once we have explored that too.
- [ ] Pretty-Printing. Pretty important for JSON.
- [ ] Relaxed JSON. Comments, trailing commas ... I'd like to see how well we can blend these into our current approach. Comments in particular are going to be very interesting to solve!

**Comment by lemire** [comment]
@jkeiser 

We could discuss bumping this whole thing to release 0.5 and introduce a release 0.4 where we address issue https://github.com/simdjson/simdjson/issues/632

It is likely a blocking issue for many users.

**Comment by pauldreik** [comment]
The default C++ standard of gcc is C++14 since version 6 (released in 2016). Clang uses C++14 by default since version 6 (released in 2017).

**Comment by lemire** [comment]
@pauldreik As I recall (without cheating), there is not a lot that differs between C++14 and C++11, right?

**Comment by jkeiser** [comment]
My primary motivations for C++ 11 or 14 support are:
1. Quick start: Most people should be able to compile with `g++ myproject.cpp simdjson.cpp -o myproject` and have it work.
2. Inclusion in older projects: I just want to work where the majority of other libraries work, and my guess is "compiles without flags" is the minbar, so if C++14 is no flags, that's good enough for me!

**Comment by pauldreik** [comment]
> @pauldreik As I recall (without cheating), there is not a lot that differs between C++14 and C++11, right?

Right, C++14 is a minor (I have heard "bug fix") release.

**Comment by pauldreik** [comment]
> My primary motivations for C++ 11 or 14 support are:
> 
>     1. Quick start: Most people should be able to compile with `g++ myproject.cpp simdjson.cpp -o myproject` and have it work.
> 
>     2. Inclusion in older projects: I just want to work where the majority of other libraries work, and my guess is "compiles without flags" is the minbar, so if C++14 is no flags, that's good enough for me!

I agree with your motivation! But I think it conflicts with for instance the examples which use the C++17 structured bindings: https://github.com/simdjson/simdjson/blob/master/doc/basics.md#error-handling 
Perhaps it is enough if the core library compiles with C++14, and the rest (fuzzers, examples) can use later C++ if they wish?

**Comment by jkeiser** [comment]
> I agree with your motivation! But I think it conflicts with for instance the examples which use the C++17 structured bindings: https://github.com/simdjson/simdjson/blob/master/doc/basics.md#error-handling
Perhaps it is enough if the core library compiles with C++14, and the rest (fuzzers, examples) can use later C++ if they wish?

@pauldreik I think we should use C++11 and no-exception support in fuzzers personally, just as a minbar. For examples, there's a legitimate question there: should we promote structured bindings in error handling, and should we add warnings when we do so? I don't think we actually have many examples where we do it, and we could easily add a C++17 note to the example you linked!

**Comment by pauldreik** [comment]
> I think we should use C++11 and no-exception support in fuzzers personally

Sure! I am thinking about providing both exception and no-exception code, selected using the simdjson exceptions macro. That way one can add another no-except build and fuzz it as usual.

> should we promote structured bindings in error handling, and should we add warnings when we do so? I don't think we actually have many examples where we do it, and we could easily add a C++17 note to the example you linked!

I think it is good to look forward, and use C++17 where it makes sense. Sure, add a comment to the example! But no warnings :-)

**Comment by lemire** [comment]
Here is what we have currently...

Highlights

- Test coverage has been greatly improved and we have resolved many static-analysis warnings on different systems. 

Performance and new features:
- We have exposed a fast (8GB/s) minifier that works directly on JSON strings.
- Performance improvements to API (type(), get<>()).
- The array and object elements have a constant-time size() method. 
- We have introduced a faster UTF-8 validation algorithm (lookup3) for all kernels.

System support:
- C++11 support for older compilers and systems
- FreeBSD support
- We support the clang front-end compiler (clangcl) under Visual Studio
- It is now possible to target ARM platforms under Visual Studio
- The simdjson library will never abort or print to standard output or standard error.



We did not achieve the "streaming" feature that @jkeiser alluded to in the outline, but, maybe surprisingly, C++11 is in!

**Comment by lemire** [comment]
@jkeiser There are a few outstanding issues for 0.4 regarding the public API where you input would be ideal. The main one has to do with the templated get and is... which we may keep, but it seems that we may want to add friendlier ones as well. Or not.

**Comment by jkeiser** [comment]
I'll go through the API changes next, they are all simple IIRC.

**Comment by lemire** [comment]
Ok. I think 0.4 is done. We just need to outline. I have a sketch above which could do.

**Comment by jkeiser** [comment]
Yeah, that covers everything on my list!

**Comment by lemire** [comment]
@jkeiser 

Happy with these release notes or do you have more ideas...

```
Highlights

- Test coverage has been greatly improved and we have resolved many static-analysis warnings on different systems. 

New features:
- We a fast (8GB/s) minifier that works directly on JSON strings.
- We a fast (10GB/s) UTF-8 validator that works directly on strings (any strings, including non-JSON). 
- The array and object elements have a constant-time size() method. 

Performance:
- Performance improvements to API (type(), get<>()).
- The `parse_many` function (ndjson) has been entirely reworked. It now uses a single secondary thread instead of several new threads.
- We have introduced a faster UTF-8 validation algorithm (lookup3) for all kernels.

System support:
- C++11 support for older compilers and systems.
- FreeBSD support (and tests).
- We support the clang front-end compiler (clangcl) under Visual Studio.
- It is now possible to target ARM platforms under Visual Studio.
- The simdjson library will never abort or print to standard output/error.

```

**Comment by jkeiser** [comment]
Just "We a fast". If I hadn't spent all my energy on a twitter.json struct representation, I might have more left for wordsmithing, but I think this looks good :)

**Comment by lemire** [comment]
Ok. I will start the release process while trying to fix the English.

**Comment by lemire** [comment]
```
Highlights

- Test coverage has been greatly improved and we have resolved many static-analysis warnings on different systems. 

New features:
- We added a fast (8GB/s) minifier that works directly on JSON strings.
- We added fast (10GB/s) UTF-8 validator that works directly on strings (any strings, including non-JSON). 
- The array and object elements have a constant-time size() method. 

Performance:
- Performance improvements to the API (type(), get<>()).
- The parse_many function (ndjson) has been entirely reworked. It now uses a single secondary thread instead of several new threads.
- We have introduced a faster UTF-8 validation algorithm (lookup3) for all kernels (ARM, x64 SSE, x64 AVX).

System support:
- C++11 support for older compilers and systems.
- FreeBSD support (and tests).
- We support the clang front-end compiler (clangcl) under Visual Studio.
- It is now possible to target ARM platforms under Visual Studio.
- The simdjson library will never abort or print to standard output/error.

```

**Comment by lemire** [comment]
Closing.

**Comment by lemire** [comment]
I have to update the web site (doxygen).
