### ISSUE TITLE
update vcpkg to simdjson 0.3

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#658]
I think that we need to update our vcpkg.

https://github.com/microsoft/vcpkg/blob/be4158fb89045319f19d83d08b851e6e694b5b12/ports/simdjson/portfile.cmake

@myd7349 can you help?

**Comment by myd7349** [comment]
Hi! @lemire Sorry for the long delay!
I have just created a PR for simdjson v0.3.1.

**Comment by lemire** [comment]
+1

**Comment by lemire** [comment]
Closing.
