### ISSUE TITLE
Top-level simdjson.h is not installed with CMake

### ISSUE THREAD

**Issue by theirix** [simdjson/simdjson#660]
File `include/simdjson.h` which should be the one to include is not installed.

**Comment by lemire** [comment]
I am going to verify this issue and fixed it if verified for an immediate patch release.

**Comment by lemire** [comment]
The issue has been verified.

**Comment by lemire** [comment]
Marking as a bug.

**Comment by lemire** [comment]
Fixes in the following PR https://github.com/simdjson/simdjson/pull/668 with tests.

**Comment by lemire** [comment]
Closed by PR.
