### ISSUE TITLE
CMake: SOVERSION not bumped

### ISSUE THREAD

**Issue by cdluminate** [simdjson/simdjson#661]
The SOVERSION was left not bumped after introducing significant API/ABI changes (breaking compatibility to the previous version) since the 0.3.0 release. This is not a good practice, and it's easy to fix:
https://github.com/simdjson/simdjson/blob/master/CMakeLists.txt#L32

We just need to change it from `0` to `1`.

**Comment by lemire** [comment]
For future reference: we only deprecated the previous API.
