### ISSUE TITLE
Support std::ignore

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#672]
The current API sometimes entices us to capture values that we never use. It might be useful to support std::ignore to indicate that we do not wish to capture a given value.

cc @jkeiser

**Comment by lemire** [comment]
(Note: I am not sure it is a good idea.)

**Comment by jkeiser** [comment]
Can you be more specific about what values we're enticed to capture but not use? Are we talking about cases where the user only wants to validate JSON, but does not care about the parsed JSON itself?

**Comment by jkeiser** [comment]
I'll have to check it when I get a minute--are you saying std::tie(std::ignore, error) = simdjson_result<T> doesn't work right now?

**Comment by lemire** [comment]
Let me write a test.

**Comment by lemire** [comment]
This does not work: `doc["d"].tie(std::ignore, error);`.

**Comment by lemire** [comment]
But this `std::tie(std::ignore, error) = simdjson_result` works (though not with libc++).

**Comment by lemire** [comment]
Here is the error one gets...

```
tests/basictests.cpp:821:36: error: no matching function for call to 'simdjson::simdjson_result<simdjson::dom::element>::tie(const std::_Swallow_assign&, simdjson::error_code&)'
     doc["d"].tie(std::ignore, error);
                                    ^
In file included from include/simdjson.h:14,
                 from tests/basictests.cpp:17:
include/simdjson/error.h:125:22: note: candidate: 'void simdjson::internal::simdjson_result_base<T>::tie(T&, simdjson::error_code&) && [with T = simdjson::dom::element]'
   really_inline void tie(T &value, error_code &error) && noexcept;
                      ^~~
include/simdjson/error.h:125:22: note:   no known conversion for argument 1 from 'const std::_Swallow_assign' to 'simdjson::dom::element&'

```

**Comment by lemire** [comment]
Maybe a simple overload would do? Let me try.

**Comment by lemire** [comment]
Nope. I don't know how to pull it off.

**Comment by lemire** [comment]
But we can at least add tests for std::ignore regarding the part that we support, this implies detecting libc++ to get around its limitations.

**Comment by lemire** [comment]
The resolution is that we support it, except when dealing with libc++ where *I* don't know how do it.

You would like to support a syntax like...

`doc["d"].tie(std::ignore, error);`

but I don't know how if it is even valid C++... 

You can do...

`doc["d"].error();`

which is even better... (I'll add a test to make sure.)

**Comment by jkeiser** [comment]
Yeah, .error() is the best way to ignore the document IMO.

**Comment by lemire** [comment]
Yes. I just thinking about idiot-proofing the API.

**Comment by jkeiser** [comment]
Agreed :) If it's something people are likely to try and *ought* to work, we may as well make it work.
