### ISSUE TITLE
Restore ability to easily keep the parsed document

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#679]
As an exercise, I updated the simdjson nodejs binding to 0.3.1, and needed the ability to preserve the document longer than the parser itself. Basically, the parse() call from JavaScript creates a parser, parses the document, and returns it. Pretty typical.

But the current parse() interface returns document::element, which becomes invalid when the parser disappears; therefore you need to reach into the parser and use std::move on parser.doc. I don't think we should expose the doc field publicly (it's marked @private right now). We should make it so you can "steal" the result of the parse.

**Comment by lemire** [comment]
Proposed API:

```
  std::vector<dom::document> results;
  dom::parser parser(new dom::parser{});
  for (const auto &f : files) {
    element root;
    auto error = parser->load(f).get(root);
    if (error) {
      throw std::runtime_error(std::string{"Failed to parse "} +
                               std::string{f});
    }
    results.emplace_back(parser.get_document_copy());
  }
  for (auto &t : results) {
    std::cout << "reserialized: " << simdjson::to_string(t.root()) << " ...\n";
  }
```

**Comment by jkeiser** [comment]
What we did before - - and what might make sense now - - was *move * the document to the user, and allocate a new one the next time you parse. Avoids am unnecessary trailing allocation, at the least.

**Comment by jkeiser** [comment]
Like. take_document().

**Comment by lemire** [comment]
Yes...
