### ISSUE TITLE
Why remove bool ParsedJson::printjson(STD ::ostream & OS)

### ISSUE THREAD

**Issue by 2273816832** [simdjson/simdjson#686]
Hello, Simdjson parsing is fast, but anti-parsing is slow, right? 
Now，why remove bool  ParsedJson::printjson(STD ::ostream & OS)?
I am looking forward to your reply！

**Comment by jkeiser** [comment]
Do you mean in simdjson 0.3? The functionality has been moved and the actual print_json method is deprecated, but it should still work. Can you share some code that is failing?

print_json is supposed to work, but simdjson's new 0.3 apis can also parse and print a document with:

```c++
dom::parser parser;
cout << parser.parse(json);
```

**Comment by lemire** [comment]
I am going to close this. If you can elaborate further on the issue, we are inviting comments.

**Comment by 2273816832** [comment]
ok. There is no problem with my code, thank you for your detailed explanation。
