### ISSUE TITLE
as_int64_t()  9223372036854775808  ==> -9223372036854775808

### ISSUE THREAD

**Issue by mitu626** [simdjson/simdjson#704]
std::string s=R"({"t":9223372036854775808})";
::simdjson::document::parser parser;
auto doc = parser.parse(s);
auto obj = doc.as_object();
auto [value, error] = obj["t"].as_int64_t();
printf("value is %ld\n", value); /*where prints -9223372036854775808*/

**Comment by TkTech** [comment]
What are you expecting to happen here? This result is correct. Use `as_uint64_t();`.

**Comment by lemire** [comment]
@mitu626 Are you working from a release? I vaguely remember that we had a "as_int64_t" function at some point as part of our API design work, but this was never released. Please try again with a release. You probably want functions like...

```
obj["t"].is<uint64_t>()
obj["t"].is<int64_t>()
obj["t"].get<uint64_t>()
static_cast<uint64_t>(obj["t"]) 
```


and so forth.

Please see our API online...

https://simdjson.org/api/0.3.1/annotated.html

**Comment by lemire** [comment]
I am going to close this since I believe the submitted was working from an unreleased API. For obvious reasons, we do not support unreleased APIs.

**Comment by TkTech** [comment]
@lemire probably confused because the getting started documentation still tells you to use as_. See the first point under https://github.com/simdjson/simdjson/blob/master/doc/basics.md#using-the-parsed-json

**Comment by lemire** [comment]
Yes. The documentation is out of sync... let us fix that:

https://github.com/simdjson/simdjson/pull/710

**Comment by mitu626** [comment]
> @mitu626 Are you working from a release? I vaguely remember that we had a "as_int64_t" function at some point as part of our API design work, but this was never released. Please try again with a release. You probably want functions like...
> 
> ```
> obj["t"].is<uint64_t>()
> obj["t"].is<int64_t>()
> obj["t"].get<uint64_t>()
> static_cast<uint64_t>(obj["t"]) 
> ```
> 
> and so forth.
> 
> Please see our API online...
> 
> https://simdjson.org/api/0.3.1/annotated.html

yes,  this is from an unreleased api. besides, i just think error should set if the value out of range of int64. 
thanks!

**Comment by lemire** [comment]
> yes, this is from an unreleased api. besides, i just think error should set if the value out of range of int64. thanks!

Yes. It should. You should get an exception.
