### ISSUE TITLE
std::string_view or const std::string_view

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#714]
Currently, we can recover a `std::string_view` instance or a `const char*`pointer from the API. Shouldn't that be a `const std::string_view` ?

**Comment by jkeiser** [comment]
`std::string_view` doesn't let you mutate the string: the `const` refers to whether you are allowed to change the *indices* on the string_view--for example, by widening or narrowing them. I think I ran into this at some point when writing something against a string.

**Comment by lemire** [comment]
Verified (https://en.cppreference.com/w/cpp/header/string_view). Closing.
