### ISSUE TITLE
question: what is the use of JSON_VALUE_MASK?

### ISSUE THREAD

**Issue by nojvek** [simdjson/simdjson#724]
I see this code when iterating over the tape `tape[tape_idx] & internal::JSON_VALUE_MASK`.

What is the use of JSON_VALUE_MASK being `0x00FFFFFFFFFFFFFF`?. Why not have the tape[tape_idx] simply be a normal number that is the index of referencing element ?

fyi @lemire ^

**Comment by lemire** [comment]
Because the most significant 8 bits tell you about the type of element.

**Comment by nojvek** [comment]
Ahhh. It’s similar to`num << 56`. I cannot brain today.
