### ISSUE TITLE
Reduce number of allocations in parser and document

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#726]
Right now, we do [3 allocations per parser](https://github.com/simdjson/simdjson/blob/master/include/simdjson/inline/document.h#L223-L224) and [2 allocations per document](https://github.com/simdjson/simdjson/blob/master/include/simdjson/inline/document.h#L223-L224), for a total of 5. Instead, we could do 1 megaallocation for the parser, and another for the document; and the pointers would each just take their portion of that allocated memory.

This would probably allow us to reference a document with a single pointer-sized object, which would help simdjson bind to languages that can store a single pointer efficiently (but can't store 2 efficiently).

**Comment by lemire** [comment]
@jkeiser Maybe this is relevant: https://github.com/simdjson/simdjson/issues/94

**Comment by jkeiser** [comment]
Seems like a duplicate to me!
