### ISSUE TITLE
Header without warnings with g++

### ISSUE THREAD

**Issue by ostri** [simdjson/simdjson#735]
I tried simdjson. Nice work. :-)

How can I make that the program which includes simdjson compiles without warnings?
I don't care for simdjson cpp warnings, but header file warnings are annoying, since they must be included in the application and they are therefore appearing at majority of recompilations of the application.

our usual application switches: -Wall -Wextra -Wshadow -Weffc++ -Wstrict-aliasing -ansi -pedantic
Warnings reported are of three types:

1. trivial: e.g. additional ','
2. solvable: e.g. comparing signed and unsigned
                      missing operator= if there are pointer members
3. don't know:  (trivially to fix it, but I don't know if there are some consequences on speed)
     e.g. non virtual destructors, uninitialized members in constructor, ...

I noticed, that you already worked on that, but results are not there. ;-)

    #define SIMDJSON_PUSH_DISABLE_ALL_WARNINGS SIMDJSON_PUSH_DISABLE_WARNINGS \
      SIMDJSON_DISABLE_GCC_WARNING(-Wall) \
      SIMDJSON_DISABLE_GCC_WARNING(-Wextra) \
      SIMDJSON_DISABLE_GCC_WARNING(-Wshadow) \
      SIMDJSON_DISABLE_GCC_WARNING(-Wunused-parameter) \
      SIMDJSON_DISABLE_GCC_WARNING(-Wimplicit-fallthrough) \
      SIMDJSON_DISABLE_GCC_WARNING(-Weffc++)
    #define SIMDJSON_PRAGMA(P) _Pragma(#P)  
    #define SIMDJSON_DISABLE_GCC_WARNING(WARNING) SIMDJSON_PRAGMA(GCC diagnostic ignored #WARNING)
    #define SIMDJSON_DISABLE_DEPRECATED_WARNING SIMDJSON_DISABLE_GCC_WARNING(-Wdeprecated-declarations)
    #define SIMDJSON_POP_DISABLE_WARNINGS _Pragma("GCC diagnostic pop")

Best regards

**Comment by jkeiser** [comment]
Is this master or 0.3.1? If it's master, try running `make amalgamate` and using the .h and .cpp in the singleheader directory.

**Comment by jkeiser** [comment]
This should be fixed in master, but singleheader wasn't up to date :) I went and updated it.

Can you re-pull master and use the headers from [the singleheader directory](https://github.com/simdjson/simdjson/tree/master/singleheader)?) and try again? Thanks.

**Comment by ostri** [comment]
@jkeiser thanks it works now if I have
g++ -Wall -Wextra -Wshadow -Weffc++ -Wstrict-aliasing -pedantic

but it doesn't, if I have -Weffc++
-Wall -Wextra -Wshadow -Weffc++ -Wstrict-aliasing  -pedantic

so missing class member initialisation, missing virtual destructors and invalid function signatures are still reported.

**Comment by jkeiser** [comment]
> @jkeiser thanks it works now if I have
> g++ -Wall -Wextra -Wshadow -Weffc++ -Wstrict-aliasing -pedantic
> 
> but it doesn't, if I have -Weffc++
> -Wall -Wextra -Wshadow -Weffc++ -Wstrict-aliasing -pedantic

I can't tell what's different between those--is it the pedantic that's causing the warnings?

**Comment by ostri** [comment]
its -Weffc++ that is causing warnings.
And at least some of them are serious.

**Comment by jkeiser** [comment]
So, you still get warnings, yes? Seems like we should leave this open.

**Comment by ostri** [comment]
I played a bit with hpp file (I know I should fix the master), just to see what we can do.
There is bunch of warnings because some class instance members are not initialised in the constructor.
This is easy to fix.
Also those missing assignment operators due to pointer members are also easy to fix.
For others I don't know.
We are using this switch, because we had a lot of tricky errors because of invalid, copy constructors, etc.

**Comment by lemire** [comment]
Being `-Weffc++` clean is a non-goal. The flag `-Weffc++` is from an obsolete set of guidance.

> And at least some of them are serious.

Please be specific as to the warnings that you feel are serious.

**Comment by ostri** [comment]
Warnings are not errors. We can ignore them, but usually they point to some practice that can make us problems. That's why we are using this switch.
If you think that this is neglectable, try with some other linter. E.g. cppcheck

```
Member variable 'parser::current_string_buf_loc' is not initialized in the constructor.
{
	"resource": "/home/ostri/vjson/simdjson/simdjson.hpp",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "uninitMemberVar",
	"severity": 4,
	"message": "Member variable 'parser::current_string_buf_loc' is not initialized in the constructor.",
	"source": "CppCheck",
	"startLineNumber": 4833,
	"startColumn": 1,
	"endLineNumber": 4833,
	"endColumn": 59
}
{
	"resource": "/home/ostri/vjson/simdjson/simdjson.hpp",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "noOperatorEq",
	"severity": 4,
	"message": "Class 'Iterator' does not have a operator= which is recommended since it has dynamic memory/resource allocation(s).",
	"source": "CppCheck",
	"startLineNumber": 6490,
	"startColumn": 3,
	"endLineNumber": 6490,
	"endColumn": 47
}
{
	"resource": "/home/ostri/vjson/simdjson/simdjson.hpp",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "noCopyConstructor",
	"severity": 4,
	"message": "Class 'Iterator' does not have a copy constructor which is recommended since it has dynamic memory/resource allocation(s).",
	"source": "CppCheck",
	"startLineNumber": 6490,
	"startColumn": 3,
	"endLineNumber": 6490,
	"endColumn": 47
}

```
and of course a bunch of single parameter constructors that are missing explicit keyword.
All are neglectable, until you start to search for some obscure bug, that is at the end not so obscure.
;-)

**Comment by jkeiser** [comment]
I just want to note, @lemire is asking for specifics genuinely. We don't want to have actual problems in our code.

We're not interested in ignoring warnings--as you can see, we already enable Wall, Wextra, and a host of other warnings, and we set -Werror on both Windows and Linux :) But some warnings *do* get obsoleted because they cause more signal than noise, and in a lot of cases there are new versions we can enable that have less noise! So let's track that down.

**Comment by ostri** [comment]
Ok.

**Comment by lemire** [comment]
@ostri  Would you submit a pull request with the fixes for the issues that you feel are important?

**Comment by ostri** [comment]
Sure. Just give me brief instructions how to do it.

**Comment by ostri** [comment]
> amalgation.sh

 had bug. I believe last weekend complaints were caused by this bug.
the script is also littering working directory. It should either use mv or cp and rm.

> json_minifier

source code of json_minifier is included in _simdjson.cpp_ three times. Was that really intended?
Some other parts are also multiplied (i.e. the same multiline string)

> members

Quite often not all members are initialized in constructor. Some of them are later on within the body of constructor or inside the declaration.  I used to do the same, but I had very long debugging cycles and hard to find bugs. ;-)

>virtual destructors

Non virtual destructor in a class with virtual method. It can run now, but it might cause troubles later.

>nonstandard operator signatures

Increment operators should have standard signatures e.g. T& operator++(). 

`void operator++()
`
is possible, but highly non standard.

> can't fix

```
template<typename T>
class atomic_ptr {
public:
  atomic_ptr(T *_ptr) : ptr{_ptr} {}

  operator const T*() const { return ptr.load(); }
  const T& operator*() const { return *ptr; }
  const T* operator->() const { return ptr.load(); }

  operator T*() { return ptr.load(); }
  T& operator*() { return *ptr; }
  T* operator->() { return ptr.load(); }
  T* operator=(T *_ptr) { return ptr = _ptr; }

private:
  std::atomic<T*> ptr;
};

```
Don't know the semantics of the atomic_ptr. Why is std::atomic not enough?

tested on linux (fedora)

```
c++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.

make amalgamate

clear && c++ -O3 -std=c++{11,14,17,2a} -Weffc++ -pthread -o amalgamation_demo amalgamation_demo.cpp  && ./amalgamation_demo ../jsonexamples/twitter.json ../jsonexamples/amazon_cellphones.ndjson

tested c++11, c++14, c++17, c++20
warning: structured bindings only available with ‘-std=c++17’ or ‘-std=gnu++17’
otherwise it compiles.

```

**Comment by ostri** [comment]
Hi Daniel,

I need a little help.
I've cloned the repository and fixed the warnings, all but one.
How can I deliver this as a pull request?

Thanks in advance

Matjaž

**Comment by lemire** [comment]
@ostri  It looks to me like you figured out how to do the PR?

**Comment by lemire** [comment]
> had bug. I believe last weekend complaints were caused by this bug.

Can you explain why you think that there was a bug?

**Comment by ostri** [comment]
Let me fix the "fix" and I'll explain. ;-)

**Comment by lemire** [comment]
> Don't know the semantics of the atomic_ptr. Why is std::atomic not enough?

A std::atomic<T *> instance does not behave like a pointer. This class you point at is a convenience wrapper, to  make the code easier to read and write.

**Comment by jkeiser** [comment]
@ostri please absolutely feel free to change operator= in atomic_ptr to return *this. I suspect everything else will compile.
