### ISSUE TITLE
simdjson doesn't compile for x86 with VS2019

### ISSUE THREAD

**Issue by pps83** [simdjson/simdjson#742]
The errors that I get:
```
1>C:\src\simdjson.cpp(5865,16): error C3861: '_umul128': identifier not found
1>C:\src\simdjson.cpp(8658,3): error C3861: '_BitScanForward64': identifier not found
1>C:\src\simdjson.cpp(8676,7): error C3861: '_BitScanReverse64': identifier not found
```

**Comment by lemire** [comment]
We do not support 32-bit systems. Please build for 64-bit systems.

**Comment by jkeiser** [comment]
BTW, please leave this open, we at least need to give a clear error when you try to do this!

**Comment by pps83** [comment]
> We do not support 32-bit systems. Please build for 64-bit systems.

I think it should at least not fail compilation in 32-bit builds. If 32-bit isn't well optimized it should maybe print a warning or something like that. In my tests simdjson was 5% slower than rapidjson in 32-bit builds, but I do use it in 64 built except: I've seen cases where debugging didn't work well in x64 builds and I had better results debugging in x86. Any libs that do not compile for x86 suddenly become huge pain even if they are used for some minor details. I think I've added similar fixes to allow 32-bit builds in fastpfor and/or turbopfor.

Also, at my work we use rapidjson and I'm considering to switch to simdjson. We have 100M+ users and we only build 32-bit on Windows (64-bit only on mobiles). Yes, that's strange, mobile builds are already 64-bit and windows is still 32-bit for us :)

**Comment by jkeiser** [comment]
> Also, at my work we use rapidjson and I'm considering to switch to simdjson. We have 100M+ users and we only build 32-bit on Windows (64-bit only on mobiles). Yes, that's strange, mobile builds are already 64-bit and windows is still 32-bit for us :)

I'm on board with running 32-bit if it can be done! Caution: I think the SIMD intrinsics are only available in x64, so you'd only be able to use the fallback parser. It's still fast, but I can't recall offhand whether it was faster than rapidjson :)

**Comment by jkeiser** [comment]
Either way, we should either work, or give an explicit error when you compile. This is a common enough scenario that it matters to at least tell people.

**Comment by pps83** [comment]
Fixed by https://github.com/simdjson/simdjson/commit/ffaa292006b8fdc68e4e9de16fea066d51cc2735

**Comment by jkeiser** [comment]
Yay! I'm curious if this means we've got 32-bit compiles licked for other OS's then? This is excellent.

**Comment by pps83** [comment]
Very likely it should now compile and run, but I didn't testing anything other than vs2019-x86. Note, that x86 build doesn't use optimized versions, so, it's less performant. code for westmere and other optimizations might easily be adjusted (missing intrinsics) to improve it if anybody needs it.

**Comment by jkeiser** [comment]
Yeah. I have no idea if there are optimizations, but first step is the biggest :) Making it so we can run anywhere, even if we're not as fast on 32-bit, is a huge win, allowing simdjson to be used inside other libraries and programs that *do* want to be able to run on 32-bit. "Faster on 64-bit, but works everywhere" is a mantra I can live with.
