### ISSUE TITLE
simdjson profiling vs rapidjosn

### ISSUE THREAD

**Issue by pps83** [simdjson/simdjson#745]
Hi @lemire ,

I decided to try simdjson in my project instead of RapidJSON. Overall, after I fixed minor compilation issues (please check these PRs: https://github.com/simdjson/simdjson/pull/738, https://github.com/simdjson/simdjson/pull/740, https://github.com/simdjson/simdjson/pull/741, https://github.com/simdjson/simdjson/pull/743, https://github.com/simdjson/simdjson/pull/744), I'm very impressed by the results (just like with your FastPFor lib).

In my test app, according to profiler, parsing json with in-situ RapidJSON was taking roughly 53% from overall CPU time. After I replaced it with simdjson I get approximately 15-25% overall speedup and josn parsing with simdjson now takes 41%. 

There is something interesting however in the results that I saw: parsing with simdjson is much faster than with RapidJSON. Using the results of parsing however, seems to be slower. Only function in particular jumps in profiler when I use simdjson: `_free_base` as if simdjson allocates way more than RapidJSON and freeing that memory takes much longer.

This is a hot path call tree and you can see that _free_base at the bottom.
![image](https://user-images.githubusercontent.com/1614246/79707384-2565ca80-82de-11ea-8886-8fed577f413c.png)

Note, that if I use in-situ or regular RapidJSON parsing, total percentage of `_free_base` with RapidJSON doesn't change much, but right away jumps up to 5% from 1.3% when using simdjson. Since, overall json parsing takes roughly 40-50% in my app, then the `_free_base` actually take roughly 10% when processing json with simdjson.

Any idea, why such a big difference?

**Comment by lemire** [comment]
Thanks for the report. Note that simdjson (like FastPFor) is joint work with many people. I am just one of the authors.

Back to the issue...

Normally, a "free" should only occur when you drop the `parser`. If you keep the `parser` around, then you should avoid this issue entirely. If JSON parsing is  40-50% of your app, I would assume that you are keeping the `parser` around.

Can you share with us a sketch of your hot code?

**Comment by lemire** [comment]
The important point with simdjson is that you are meant to *reuse* the `parser` object.

Maybe the documentation should be clearer about this.

But anyhow, please give us your hot code... so we can see what you are doing.

**Comment by lemire** [comment]
> Maybe the documentation should be clearer about this.

The documentation is clear about this, I think. The performance.md file includes a specific recommandation.

**Comment by jkeiser** [comment]
Also, note that the "free" includes not *just* the document, but also parser internal buffers. So you sort of have to consider part of that "free" cost as part of the parsing. (Not all, though.)

**Comment by pps83** [comment]
> Can you share with us a sketch of your hot code?

So, in my case, it goes this way:

I start 16 threads, and all of them process huge amount of json (stored in zip files).
Each thread, extracts json as a string, and then extracts data from it and uses the data (actually encodes it using fastpfor/turbopfor). Relevant function: `JsonData getData(std::string json)` that creates structure that represents data from the json string. My json has this structure:
```
{  "12345" : {"a":12.34, "b":56.78, "c": 9998877}, "123445646": { .. same fields ..} } 
```
each json string is approximately 2-3MB in size and there are like 10 fields that I extract, and field name lengs are in the range of 10-30 chars long
Code that I use to parse it with rapidjson:

```
    rapidjson::Document d;
    if (d.ParseInsitu(&json[0]).HasParseError())
        LOG("failed to parse json");

    for (auto x = d.MemberBegin(); x!= d.MemberEnd(); ++x)
    {
        // x->name is "12345", x->value is {"a":12.34, "b":56.78, "c": 9998877}
    }
```

Firs of all, I tried really really hard to get these basics working with simdjson. TO the point that I though it's broken and I wanted to abandon it. I just couldn't figure out how to iterate members.

The reason was that I was assigning to element result of parsing, while I had to assing to object I think. This is what I do now:
```
        simdjson::dom::parser parser;
        auto jObj = parser.parse(json);
        if (jObj.error() || !jObj.is<simdjson::dom::object>())
        {
            LOG("failed to parse json");
            return;
        }
        for (const auto& x: jObj.get<simdjson::dom::object>())
        {
            // x.key is "12345", x.value is {"a":12.34, "b":56.78, "c": 9998877}
        }
```

So, as I understood, I need to reuse the same parse for parsing other json string?

In my case, I parse millions of lines. It seems that x.key returns terminated `const char*` and because it doesn't do insitu parsing, clearly, each of these keys have to be copied somewhere, what's even more surprising, that string_view refers to the copied memory as well. I'd certainly not want that, and prefer either insitu that modifies original keys and adds `\0`, or simple returns reference to the key.

The other point, not sure if I've raised it before.
I've used a few json libraries. I strongly believe that templated `is<T>()`, `get<T>` are wrong (for publicly faced api at least). It's not completely clear what T has to be for a json string (in simdjson, std::string isn't even there, right?). One may try to do`.is<MyClas>()` which makes no sense in json context. Json has clear set of types, and I'd rather prefer clear names for these. When I type `jobj.` and get `.is` one of intellisense offers, I have no clue what I need to do: I need to go to the source code to see how it works.

**Comment by lemire** [comment]
> So, as I understood, I need to reuse the same parse for parsing other json string?

Yes.

**Comment by lemire** [comment]
> The other point, not sure if I've raised it before. 

This is a distinct issue which I created for you.

**Comment by lemire** [comment]
> In my case, I parse millions of lines. It seems that x.key returns terminated const char* and because it doesn't do insitu parsing, clearly, each of these keys have to be copied somewhere, what's even more surprising, that string_view refers to the copied memory as well. I'd certainly not want that, and prefer either insitu that modifies original keys and adds \0, or simple returns reference to the key.



Currently, if you want to get good performance out of simdjson, you have to reuse the parser object. If you flush it constantly, you will be allocating and deallocating memory. It is not going to be performant.  I made sure that the document is clear about so I am going to close the issue. 


Would you be willing to produce a parser that uses insitu parsing? I am inviting a pull request.
 If you do want to work on insitu parsing, I will happily create an issue and assign it to you.

**Comment by lemire** [comment]
> Firs of all, I tried really really hard to get these basics working with simdjson. TO the point that I though it's broken and I wanted to abandon it. I just couldn't figure out how to iterate members.

I will add an example.

**Comment by pps83** [comment]
FYI, I modified my code to reuse parser, and I got **HUGE** perf improvements. Overall, my test exe times went down from 8.2 to 6.2 seconds. In 6.2 run, according to profiler 50% of CPU is consumed by unzipping files, that is, actual improvement is like 5.1sec -> 3.1sec.

**Comment by lemire** [comment]
Thank you for reporting the problems you were having. This forced me to carefully review the documentation. There is  more that we should do as well to make sure people better use the API.

**Comment by pps83** [comment]
I made more trials, I removed zlib decompression from my code and run these cases:


In all cases, json parsing took more than 90% of cpu time, with 12 cores loaded (cpu is the top line available with mac mini, but run it at reduced power settings, so it mostly runs at 3.2G instead of boost at 4.6G).

These are the values:

| Parser Type | Run time, seconds  |
|---|---|
| rapidjson regular parse | 6:147  |
|rapidjson insitu parse|  5:754 |
|rapidjson sax-style parser| 4:268  |
|simdjson dom parser| 4:936  |
|simdjson reused dom parser | 2:687  |

Note, that for insitu parsing, on each iteration json string had to be copied, yet, the result is better, than regular parsing. Seems like RapidJSON should always copy internally and parse insitu.
sax-style parser test was done similar to [Parsing JSON to Custom Data Structure example](https://rapidjson.org/md_doc_sax.html#CustomDataStructure)

**Comment by lemire** [comment]
Thanks for these numbers. We shall offer SAX-like parsing in simdjson "soon" (if we can get a minute to do it).
