### ISSUE TITLE
fopen_s warning

### ISSUE THREAD

**Issue by h5rdly** [simdjson/simdjson#746]
Hi,

First of all, how awesome is this project, cheers!

I was trying to run the sample code on my machine with clang 10, and get this warning (#4996):

> 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS

I understand this is some kind of Microsoft play on Windows..

Adding this:
```
#ifdef _MSC_VER
    #define _CRT_SECURE_NO_WARNINGS
#endif

#include "simdjson.h"
```

removes the warning. 

Perhaps there is something that could be done at the library level?

Thanks,
Eli

**Comment by lemire** [comment]
Actually, why don't we use `fopen_s`? It is part of the standard and does some extra checking on the parameters.

I think it is a bit much to refer to `fopen` as unsafe... but I think we could use `fopen_s`.

**Comment by h5rdly** [comment]
I'm hardly an expert on this, SO suggested `fopen_s`  is not portable and I didn't want to presume

**Comment by jkeiser** [comment]
[Looks like it's C++11](https://en.cppreference.com/w/c/io/fopen), so I think we're golden there!

**Comment by pps83** [comment]
> [Looks like it's C++11](https://en.cppreference.com/w/c/io/fopen), so I think we're golden there!

No it's not. It's C11, not C++11.
Perhaps, if you rewrite it with std prefix it sholdn't claim that it's deprecated, as [std::fopen](https://en.cppreference.com/w/cpp/io/c/fopen) is part of c++ and not going to be deprecated anywhere soon.

**Comment by pps83** [comment]
@lemire once/if [Amalgamate src/simdjson.cpp as-is](https://github.com/simdjson/simdjson/pull/740/commits/c20b868fe4d0e772cfe4dc68670ddbc29a0ee3b7) and [Do not inline file IO functions](https://github.com/simdjson/simdjson/pull/741) get through PR, I'll be able to [add a follow up commit to fix the warning](https://github.com/pps83/simdjson/commit/e4bff0e13ebc53fa6c28a496a92ff4fa1ab76807) in non-intrusive way.

By `non-intrusive way` I mean a way to disable it for simdjson code only, without affecting users' code that includes simdjson.

**Comment by jkeiser** [comment]
> No it's not. It's C11, not C++11.

Is C11 not a subset of C++11? (Genuine ignorance here.)

**Comment by pps83** [comment]
> > No it's not. It's C11, not C++11.
> 
> Is C11 not a subset of C++11? (Genuine ignorance here.)

No, it's not. This is fopen for c++: https://en.cppreference.com/w/cpp/io/c/fopen and this is for C: https://en.cppreference.com/w/c/io/fopen

There are lots of new things in latest c11 that aren't in c++ (eg something that was in c for 10 years isn't in latest c++)

**Comment by jkeiser** [comment]
Thanks for the info. Even gcc doesn't implement that part of the C11 standard. Weird!

I agree we should locally disable the warnings (after we check that our use of fopen/getenv/strcpy is safe).

**Comment by jkeiser** [comment]
This gets fixed by #849.

**Comment by lemire** [comment]
@jkeiser Is this fixed?

**Comment by jkeiser** [comment]
Yep, thanks for the reminder!
