### ISSUE TITLE
To do: include specific documentation for Visual Studio

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#750]
We used to have specific documentation regarding Visual Studio. I think we need to bring it back.

Here is what we had...

We are assuming that you have a common Windows PC with at least Visual Studio 2017.

- Grab the simdjson code from GitHub, e.g., by cloning it using [GitHub Desktop](https://desktop.github.com).
- Install [CMake](https://cmake.org/download/). When you install it, make sure to ask that cmake be made available from the command line.
- Create a subdirectory within simdjson, such as VisualStudio.
- Using a shell, go to this newly created directory.
- Type cmake -DCMAKE_GENERATOR_PLATFORM=x64 .. in the shell while in the VisualStudio repository. (Alternatively, if you want to build a DLL, you may use the command line cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DSIMDJSON_BUILD_STATIC=OFF ...)
- This last command created a Visual Studio solution file in the newly created directory (e.g., simdjson.sln). Open this file in Visual Studio. You should now be able to build the project and run the tests. For example, in the Solution Explorer window (available from the View menu), right-click ALL_BUILD and select Build. To test the code, still in the Solution Explorer window, select RUN_TESTS and select Build.

The need to specify "-DCMAKE_GENERATOR_PLATFORM=x64" is really annoying. We could work around it with code like this:

```
if(MSVC)
  if("${CMAKE_GENERATOR}" MATCHES "(Win64|IA64)")
     set(CMAKE_GENERATOR_PLATFORM "x64")		    
   elseif("${CMAKE_GENERATOR_PLATFORM}" MATCHES "ARM64")
     set(CMAKE_GENERATOR_PLATFORM "ARM64")
  endif()
endif()
```

Note that it is also possible to work directly from within the project...

- Select the Visual C++ tools for CMake optional component when installing the C++ Development Workload within Visual Studio.
- Within Visual Studio use File > Open > Folder... to open the CRoaring folder.
- Right click on CMakeLists.txt in the parent directory within Solution Explorer and select Build to build the project.
- For testing, in the Standard toolbar, drop the Select Startup Item... menu and choose one of the tests. Run the test by pressing the button to the left of the dropdown.

I bet it is also possible to git clone simdjson from within Visual Studio... So a 100% pure visual studio approach is possible.

I am "assigning" @jkeiser because though I could write the above in the documentation, I have a feeling that he wants more.

**Comment by lemire** [comment]
Help is invited on this issue.

**Comment by jkeiser** [comment]
I moved most of the build documentation to HACKING.md, BTW. Clearly it, or something like it, needed to stay in README--but if you want a starting point that might work.

**Comment by jkeiser** [comment]
The extra thing we'd want is instructions on how to add simdjson to your C++ project in Visual Studio. We need to fix warnings first, though.

**Comment by pps83** [comment]
> The extra thing we'd want is instructions on how to add simdjson to your C++ project in Visual Studio. We need to fix warnings first, though.

Those amalgamated versions are perfect imo. Better than any cmake/vs instructions. People who do c++ should be able to add files to their projects :)

**Comment by jkeiser** [comment]
> The need to specify "-DCMAKE_GENERATOR_PLATFORM=x64" is really annoying. 

@lemire I just ran `cmake ..` with no arguments from my Visual Studio Code terminal window, and noticed this output:

```
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
```

Maybe it's defaulting to 64-bit now?

**Comment by jkeiser** [comment]
Further evidence: after building, running json2json.exe yields:

```
PS C:\Users\john\Source\simdjson\build> .\tools\Debug\json2json.exe

C:\Users\john\Source\simdjson\build\tools\Debug\json2json.exe v0.3.1 (haswell)

Reads json in, out the result of the parsing.
Usage: C:\Users\john\Source\simdjson\build\tools\Debug\json2json.exe <jsonfile>
The -d flag dumps the raw content of the tape.
```

It should be noted, BTW, that our code trying to default the Release target doesn't seem to stick.

**Comment by lemire** [comment]
> It should be noted, BTW, that our code trying to default the Release target doesn't seem to stick.


This answer ...
https://stackoverflow.com/questions/24460486/cmake-build-type-is-not-being-used-in-cmakelists-txt

Looks credible. I think that what happens is that in Visual Studio, you get both (release and debug), and which one you select is a GUI issue.

Visual Studio, reasonably enough, defaults the programmer on debug...

**Comment by lemire** [comment]
@jkeiser 

This is actually in the documentation now ...

- For VS 2017, the default in Win32 https://cmake.org/cmake/help/v3.14/generator/Visual%20Studio%2015%202017.html

- For VS 2019, the default is that of the host https://cmake.org/cmake/help/v3.14/generator/Visual%20Studio%2016%202019.html

This is a reasonable way to do things considering that Windows comes into 32-bit and 64-bit flavours.

So we can instruct the users to omit the flag is they are using VS 2019 and are on a 64-bit OS.

If the are using VS 2019 and are on a 32-bit OS, they need rethink their life choices.

**Comment by jkeiser** [comment]
Hooray! We should consider warning or even erroring if you are running Win32 by default on 2017 or earlier; it's a small price to pay to force users to use -A Win32 when they want 32-bit. The use case for 2017 is more about corporations, where users generally upgrade VS in lockstep and legacy reasons lock them into earlier versions.

**Comment by lemire** [comment]
> Hooray! We should consider warning or even erroring if you are running Win32 by default on 2017 or earlier; it's a small price to pay to force users to use -A Win32 when they want 32-bit. The use case for 2017 is more about corporations, where users generally upgrade VS in lockstep and legacy reasons lock them into earlier versions.

I added a message, but it is neither a warning nor an error currently because x86 is part of our tests.


I hope people upgrade to Visual Studio 2019 and that will be all.

**Comment by jkeiser** [comment]
@lemire we can fix that and make it an error by actually adding -A Win32 to the cmake command in CI :)

**Comment by lemire** [comment]
@jkeiser I think we may want to move this to milestone 0.5.

**Comment by lemire** [comment]
I am pushing this to milestone 0.5.

**Comment by jkeiser** [comment]
Yeah, I think it's fine not to make the cut.

**Comment by lemire** [comment]
@jkeiser By removing this one, we have everything we need.
