### ISSUE TITLE
Put #line directives into singleheader/

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#754]
Would make it easier to relate errors in singleheader/ back to the source.

**Comment by lemire** [comment]
It can be a mixed bag. When I started out on the amalgamation path, I thought it was neat to reassign line numbers... but I think it can be mildly harmful to the users who don’t care about the original source...

**Comment by jkeiser** [comment]
That's a really good point. Actually, it'd be super aggravating. I think we can close this.
