### ISSUE TITLE
Consider add -Wconversion to Linux build

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#756]
We are going through Visual Studio type conversion warnings like madmen, but the same flag exists under clang and gcc, it is just very rarely used. I think that `-Wconversion` is even more aggressive.

**Comment by jkeiser** [comment]
Oh God it would be nice not to have to wait for appveyor.

**Comment by lemire** [comment]
@jkeiser Do we close this?

**Comment by jkeiser** [comment]
Yep!

**Comment by jkeiser** [comment]
I'd say we considered it. We considered it **real good.**
