### ISSUE TITLE
CMake build will fail on any non-Visual Studio system without bash

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#770]
There is a dependency on bash in CMake. It might be more elegant to disable tests and setup requiring bash on systems where it is not present.

**Comment by lemire** [comment]
Specifically, issue150, testjson2json, amalgamate... are all dependent on bash.

**Comment by lemire** [comment]
Right now, they are guarded with "if (NOT MSVC)" but that's not sufficient.

**Comment by lemire** [comment]
We might be able to do something like this:

```
   find_program(BASH bash) 

    if (NOT BASH)
        message(FATAL_ERROR "Bash not found!")
    endif ()
```

**Comment by jkeiser** [comment]
Yeah, find_program seems to be the right way to do that.

Ultimately, we don't really need these .sh wrappers. They really don't do very much--even checkperf. We can run the underlying programs directly from cmake.

**Comment by BarrOff** [comment]
Hello,

for better compatibility you might want to consider replacing the `#!/bin/bash` line in the shell scripts with `#!/usr/bin/env bash`.
I know on FreeBSD bash gets installed as `/usr/local/bin/bash` and I would assume it is the same for the other BSDs.

**Comment by lemire** [comment]
@BarrOff Yes. That would be better.

We do support freeBSD currently btw.
