### ISSUE TITLE
We should not test compilations without explicitly specifying the C++11 requirement

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#774]
I think that it is silly to test the compiler without any requirement on the standard. If the user happens to want to compile with a compiler that defaults on a pre-C++11 standard, he can't. What is the logic in that?

**Comment by ostri** [comment]
Maybe at the the top of the header

`static_assert( __has_cpp_attribute( fallthrough ), "no fallthrough");
`
1. If compiler doesn't have c++11 features, static_assert won't work.
2. Later we mention only the features we really need, so that we can work with the lowest version of c++ above c+11.

see <https://en.cppreference.com/w/cpp/feature_test>

currently it works with c++11:

```
g++ --std=c++11 ../singleheader/amalgamate_demo.cpp  -I../singleheader/
g++ --std=c++14 ../singleheader/amalgamate_demo.cpp  -I../singleheader/
g++ --std=c++17 ../singleheader/amalgamate_demo.cpp  -I../singleheader/
g++ --std=c++2a ../singleheader/amalgamate_demo.cpp  -I../singleheader/
```
and not with prior C++11:
`g++ --std=c++98 ../singleheader/amalgamate_demo.cpp  -I../singleheader/
`

**Comment by jkeiser** [comment]
@ostri we do actually give a reasonable error at compile time; I think @lemire is talking about adding the C++11 requirement in documentation.

Feature testing would be a good idea though!

**Comment by jkeiser** [comment]
Brief note: I toyed with c++98, but definitely came away with the impression that the task would be herculean.

**Comment by ostri** [comment]
> Brief note: I toyed with c++98, but definitely came away with the impression that the task would be herculean.

Why don't you catch low hanging fruits first? Set c++20 as standard.
Only after you'll have customers that need lower standard and they are willing to pay, you'll go back.
When modules are implemented(c++20), no one will want to go back anyway.

With decent standard you can also purify the header (string_view, memory allocation, ...)
You'll "die" if you want to backport thread support to C++98 standard. ;-)

**Comment by jkeiser** [comment]
We're already at C++11 and I'm happy to keep it that way :) I'd like to support newer features where we can like with inline destructuring, but we should still work well under older versions: a lot of other projects or libraries support older versions of C++ and we'd like them to be able to incorporate simdjson.
