### ISSUE TITLE
Include Node.js native JSON parser in comparison stats/charts

### ISSUE THREAD

**Issue by csuwildcat** [simdjson/simdjson#80]
Any way you can include the native Node.js runtime's JSON.parse() so folks can get a sense of this solution vs a native Node.js baseline?

**Comment by lemire** [comment]
From the paper (https://arxiv.org/pdf/1902.08318.pdf):

> Other parsers are tightly integrated into larger frameworks, making it difficult to benchmark them fairly. For methodological simplicity, we also do not consider parsers written in Java or other languages.

Marked as "help wanted".

I would point out, meanwhile, that it ought to be relatively easy to take large files (look at jsonexamples), load them up using node's parser and measure the time spent.

**Comment by geofflangdale** [comment]
I would be happy to have a 'contributed benchmarks' page which serves as a clearinghouse for benchmarks of simdjson done by third parties against anything that they are sufficiently motivated to test against. I don't see us taking on the task of benchmarking against many different JSON implementations on many different platforms.

**Comment by csuwildcat** [comment]
My only reason for suggesting you include Node.js/Chromium's implementation
is that it represent the vast majority of JSON parsing that occurs in the
world (via 70% market share in browsers and one of the most used server
envs). I'd argue it's the de facto baseline, and not including makes all
other library-level comparisons a sort of untethered, relative measure.
Just my 2¢.

I've never written a test like this before, so I'd need help understanding
what you're doing in your current tests, then have someone verify that I
did it right afterwards.

**Comment by lemire** [comment]
The disagreement is not about whether it is a good thing but as to whether it needs to be done in the simdjson repository/project.

**Comment by lemire** [comment]
The wrapper for node is not perfect, and I am sure it will massively improve (give people a break: it was obviously written very quickly). However, we can check the numbers already. The differences range between 2x and 5x in favour of simdjson.

```
apache_builds.json#simdjson x 7,622 ops/sec ±0.58% (89 runs sampled) => 0.00013120465355748363
apache_builds.json#JSON x 1,391 ops/sec ±1.13% (90 runs sampled) => 0.0007187123801716652
canada.json#simdjson x 236 ops/sec ±0.55% (84 runs sampled) => 0.004240565511370573
canada.json#JSON x 42.67 ops/sec ±1.31% (56 runs sampled) => 0.023433125946428573
citm_catalog.json#simdjson x 116 ops/sec ±0.57% (74 runs sampled) => 0.00862821200096525
citm_catalog.json#JSON x 79.48 ops/sec ±1.87% (68 runs sampled) => 0.012581310435294117
github_events.json#simdjson x 3,306 ops/sec ±0.43% (95 runs sampled) => 0.0003024769703496055
github_events.json#JSON x 1,650 ops/sec ±1.23% (92 runs sampled) => 0.000606156420195201
gsoc-2018.json#simdjson x 281 ops/sec ±0.59% (88 runs sampled) => 0.003557362459253248
gsoc-2018.json#JSON x 57.99 ops/sec ±2.26% (60 runs sampled) => 0.017244597679166664
instruments.json#simdjson x 4,298 ops/sec ±0.56% (95 runs sampled) => 0.0002326451132910277
instruments.json#JSON x 1,033 ops/sec ±1.79% (88 runs sampled) => 0.0009677125544015644
marine-ik.json#simdjson x 161 ops/sec ±0.59% (81 runs sampled) => 0.0062001457338820305
marine-ik.json#JSON x 43.48 ops/sec ±1.29% (57 runs sampled) => 0.023001695748538015
mesh.json#simdjson x 693 ops/sec ±0.64% (91 runs sampled) => 0.0014432593387370893
mesh.json#JSON x 196 ops/sec ±1.21% (82 runs sampled) => 0.0051030897583148535
mesh.pretty.json#simdjson x 370 ops/sec ±0.81% (84 runs sampled) => 0.002700871435166786
mesh.pretty.json#JSON x 142 ops/sec ±1.33% (80 runs sampled) => 0.0070244677156250015
numbers.json#simdjson x 3,710 ops/sec ±0.52% (92 runs sampled) => 0.00026952393988960194
numbers.json#JSON x 980 ops/sec ±1.49% (88 runs sampled) => 0.001020789959175084
random.json#simdjson x 318 ops/sec ±0.50% (88 runs sampled) => 0.003142749020011699
random.json#JSON x 119 ops/sec ±2.29% (75 runs sampled) => 0.008408114811428573
twitter.json#simdjson x 334 ops/sec ±0.47% (87 runs sampled) => 0.002995028150702426
twitter.json#JSON x 156 ops/sec ±1.49% (79 runs sampled) => 0.006392268774964838
twitterescaped.json#simdjson x 1,153 ops/sec ±0.52% (93 runs sampled) => 0.0008673295529352932
twitterescaped.json#JSON x 340 ops/sec ±1.63% (85 runs sampled) => 0.002938425365325077
update-center.json#simdjson x 384 ops/sec ±0.57% (90 runs sampled) => 0.002606976810584796
update-center.json#JSON x 130 ops/sec ±2.30% (73 runs sampled) => 0.007703586972358122
```

**Comment by csuwildcat** [comment]
This is helpful, I really appreciate yoi including this measure. We're
always actively searching to improve a critical JSON.parse() aspect of an
open source project we're developing, and the native Node env is always the
starting point we check against. We've considered some GPU strategies and
other directions, so I'd love to read a blog posting about your experience
and realizations as you tackled this work.

**Comment by luizperes** [comment]
Hi @csuwildcat, I've spent some time thinking about what you just said (I think I mention it somewhere [here](https://github.com/luizperes/simdjson_nodejs/issues/5)). I might work on it in the future. Will let you know if I do!

**Comment by lemire** [comment]
I am going to close this. It really belonds to the Node bindings, downstream, and we have lots of comparisons now.
