### ISSUE TITLE
cl.exe on VS 2019 emits exception handler warnings

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#807]
```cmd
> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
> cd src
> cl /c /I..\include simdjson.cpp

Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28614 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

simdjson.cpp
The contents of <string_view> are available only with C++17 or later.
The contents of <optional> are available only with C++17 or later.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\ostream(408): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\ostream(401): note: while compiling class template member function 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(double)'
C:\Users\john\Source\simdjson\include\simdjson/inline/document.h(279): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(double)' being compiled
C:\Users\john\Source\simdjson\include\simdjson/padded_string.h(121): note: see reference to class template instantiation 'std::basic_ostream<char,std::char_traits<char>>' being compiled
```

**Comment by jkeiser** [comment]
Note this is *not* the same as what happens when you make a new project. It's just what happens when you use cl.exe with no arguments.

**Comment by jkeiser** [comment]
This only appears to emit warnings when you do `ostream << double`.

**Comment by jkeiser** [comment]
According to [this](https://support.microsoft.com/en-us/help/154419/frequently-asked-questions-about-the-standard-c-library), you just aren't supposed to use the C++ standard library without exceptions? They have a bunch of code in there to switch on it ...

Anyway, by default in cl.exe exceptions are enabled, but it won't call destructors on in-scope objects. Apparently Microsoft's ostream is not clean in this regard. _HAS_EXCEPTIONS is in fact defined on, and I don't really think we should turn it off and make the decision for our users.

I suspect this is a "document it and move on" case. There isn't a code fix for us.

**Comment by jkeiser** [comment]
[RapidJSON's solution](https://github.com/Tencent/rapidjson/issues/428) was basically to make sure and not use STL.

**Comment by lemire** [comment]
Is this a bug?

**Comment by jkeiser** [comment]
I no longer think so. Worth investigating if there is a way, but cl.exe without arguments is way less common than default visual studio project.

**Comment by lemire** [comment]
Closing this issue. Reopen if you think there is more to do.

See https://github.com/simdjson/simdjson/pull/1256
