### ISSUE TITLE
Amalgamate.sh should print detailed paths for included files

### ISSUE THREAD

**Issue by pps83** [simdjson/simdjson#808]
![image](https://user-images.githubusercontent.com/1614246/80293740-bc6dcf00-8783-11ea-9875-d7f570882e92.png)

That's a recent regression. On the right of the screenshot is the version from a few days ago.

**Comment by jkeiser** [comment]
Oh! So we're saying I or somebody *regressed* it. The one on the right is the one I like more, I think.

**Comment by pps83** [comment]
> Oh! So we're saying I or somebody _regressed_ it. The one on the right is the one I like more, I think.

Yes, the one on the right what was there before. amalgamate.sh prints `end of $RELFILE` or something, while that variable is never set. I think it would be much easier to handle if it was amalgamete.c :)

**Comment by jkeiser** [comment]
Ouch!
