### ISSUE TITLE
Use the new DOM navigation API instead (see doc/usage.md) - ???

### ISSUE THREAD

**Issue by Dariusz1989** [simdjson/simdjson#819]
Hey

I can't find usage.md nor how to properly configure it so I don't have that warning.

Win10x64/msvc2019/clion.

I'm just including the one h/cpp combo to try the lib out.

Regards
Dariusz

**Comment by jkeiser** [comment]
Hmm, perhaps we should (a) give a direct URL, and (b) jump directly to why the warning exists and how to fix it. What code are you having the issue on?

This is the place to look: https://github.com/simdjson/simdjson/blob/master/doc/basics.md#using-the-parsed-json

**Comment by Dariusz1989** [comment]
Hey

I'm not running any code. Just imported lib and hit compile to see if anything pops up. This pretty much shows up with a clean void main() function. Do I need to create a macro or something to get rid of it?

I'm just starting, actually trying to convert my string value to QString...  :- )

Thanks for the link, I will go over it again.

**Comment by jkeiser** [comment]
So you haven't actually called any simdjson APIs in your code? Did you import them into a new Visual Studio project, and then make a main() like this?

```c++
#include "simdjson.h"
int main() {}
```

If that's the case, where did you grab the lib from? I'd definitely want to debug :)

**Comment by Dariusz1989** [comment]
Latest release :- )

**Comment by jkeiser** [comment]
If you are still getting the warning let us know and link your code, even if it seems trivial :)

You can also try grabbing the .cpp / .h from master--we've done a lot of work since v0.3.1 to get rid of warnings on Windows: https://github.com/simdjson/simdjson/tree/master/singleheader. But I don't recall fixing or seeing the warning you're getting, so this might be something else.

**Comment by jkeiser** [comment]
... oh. This might be coming from simdjson.cpp. Yeah, if you don't mind, try the .cpp/.h from that link ...

**Comment by Dariusz1989** [comment]
Hey

Looks to be fixed using your link. Thank you!

**Comment by jkeiser** [comment]
Oh good! OK. Happy parsing!
