### ISSUE TITLE
Document the CMake targets as part of our main documentation

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#820]
One should not need to read the cmake files to find out about  checkperf-parse.

**Comment by jkeiser** [comment]
Just a note (which documentation would have helped with :): in the case you cited you're better off running `make checkperf` or `cmake --build . --target checkperf`, which builds everything needed for checkperf to run.

**Comment by lemire** [comment]
Delaying to 0.5.

**Comment by lemire** [comment]
Users can type `cmake --build . --target help`.


I am going to close this because I don't think we want to maintain such a documentation. It would be mostly good for internal use.
