### ISSUE TITLE
Under the regular Visual Studio compiler, arch:AVX2 should not help performance

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#828]
There are reports that breaking runtime dispatch and using the arch:AVX2 at compile time under Visual Studio boost the performance by ~10%. This should not happen.

Reference: https://github.com/simdjson/simdjson/issues/812

**Comment by jkeiser** [comment]
I don't believe this is true anymore; it was based on me reading the wrong numbers in the reports, and those numbers are highly variable. When I looked at the GB/s numbers, they stayed the same with /arch:AVX2 and not.

Reopen if this is based on anyone's report besides mine :)
