### ISSUE TITLE
We should manually review the inlining under Visual Studio

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#829]
The flags `/d2inlinelogfull:FunctionName` and `/d2inlinestats` allow us to review the inlining decisions made by Visual Studio 2019. We should review them, as carefully as possible, to rule out any problem.

https://github.com/simdjson/simdjson/issues/812

**Comment by jkeiser** [comment]
We absolutely should. It's worth noting that @terrymah, the owner of MSVC's inlining, believes most of stage 1 is inlined and that __forceinline is respected. The overall `/d2inlinestats` numbers reflect this, without having dug into what was and wasn't specifically inlined:

```
CL.exe /c /d2inlinestats /I..\src /I..\include /nologo /W3 /WX /diagnostics:column /sdl /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D_CRT_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"src\simdjson.dir\Release\\" /Fd"src\simdjson.dir\Release\simdjson.pdb" /Gd /TP /errorReport:queue ..\src\simdjson.cpp
simdjson.cpp
Success: 23801
Gather Candidates (72):
        varargs: 1
        not eligible: 54
        postdominated by noreturn call: 9
        soft depth exceeded: 10
ShouldInline: 279

Heuristic Stats:
        CMPS folded: 52
        Function Calls Devirtualized: 0
        Total Devirt Inlinees: 0
        Total Devirt Branches: 0
        Total Devirt Branches Removed: 0

Heuristic Acceptance Counts:
        force inline: 21182
        optimized to trivial routine: 480
        small function: 1426
        callgraph decision: 713
```

**Comment by lemire** [comment]
Note that `-Rpass=inline` under clang seem to provide  a similar analysis, so it should be possible to see whether a given function is inlined in both or neither compilers.

**Comment by lemire** [comment]
When compiling in somewhat different conditions under /Ox with Python setup tools, [I get different results](https://github.com/lemire/simple_simdjson_python_wrapper)... but then it is somewhat different code since this is a Python wrapper...

```
/Ob1

Success: 29545
Gather Candidates (4495):
        parameter mismatch: 2205
        has try: 12
        varargs: 4023
        not eligible: 4453
        postdominated by noreturn call: 28
        soft depth exceeded: 14
ShouldInline: 224
InlineeTree (56):
        late size check: 56

Heuristic Stats:
        CMPS folded: 277
        Function Calls Devirtualized: 0
        Total Devirt Inlinees: 0
        Total Devirt Branches: 0
        Total Devirt Branches Removed: 0

Heuristic Acceptance Counts:
        additional inlinees saved by optimized inlining: 461
        force inline: 24720
        preexec force: 9
        optimized to trivial routine: 1108
        small function: 1176
        callgraph decision: 816
        simple decision: 1255
Finished generating code


/Ob2


Success: 29259
Gather Candidates (4132):
        parameter mismatch: 2205
        has try: 16
        varargs: 4023
        not eligible: 4076
        postdominated by noreturn call: 28
        soft depth exceeded: 15
ShouldInline: 271
InlineeTree (166):
        late size check: 166

Heuristic Stats:
        CMPS folded: 243
        Function Calls Devirtualized: 0
        Total Devirt Inlinees: 0
        Total Devirt Branches: 0
        Total Devirt Branches Removed: 0

Heuristic Acceptance Counts:
        additional inlinees saved by optimized inlining: 252
        force inline: 24735
        preexec force: 9
        optimized to trivial routine: 958
        small function: 1223
        callgraph decision: 782
        simple decision: 1300
Finished generating code

/Ob3

Success: 28319
Gather Candidates (153):
        parameter mismatch: 27
        has try: 12
        varargs: 45
        not eligible: 98
        postdominated by noreturn call: 32
        soft depth exceeded: 14
ShouldInline: 235

Heuristic Stats:
        CMPS folded: 255
        Function Calls Devirtualized: 0
        Total Devirt Inlinees: 0
        Total Devirt Branches: 0
        Total Devirt Branches Removed: 0

Heuristic Acceptance Counts:
        additional inlinees saved by optimized inlining: 347
        force inline: 23761
        preexec force: 9
        optimized to trivial routine: 1287
        small function: 1619
        callgraph decision: 1295
        simple decision: 1
Finished generating code
```

**Comment by terrymah** [comment]
My thoughts:
- Almost *all* of your inlining is happening because of __forceinline. This to me says you may think you have inlining "solved" and already aggressively marked what you think are the important inline sites in your program. That's not entirely uncommon, but in this case, tweaking the inliner heuristics might not make that big of a difference.
- It's kind of hilarious that the number of inline instances goes down the more permissive you make inline candidate selection. This is counter intuitive, but can happen because inlining "downstream" can make inline candidates appear less appealing "upstream"
- Ob2 vs Ob3 is most visible in the "callgraph decision" line: there are some internal numbers here that get bumped up in Ob3. But still, it's funny the total number of instances went down.

**Comment by terrymah** [comment]
Ultimately guys, I don't think this problem will be solved by staring at benchmark results and inliner stats. At some point someone needs to just put the thing under a profiler and see why it's slower. It might end up being literally *one* inline decision, or *one* code generation difference (some optimization MSVC misses, or some "bad" optimization MSVC makes)

**Comment by lemire** [comment]
@terrymah I have been toying for some time with /d2inlinelogfull:FunctionName, but I cannot get any output whatsoever. Should it just be printing something... or logging something out somewhere?
> tweaking the inliner heuristics might not make that big of a difference.

That's what I would think but @TkTech and myself get a 2x difference between Ob2 and Ob3. It does not occur in our main builds (pure C++), but it happens with the python setup build (the numbers I report are from this simple python extension build).


Maybe it is an artefact of something else, but @TkTech is absolutely correct to report that in some cases Ob3 fares much better than Ob2. This must be resolved.

**Comment by terrymah** [comment]
Interesting. In that case looking at the total number of instances is probably a bad idea, perhaps Ob3 is catching one specific key inline decision that is otherwise being missed. Like I said, I think a profiler is the next step.. I doubt this is a widespread problem in codegen across the binary, it's more likely to be one specific decision out of a million that just happens to matter a ton.

Regarding the output; are you on the latest VS2019?

**Comment by lemire** [comment]
> Regarding the output; are you on the latest VS2019?

I think I am. Updated last week.

Note that I can't seem to get any output out of `/d2inlinelogfull:FunctionName`.

**Comment by TkTech** [comment]
`/d2inlinelogfull:FunctionName`: are you replacing the FunctionName? ex: `/d2inlinelogfull:malloc`. It's not literally FunctionName.

**Comment by lemire** [comment]
@TkTech Oh. That's not very useful then unless you know where the problem is.

**Comment by lemire** [comment]
If I read the documentation correctly, "/WX /W3 /w34714" should fail whenever a "forced" inline function was not inline. I get no failure...

https://github.com/simdjson/simdjson/pull/1025/

**Comment by terrymah** [comment]
/d2inlinelogfull:* will give you the detailed inline log of every function in the binary, but that is quite verbose. 

I don't think forceinline is failing; it rarely does, and typically only for a small set of fixed reasons (if you have a try/catch inside a forceinline function, etc)

I really think profiling it is what you want to do; that could point out a function which is taking more time and show you where the problem might be, etc.

**Comment by lemire** [comment]
> I really think profiling it is what you want to do; that could point out a function which is taking more time and show you where the problem might be, etc.

I am sure that it is what is needed, but while I can easily profile any application on a POSIX system, my skills with Windows are limited and it is not like anyone else has jumped at the opportunity. I can use vtune, of course, but then I get that the time is used up by four functions. That is two too many. In release mode, vtune won't give me the function names, just the addresses. If this were Linux, I'd map the addresses back to function names in one second, but I don't know how to do it under Windows.



Anyhow, the running time should be dominated by two functions. That's what I get everywhere (including under msys2), but under Visual Studio, there are four functions. 

I am trying to find out what they are.

The fact also that Ob3 seems to help in some cases, massively, is another indication of an inlining problem.

It seems that our force_inline are respected. That is good, if that is correct. So maybe we are just missing a couple of those... Or it is something more complicated. I don't know. I'd love to find out.


Of course, this should be profiled by someone who knows who to profile Windows software. Not me. But me is all we got.

**Comment by terrymah** [comment]
Add /Zi to the command line for cl.exe and /DEBUG to the command line for
link.exe, and you'll get a .pdb file, which vtune should automatically pick
up and use to give you function names of those 4 functions. Not sure how to
do this in your build system.

**Comment by lemire** [comment]
@terrymah I added /Z7  and /Zi some time ago. I will see about /DEBUG in the linker.

**Comment by lemire** [comment]
@terrymah 

Ok. This did it. I was missing the /DEBUG in the link routine. Somehow this made the four functions collapse into the two functions that I was expecting. Before I was getting 4 addresses, but now I get two function names that match what I would expect...

<img width="1888" alt="Screen Shot 2020-07-06 at 11 59 02 AM" src="https://user-images.githubusercontent.com/391987/86613936-41454800-bf80-11ea-9ba4-3f361acd075a.png">

So the inlining works as I expected.

Note that our "parse" routine already reports these same timings (under the name stage 1 and stage 2) so we don't really need vtune to get this information but it is nice confirmation.


Now... as for figuring things out when you call simdjson from Python, that's a whole other project.

**Comment by lemire** [comment]
Thanks to @terrymah 's technical clue, I think we can now close this. There is no inlining issue that I can see when building the code directly into a C++ benchmark program.

There might be inlining issue when linking against a Python interpreter but I don't have an angle of attack to study this problem. Ideas invited.

I will leave this issue open for a while in case someone wants to raise an issue.

**Comment by terrymah** [comment]
Can you manually compare the assembly of those two hot functions and see if any drastic differences jump out? Maybe a loop that isn't unrolled, a missing intrinsic (MSVC makes a function call instead of an intrinsic expansion of some operation), etc.

**Comment by lemire** [comment]
@terrymah [That's where I started, actually, back in May](https://github.com/simdjson/simdjson/issues/847#issuecomment-628799072). There are thousands of instructions to look at. Unless you know what to look for, it is hard. At least, it is hard for me. 

I was preoccupied by a bit decoding routine in stage 1, so I looked specifically at its assembly and it looked fine to me.

I aggregated all instructions and compared with ClangCL and though they make different choices, it is not like, for example, Visual Studio would generate a much larger or much smaller binary... I looked for the instructions that I want the kernels to use, and they were there.

One way that clang differs from Visual Studio is that you can tell it to use some instructions over a given region of code, and we do so. So this gives clang an advantage in the sense that it could use SIMD instructions that we have not planned for. However, compiling visual studio with an AVX flag did not solve the problem.

So the puzzle remains.

**Comment by lemire** [comment]
> MSVC makes a function call instead of an intrinsic expansion of some operation

I would assume that Intel intrinsics are always inlined. Aren't they _force_inline?

**Comment by TkTech** [comment]
__forceinline is a "lie", msvc may decide not to inline based on its own heuristics. To be fair the documentation on inlining does make that clear.

**Comment by terrymah** [comment]
@lemire Not every compiler implements intrinsics the same way. Sometimes they are emitted directly inline with special code generation logic. This takes a lot of work. Sometimes they are calls into a library. Generally that is easier to write. When I say "missing intrinsics" I'm referring to intrinsics which are implemented as a library call and don't have bespoke code generation logic.

@TkTech If it's physically possible to inline a __forceinline function, MSVC will inline it. No heuristics are involved. We emit a warning if we ever fail to inline a forceinline call. You're thinking of the "inline" keyword, which has to do more with providing an ODR exception than anything to do with inlining (although, as I recall, there is a small bonus for being decorated with "inline").

**Comment by lemire** [comment]
@TkTech Well... there is a level 4 warning that we can enable and that I did enable (now in simdjson CMake but also in my python demo) that should fire whenever _force_inline is not respected.

Maybe my understanding is off... but it seems that all of our _force_inline are respected. 

You can even get warnings when inline (not forced inline) is not respected but that did not trigger many warnings for us.

I did verify your Ob3 perf boost when simdjson is called from Python. So something is going on, but I don’t think it has to do with _force_inline not being respected.

It might have to do with the lambdas... I think that’s what you were hinting at... but I removed a bunch just now. It did improve performance under Visual Studio. (Nothing like 2x though.) I have not yet revisited the Python results. Please do so if you can with the code in our main branch.

It is possible that I might have helped that particular Python issue...

**Comment by lemire** [comment]
> @lemire Not every compiler implements intrinsics the same way. Sometimes they are emitted directly inline with special code generation logic. This takes a lot of work. Sometimes they are calls into a library. Generally that is easier to write. When I say "missing intrinsics" I'm referring to intrinsics which are implemented as a library call and don't have bespoke code generation logic.


Ok. That makes sense.

**Comment by lemire** [comment]
@terrymah 

> When I say "missing intrinsics" I'm referring to intrinsics which are implemented as a library call and don't have bespoke code generation logic.

I reviewed the intrinsics that we use and I don't think it is likely that any of them would fall in this category.

**Comment by lemire** [comment]
I am closing this as I am now quite sure that there is no inlining problem.

It is possible that Visual Studio has faults, but inlining is not it.
