### ISSUE TITLE
CMake find_package can not find simdjson

### ISSUE THREAD

**Issue by myd7349** [simdjson/simdjson#830]
**Describe the bug**
I am trying to update vcpkg's simdjson to lastest recently, and found that simdjson's CMake module seems broken on Windows(and maybe on other platforms too) because of unknown target.

**To Reproduce**
I created a small project here to reproduce this problem: https://github.com/myd7349/simdjson-cmake-example

and the [CI log](https://github.com/myd7349/simdjson-cmake-example/runs/630199117?check_suite_focus=true) shows that:
```
The file was found at

    D:/a/simdjson-cmake-example/simdjson-cmake-example/simdjson/build/install/lib/cmake/simdjson/simdjson-config.cmake



CMake Error at CMakeLists.txt:5 (find_package):
  Found package configuration file:

    D:/a/simdjson-cmake-example/simdjson-cmake-example/simdjson/build/install/lib/cmake/simdjson/simdjson-config.cmake

  but it set simdjson_FOUND to FALSE so package "simdjson" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  simdjson-headers simdjson-source simdjson-flags
```

After some investigation, I found that these targets are exported to cmake config files in a `simdjson-private` subdir. But none of these cmake file are included by the `simdjson-config.cmake`.

**Configuration (please complete the following information if relevant):**
 - OS: [e.g. Ubuntu 16.04.6 LTS]
 - Compiler [e.g. Apple clang version 11.0.3 (clang-1103.0.32.59) x86_64-apple-darwin19.4.0]

**Indicate whether you are willing or able to provide a bug fix as a pull request**

If you plan to contribute to simdjson, please read our 
* CONTRIBUTING guide: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md and our
* HACKING guide: https://github.com/simdjson/simdjson/blob/master/HACKING.md

**Comment by lemire** [comment]
@jkeiser  refers to https://gitlab.kitware.com/cmake/cmake/issues/15415#note_633938 in CMake.

**Comment by jkeiser** [comment]
@myd7349 thanks tons for the detailed bug report :)
