### ISSUE TITLE
Consider documenting direct CMake usage as a dependency

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#833]
I wrote a small demo on how one could use simdjson as a CMake dependency...

https://github.com/simdjson/cmakedemo

It works... but it wasn't as easy as it should: figuring out how to turn off SIMDJSON_COMPETITION was annoying.

Also, you need to set EXCLUDEFROMALL.

**Comment by jkeiser** [comment]
Google Benchmarks has this same problem. This is what I had to do to get rid of all the extraneous stuff: https://github.com/simdjson/simdjson/blob/master/dependencies/CMakeLists.txt#L16-L23

Perhaps we should default to only building the lib, and require users to specify a -DSIMDJSON_TEST=ON to enable tests and such?

**Comment by lemire** [comment]
I am going to close this since we now document it with a rather clean example.
