### ISSUE TITLE
In CI, remove the checkperf from the sanitize builds

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#839]
We are apparently looking for performance degradation in the sanitize builds...
<img width="689" alt="Screen Shot 2020-04-30 at 3 50 12 PM" src="https://user-images.githubusercontent.com/391987/80752888-57570800-8afa-11ea-8134-bc077d43b640.png">

**Comment by lemire** [comment]
Hoping that this is gone.

**Comment by jkeiser** [comment]
Oh! Yeah, I fixed it in the linked checkin.
