### ISSUE TITLE
stderr and abort prevent R usage

### ISSUE THREAD

**Issue by knapply** [simdjson/simdjson#891]
As requested in https://github.com/eddelbuettel/rcppsimdjson/issues/10#issuecomment-630838200

`stderr` and `abort` cause `R CMD check` warnings for [`RcppSimdJson`](https://github.com/eddelbuettel/rcppsimdjson).

```{sh}
git clone https://github.com/dcooley/rcppsimdjson # has latest simdjson
cd rcppsimdjson
R CMD check --no-tests .

.....

## * checking compiled code ... WARNING
## File ‘RcppSimdJson/libs/RcppSimdJson.so’:
##   Found ‘abort’, possibly from ‘abort’ (C)
##     Object: ‘simdjson_example.o’
##   Found ‘stderr’, possibly from ‘stderr’ (C)
##     Object: ‘simdjson_example.o’
## 
## Compiled code should not call entry points which might terminate R nor
## write to stdout/stderr instead of to the console, nor use Fortran I/O
## nor system RNGs.

.....
```

Here is the affected code that I'm seeing in the main library...

https://github.com/simdjson/simdjson/blob/25fe6d7dde512703c7dedfdb9180ea69946261a3/src/implementation.cpp#L133-L134

and here's the affected code in the single-header files used by `RcppSimdJson`...

https://github.com/simdjson/simdjson/blob/8927a0561f7ef7e5b1830cb2b19f8418b27cbbfd/singleheader/simdjson.cpp#L584-L585

https://github.com/simdjson/simdjson/blob/8927a0561f7ef7e5b1830cb2b19f8418b27cbbfd/singleheader/simdjson.h#L3611

https://github.com/simdjson/simdjson/blob/8927a0561f7ef7e5b1830cb2b19f8418b27cbbfd/singleheader/simdjson.h#L5644

https://github.com/simdjson/simdjson/blob/8927a0561f7ef7e5b1830cb2b19f8418b27cbbfd/singleheader/simdjson.h#L3611

I am willing to provide a fix, but I am unsure what the preferred path would be.

The solution for `stderr` seems to be just removing the code, as was the case in #455, but I'm not seeing a precedent for `abort`. Please advise.

**Comment by lemire** [comment]
Thank you.

**Comment by lemire** [comment]
So we cleaned out stderr and aborts but they came crawling back. It is my fault for not adding tests.

PR https://github.com/simdjson/simdjson/pull/893 should resolve the matter. I have added tests so they should not come back.

**Comment by knapply** [comment]
@lemire Thank you so much for tackling this (and so quickly!).

I just checked the new amalgamated files in https://github.com/simdjson/simdjson/pull/893 and everything seems good to go. 

Unless you'd prefer otherwise, I'll close this issue once the PR is merged.

**Comment by lemire** [comment]
> Unless you'd prefer otherwise, I'll close this issue once the PR is merged.

We shall be closing it, don't worry. It just takes longer for us to merge PR because we are (despite appearances to the contrary) extremely careful.  

This is not a "move fast and break things" project. :-)

**Comment by knapply** [comment]
Rest assured, I haven't thought that this is anything but a world-class engineering project,.. and I'm definitely not the only one!.

Thank you again!
