### ISSUE TITLE
simdjson as an msys package

### ISSUE THREAD

**Issue by shavesha** [simdjson/simdjson#905]
please submit  simdjson as an msys package it will make life much much easier for windows programmers

**Comment by lemire** [comment]
The simdjson library is a community project. Are you willing to prepare and submit a package?

**Comment by lemire** [comment]
@lazka @Biswa96 : Can we close this issue? It seems like the following PR should provide simdjson to msys2 users, right?

https://github.com/msys2/MINGW-packages/commit/c503eddeb7414b87da6b2caf9f4835ad800bdae5

**Comment by Biswa96** [comment]
Thought it is added in MINGW-packages repository, it is not added in as a package in Pacman repositry. i.e. users can't download it now. So, in my opinion this issues is not yet resolved.

**Comment by Biswa96** [comment]
Though it has been added in MINGW-packages repository, it is not added in as a package in Pacman repository. i.e. users can't download it now. There are some changes in maintainership in msys2. So, packaging will take some time. In my opinion, this issues is not yet resolved.

**Comment by shavesha** [comment]
Building and installing is possible with some extra work. Although i ran into a problem don't know if its part of the install process. thanks @Biswa96 for the assistance. I used mingw64 terminal.
1. clone git repo: $git clone https://aur.archlinux.org/simdjson.git
2. change directory : $cd simdjson (in my case the repo is in msys2/home/${my_user_name}/simdjson)
3. make the package: $ makepkg -s (install or update any dependencies e.g jsoncpp in my case)
4. finally: $ makepkg --install

I had to add a find_package(Threads) to my cmake file. i ran one of the basics examples and it failed with a Signal: SIGILL (Illegal instruction)
![simdjson Signal SIGILL (Illegal instruction)](https://user-images.githubusercontent.com/30215247/86463959-23fc4980-bcf4-11ea-9dd2-ae2db1af5039.jpg)

**Comment by lazka** [comment]
You need to use makepkg-mingw for mingw packages

**Comment by shavesha** [comment]
ahh. I will be back! thanks

**Comment by lemire** [comment]
I tried to follow @shavesha  instructions, but the package does not build when I type `makepkg-mingw -s`.

<img width="560" alt="Screen Shot 2020-07-03 at 6 30 53 PM" src="https://user-images.githubusercontent.com/391987/86499869-57be8a00-bd5b-11ea-8072-b3247902b313.png">

**Comment by lazka** [comment]
you're probably missing `pacman -S --needed base-devel mingw-w64-x86_64-toolchain` (yeah, out docs need work..). Either way, simdjson is now in the repo.

**Comment by lemire** [comment]
@lazka Verified as fixed!

The package is indeed there...
https://packages.msys2.org/base/mingw-w64-simdjson


Instructions...

Get MSYS2. Start a MinGW 64-bit console. Type...

```
pacman -Syu 

pacman -S mingw-w64-x86_64-simdjson
```

create a file test.cpp with the following content :

```
#include "simdjson.h"
int main(void) {
  simdjson::dom::parser parser;
  simdjson::dom::element tweets = parser.load("twitter.json");
  std::cout << tweets["search_metadata"]["count"] << " results." << std::endl;
}
```

Then get the `twitter.json` file:

wget https://raw.githubusercontent.com/simdjson/simdjson/master/jsonexamples/twitter.json

Compile and run...

```
g++ -o test test.cpp -lsimdjson

./test twitter.json
```

Thanks to all!
