### ISSUE TITLE
Buffer overrun on incomplete document (if not null terminated)

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#906]
If you have an incomplete document, stage 1 will scan past the end of the detected structural indexes, most of which are either uninitialized or filled with data from other parses. Those indexes will sometimes point outside the buffer.

The minimal example is the document `[` with padding `[[[[[[[[[[[[[[[[` (1 byte doc + 16 bytes). Instead of noticing it's at the end of the document, stage 2 will parse the next structural index.

Most of the time this is fine since stage 1 pads the structural indexes with a `len`, and our buffer padding usually has spaces or a terminating `\0`. But our current contract is the user doesn't have to guarantee anything about their buffer padding, and if the character there happens to be a `[`, we'll happily continue to the next index (which stage 1 sets to 0), and as long as that's `[`, we'll start accessing uninitialized indexes.

Basically, we're relying on the buffer padding having invalid characters in it and forcing us to terminate.

It didn't *crash* on my machine, but [this branch](https://github.com/simdjson/simdjson/tree/jkeiser/buffer-overrun) has the test with logging enabled, and you can see it access buffers that have nothing to do with it:

```c++
  bool padded_with_open_bracket() {
    std::cout << __func__ << std::endl;
    simdjson::dom::parser parser;
    // This is an invalid document ([]), but it's padded with open braces so we overrun the buffer.
    auto error = parser.parse("[[[[[[[[[[[[[[[[[", 1, false).error();
    if (error) { std::cerr << "Error: " << error << std::endl; return false; }
    return true;
  }
```

```
Running basic tests.
padded_with_open_bracket

| Event                          | Buffer               | Curr | Next | Next# | Detail                                             |
|--------------------------------|----------------------|------|------|-------|----------------------------------------------------|
| +document                      | [[[[[[[[[[[[[[[[[ Er |    [ |    [ |     1 |                                                    |
|   +array                       | [[[[[[[[[[[[[[[[[ Er |    [ |    [ |     1 |                                                    |
|     +array                     | [[[[[[[[[[[[[[[[ Err |    [ |    [ |     2 |                                                    |
|       +array                   | [[[[[[[[[[[[[[[[[ Er |    [ |    g |     3 |                                                    |
|         ERROR                  | ght":600,"Title":"Vi |    g |    g |     4 | Non-value found when value was expected!           |
Error: The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.
```

**Comment by jkeiser** [comment]
@lemire it seems like without changing the contract, the least costly solution here would be to pad the structural indexes with 2 `len` values instead of 1. It's within the padding, but that's fine--we don't care what the character is, just that it's the same one twice in a row. The only structurals that can *validly* happen twice in a row are `[`, `]` and `}` (values must be followed by , : ] or }, , and : must be followed by a value, and { must be followed by a string or }). Then we add a branch to those three places to check if we've run off the end of the buffer.

However, there is a zero cost alternative that avoids the extra branches: we could mandate that you terminate your buffer with a non-structural, and offer a version of `parse()` that temporarily sets the terminal character to `\0` while parsing and sets it back after. This would guarantee we would stop as soon as we hit the terminal character. We could also guarantee number parsing and atom parsing would stop at the end of the document, so we wouldn't need special cases for those anymore ...

**Comment by jkeiser** [comment]
Actually ... if we add another 0 at the end of the document (we could even keep the length one if we wanted), that gives us more guarantees. ] and } are invalid at the beginning of a document, so the only possibly valid repeating character there is [. Just one branch, and it's not on objects (which happen more often than arrays in the wild, generally)!

**Comment by lemire** [comment]
If this is real, then this is a regression because stage 1 would handle this issue. Since things have been completely, it is hard to tell when the regression could have happened.

>  and offer a version of parse() that temporarily sets the terminal character to \0 while parsing and sets it back after.

No. Just add a virtual structural character at end of stage 1. No need to touch the data.

**Comment by lemire** [comment]
> However, there is a zero cost alternative that avoids the extra branches: we could mandate that you terminate your buffer with a non-structural, and offer a version of parse() that temporarily sets the terminal character to \0 while parsing and sets it back after. This would guarantee we would stop as soon as we hit the terminal character. We could also guarantee number parsing and atom parsing would stop at the end of the document, so we wouldn't need special cases for those anymore ... Actually ... if we add another 0 at the end of the document (we could even keep the length one if we wanted), that gives us more guarantees. ] and } are invalid at the beginning of a document, so the only possibly valid repeating character there is [. Just one branch, and it's not on objects (which happen more often than arrays in the wild, generally)!

I agree. You have found a real issue that needs fixing. I wonder how we did not find it earlier. Mind you, it can only occur in weird circonstances.

I suggest we document it correctly, both here and in the code.

Ok. So to be clear, at the end of stage 1, we have indexed exactly one byte beyond the end of the string (in the padding region). This is what I called the virtual null character. Then, next, we point at the beginning of the document:

```C++
  if (len != parser.structural_indexes[parser.n_structural_indexes - 1]) {
    /* the string might not be NULL terminated, but we add a virtual NULL
     * ending character. */
    parser.structural_indexes[parser.n_structural_indexes++] = uint32_t(len);
  }
  /* make it safe to dereference one beyond this array */
  parser.structural_indexes[parser.n_structural_indexes] = 0;
```

In the normal course of things, we should never make it beyond the end of the document, this can only happen when the document is invalid. So we need to make it fail.

Your idea would be do double this up... like so...

```C++
  if (len != parser.structural_indexes[parser.n_structural_indexes - 1]) {
    /* the string might not be NULL terminated, but we add a virtual NULL
     * ending character. */
    parser.structural_indexes[parser.n_structural_indexes++] = uint32_t(len);
  }
  parser.structural_indexes[parser.n_structural_indexes++] = 0;
  parser.structural_indexes[parser.n_structural_indexes] = 0;
```

?

*My idea:*

We might be able to do away with the whole thing and just do
```C++
  parser.structural_indexes[parser.n_structural_indexes] = 0;
```

Indeed, we want that if we read the first structural character, we fail, always. Well, when might this not happen? Exactly when the first structural character is '[' as well as the last one ('['), but that's a single check (done once). So we could possibly fix this bug while streamlining it.

Not that the streaming version of stage 2 might be affected... possibly. At a minimum, we should add a version of your test where the input is just the pathological case you have described.


Anyhow, congratulation on finding a bug. We don't tend to find those very much.

**Comment by lemire** [comment]
I have issued a fix in a PR. It is much uglier but I think it works. I still think we could simplify things greatly, but I am preoccupied with fixing this hole as quickly as possible. We can streamline later.

**Comment by lemire** [comment]
Closed.
