### ISSUE TITLE
Core Dump when using pysimdjson

### ISSUE THREAD

**Issue by fuzihaofzh** [simdjson/simdjson#921]
Before submitting an issue, please ensure that you have read the documentation:

* Basics is an overview of how to use simdjson and its APIs: https://github.com/simdjson/simdjson/blob/master/doc/basics.md
* Performance shows some more advanced scenarios and how to tune for them: https://github.com/simdjson/simdjson/blob/master/doc/performance.md
* Contributing: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md

**Describe the bug**
Core dump with 
python 3.7.6.  
pysimdjson : 1.5.0
OS: Centos 3.10.0-957.21.3.el7.x86_64

**To Reproduce**

import simdjson
a = open("test.txt").read()
b = simdjson.loads(a.encode())
[test.txt](https://github.com/simdjson/simdjson/files/4749603/test.txt)

**Comment by lemire** [comment]
Why did you report it here instead of downstream at https://github.com/TkTech/pysimdjson ?

I am running tests over your file and, so far, I have not found it to cause any issue to simdjson.

**Comment by lemire** [comment]
I reported the issue downstream. Closing here. Reopen if you can reproduce the bug with C++...

https://github.com/TkTech/pysimdjson/issues/38

**Comment by lemire** [comment]
The problem, I think, is that pysimdjson uses simdjson 0.1.1 where we, indeed, a bug as to how the data was padded. Probabilistically speaking, it was almost safe, but you could certainly get in trouble some of the time. This was resolved in later versions.

I will patch version 0.1.1 if @TkTech wishes to issue a new pysimdjson based on version 0.1.1. I guess that would be version 0.1.2 at that point. The longer term fix would be for pysimdjson to catch up a little to where simdjson is. Just for the runtime dispatching, it would be worth it for pysimdjson to upgrade.

**Comment by TkTech** [comment]
No point backporting. pysimdjson is already on the latest version in the develop branch. Just needs a bit of work for packaging.
