### ISSUE TITLE
Quick Start is Broken

### ISSUE THREAD

**Issue by anilmaurya** [simdjson/simdjson#928]
**Describe the bug**
Step 1 mention to pull simdjson.h and simdjson.cpp into a directory.
Path mention in command does not exist https://raw.githubusercontent.com/simdjson/simdjson/master/singleheader/simdjson.h https://raw.githubusercontent.com/simdjson/simdjson/master/singleheader/simdjson.cpp

**To Reproduce**
Steps to reproduce the behaviour:
wget https://raw.githubusercontent.com/simdjson/simdjson/master/singleheader/simdjson.h https://raw.githubusercontent.com/simdjson/simdjson/master/singleheader/simdjson.cpp

**Comment by lemire** [comment]
The issue is real. I think John (@jkeiser) deleted the files. Probably by mistake. I am trying to find out why this was allowed at it. It should have failed our tests.

**Comment by anilmaurya** [comment]
Thank you.

**Comment by lemire** [comment]
@anilmaurya Please keep reporting problems!!!

We should have caught this one. We will in the future.
