### ISSUE TITLE
Tune the string serialization for performance (do not use C++ streams)

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#933]
Currently, a parsed document can be serialized back as a minified string. Though it is not a performance-critical aspect of simdjson, we should do some attempt to tune the performance.

**Comment by jkeiser** [comment]
True. We haven't fully expanded into serialization yet, so it's not yet one of the primary aspects of simdjson. There's still a lot we can probably do to tune the performance here; it's just a naive recursive algorithm and there is absolutely no reason it needs to be. We have a self-consistent linear tape, we should have a linear algorithm :)

There are relevant scenarios that *are* performance critical for users, too, including read/edit/write, read/process/write and append ... but I'm skeptical that any of these scenarios are best handled by modifying a full parsed document. I expect we'll want partial parsing for read/edit/write scenarios, reverse partial parsing for append scenarios, and streaming writes for read/process/write scenarios, to be the important bits.

**Comment by lemire** [comment]
cc @geofflangdale

**Comment by lemire** [comment]
Ok. I have written a benchmark that does the following...

```
    std::string serial = simdjson::minify(doc);
```

You can run it with

`./benchmark/bench_dom_api --benchmark_filter=serialize_twitter`.

Predictably, we are entirely bound by the C++ stream functions. They are known to be slow.
