### ISSUE TITLE
Extracting raw recorcd text in parse_many

### ISSUE THREAD

**Issue by Skyprophet** [simdjson/simdjson#937]
In FIshStore, we basically need the following two things from the underlying parser:

1. Extract raw data record (in text) so as to supply the raw storage on the WAL.
2. Extract all related fields and wait for the further parsing.

The second one has been implemented by `dom::element`, but I do not have a way to get the raw text data reference through the current API.

Ideally, I would like an API returns a string reference of each record when using `parse_many` to traverse the records. More or less like this:

```c++
auto res = parser.parse_many(string_buf, length);
for (auto doc: res) {
    StringRef ref = doc.get_ref();
}
```

I understand this will be particularly tricky because all the parsed documents are translated to a tape and `element` is a reference on the **tape** but not the **original text**. I think ultimately, another solution is to directly dump the tape as raw data to FishStore log. Even in that case, having the capability to separate tapes for different record is essential as well.

**Comment by lemire** [comment]
The parser in `parse_many` keeps track of where it is in the input, it has to. So it would be possible to expose the index. It even makes sense.

I am less sure how to do it elegantly as far as the API is concerned.

Pinging @jkeiser

**Comment by lemire** [comment]
I am tentatively marking this as 0.4 in case we can quickly find a way to extend the API to accommodate this request.

**Comment by lemire** [comment]
I have a PR implementing a possible solution. The API is a tad ugly. I don't know how to do better.

I'll wait for feedback from @jkeiser.

**Comment by lemire** [comment]
@Skyprophet 

This is fixed and will be part of 0.4, but the API is experimental and subject to change... for now, it will be a silent feature until we are happy with the API:

```C++
auto stream = parser.parse_many(json,window);
auto i = stream.begin();
for(; i != stream.end(); ++i) {
          auto doc = *i;
           size_t index = i.current_index();
 }
```

You can rely on it, starting with version 0.4, but expect the construction to be replaced in later versions (say 0.5). 

We will make sure that there is a clear upgrade path if we release a new API.

If not, then this may become officially part of our API... in time.

**Comment by Skyprophet** [comment]
Thanks, I will look into it see how it will fit in FishStore.

**Comment by lemire** [comment]
@Skyprophet You would be, very likely, the first user, so we would be very responsive to your feedback and ideas.

We have tests and we are committed to having this functionality work well (for all users) on the long term.
