### ISSUE TITLE
Warning: unused variable `TITLE_SIZE`

### ISSUE THREAD

**Issue by pfirsich** [simdjson/simdjson#953]
When compiling the singleheader version (probably other versions too, haven't checked) I get a warning for an unused variable `TITLE_SIZE` with `-Wall`.

I am Using Ubuntu 20.04 with clang 10.0.0-4ubuntu1 and the bug can be easily reproduced like this:
```
$ clang++ simdjson.cpp -Wall
simdjson.cpp:8149:21: warning: unused variable 'TITLE_SIZE' [-Wunused-const-variable]
constexpr const int TITLE_SIZE = 12;
                    ^
simdjson.cpp:11357:21: warning: unused variable 'TITLE_SIZE' [-Wunused-const-variable]
constexpr const int TITLE_SIZE = 12;
```
This occurs with the master I very recently pulled (`2cc84b6e51df1b71dd08df1f2f3435df2bc47783`)

**Comment by lemire** [comment]
@jkeiser Want to take this one?

**Comment by lemire** [comment]
Verified. I am curious why our tests don't catch this one.

**Comment by jkeiser** [comment]
> Verified. I am curious why our tests don't catch this one.

That is indeed weird.

I haven't looked at this yet, but I'm assuming a reamalgamate will fix it, and one of my PRs does that ... we can see if that shakes out tomorrow.

**Comment by lemire** [comment]
@jkeiser  It is the original source, it comes from this commit...

https://github.com/simdjson/simdjson/commit/ef63a84a3e667f87365cc54e70029e565ddaa3a8

I missed it in my review.

**Comment by lemire** [comment]
When I compile locally, even with clang++, I don't get this warning when going through cmake.

**Comment by lemire** [comment]
Hmmm... I think that the warning is only visible if you compile everything in one unit.

**Comment by pfirsich** [comment]
Did you make sure to compile with `-Wall`? There is no usage of this variable anywhere in the code, can't it just be removed?
If you need me to give any more info or try something out, I'd be glad to help.

**Comment by lemire** [comment]
> Did you make sure to compile with -Wall? 

We compile with a lot more than just `-Wall`.

>  There is no usage of this variable anywhere in the code, can't it just be removed?

I think it can be. It looks like garbage.

Removing it is easy. What puzzles me is why our tests do not catch it... my current guess is that it is a matter of compilation units but I have not had time to investigate.

To be clear, it is a real issue, but we don't just want to fix the issue, we want to also make sure we catch such issues in the future.

**Comment by jkeiser** [comment]
Seconded. One of the headlining features of the upcoming 0.4 is being warning free (i.e. compiling clean everywhere).

**Comment by jkeiser** [comment]
This is odd ... it repros when you do `c++ -Wall -c simdjson.cpp`. BUT. If you make an x.cpp in that directory with just this in it:

```c++
#include "simdjson.cpp"
```

Then `c++ -Wall -c x.cpp` does NOT cause the warning.

It clearly has something to do with file scope.

**Comment by pfirsich** [comment]
> Removing it is easy. What puzzles me is why our tests do not catch it... my current guess is that it is a matter of compilation units but I have not had time to investigate.
Sorry for misunderstanding!

**Comment by jkeiser** [comment]
@lemire the above is also why it doesn't repro in CI. We compile amalgamate_demo.cpp, which includes simdjson.cpp; we don't compile simdjson.cpp directly.

**Comment by lemire** [comment]
> the above is also why it doesn't repro in CI. We compile amalgamate_demo.cpp, which includes simdjson.cpp; we don't compile simdjson.cpp directly.

I'm having a hard time figuring out the logic in that.

**Comment by jkeiser** [comment]
@lemire me either. Either way, it repros if I add this to CMakeLists.txt:

```
add_library(simdjson-singleheader STATIC "")
target_link_libraries(simdjson-singleheader simdjson-singleheader-source simdjson-internal-flags)
```
