### ISSUE TITLE
Don't rely on the .git folder

### ISSUE THREAD

**Issue by dgrr** [simdjson/simdjson#955]
Hello,

I recently moved from Linux to Windows with WSL. Under Visual Studio you can easily work with remote systems as native ones.
Then I encountered a problem: The .git folder wasn't copied to the remote system causing compilation errors on the CMake configuration. Specifically, on `dependencies/CMakeLists.txt`.
The solution was easy: Don't exclude the .git folder. But, the problem now should be solved on every project I setup with simdjson.

I'd want to suggest if it's possible to not rely on the `.git` folder. In my case, I don't want to compile the benchmarks, so why do I need to download dependencies to compile simdjson as static dependency on my programs?

Thank you.

**Comment by lemire** [comment]
> I'd want to suggest if it's possible to not rely on the .git folder. In my case, I don't want to compile the benchmarks, so why do I need to download dependencies to compile simdjson as static dependency on my programs?

This is sensible, but here is a genuine question... how do you grab the simdjson repo. if not through git? (I am not questioning the validity of the issue, I am genuinely curious.)

**Comment by lemire** [comment]
I'll remove the "bug" flag since I do not think it is a bug.

**Comment by lemire** [comment]
My expectation is that under WSL, you would just do `git clone https://github.com/simdjson/simdjson.git`.

**Comment by lemire** [comment]
But I think that what you really want is just build the library... if so, I think it is fixed by the following PR https://github.com/simdjson/simdjson/pull/957 which takes everything out and just builds the library.

**Comment by dgrr** [comment]
Hello @lemire 

You can take a look [here](https://github.com/dgrr/kucoin-cpp-sdk). I add simdjson as submodule.
Everything is managed by Visual Studio. Visual Studio copies the files to the remote linux system (it can be WSL or just a Linux system with ssh open) using rsync and ignores `.git` by default.

**Comment by lemire** [comment]
> Everything is managed by Visual Studio. Visual Studio copies the files to the remote linux system (it can be WSL or just a Linux system with ssh open) 

Can you elaborate on this process? Is this something documented in Visual Studio?

**Comment by dgrr** [comment]
Hello @lemire 

On the [Visual Studio 2019 documentation](https://docs.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=vs-2019#tcp-port-forwarding) says:
> rsync is also used by Visual Studio's CMake support to copy source files to the remote system. [...]

The steps ran by VS when building the project are:
1. Copy the files to the remote host (excluding the folders ".vs", ".git", "out").
2. Configures the project.
3. Build the project.
4. Display errors/warnings.

The folders excluded on the first step can change by editing a variable on a json config file. But the problem relies on the .git folder not being copied and then not being found by the simdjson CMake configuration.

So, let's say on my host machine I have the .git folders but no the submodules (i didn't perform a `git clone --recursive`, just a `git clone`). If I open the project on VS only the files and the folder hierarchy will be copied to my target machine (a remote Linux).
In this case, when I try to either configure or build the project I won't success because simdjson will expect me to have the `.git` folder and the submodules (or at least `cxxopts`).

Maybe the title of the issue should be `Git submodules should be optional` or something in that way.
As far as I see, the only dependency on the `.git` folder is present on the `dependencies/CMakeLists.txt`, which if doesn't find the `cxxopts`, will try to initialize it.

Thank you.

**Comment by lemire** [comment]
@dgrr Thanks for the details. It is very helpful to understand the source of the issue.

**Comment by lemire** [comment]
I have merged the PR with SIMDJSON_JUST_LIBRARY which should solve your issue for now. We will discuss making it true by default in a future release. Just set the variable to 

```
set(SIMDJSON_JUST_LIBRARY ON CACHE STRING "Do not give me all the dependencies." FORCE)

```
