### ISSUE TITLE
remove suffix "_t" to new get methods

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#961]
get_uint64_t should be get_uint64.

**Comment by lemire** [comment]
@jkeiser Note that I can do it, it is easy. I just don't want to go play in your playground for fun.

**Comment by jkeiser** [comment]
Feel free :) I don't get offended easily and the playground is shared.

I agree with this change anyway, just too many other things in the queue ahead of it :)

**Comment by lemire** [comment]
Ok. Will do it now.
