### ISSUE TITLE
Update Microsoft vpkg to 0.4.2

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#981]
@myd7349  We released version 0.4 of simdjson. Would you consider updating the Microsoft vpkg  package?

I recommend setting SIMDJSON_JUST_LIBRARY=ON.

**Comment by myd7349** [comment]
Hi! @lemire When `SIMDJSON_JUST_LIBRARY=ON` is specified, this line will be skiped:
https://github.com/simdjson/simdjson/blob/6b85b9a416ca464289bb5673ce277b5bbf3f912a/CMakeLists.txt#L46

as a result, the header file of simdjson won't be installed.

**Comment by myd7349** [comment]
#1000

**Comment by lemire** [comment]
Moved to version 0.4.2

**Comment by myd7349** [comment]
Hi! @lemire https://github.com/microsoft/vcpkg/pull/12140 has been merged. I think this issue can be closed safely now.

**Comment by lemire** [comment]
Closing thanks to @myd7349

**Comment by lemire** [comment]
Note that instructions on how to use vcpkg are found on our wiki...

https://github.com/simdjson/simdjson/wiki/vcpkg

The hacking file is still available, but it is kind of a mess right now... So I am moving these odd bits to the wiki for now.
