### ISSUE TITLE
Undocumented std::string_view aliasing for pre-C++17 systems

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#984]
There seems to be no exposure of `internal::tape_ref::get_string_length()` in the public interface. `Element::get_c_str()` is unsafe, since we don't know what the length should be. With C++17, we can use the string_view instead, but this is unavailable in C++11.

If the strings are guaranteed to be NULL terminated, we could strlen(), but even then this is a waste of cycles when the tape already knows the exact length of the string. I'm pretty sure simdjson wants to explicitly support embedded NULLs, so that's also an issue.

**Comment by jkeiser** [comment]
You should be able to get the length from the string_view: when a target doesn't have it, we export one for consistency. c_str is indeed null terminated, though.

I don't inherently mind having a method for this, but with inlining I would expect get_string().size() to do the exact same thing exactly as fast.

**Comment by TkTech** [comment]
That itself needs to be documented (maybe I missed it?). How about changing the non-C++17 examples in the documentation to use the `nonstd::string_view` instead of `std::string_view`? `string-view-lite` does *not* behave exactly the same as `std::string_view`, although it's very, very close. It would also make it clear that you can use some C++20 features not found in the C++17 std::string_view.

**Comment by lemire** [comment]
You should be able to use string_view.  We work super hard so that you can use string_view in C++11 as if it were C++17.

Can you document your issue in terms of code?

There should be no issue.

**Comment by TkTech** [comment]
Because I'm creating bindings, I need the real signature, which is an easy change (std::string_view -> nonstd::string_view). This really isn't an issue, it just needs to be documented that string-view-lite is being used. For example I'll get errors like:

```
 TypeError: at(): incompatible function arguments. The following argument types are supported:
E           1. (self: csimdjson.element, arg0: nonstd::sv_lite::basic_string_view<char,std::char_traits<char> >) -> csimdjson.element
```

Not using the real std::string_view means template magic ceases to work when you're using any kind of wrapper-generator that has automatic handling for std::string_view.

If this is the approach you want to take, you should just drop `get_c_str()`. It's dangerous to exist without a reliable length, and NULLs are allowed in the string (#40, #101) so `strlen()` isn't going to be accurate.

**Comment by TkTech** [comment]
https://github.com/simdjson/simdjson/blob/187084ce466cddfaea0ef9ce3c98df15da1ca522/include/simdjson/common_defs.h#L200 I admit it's been a long time since I've worked in C++, but this seems like bad practice, no? A library shouldn't be modifying std. You should just use nonstd::string_view in your own code, which itself is replaced by std::string_view if it's available. This is certain to screw up large projects that already have their own backports. I feel like if this was safe to do, every string_view library would be doing it, and yet none of them do.

**Comment by lemire** [comment]
> If this is the approach you want to take, you should just drop get_c_str(). It's dangerous to exist (...) NULLs are allowed in the string (#40, #101) so strlen() isn't going to be accurate.

The idea that one can retrieve a C string from a string object in C++ is  not new. The following is standard C++:

```C++
#include <string>
#include <iostream>

int main() {
  std::string s("bal\0fdsd");
  std::cout << s.c_str() << std::endl;
}
```

It is the user's responsibility, when asking for a C string, to know whether the string contains a NULL character. Or to otherwise query the length...

> It's dangerous to exist without a reliable length, and NULLs are allowed in the string (#40, #101) so strlen() isn't going to be accurate.

Using strlen() is a bad idea. Internally, we have `get_string_length`, but we expect users to get a string_view instance instead.

I will see about exposing `get_string_length`. It is easy.


> this seems like bad practice, no?

I do not think so. These libraries are meant to precisely to allow people to use string_view on systems where it is not yet supported. In fact, string_view predates C++17 and is available on some compilers prior to C++17.

> Not using the real std::string_view means template magic ceases to work when you're using any kind of wrapper-generator that has automatic handling for std::string_view.

You are correct that it should be documented.

**Comment by lemire** [comment]
> How about changing the non-C++17 examples in the documentation to use the nonstd::string_view instead of std::string_view? 

We don't want the C++11 to differ from the C++17. As much as possible, we want to have one way to use simdjson, irrespective of whether you have C++11 or C++17.

**Comment by lemire** [comment]
Note that it is more complicated than it seems. For example, it is not the case that `std::string_view` is *only* available with C++17. It is an old pre-existing class that was available on LLVM compilers prior to C++17. 

But what we do is that we define SIMDJSON_HAS_STRING_VIEW when string_view is found in the system. We only type alias as a backup, and in such cases SIMDJSON_HAS_STRING_VIEW is undefined.

I will be documenting this. I agree that it is important to do so.

I also adding a function to query the string length. Please do not use strlen: as you point out, it is unsafe. It is almost surely slower too.

**Comment by lemire** [comment]
@TkTech Please keep the issues coming. I believe that this one is solved. We will release 0.4.1 soon.
