### ISSUE TITLE
Use of <optional>, a C++17 feature.

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#985]
Release v0.4 isn't really C++11, as it's still using the <optional> header https://github.com/simdjson/simdjson/blob/0062e54e93685a2464f1c7fc1e8f4e13ec32f17c/include/simdjson/implementation.h#L6.

This means we can't build simdjson on VS2015 (which is supported until 2025) or in strict C++11. For pysimdjson, this means we can't compile portable binaries for Py3.5 or Py3.6 since these must be built with VS2015 for ABI compatibility.

Can this header just be removed? I don't actually see std::optional being used anywhere.

**Comment by lemire** [comment]
Looks indeed like a bug.

**Comment by lemire** [comment]
@TkTech Again, please keep the issues coming. We will release 0.4.1 soon.
