### ISSUE TITLE
Version 0.5 outline

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#997]
Performance
* Faster and simpler UTF-8 validation with the lookup4 algorithm https://github.com/simdjson/simdjson/pull/993
* We improved the performance of simdjson under Visual Studio by about 25%. Users will still get better performance with clang-cl (+30%) but the gap has been reduced. https://github.com/simdjson/simdjson/pull/1031

Code usability
* In `parse_many`, when parsing streams of JSON documetns, we give to the users runtime control as to whether threads are used (via the parser.threaded attribute). https://github.com/simdjson/simdjson/issues/925
* Prefixed public macros to avoid name clashes with other libraries. https://github.com/simdjson/simdjson/issues/1035
* Better documentation regarding package managers (brew, MSYS2, conan, apt, vcpkg, FreeBSD package manager, etc.).
* Better documentation regarding  CMake usage.

Standards
* We improved standard compliance with respect to both the JSON RFC 8259 and JSON Pointer RFC 6901. We added the at_pointer method to nodes for standard-compliant JSON Pointer queries. The legacy `at(std::string_view)` method remains but is deprecated since it is not standard-compliant as per  RFC 6901.
* We removed computed GOTOs without sacrificing performance thus improving the C++ standard compliance (since computed GOTOs are compiler-specific extensions).
* Better support for C++20 https://github.com/simdjson/simdjson/pull/1050

**Comment by lemire** [comment]
@jkeiser Regarding the point "Conan / Package Managers" =>

https://github.com/conan-io/conan-center-index/search?q=simdjson&unscoped_q=simdjson

**Comment by lemire** [comment]
Version 0.2.1 is on conan. I have created a PR to add version 0.4.6, see https://github.com/conan-io/conan-center-index/pull/2104

**Comment by lemire** [comment]
Version 0.4.7 is in conan. We are also in msys2, vcpckg, debian... there is a freebsd port.

**Comment by lemire** [comment]
You can now install simdjson via brew.

**Comment by lemire** [comment]
You can also install simdjson via "apt-get".

**Comment by lemire** [comment]
@jkeiser  I have updated the outline. Have a look if you'd like.

**Comment by jkeiser** [comment]
Whichever of these package managers is new, I think it's worth calling out that it's easier than ever to *get* simdjson. I'd call out what package managers we support and that you can use cmake via fetch. That's awesome work :)

Any new platforms? mingw?

**Comment by lemire** [comment]
The MSYS2 and brew support came in after 0.4.7, so it is new.

I'll add a note about the better documentation regarding CMake usage.

**Comment by lemire** [comment]
Released.
