### ISSUE TITLE
VS2015, Patch 3 (VS14.*) support.

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#999]
VS2015 is a supported, C++11-capable compiler which will continue to be supported until 2025. The current amalgamation does not build under VS2015, but can with a few changes.

To me, the main benefit is ABI compatibility with older versions of CPython and PyPy3 on Windows, which require portable binary extensions to be built with the same version as the interpreter. There's really only one error, and one nice-to-fix warning.

- Unreliable warnings, which is a known issue mentioned in the source. https://github.com/simdjson/simdjson/blob/master/include/simdjson/common_defs.h#L86. Instead of using `__has_include`, how about we always assume warning.h is available, and make Microsoft's backport a build requirement on older versions of VS? https://www.nuget.org/packages/Microsoft.CppCoreCheck (further reading: https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/code-quality/cpp-core-guidelines-warnings.md#-use-the-c-core-check-guidelines-in-visual-studio-2015-projects).

- VS2015 does not like the constructor on loaded_bytes. https://github.com/simdjson/simdjson/blob/eef117194478115f842e08682bc769051a0a863f/include/simdjson/inline/parser.h#L20 results in:

        error C2661: 'std::unique_ptr<char [],void (__cdecl *)(char *)>::unique_ptr': no overloaded function takes 2 arguments

    I'm not sure how to fix this one properly; I temporarily made loaded_bytes a regular ol' pointer and everything worked fine. VS2015 *does* have support for `unique_ptr` with deleters so I'm not sure why this is an issue.

Since these are the only issue's I've run into with VC2015, I think it's worth supporting it as a target considering its wide use. If not, I'll just maintain a patch for it in pysimdjson.

**Comment by lemire** [comment]
> instead of using __has_include, how about we always assume warning.h is available, and make Microsoft's backport a build requirement on older versions of VS?

That sounds reasonable enough.

**Comment by lemire** [comment]
I have created a PR https://github.com/simdjson/simdjson/pull/1002

I was hopeful if there were only these two issues that we could support Visual Studio 2015 but it seems more complicated. There are many, many problems. So unless someone is willing to do the leg work of porting everything to Visual Studio 2015, there is no way we can support Visual Studio 2015.

However, I am happy to fix these two particular issues in the main branch.

Whether it works properly, I could not tell.

**Comment by TkTech** [comment]
The other issues you ran into are just with the tooling, correct? If you're having trouble with the amalgamation, make sure you're on VS2015 patch 3. The earlier versions had far more issues.

**Comment by lemire** [comment]
> The other issues you ran into are just with the tooling, correct?

I can build the library fixing the two issues you have pointed out, but I cannot build and run tests. 

> If you're having trouble with the amalgamation, make sure you're on VS2015 patch 3. The earlier versions had far more issues.

I got a fresh copy of VS 2015 which I assumed was the latest. I did not check.

**Comment by TkTech** [comment]
I'll work off your PR and see how much work the tests will need. If it's too much or would loose clarity, I think it'd be better to maintain this in a branch of pysimdjson.

**Comment by lemire** [comment]
@TkTech Turns out that we do pass the tests.

https://github.com/simdjson/simdjson/pull/1002

So you were correct. I'll just wait for @jkeiser to review the PR.

I don't know that we will ever list Visual Studio 2015 in our documentation. There is currently a lot of warnings. But the tests pass.

> If it's too much or would loose clarity, I think it'd be better to maintain this in a branch of pysimdjson.

This is not good. We want to avoid that.

**Comment by lemire** [comment]
Ok. Merge in our main branch. So we will not build and test under Visual Studio 2015 as part of our CI.

I won't advertise  Visual Studio 2015 if only because I don't want to spend the next week figuring out how to silence all the crazy warnings. We build warning-free under Visual Studio 2017 and Visual Studio 2019, and that will be all for now.

**Comment by lemire** [comment]
(Previous comment was edited: we will build and test under Visual Studio 2015 as part of our CI.)

**Comment by lemire** [comment]
Supported and part of our CI as of Version 0.4.3.
